// Central tuning values for gameplay balance.
window.BRASSLINE_BALANCE = {
  rules: {
    handSize: 5,
    maxHeat: 120,
    trackLanes: 5,
  },
  rewards: {
    choiceCount: 3,
    chosenHeal: 8,
    skipHeal: 4,
  },
  telegraph: {
    cookTurns: {
      fast: 1,
      medium: 2,
      slow: 3,
    },
  },
  player: {
    baseMaxHull: 72,
    baseMaxEnergy: 3,
    startHeat: 35,
    carryRatio: 0.55,
    carryFloor: 15,
  },
  upgrades: {
    hullPerHullPlatingLevel: 6,
    turnStartCoolingBase: 8,
    turnStartCoolingPerLevel: 2,
    turnStartBlockPerGuardLevel: 3,
  },
  upgradePaths: {
    condenser_bank: {
      title: "Condenser Bank",
      icon: "./assets/curated/icons/ui/energy_battery-50.svg",
      description: "Increase max Steam for stronger turns.",
      maxLevel: 3,
    },
    coolant_loop: {
      title: "Coolant Loop",
      icon: "./assets/curated/icons/ui/heat_radiations.svg",
      description: "Increase passive cooling at turn start.",
      maxLevel: 3,
    },
    hull_plating: {
      title: "Hull Plating",
      icon: "./assets/curated/icons/ui/hp_life-bar.svg",
      description: "Increase max Hull and gain immediate repairs.",
      maxLevel: 3,
    },
    guard_protocol: {
      title: "Guard Protocol",
      icon: "./assets/curated/icons/ui/alert_wall-light.svg",
      description: "Start each turn with extra Block.",
      maxLevel: 3,
    },
  },
  overclock: {
    heatGain: 12,
    strainThreshold: 100,
    strainDamage: 3,
  },
  enemies: {
    rail_hound: {
      maxHp: 30,
      intents: [
        { value: 6, hits: 1 },
        { value: 8, hits: 1 },
      ],
    },
    ash_gunner: {
      maxHp: 25,
      intents: [
        { value: 3, hits: 2 },
        { value: 6, hits: 0 },
      ],
    },
    rail_sentry: {
      maxHp: 29,
      startIntentIndex: 0,
      intents: [
        { value: 4, hits: 0 },
        { value: 9, hits: 1 },
      ],
    },
    mortar_engineer: {
      maxHp: 33,
      intents: [
        { value: 12, cookTier: "slow", radius: 1 },
        { value: 5, hits: 0 },
      ],
    },
    arc_lancer: {
      maxHp: 31,
      intents: [
        { value: 11, cookTier: "medium", width: 3 },
        { value: 2, hits: 0 },
      ],
    },
    clockwork_diver: {
      maxHp: 34,
      intents: [
        { value: 6, hits: 0 },
        { value: 7, hits: 1 },
      ],
    },
    zephyr_scout: {
      maxHp: 28,
      intents: [
        { value: 2, hits: 0 },
        { value: 5, hits: 2 },
      ],
    },
    boiler_guard: {
      maxHp: 40,
      intents: [
        { value: 8, hits: 0 },
        { value: 9, hits: 1 },
      ],
    },
    fume_bomber: {
      maxHp: 32,
      intents: [
        { value: 10, cookTier: "medium", radius: 1 },
        { value: 5, hits: 0 },
        { value: 6, hits: 1 },
      ],
    },
    coil_priest: {
      maxHp: 30,
      intents: [
        { value: 2, hits: 0 },
        { value: 7, hits: 1 },
        { value: 6, hits: 0 },
      ],
    },
    orbital_miner: {
      maxHp: 35,
      intents: [
        { value: 10, cookTier: "medium", width: 2 },
        { value: 6, hits: 0 },
        { value: 6, hits: 2 },
      ],
    },
    cinder_tyrant: {
      maxHp: 95,
      intents: [
        { value: 10, hits: 0 },
        { value: 12, hits: 1 },
        { value: 3, hits: 0 },
        { value: 13, cookTier: "fast", width: 2 },
        { value: 8, hits: 2 },
      ],
    },
  },
  cards: {
    stoke_burners: {
      cost: 1,
      text: "Gain 8 Heat. Deal 7 damage.",
      heatText: "+8 heat",
      heatGain: 8,
      baseDamage: 7,
    },
    pressure_vent: {
      cost: 1,
      text: "Lose 12 Heat. Draw 1 card.",
      heatText: "-12 heat",
      heatGain: -12,
      draw: 1,
    },
    spark_lance: {
      cost: 2,
      text: "Deal 12 damage. +6 at 60+ Heat.",
      heatText: "+6 heat",
      heatGain: 6,
      baseDamage: 12,
      bonusDamage: 6,
      heatThreshold: 60,
    },
    emergency_fog: {
      cost: 1,
      text: "Gain 9 Block and Exhaust.",
      heatText: "+4 heat",
      heatGain: 4,
      blockGain: 9,
    },
    turret_burst: {
      cost: 2,
      text: "Deal 9 to all enemies.",
      heatText: "+10 heat",
      heatGain: 10,
      baseDamage: 9,
    },
    overpressure: {
      cost: 0,
      text: "Next attack deals double this turn.",
      heatText: "+15 heat",
      heatGain: 15,
      attackMultiplier: 2,
    },
    condenser_tap: {
      cost: 1,
      text: "Lose 8 Heat. Gain 5 Block.",
      heatText: "-8 heat",
      heatGain: -8,
      blockGain: 5,
    },
    arc_drill: {
      cost: 1,
      text: "Deal 8 damage twice if Heat >= 50.",
      heatText: "+5 heat",
      heatGain: 5,
      baseDamage: 8,
      heatThreshold: 50,
      hitsCold: 1,
      hitsHot: 2,
    },
    rail_cannon: {
      cost: 3,
      text: "Deal 22 damage. +8 at 70+ Heat.",
      heatText: "+12 heat",
      heatGain: 12,
      baseDamage: 22,
      bonusDamage: 8,
      heatThreshold: 70,
    },
    coolant_flush: {
      cost: 1,
      text: "Lose 18 Heat. Gain 7 Block and draw 1.",
      heatText: "-18 heat",
      heatGain: -18,
      blockGain: 7,
      draw: 1,
    },
    boiler_bastion: {
      cost: 2,
      text: "Gain 18 Block.",
      heatText: "+6 heat",
      heatGain: 6,
      blockGain: 18,
    },
    flash_relay: {
      cost: 1,
      text: "Gain 1 Steam. Gain +1 more at 60+ Heat.",
      heatText: "+10 heat",
      heatGain: 10,
      heatThreshold: 60,
      energyCold: 1,
      energyHot: 2,
    },
    static_field: {
      cost: 1,
      text: "Deal 4 to all enemies. Gain 4 Block.",
      heatText: "+5 heat",
      heatGain: 5,
      damageEach: 4,
      blockGain: 4,
    },
    pressure_spike: {
      cost: 1,
      text: "Deal 14 damage. +6 vs blocked targets.",
      heatText: "+9 heat",
      heatGain: 9,
      baseDamage: 14,
      bonusVsBlock: 6,
    },
    steam_barrier: {
      cost: 1,
      text: "Lose 10 Heat. Gain 11 Block. Draw 1 if Heat <= 30.",
      heatText: "-10 heat",
      heatGain: -10,
      blockGain: 11,
      coolDrawThreshold: 30,
      drawOnCool: 1,
    },
    boiler_spike: {
      cost: 2,
      text: "Deal 10 damage. +8 at 80+ Heat.",
      heatText: "+6 heat",
      heatGain: 6,
      baseDamage: 10,
      bonusDamage: 8,
      heatThreshold: 80,
    },
    scrap_hail: {
      cost: 2,
      text: "Deal 5 to all enemies twice.",
      heatText: "+8 heat",
      heatGain: 8,
      damageEach: 5,
      hits: 2,
    },
    circuit_break: {
      cost: 1,
      text: "Lose 14 Heat. Gain 1 Steam.",
      heatText: "-14 heat",
      heatGain: -14,
      energyGain: 1,
    },
    slag_round: {
      cost: 1,
      text: "Deal 11 damage. +5 if target is Charged.",
      heatText: "+4 heat",
      heatGain: 4,
      baseDamage: 11,
      chargedBonus: 5,
    },
    blast_shield: {
      cost: 1,
      text: "Gain 7 Block. Gain +5 if Heat >= 70.",
      heatText: "+2 heat",
      heatGain: 2,
      blockBase: 7,
      blockBonus: 5,
      heatThreshold: 70,
    },
  },
  progression: {
    sectors: [
      {
        name: "Freight Corridor",
        enemies: [
          { key: "rail_hound", power: 1.0 },
          { key: "rail_sentry", power: 1.0 },
          { key: "ash_gunner", power: 1.0 },
          { key: "mortar_engineer", power: 0.9 },
        ],
      },
      {
        name: "Soot Tunnels",
        enemies: [
          { key: "rail_sentry", power: 1.2 },
          { key: "ash_gunner", power: 1.2 },
          { key: "arc_lancer", power: 1.1 },
          { key: "zephyr_scout", power: 1.1 },
          { key: "fume_bomber", power: 1.05 },
          { key: "coil_priest", power: 1.0 },
          { key: "rail_hound", power: 1.1 },
        ],
      },
      {
        name: "Voltage Causeway",
        enemies: [
          { key: "coil_priest", power: 1.15 },
          { key: "rail_sentry", power: 1.25 },
          { key: "arc_lancer", power: 1.15 },
          { key: "fume_bomber", power: 1.1 },
          { key: "zephyr_scout", power: 1.2 },
          { key: "ash_gunner", power: 1.2 },
        ],
      },
      {
        name: "Orbital Yards",
        enemies: [
          { key: "orbital_miner", power: 1.2 },
          { key: "boiler_guard", power: 1.1 },
          { key: "mortar_engineer", power: 1.2 },
          { key: "coil_priest", power: 1.2 },
          { key: "rail_hound", power: 1.25 },
        ],
      },
      {
        name: "Foundry Crown",
        boss: true,
        enemies: [
          { key: "cinder_tyrant", power: 1.0 },
          { key: "rail_sentry", power: 1.35 },
          { key: "mortar_engineer", power: 1.25 },
          { key: "arc_lancer", power: 1.25 },
          { key: "fume_bomber", power: 1.2 },
          { key: "orbital_miner", power: 1.15 },
          { key: "ash_gunner", power: 1.25 },
        ],
      },
    ],
    starterDeck: [
      "stoke_burners",
      "stoke_burners",
      "pressure_vent",
      "pressure_vent",
      "spark_lance",
      "spark_lance",
      "emergency_fog",
      "turret_burst",
      "overpressure",
      "condenser_tap",
      "arc_drill",
      "arc_drill",
    ],
    rewardPool: [
      "rail_cannon",
      "coolant_flush",
      "boiler_bastion",
      "flash_relay",
      "static_field",
      "pressure_spike",
      "steam_barrier",
      "boiler_spike",
      "scrap_hail",
      "circuit_break",
      "slag_round",
      "blast_shield",
      "turret_burst",
      "overpressure",
      "spark_lance",
    ],
    interludes: [
      {
        afterSector: 2,
        type: "event",
        title: "Switchyard Detour",
        description: "Pick a route before the convoy reaches the broken rail split.",
        options: [
          {
            label: "Service siding (stabilize)",
            hull: 6,
            heat: -6,
          },
          {
            label: "Express bypass (risky jump)",
            heat: 10,
            targetSector: 4,
          },
        ],
      },
      {
        afterSector: 4,
        type: "shop",
        title: "Coal Exchange",
        description: "A depot crew offers quick refits before the final push.",
        options: [
          {
            label: "Patch the hull",
            hull: 10,
            heat: 4,
          },
          {
            label: "Swap Stoke Burners for Rail Cannon",
            removeCard: "stoke_burners",
            addCard: "rail_cannon",
          },
        ],
      },
    ],
  },
  ui: {
    metaResetConfirmMs: 2500,
    recordsResetConfirmMs: 2500,
    timelineRecentCount: 14,
  },
};
