(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  const ACCESSORY_ITEM_TEMPLATES: Record<string, ItemTemplateDefinition> = {
    // ── Helms ──
    item_cap: {
      sourceId: "cap",
      slot: "helm",
      family: "Helms",
      actRequirement: 1,
      progressionTier: 1,
      bonuses: { heroMaxLife: 3, heroGuardBonus: 1 },
    },
    item_skull_cap: {
      sourceId: "skull_cap",
      slot: "helm",
      family: "Helms",
      actRequirement: 2,
      progressionTier: 2,
      bonuses: { heroMaxLife: 5, heroGuardBonus: 1 },
    },
    item_helm: {
      sourceId: "helm",
      slot: "helm",
      family: "Helms",
      actRequirement: 3,
      progressionTier: 3,
      bonuses: { heroMaxLife: 6, heroGuardBonus: 2 },
    },
    item_great_helm: {
      sourceId: "great_helm",
      slot: "helm",
      family: "Helms",
      actRequirement: 4,
      progressionTier: 5,
      bonuses: { heroMaxLife: 8, heroGuardBonus: 2 },
    },
    item_crown: {
      sourceId: "crown",
      slot: "helm",
      family: "Helms",
      actRequirement: 5,
      progressionTier: 7,
      bonuses: { heroMaxLife: 10, heroGuardBonus: 3, heroMaxEnergy: 1 },
    },
    // ── Shields ──
    item_buckler: {
      sourceId: "buckler",
      slot: "shield",
      family: "Shields",
      actRequirement: 1,
      progressionTier: 1,
      bonuses: { heroGuardBonus: 2 },
    },
    item_small_shield: {
      sourceId: "small_shield",
      slot: "shield",
      family: "Shields",
      actRequirement: 2,
      progressionTier: 2,
      bonuses: { heroGuardBonus: 2, heroMaxLife: 3 },
    },
    item_large_shield: {
      sourceId: "large_shield",
      slot: "shield",
      family: "Shields",
      actRequirement: 3,
      progressionTier: 3,
      bonuses: { heroGuardBonus: 3, heroMaxLife: 4 },
    },
    item_tower_shield: {
      sourceId: "tower_shield",
      slot: "shield",
      family: "Shields",
      actRequirement: 4,
      progressionTier: 5,
      bonuses: { heroGuardBonus: 4, heroMaxLife: 5 },
    },
    item_monarch: {
      sourceId: "monarch",
      slot: "shield",
      family: "Shields",
      actRequirement: 5,
      progressionTier: 7,
      bonuses: { heroGuardBonus: 5, heroMaxLife: 6 },
    },
    // ── Gloves ──
    item_leather_gloves: {
      sourceId: "leather_gloves",
      slot: "gloves",
      family: "Gloves",
      actRequirement: 1,
      progressionTier: 1,
      bonuses: { heroDamageBonus: 1 },
    },
    item_heavy_gloves: {
      sourceId: "heavy_gloves",
      slot: "gloves",
      family: "Gloves",
      actRequirement: 2,
      progressionTier: 2,
      bonuses: { heroDamageBonus: 1, heroBurnBonus: 1 },
    },
    item_chain_gloves: {
      sourceId: "chain_gloves",
      slot: "gloves",
      family: "Gloves",
      actRequirement: 3,
      progressionTier: 3,
      bonuses: { heroDamageBonus: 2, heroBurnBonus: 1 },
    },
    item_gauntlets: {
      sourceId: "gauntlets",
      slot: "gloves",
      family: "Gloves",
      actRequirement: 5,
      progressionTier: 5,
      bonuses: { heroDamageBonus: 3, heroBurnBonus: 2 },
    },
    // ── Boots ──
    item_boots: {
      sourceId: "boots",
      slot: "boots",
      family: "Boots",
      actRequirement: 1,
      progressionTier: 1,
      bonuses: { heroMaxLife: 3 },
    },
    item_heavy_boots: {
      sourceId: "heavy_boots",
      slot: "boots",
      family: "Boots",
      actRequirement: 2,
      progressionTier: 2,
      bonuses: { heroMaxLife: 4, mercenaryMaxLife: 2 },
    },
    item_chain_boots: {
      sourceId: "chain_boots",
      slot: "boots",
      family: "Boots",
      actRequirement: 3,
      progressionTier: 3,
      bonuses: { heroMaxLife: 5, mercenaryMaxLife: 3 },
    },
    item_war_boots: {
      sourceId: "war_boots",
      slot: "boots",
      family: "Boots",
      actRequirement: 5,
      progressionTier: 5,
      bonuses: { heroMaxLife: 7, mercenaryMaxLife: 4 },
    },
    // ── Belts ──
    item_sash: {
      sourceId: "sash",
      slot: "belt",
      family: "Belts",
      actRequirement: 1,
      progressionTier: 1,
      bonuses: { heroPotionHeal: 1 },
    },
    item_light_belt: {
      sourceId: "light_belt",
      slot: "belt",
      family: "Belts",
      actRequirement: 2,
      progressionTier: 2,
      bonuses: { heroPotionHeal: 1, heroMaxLife: 3 },
    },
    item_heavy_belt: {
      sourceId: "heavy_belt",
      slot: "belt",
      family: "Belts",
      actRequirement: 3,
      progressionTier: 3,
      bonuses: { heroPotionHeal: 2, heroMaxLife: 4 },
    },
    item_war_belt: {
      sourceId: "war_belt",
      slot: "belt",
      family: "Belts",
      actRequirement: 5,
      progressionTier: 5,
      bonuses: { heroPotionHeal: 3, heroMaxLife: 5 },
    },
    // ── Rings ──
    item_ring: {
      sourceId: "ring",
      slot: "ring",
      family: "Rings",
      actRequirement: 1,
      progressionTier: 1,
      bonuses: { heroDamageBonus: 1 },
    },
    item_coral_ring: {
      sourceId: "coral_ring",
      slot: "ring",
      family: "Rings",
      actRequirement: 2,
      progressionTier: 2,
      bonuses: { heroMaxLife: 4, heroPotionHeal: 1 },
    },
    item_jade_ring: {
      sourceId: "jade_ring",
      slot: "ring",
      family: "Rings",
      actRequirement: 3,
      progressionTier: 3,
      bonuses: { heroDamageBonus: 1, heroGuardBonus: 1, heroMaxLife: 3 },
    },
    item_diamond_ring: {
      sourceId: "diamond_ring",
      slot: "ring",
      family: "Rings",
      actRequirement: 5,
      progressionTier: 5,
      bonuses: { heroDamageBonus: 2, heroGuardBonus: 2, heroMaxLife: 4 },
    },
    // ── Amulets ──
    item_amulet: {
      sourceId: "amulet",
      slot: "amulet",
      family: "Amulets",
      actRequirement: 1,
      progressionTier: 1,
      bonuses: { heroMaxEnergy: 1 },
    },
    item_jade_amulet: {
      sourceId: "jade_amulet",
      slot: "amulet",
      family: "Amulets",
      actRequirement: 2,
      progressionTier: 2,
      bonuses: { heroMaxEnergy: 1, heroMaxLife: 3 },
    },
    item_prismatic_amulet: {
      sourceId: "prismatic_amulet",
      slot: "amulet",
      family: "Amulets",
      actRequirement: 4,
      progressionTier: 4,
      bonuses: { heroMaxEnergy: 1, heroDamageBonus: 1, heroGuardBonus: 1 },
    },
    item_highlords_amulet: {
      sourceId: "highlords_amulet",
      slot: "amulet",
      family: "Amulets",
      actRequirement: 5,
      progressionTier: 6,
      bonuses: { heroMaxEnergy: 2, heroDamageBonus: 2, mercenaryAttack: 1 },
    },
  };

  runtimeWindow.__ROUGE_ITEM_DATA_ACCESSORIES = ACCESSORY_ITEM_TEMPLATES;
})();
