(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;
  const helpers = runtimeWindow.__ROUGE_OPP_HELPERS;
  const buildDetourChoice = (...args) => helpers.buildOpportunityChoice("Detour Opportunity", ...args);
  const { buildLateRouteVariant } = helpers;

  const DETOUR_OPPORTUNITY_DEFINITIONS: Record<number, DetourOpportunityDefinition> = {
    1: {
      kind: "opportunity",
      id: "rogue_detour_opportunity",
      title: "Monastery Detour",
      zoneTitle: "Monastery Detour",
      description: "After the monastery covenant closes, the rogue line can still peel into a quieter detour that banks recovery work instead of rushing the catacombs.",
      summary: "The post-covenant route now fans back out into a safer rogue detour lane.",
      grants: { gold: 10, xp: 12, potions: 0 },
      requiresQuestId: "tristram_relief",
      requiresRecoveryOpportunityId: "rogue_recovery_opportunity",
      requiresAccordOpportunityId: "rogue_accord_opportunity",
      requiresCovenantOpportunityId: "rogue_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildDetourChoice, "rogue_detour_opportunity", "tristram_relief", {
          id: "supply_detour",
          title: "Supply Detour",
          description: "Even without a cleaner monastery line, the rogues can still cut one late supply detour before the catacombs open.",
          summary: "A fallback detour opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "secure_the_abbey_sidepass",
            title: "Secure the Abbey Sidepass",
            description: "Cut a quiet line through the abbey stores and hold it ready for the next clash.",
            consequenceId: "abbey_sidepass_secured",
            flagIds: ["rogue_detour_abbey_sidepass"],
            extraEffects: [{ kind: "refill_potions", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "rogue_detour_opportunity", "tristram_relief", {
          id: "lantern_detour",
          title: "Lantern Detour",
          description: "Recovery lanterns and cloister path marks turn the detour lane into a true chapel sidepass instead of one more store check.",
          summary: "The recovery and accord lanes now open a safer sidepass through the monastery.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["rogue_recovery_chapel_lanterns", "rogue_accord_cloister_paths"],
          choice: {
            outcomeId: "open_the_chapel_sidepass",
            title: "Open the Chapel Sidepass",
            description: "Turn the relit chapel lanterns and marked cloister paths into a guarded sidepass around the next push.",
            consequenceId: "chapel_sidepass_opened",
            flagIds: ["rogue_detour_chapel_sidepass"],
            extraEffects: [{ kind: "hero_max_life", value: 2 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "rogue_detour_opportunity", "tristram_relief", {
          id: "wayfinder_detour",
          title: "Wayfinder Detour",
          description: "The sealed wayfinder ledger turns the detour into a hidden convoy route that changes how the monastery handles the next fight.",
          summary: "A full rogue late-route close can now turn into a protected convoy detour instead of one more straight assault lane.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["rogue_recovery_chapel_lanterns", "rogue_accord_cloister_paths", "rogue_covenant_wayfinder_ledger"],
          choice: {
            outcomeId: "stage_the_hidden_abbey_convoy",
            title: "Stage the Hidden Abbey Convoy",
            description: "Move the covenant ledger, lantern chain, and cloister marks into one hidden convoy around the monastery flank.",
            consequenceId: "hidden_abbey_convoy_staged",
            flagIds: ["rogue_detour_hidden_convoy"],
            extraEffects: [{ kind: "hero_max_life", value: 2 }, { kind: "belt_capacity", value: 1 }],
          },
        }),
      ],
    },
    2: {
      kind: "opportunity",
      id: "sunwell_detour_opportunity",
      title: "Reliquary Detour",
      zoneTitle: "Reliquary Detour",
      description: "After the reliquary covenant closes, the desert line can still break into a supply detour that circles the tomb approach instead of driving straight inward.",
      summary: "The post-covenant route now fans back out into a safer desert detour lane.",
      grants: { gold: 10, xp: 12, potions: 0 },
      requiresQuestId: "lost_reliquary",
      requiresRecoveryOpportunityId: "sunwell_recovery_opportunity",
      requiresAccordOpportunityId: "sunwell_accord_opportunity",
      requiresCovenantOpportunityId: "sunwell_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildDetourChoice, "sunwell_detour_opportunity", "lost_reliquary", {
          id: "caravan_detour",
          title: "Caravan Detour",
          description: "Even without a truer spearline route, the reliquary can still throw one late detour around the tomb mouth.",
          summary: "A fallback detour opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "secure_the_tomb_sidepass",
            title: "Secure the Tomb Sidepass",
            description: "Cut a caravan sidepass through the outer tomb markers and bank it for the next clash.",
            consequenceId: "tomb_sidepass_secured",
            flagIds: ["sunwell_detour_tomb_sidepass"],
            extraEffects: [{ kind: "refill_potions", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "sunwell_detour_opportunity", "lost_reliquary", {
          id: "ward_detour",
          title: "Ward Detour",
          description: "Recovery wards and accorded spear posts turn the detour lane into a true guarded sidepass instead of another caravan count.",
          summary: "The recovery and accord lanes now open a safer sidepass through the desert line.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["sunwell_recovery_spearline_wards", "sunwell_accord_spear_posts"],
          choice: {
            outcomeId: "open_the_warded_sidepass",
            title: "Open the Warded Sidepass",
            description: "Turn the spearline wards and accorded posts into a safer reliquary sidepass for the next advance.",
            consequenceId: "warded_sidepass_opened",
            flagIds: ["sunwell_detour_warded_sidepass"],
            extraEffects: [{ kind: "hero_max_life", value: 3 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "sunwell_detour_opportunity", "lost_reliquary", {
          id: "lance_detour",
          title: "Lance Detour",
          description: "The final lance ledger turns the detour into a hidden caravan line that changes how the next desert fight opens.",
          summary: "A full desert late-route close can now turn into a protected hidden detour instead of another direct push.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["sunwell_recovery_spearline_wards", "sunwell_accord_spear_posts", "sunwell_covenant_final_lance_ledger"],
          choice: {
            outcomeId: "stage_the_hidden_reliquary_caravan",
            title: "Stage the Hidden Reliquary Caravan",
            description: "Move the final lance ledger, wards, and spear posts into one hidden caravan around the next tomb breach.",
            consequenceId: "hidden_reliquary_caravan_staged",
            flagIds: ["sunwell_detour_hidden_caravan"],
            extraEffects: [{ kind: "hero_max_life", value: 3 }, { kind: "belt_capacity", value: 1 }],
          },
        }),
      ],
    },
    3: {
      kind: "opportunity",
      id: "kurast_detour_opportunity",
      title: "Harbor Detour",
      zoneTitle: "Harbor Detour",
      description: "After the harbor covenant closes, Kurast can still peel into a quieter river detour that banks recovery work instead of running straight at the Durance.",
      summary: "The post-covenant route now fans back out into a safer harbor detour lane.",
      grants: { gold: 10, xp: 12, potions: 0 },
      requiresQuestId: "smugglers_wake",
      requiresRecoveryOpportunityId: "kurast_recovery_opportunity",
      requiresAccordOpportunityId: "kurast_accord_opportunity",
      requiresCovenantOpportunityId: "kurast_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildDetourChoice, "kurast_detour_opportunity", "smugglers_wake", {
          id: "dock_detour",
          title: "Dock Detour",
          description: "Even without a sharper channel line, the harbor can still open one last detour through the old docks.",
          summary: "A fallback detour opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "secure_the_dock_sidepass",
            title: "Secure the Dock Sidepass",
            description: "Cut a quiet path through the dock stores and keep it ready for the next river fight.",
            consequenceId: "dock_sidepass_secured",
            flagIds: ["kurast_detour_dock_sidepass"],
            extraEffects: [{ kind: "refill_potions", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "kurast_detour_opportunity", "smugglers_wake", {
          id: "spellward_detour",
          title: "Spellward Detour",
          description: "Recovery spellward bins and accorded channel marks turn the detour lane into a true riverside sidepass instead of another dock tally.",
          summary: "The recovery and accord lanes now open a safer sidepass through the harbor line.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["kurast_recovery_spellward_bins", "kurast_accord_channel_marks"],
          choice: {
            outcomeId: "open_the_spellward_sidepass",
            title: "Open the Spellward Sidepass",
            description: "Turn the spellward bins and channel marks into a guarded sidepass around the next Kurast clash.",
            consequenceId: "spellward_sidepass_opened",
            flagIds: ["kurast_detour_spellward_sidepass"],
            extraEffects: [{ kind: "hero_max_energy", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "kurast_detour_opportunity", "smugglers_wake", {
          id: "harbor_detour",
          title: "Harbor Detour",
          description: "The sealed spellward ledger turns the detour into a hidden fleet line that changes how the next harbor fight opens.",
          summary: "A full harbor late-route close can now turn into a protected fleet detour instead of another straight dock surge.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["kurast_recovery_spellward_bins", "kurast_accord_channel_marks", "kurast_covenant_spellward_ledger"],
          choice: {
            outcomeId: "stage_the_hidden_river_fleet",
            title: "Stage the Hidden River Fleet",
            description: "Move the covenant ledger, spellward bins, and channel marks into one hidden fleet around the next Durance push.",
            consequenceId: "hidden_river_fleet_staged",
            flagIds: ["kurast_detour_hidden_fleet"],
            extraEffects: [{ kind: "hero_max_energy", value: 1 }, { kind: "gold_bonus", value: 12 }],
          },
        }),
      ],
    },
    4: {
      kind: "opportunity",
      id: "hellforge_detour_opportunity",
      title: "Sanctuary Detour",
      zoneTitle: "Sanctuary Detour",
      description: "After the sanctuary covenant closes, the forge line can still turn into a hard relief detour that circles the next breach instead of driving straight through it.",
      summary: "The post-covenant route now fans back out into a safer sanctuary detour lane.",
      grants: { gold: 12, xp: 12, potions: 0 },
      requiresQuestId: "hellforge_claim",
      requiresRecoveryOpportunityId: "hellforge_recovery_opportunity",
      requiresAccordOpportunityId: "hellforge_accord_opportunity",
      requiresCovenantOpportunityId: "hellforge_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildDetourChoice, "hellforge_detour_opportunity", "hellforge_claim", {
          id: "ash_detour",
          title: "Ash Detour",
          description: "Even without a truer forge relief line, the sanctuary can still open one late detour through the ash belts.",
          summary: "A fallback detour opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "secure_the_ash_sidepass",
            title: "Secure the Ash Sidepass",
            description: "Cut a relief line through the ash belts and hold it ready for the next sanctuary clash.",
            consequenceId: "ash_sidepass_secured",
            flagIds: ["hellforge_detour_ash_sidepass"],
            extraEffects: [{ kind: "refill_potions", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "hellforge_detour_opportunity", "hellforge_claim", {
          id: "hellward_detour",
          title: "Hellward Detour",
          description: "Recovery hellward screens and accord relief lines turn the detour lane into a true sidepass instead of another ash count.",
          summary: "The recovery and accord lanes now open a safer sidepass through the infernal cut.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["hellforge_recovery_hellward_screen", "hellforge_accord_hellward_relief"],
          choice: {
            outcomeId: "open_the_hellward_sidepass",
            title: "Open the Hellward Sidepass",
            description: "Turn the screened hellward line and relief posts into a guarded sidepass around the next breach.",
            consequenceId: "hellward_sidepass_opened",
            flagIds: ["hellforge_detour_hellward_sidepass"],
            extraEffects: [{ kind: "hero_max_life", value: 3 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "hellforge_detour_opportunity", "hellforge_claim", {
          id: "breachscreen_detour",
          title: "Breachscreen Detour",
          description: "The breachscreen ledger turns the detour into a hidden relief line that changes how the next sanctuary fight breaks.",
          summary: "A full sanctuary late-route close can now turn into a protected relief detour instead of another direct breach.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["hellforge_recovery_hellward_screen", "hellforge_accord_hellward_relief", "hellforge_covenant_breachscreen_ledger"],
          choice: {
            outcomeId: "stage_the_hidden_relief_line",
            title: "Stage the Hidden Relief Line",
            description: "Move the covenant ledger, relief posts, and hellward screens into one hidden line around the next sanctuary break.",
            consequenceId: "hidden_relief_line_staged",
            flagIds: ["hellforge_detour_hidden_relief"],
            extraEffects: [{ kind: "hero_max_life", value: 3 }, { kind: "belt_capacity", value: 1 }],
          },
        }),
      ],
    },
    5: {
      kind: "opportunity",
      id: "harrogath_detour_opportunity",
      title: "Summit Detour",
      zoneTitle: "Summit Detour",
      description: "After the summit covenant closes, Harrogath can still break into a guarded sled detour that circles the last ascent instead of driving straight at the Worldstone.",
      summary: "The post-covenant route now fans back out into a safer summit detour lane.",
      grants: { gold: 12, xp: 14, potions: 0 },
      requiresQuestId: "harrogath_rescue",
      requiresRecoveryOpportunityId: "harrogath_recovery_opportunity",
      requiresAccordOpportunityId: "harrogath_accord_opportunity",
      requiresCovenantOpportunityId: "harrogath_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildDetourChoice, "harrogath_detour_opportunity", "harrogath_rescue", {
          id: "summit_detour",
          title: "Sled Detour",
          description: "Even without a sharper summit line, Harrogath can still open one last sled detour around the frozen climb.",
          summary: "A fallback detour opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "secure_the_sled_sidepass",
            title: "Secure the Sled Sidepass",
            description: "Cut a quiet sled path across the frozen switchbacks and bank it for the next clash.",
            consequenceId: "sled_sidepass_secured",
            flagIds: ["harrogath_detour_sled_sidepass"],
            extraEffects: [{ kind: "refill_potions", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "harrogath_detour_opportunity", "harrogath_rescue", {
          id: "banner_detour",
          title: "Banner Detour",
          description: "Recovery banners and accorded Ancients posts turn the detour lane into a true mountain sidepass instead of another ration count.",
          summary: "The recovery and accord lanes now open a safer sidepass across the summit line.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["harrogath_recovery_guard_banners", "harrogath_accord_ancients_posts"],
          choice: {
            outcomeId: "open_the_banner_sidepass",
            title: "Open the Banner Sidepass",
            description: "Turn the recovered banners and accorded posts into a guarded sidepass around the next summit clash.",
            consequenceId: "banner_sidepass_opened",
            flagIds: ["harrogath_detour_banner_sidepass"],
            extraEffects: [{ kind: "hero_max_life", value: 4 }],
          },
        }),
        buildLateRouteVariant(buildDetourChoice, "harrogath_detour_opportunity", "harrogath_rescue", {
          id: "ancients_detour",
          title: "Ancients Detour",
          description: "The Ancients ledger turns the detour into a hidden sled chain that changes how the next summit fight opens.",
          summary: "A full summit late-route close can now turn into a protected sled detour instead of another straight Worldstone rush.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["harrogath_recovery_guard_banners", "harrogath_accord_ancients_posts", "harrogath_covenant_ancients_ledger"],
          choice: {
            outcomeId: "stage_the_hidden_ancients_sleds",
            title: "Stage the Hidden Ancients Sleds",
            description: "Move the covenant ledger, guard banners, and Ancients posts into one hidden sled chain before the next Worldstone push.",
            consequenceId: "hidden_ancients_sleds_staged",
            flagIds: ["harrogath_detour_hidden_sleds"],
            extraEffects: [{ kind: "hero_max_life", value: 4 }, { kind: "belt_capacity", value: 1 }],
          },
        }),
      ],
    },
  };


  runtimeWindow.__ROUGE_OPP_STAGING = runtimeWindow.__ROUGE_OPP_STAGING || {};
  runtimeWindow.__ROUGE_OPP_STAGING.detourOpportunityDefinitions = DETOUR_OPPORTUNITY_DEFINITIONS;
})();
