(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;
  const helpers = runtimeWindow.__ROUGE_OPP_HELPERS;
  const buildEscalationChoice = (...args) => helpers.buildOpportunityChoice("Escalation Opportunity", ...args);
  const { buildLateRouteVariant } = helpers;

  const ESCALATION_OPPORTUNITY_DEFINITIONS: Record<number, EscalationOpportunityDefinition> = {
    1: {
      kind: "opportunity",
      id: "rogue_escalation_opportunity",
      title: "Catacomb Escalation",
      zoneTitle: "Catacomb Escalation",
      description: "After the monastery covenant closes, the rogue line can also sharpen into a harsher escalation that spends the late gains on direct pressure.",
      summary: "The post-covenant route now fans back out into a higher-risk rogue escalation lane.",
      grants: { gold: 10, xp: 12, potions: 0 },
      requiresQuestId: "tristram_relief",
      requiresLegacyOpportunityId: "rogue_legacy_opportunity",
      requiresReckoningOpportunityId: "rogue_reckoning_opportunity",
      requiresCovenantOpportunityId: "rogue_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildEscalationChoice, "rogue_escalation_opportunity", "tristram_relief", {
          id: "ridge_escalation",
          title: "Ridge Escalation",
          description: "Even without a cleaner line, the rogues can still turn the late route into one final ridge push.",
          summary: "A fallback escalation opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "press_the_ridge_watch",
            title: "Press the Ridge Watch",
            description: "Spend the late route on a direct ridge surge instead of another slower sweep.",
            consequenceId: "ridge_watch_pressed",
            flagIds: ["rogue_escalation_ridge_watch"],
            extraEffects: [{ kind: "gold_bonus", value: 12 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "rogue_escalation_opportunity", "tristram_relief", {
          id: "ledger_escalation",
          title: "Ledger Escalation",
          description: "Legacy wayfinders and the chapel ledger turn the escalation lane into a true pressure route instead of one more ridge check.",
          summary: "The legacy and reckoning lanes now sharpen the monastery into a direct strike route.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["rogue_legacy_wayfinder_chain", "rogue_reckoning_chapel_ledger"],
          choice: {
            outcomeId: "crack_the_chapel_surge",
            title: "Crack the Chapel Surge",
            description: "Turn the wayfinder chain and chapel ledger into a harder pressure wave through the monastery.",
            consequenceId: "chapel_surge_cracked",
            flagIds: ["rogue_escalation_chapel_surge"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "rogue_escalation_opportunity", "tristram_relief", {
          id: "catacomb_escalation",
          title: "Catacomb Escalation",
          description: "The sealed wayfinder ledger turns the escalation into a full catacomb surge that changes how the next elite line behaves.",
          summary: "A full rogue late-route close can now be spent on one sharper catacomb surge instead of another cautious setup.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["rogue_legacy_wayfinder_chain", "rogue_reckoning_chapel_ledger", "rogue_covenant_wayfinder_ledger"],
          choice: {
            outcomeId: "drive_the_catacomb_surge",
            title: "Drive the Catacomb Surge",
            description: "Spend the legacy, reckoning, and covenant lines on one direct catacomb surge before Andariel.",
            consequenceId: "catacomb_surge_driven",
            flagIds: ["rogue_escalation_catacomb_surge"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }, { kind: "hero_max_energy", value: 1 }],
          },
        }),
      ],
    },
    2: {
      kind: "opportunity",
      id: "sunwell_escalation_opportunity",
      title: "Chamber Escalation",
      zoneTitle: "Chamber Escalation",
      description: "After the reliquary covenant closes, the desert line can also sharpen into a harsher escalation that spends the late gains on a direct chamber breach.",
      summary: "The post-covenant route now fans back out into a higher-risk desert escalation lane.",
      grants: { gold: 10, xp: 12, potions: 0 },
      requiresQuestId: "lost_reliquary",
      requiresLegacyOpportunityId: "sunwell_legacy_opportunity",
      requiresReckoningOpportunityId: "sunwell_reckoning_opportunity",
      requiresCovenantOpportunityId: "sunwell_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildEscalationChoice, "sunwell_escalation_opportunity", "lost_reliquary", {
          id: "dune_escalation",
          title: "Dune Escalation",
          description: "Even without a truer lance route, the desert can still spend the late path on one final dune push.",
          summary: "A fallback escalation opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "press_the_dune_push",
            title: "Press the Dune Push",
            description: "Turn the late route into one harder dune push instead of another slower screen.",
            consequenceId: "dune_push_pressed",
            flagIds: ["sunwell_escalation_dune_push"],
            extraEffects: [{ kind: "gold_bonus", value: 12 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "sunwell_escalation_opportunity", "lost_reliquary", {
          id: "lance_escalation",
          title: "Lance Escalation",
          description: "Legacy spear posts and lance wards turn the escalation lane into a true chamber breach instead of one more dune probe.",
          summary: "The legacy and reckoning lanes now sharpen the desert into a direct strike route.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["sunwell_legacy_last_spear_posts", "sunwell_reckoning_lance_wards"],
          choice: {
            outcomeId: "crack_the_lance_breach",
            title: "Crack the Lance Breach",
            description: "Turn the spear posts and lance wards into a harder breach through the next reliquary line.",
            consequenceId: "lance_breach_cracked",
            flagIds: ["sunwell_escalation_lance_breach"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "sunwell_escalation_opportunity", "lost_reliquary", {
          id: "chamber_escalation",
          title: "Chamber Escalation",
          description: "The final lance ledger turns the escalation into a full chamber surge that changes how the next elite line behaves.",
          summary: "A full desert late-route close can now be spent on one sharper chamber surge instead of another cautious setup.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["sunwell_legacy_last_spear_posts", "sunwell_reckoning_lance_wards", "sunwell_covenant_final_lance_ledger"],
          choice: {
            outcomeId: "drive_the_chamber_surge",
            title: "Drive the Chamber Surge",
            description: "Spend the legacy, reckoning, and covenant lines on one direct chamber surge before Duriel.",
            consequenceId: "chamber_surge_driven",
            flagIds: ["sunwell_escalation_chamber_surge"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }, { kind: "hero_max_life", value: 3 }],
          },
        }),
      ],
    },
    3: {
      kind: "opportunity",
      id: "kurast_escalation_opportunity",
      title: "Durance Escalation",
      zoneTitle: "Durance Escalation",
      description: "After the harbor covenant closes, Kurast can also sharpen into a harsher escalation that spends the late gains on a direct durance push.",
      summary: "The post-covenant route now fans back out into a higher-risk harbor escalation lane.",
      grants: { gold: 10, xp: 12, potions: 0 },
      requiresQuestId: "smugglers_wake",
      requiresLegacyOpportunityId: "kurast_legacy_opportunity",
      requiresReckoningOpportunityId: "kurast_reckoning_opportunity",
      requiresCovenantOpportunityId: "kurast_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildEscalationChoice, "kurast_escalation_opportunity", "smugglers_wake", {
          id: "dock_escalation",
          title: "Dock Escalation",
          description: "Even without a truer spellward line, Kurast can still spend the late route on one final dock push.",
          summary: "A fallback escalation opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "press_the_dock_push",
            title: "Press the Dock Push",
            description: "Turn the late route into one harder dockside push instead of another slower river screen.",
            consequenceId: "dock_push_pressed",
            flagIds: ["kurast_escalation_dock_push"],
            extraEffects: [{ kind: "gold_bonus", value: 12 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "kurast_escalation_opportunity", "smugglers_wake", {
          id: "seal_escalation",
          title: "Seal Escalation",
          description: "Legacy spellwards and harbor seals turn the escalation lane into a true durance breach instead of one more dock probe.",
          summary: "The legacy and reckoning lanes now sharpen the harbor into a direct strike route.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["kurast_legacy_last_spellward", "kurast_reckoning_harbor_seals"],
          choice: {
            outcomeId: "crack_the_harbor_seal_push",
            title: "Crack the Harbor Seal Push",
            description: "Turn the spellward legacy and harbor seals into a harder surge through the next river line.",
            consequenceId: "harbor_seal_push_cracked",
            flagIds: ["kurast_escalation_harbor_push"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "kurast_escalation_opportunity", "smugglers_wake", {
          id: "durance_escalation",
          title: "Durance Escalation",
          description: "The spellward ledger turns the escalation into a full durance surge that changes how the next elite line behaves.",
          summary: "A full harbor late-route close can now be spent on one sharper durance surge instead of another cautious setup.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["kurast_legacy_last_spellward", "kurast_reckoning_harbor_seals", "kurast_covenant_spellward_ledger"],
          choice: {
            outcomeId: "drive_the_durance_surge",
            title: "Drive the Durance Surge",
            description: "Spend the legacy, reckoning, and covenant lines on one direct durance surge before Mephisto.",
            consequenceId: "durance_surge_driven",
            flagIds: ["kurast_escalation_durance_surge"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }, { kind: "hero_max_energy", value: 1 }],
          },
        }),
      ],
    },
    4: {
      kind: "opportunity",
      id: "hellforge_escalation_opportunity",
      title: "Sanctuary Escalation",
      zoneTitle: "Sanctuary Escalation",
      description: "After the sanctuary covenant closes, the forge line can also sharpen into a harsher escalation that spends the late gains on a direct sanctuary breach.",
      summary: "The post-covenant route now fans back out into a higher-risk sanctuary escalation lane.",
      grants: { gold: 12, xp: 12, potions: 0 },
      requiresQuestId: "hellforge_claim",
      requiresLegacyOpportunityId: "hellforge_legacy_opportunity",
      requiresReckoningOpportunityId: "hellforge_reckoning_opportunity",
      requiresCovenantOpportunityId: "hellforge_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildEscalationChoice, "hellforge_escalation_opportunity", "hellforge_claim", {
          id: "ash_escalation",
          title: "Ash Escalation",
          description: "Even without a truer breachscreen line, the sanctuary can still spend the late route on one final ash push.",
          summary: "A fallback escalation opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "press_the_ash_push",
            title: "Press the Ash Push",
            description: "Turn the late route into one harder ash-belt push instead of another slower relief line.",
            consequenceId: "ash_push_pressed",
            flagIds: ["hellforge_escalation_ash_push"],
            extraEffects: [{ kind: "gold_bonus", value: 12 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "hellforge_escalation_opportunity", "hellforge_claim", {
          id: "screen_escalation",
          title: "Screen Escalation",
          description: "Legacy breachscreens and sanctuary screens turn the escalation lane into a true infernal break instead of one more ash probe.",
          summary: "The legacy and reckoning lanes now sharpen the sanctuary into a direct strike route.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["hellforge_legacy_last_breachscreen", "hellforge_reckoning_sanctuary_screens"],
          choice: {
            outcomeId: "crack_the_sanctuary_screen",
            title: "Crack the Sanctuary Screen",
            description: "Turn the breachscreen legacy and sanctuary screens into a harder surge through the next infernal line.",
            consequenceId: "sanctuary_screen_cracked",
            flagIds: ["hellforge_escalation_sanctuary_screen"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "hellforge_escalation_opportunity", "hellforge_claim", {
          id: "sanctuary_escalation",
          title: "Sanctuary Escalation",
          description: "The breachscreen ledger turns the escalation into a full sanctuary surge that changes how the next elite line behaves.",
          summary: "A full sanctuary late-route close can now be spent on one sharper infernal surge instead of another cautious setup.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["hellforge_legacy_last_breachscreen", "hellforge_reckoning_sanctuary_screens", "hellforge_covenant_breachscreen_ledger"],
          choice: {
            outcomeId: "drive_the_sanctuary_surge",
            title: "Drive the Sanctuary Surge",
            description: "Spend the legacy, reckoning, and covenant lines on one direct sanctuary surge before Diablo.",
            consequenceId: "sanctuary_surge_driven",
            flagIds: ["hellforge_escalation_sanctuary_surge"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }, { kind: "hero_max_life", value: 3 }],
          },
        }),
      ],
    },
    5: {
      kind: "opportunity",
      id: "harrogath_escalation_opportunity",
      title: "Worldstone Escalation",
      zoneTitle: "Worldstone Escalation",
      description: "After the summit covenant closes, Harrogath can also sharpen into a harsher escalation that spends the late gains on a direct Worldstone surge.",
      summary: "The post-covenant route now fans back out into a higher-risk summit escalation lane.",
      grants: { gold: 12, xp: 14, potions: 0 },
      requiresQuestId: "harrogath_rescue",
      requiresLegacyOpportunityId: "harrogath_legacy_opportunity",
      requiresReckoningOpportunityId: "harrogath_reckoning_opportunity",
      requiresCovenantOpportunityId: "harrogath_covenant_opportunity",
      variants: [
        buildLateRouteVariant(buildEscalationChoice, "harrogath_escalation_opportunity", "harrogath_rescue", {
          id: "watch_escalation",
          title: "Watch Escalation",
          description: "Even without a truer summit line, Harrogath can still spend the late route on one final watch push.",
          summary: "A fallback escalation opens after the covenant resolves.",
          grants: { gold: 6, xp: 8, potions: 0 },
          choice: {
            outcomeId: "press_the_watch_push",
            title: "Press the Watch Push",
            description: "Turn the late route into one harder summit watch push instead of another slower sled sweep.",
            consequenceId: "watch_push_pressed",
            flagIds: ["harrogath_escalation_watch_push"],
            extraEffects: [{ kind: "gold_bonus", value: 12 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "harrogath_escalation_opportunity", "harrogath_rescue", {
          id: "oath_escalation",
          title: "Oath Escalation",
          description: "Legacy guard ranks and oath rations turn the escalation lane into a true Worldstone breach instead of one more summit probe.",
          summary: "The legacy and reckoning lanes now sharpen the summit into a direct strike route.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["harrogath_legacy_last_guard_ranks", "harrogath_reckoning_oath_rations"],
          choice: {
            outcomeId: "crack_the_oath_surge",
            title: "Crack the Oath Surge",
            description: "Turn the guard ranks and oath rations into a harder surge through the next summit line.",
            consequenceId: "oath_surge_cracked",
            flagIds: ["harrogath_escalation_oath_surge"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }],
          },
        }),
        buildLateRouteVariant(buildEscalationChoice, "harrogath_escalation_opportunity", "harrogath_rescue", {
          id: "worldstone_escalation",
          title: "Worldstone Escalation",
          description: "The Ancients ledger turns the escalation into a full Worldstone surge that changes how the next elite line behaves.",
          summary: "A full summit late-route close can now be spent on one sharper Worldstone surge instead of another cautious setup.",
          grants: { gold: 8, xp: 8, potions: 0 },
          requiresFlagIds: ["harrogath_legacy_last_guard_ranks", "harrogath_reckoning_oath_rations", "harrogath_covenant_ancients_ledger"],
          choice: {
            outcomeId: "drive_the_worldstone_surge",
            title: "Drive the Worldstone Surge",
            description: "Spend the legacy, reckoning, and covenant lines on one direct Worldstone surge before Baal.",
            consequenceId: "worldstone_surge_driven",
            flagIds: ["harrogath_escalation_worldstone_surge"],
            extraEffects: [{ kind: "mercenary_attack", value: 1 }, { kind: "hero_max_life", value: 4 }],
          },
        }),
      ],
    },
  };

  runtimeWindow.__ROUGE_OPP_STAGING = runtimeWindow.__ROUGE_OPP_STAGING || {};
  runtimeWindow.__ROUGE_OPP_STAGING.escalationOpportunityDefinitions = ESCALATION_OPPORTUNITY_DEFINITIONS;
})();
