(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  const LIMITS = {
    COMBAT_LOG_SIZE: 18,
    STASH_PREVIEW_IDS: 4,
    STASH_PREVIEW_ENTRIES: 4,
    RUN_HISTORY_PREVIEW: 4,
    RECENT_RUNS_SCAN: 4,
    RECENT_FEATURE_IDS: 6,
    RECENT_RUNEWORD_IDS: 6,
    REWARD_CHOICES: 3,
    CARD_CHOICES: 3,
    TUTORIAL_CATEGORY_PREVIEW: 3,
    TUTORIAL_ACTION_ROWS: 2,
    TOWN_FEATURES_PREVIEW: 3,
    WORLD_OUTCOMES_LOG: 6,
    LABEL_PREVIEW: 2,
    BONUS_PREVIEW: 2,
    PROGRESSION_PREVIEW_LINES: 2,
    MARKET_PREVIEW_LINES: 3,
    PLANNING_STAGE_COMPACT: 1,
    PLANNING_STAGE_EXTENDED: 2,
    RECENT_RUNS_SUMMARY: 3,
    NIGHTMARE_HELL_GUEST_ENEMIES: 6,
  };

  runtimeWindow.ROUGE_LIMITS = LIMITS;
})();
