(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  const ICON_BASE = "./assets/curated/icons";
  const SKILL_ICON_BASE = `${ICON_BASE}/skills`;
  const SPRITE_BASE = "./assets/curated/sprites";
  const PORTRAIT_BASE = "./assets/curated/portraits";

  // ── Card Icons ──
  const CARD_ICONS: Record<string, string> = {
    strike: `${SKILL_ICON_BASE}/barbarian/bash.png`,
    defend: `${SKILL_ICON_BASE}/paladin/defiance.png`,
    rally_mercenary: `${SKILL_ICON_BASE}/barbarian/battle_command.png`,
    execution_blow: `${SKILL_ICON_BASE}/barbarian/berserk.png`,
    multishot: `${SKILL_ICON_BASE}/amazon/multiple_shot.png`,
    emberstorm: `${SKILL_ICON_BASE}/sorceress/meteor.png`,
    barbarian_bash: `${SKILL_ICON_BASE}/barbarian/bash.png`,
    barbarian_howl: `${SKILL_ICON_BASE}/barbarian/howl.png`,
    barbarian_sword_mastery: `${SKILL_ICON_BASE}/barbarian/sword_mastery.png`,
    barbarian_find_potion: `${SKILL_ICON_BASE}/barbarian/find_potion.png`,
    barbarian_iron_skin: `${SKILL_ICON_BASE}/barbarian/iron_skin.png`,
    barbarian_natural_resistance: `${SKILL_ICON_BASE}/barbarian/natural_resistance.png`,
    barbarian_double_swing: `${SKILL_ICON_BASE}/barbarian/double_swing.png`,
    barbarian_leap: `${SKILL_ICON_BASE}/barbarian/leap.png`,
    barbarian_shout: `${SKILL_ICON_BASE}/barbarian/shout.png`,
    barbarian_stun: `${SKILL_ICON_BASE}/barbarian/stun.png`,
    barbarian_concentrate: `${SKILL_ICON_BASE}/barbarian/concentrate.png`,
    barbarian_frenzy: `${SKILL_ICON_BASE}/barbarian/frenzy.png`,
    barbarian_battle_orders: `${SKILL_ICON_BASE}/barbarian/battle_orders.png`,
    barbarian_leap_attack: `${SKILL_ICON_BASE}/barbarian/leap_attack.png`,
    barbarian_whirlwind: `${SKILL_ICON_BASE}/barbarian/whirlwind.png`,
    barbarian_berserk: `${SKILL_ICON_BASE}/barbarian/berserk.png`,
    barbarian_war_cry: `${SKILL_ICON_BASE}/barbarian/war_cry.png`,
    paladin_sacrifice: `${SKILL_ICON_BASE}/paladin/sacrifice.png`,
    paladin_might: `${SKILL_ICON_BASE}/paladin/might.png`,
    paladin_prayer: `${SKILL_ICON_BASE}/paladin/prayer.png`,
    paladin_smite: `${SKILL_ICON_BASE}/paladin/smite.png`,
    paladin_thorns: `${SKILL_ICON_BASE}/paladin/thorns.png`,
    paladin_cleansing: `${SKILL_ICON_BASE}/paladin/cleansing.png`,
    paladin_holy_bolt: `${SKILL_ICON_BASE}/paladin/holy_bolt.png`,
    paladin_holy_fire: `${SKILL_ICON_BASE}/paladin/holy_fire.png`,
    paladin_defiance: `${SKILL_ICON_BASE}/paladin/defiance.png`,
    paladin_zeal: `${SKILL_ICON_BASE}/paladin/zeal.png`,
    paladin_vengeance: `${SKILL_ICON_BASE}/paladin/vengeance.png`,
    paladin_blessed_hammer: `${SKILL_ICON_BASE}/paladin/blessed_hammer.png`,
    paladin_holy_freeze: `${SKILL_ICON_BASE}/paladin/holy_freeze.png`,
    paladin_holy_shield: `${SKILL_ICON_BASE}/paladin/holy_shield.png`,
    paladin_fist_of_the_heavens: `${SKILL_ICON_BASE}/paladin/fist_of_the_heavens.png`,
    paladin_fanaticism: `${SKILL_ICON_BASE}/paladin/fanaticism.png`,
    paladin_conviction: `${SKILL_ICON_BASE}/paladin/conviction.png`,
    amazon_magic_arrow: `${SKILL_ICON_BASE}/amazon/magic_arrow.png`,
    amazon_jab: `${SKILL_ICON_BASE}/amazon/jab.png`,
    amazon_inner_sight: `${SKILL_ICON_BASE}/amazon/inner_sight.png`,
    amazon_fire_arrow: `${SKILL_ICON_BASE}/amazon/fire_arrow.png`,
    amazon_dodge: `${SKILL_ICON_BASE}/amazon/dodge.png`,
    amazon_critical_strike: `${SKILL_ICON_BASE}/amazon/critical_strike.png`,
    amazon_cold_arrow: `${SKILL_ICON_BASE}/amazon/cold_arrow.png`,
    amazon_multiple_shot: `${SKILL_ICON_BASE}/amazon/multiple_shot.png`,
    amazon_power_strike: `${SKILL_ICON_BASE}/amazon/power_strike.png`,
    amazon_exploding_arrow: `${SKILL_ICON_BASE}/amazon/exploding_arrow.png`,
    amazon_guided_arrow: `${SKILL_ICON_BASE}/amazon/guided_arrow.png`,
    amazon_charged_strike: `${SKILL_ICON_BASE}/amazon/charged_strike.png`,
    amazon_strafe: `${SKILL_ICON_BASE}/amazon/strafe.png`,
    amazon_valkyrie: `${SKILL_ICON_BASE}/amazon/valkyrie.png`,
    amazon_freezing_arrow: `${SKILL_ICON_BASE}/amazon/freezing_arrow.png`,
    amazon_lightning_fury: `${SKILL_ICON_BASE}/amazon/lightning_fury.png`,
    assassin_tiger_strike: `${SKILL_ICON_BASE}/assassin/tiger_strike.png`,
    assassin_fire_blast: `${SKILL_ICON_BASE}/assassin/fire_blast.png`,
    assassin_claw_mastery: `${SKILL_ICON_BASE}/assassin/claw_mastery.png`,
    assassin_psychic_hammer: `${SKILL_ICON_BASE}/assassin/psychic_hammer.png`,
    assassin_blade_shield: `${SKILL_ICON_BASE}/assassin/blade_shield.png`,
    assassin_cloak_of_shadows: `${SKILL_ICON_BASE}/assassin/cloak_of_shadows.png`,
    assassin_fists_of_fire: `${SKILL_ICON_BASE}/assassin/fists_of_fire.png`,
    assassin_burst_of_speed: `${SKILL_ICON_BASE}/assassin/burst_of_speed.png`,
    assassin_wake_of_fire: `${SKILL_ICON_BASE}/assassin/wake_of_fire.png`,
    assassin_cobra_strike: `${SKILL_ICON_BASE}/assassin/cobra_strike.png`,
    assassin_claws_of_thunder: `${SKILL_ICON_BASE}/assassin/claws_of_thunder.png`,
    assassin_fade: `${SKILL_ICON_BASE}/assassin/fade.png`,
    assassin_lightning_sentry: `${SKILL_ICON_BASE}/assassin/lightning_sentry.png`,
    assassin_shadow_warrior: `${SKILL_ICON_BASE}/assassin/shadow_warrior.png`,
    assassin_phoenix_strike: `${SKILL_ICON_BASE}/assassin/phoenix_strike.png`,
    assassin_death_sentry: `${SKILL_ICON_BASE}/assassin/death_sentry.png`,
    druid_firestorm: `${SKILL_ICON_BASE}/druid/firestorm.png`,
    druid_werewolf: `${SKILL_ICON_BASE}/druid/werewolf.png`,
    druid_raven: `${SKILL_ICON_BASE}/druid/raven.png`,
    druid_poison_creeper: `${SKILL_ICON_BASE}/druid/poison_creeper.png`,
    druid_cyclone_armor: `${SKILL_ICON_BASE}/druid/cyclone_armor.png`,
    druid_lycanthropy: `${SKILL_ICON_BASE}/druid/lycanthropy.png`,
    druid_molten_boulder: `${SKILL_ICON_BASE}/druid/molten_boulder.png`,
    druid_werebear: `${SKILL_ICON_BASE}/druid/werebear.png`,
    druid_oak_sage: `${SKILL_ICON_BASE}/druid/oak_sage.png`,
    druid_fissure: `${SKILL_ICON_BASE}/druid/fissure.png`,
    druid_volcano: `${SKILL_ICON_BASE}/druid/volcano.png`,
    druid_fury: `${SKILL_ICON_BASE}/druid/fury.png`,
    druid_heart_of_wolverine: `${SKILL_ICON_BASE}/druid/heart_of_wolverine.png`,
    druid_tornado: `${SKILL_ICON_BASE}/druid/tornado.png`,
    druid_hurricane: `${SKILL_ICON_BASE}/druid/hurricane.png`,
    druid_armageddon: `${SKILL_ICON_BASE}/druid/armageddon.png`,
    druid_summon_grizzly: `${SKILL_ICON_BASE}/druid/summon_grizzly.png`,
    sorceress_ice_bolt: `${SKILL_ICON_BASE}/sorceress/ice_bolt.png`,
    sorceress_fire_bolt: `${SKILL_ICON_BASE}/sorceress/fire_bolt.png`,
    sorceress_charged_bolt: `${SKILL_ICON_BASE}/sorceress/charged_bolt.png`,
    sorceress_warmth: `${SKILL_ICON_BASE}/sorceress/warmth.png`,
    sorceress_energy_shield: `${SKILL_ICON_BASE}/sorceress/energy_shield.png`,
    sorceress_frozen_armor: `${SKILL_ICON_BASE}/sorceress/frozen_armor.png`,
    sorceress_frost_nova: `${SKILL_ICON_BASE}/sorceress/frost_nova.png`,
    sorceress_fireball: `${SKILL_ICON_BASE}/sorceress/fire_ball.png`,
    sorceress_static_field: `${SKILL_ICON_BASE}/sorceress/static_field.png`,
    sorceress_inferno: `${SKILL_ICON_BASE}/sorceress/inferno.png`,
    sorceress_blizzard: `${SKILL_ICON_BASE}/sorceress/blizzard.png`,
    sorceress_meteor: `${SKILL_ICON_BASE}/sorceress/meteor.png`,
    sorceress_chain_lightning: `${SKILL_ICON_BASE}/sorceress/chain_lightning.png`,
    sorceress_teleport: `${SKILL_ICON_BASE}/sorceress/teleport.png`,
    sorceress_frozen_orb: `${SKILL_ICON_BASE}/sorceress/frozen_orb.png`,
    sorceress_hydra: `${SKILL_ICON_BASE}/sorceress/hydra.png`,
    sorceress_lightning_mastery: `${SKILL_ICON_BASE}/sorceress/lightning_mastery.png`,
    necromancer_teeth: `${SKILL_ICON_BASE}/necromancer/teeth.png`,
    necromancer_bone_armor: `${SKILL_ICON_BASE}/necromancer/bone_armor.png`,
    necromancer_amplify_damage: `${SKILL_ICON_BASE}/necromancer/amplify_damage.png`,
    necromancer_raise_skeleton: `${SKILL_ICON_BASE}/necromancer/raise_skeleton.png`,
    necromancer_bone_wall: `${SKILL_ICON_BASE}/necromancer/bone_wall.png`,
    necromancer_life_tap: `${SKILL_ICON_BASE}/necromancer/life_tap.png`,
    necromancer_corpse_explosion: `${SKILL_ICON_BASE}/necromancer/corpse_explosion.png`,
    necromancer_clay_golem: `${SKILL_ICON_BASE}/necromancer/clay_golem.png`,
    necromancer_iron_maiden: `${SKILL_ICON_BASE}/necromancer/iron_maiden.png`,
    necromancer_poison_dagger: `${SKILL_ICON_BASE}/necromancer/poison_dagger.png`,
    necromancer_bone_spear: `${SKILL_ICON_BASE}/necromancer/bone_spear.png`,
    necromancer_blood_golem: `${SKILL_ICON_BASE}/necromancer/blood_golem.png`,
    necromancer_decrepify: `${SKILL_ICON_BASE}/necromancer/decrepify.png`,
    necromancer_skeletal_mage: `${SKILL_ICON_BASE}/necromancer/skeletal_mage.png`,
    necromancer_bone_spirit: `${SKILL_ICON_BASE}/necromancer/bone_spirit.png`,
    necromancer_poison_nova: `${SKILL_ICON_BASE}/necromancer/poison_nova.png`,
    necromancer_revive: `${SKILL_ICON_BASE}/necromancer/revive.png`,
  };

  const ATTACK_ICONS = [
    `${ICON_BASE}/cards/01_steam-blast.svg`,
    `${ICON_BASE}/cards/02_bolt-bomb.svg`,
    `${ICON_BASE}/cards/03_drill.svg`,
    `${ICON_BASE}/cards/04_laser-blast.svg`,
    `${ICON_BASE}/cards/05_overdrive.svg`,
    `${ICON_BASE}/cards/06_cogsplosion.svg`,
  ];

  const SKILL_ICONS = [
    `${ICON_BASE}/cards/09_valve.svg`,
    `${ICON_BASE}/cards/10_steam.svg`,
    `${ICON_BASE}/cards/11_bellows.svg`,
    `${ICON_BASE}/cards/12_plug.svg`,
    `${ICON_BASE}/cards/13_battery-plus.svg`,
    `${ICON_BASE}/cards/17_power-generator.svg`,
  ];

  const ENEMY_SVGS = [
    `${ICON_BASE}/enemies/01_steam-locomotive.svg`,
    `${ICON_BASE}/enemies/02_iron-hulled-warship.svg`,
    `${ICON_BASE}/enemies/03_dreadnought.svg`,
    `${ICON_BASE}/enemies/04_gas-mask.svg`,
    `${ICON_BASE}/enemies/05_mechanical-arm.svg`,
    `${ICON_BASE}/enemies/06_walking-turret.svg`,
    `${ICON_BASE}/enemies/07_laser-turret.svg`,
    `${ICON_BASE}/enemies/08_spoutnik.svg`,
    `${ICON_BASE}/enemies/09_satellite.svg`,
    `${ICON_BASE}/enemies/10_tesla.svg`,
    `${ICON_BASE}/enemies/11_frankenstein-creature.svg`,
    `${ICON_BASE}/enemies/12_zeppelin.svg`,
  ];

  const UI_ICONS: Record<string, string> = {
    hp: `${ICON_BASE}/ui/hp_life-bar.svg`,
    energy: `${ICON_BASE}/ui/energy_battery-50.svg`,
    guard: `${ICON_BASE}/ui/power_plug.svg`,
    burn: `${ICON_BASE}/ui/heat_radiations.svg`,
    turn: `${ICON_BASE}/ui/turn_pocket-watch.svg`,
    alert: `${ICON_BASE}/ui/alert_wall-light.svg`,
    crit: `${ICON_BASE}/ui/crit_cross-flare.svg`,
    idea: `${ICON_BASE}/ui/idea_light-bulb.svg`,
  };

  const INTENT_ICONS: Record<string, string> = {
    attack: `${ICON_BASE}/cards/01_steam-blast.svg`,
    guard: `${ICON_BASE}/cards/09_valve.svg`,
    buff: `${ICON_BASE}/cards/13_battery-plus.svg`,
    debuff: `${ICON_BASE}/cards/14_battery-minus.svg`,
    heal: `${ICON_BASE}/cards/13_battery-plus.svg`,
    unknown: `${ICON_BASE}/ui/idea_light-bulb.svg`,
  };

  const CLASS_PORTRAITS: Record<string, string> = {
    amazon: `${PORTRAIT_BASE}/amazon.png`,
    assassin: `${PORTRAIT_BASE}/assassin.png`,
    barbarian: `${PORTRAIT_BASE}/barbarian.png`,
    druid: `${PORTRAIT_BASE}/druid.png`,
    necromancer: `${PORTRAIT_BASE}/necromancer.png`,
    paladin: `${PORTRAIT_BASE}/paladin.png`,
    sorceress: `${PORTRAIT_BASE}/sorceress.png`,
  };

  const KNOWN_ENEMY_SPRITES = new Set([
    "abominable","baal_s_minion","baboon_demon","bat_demon","blood_hawk",
    "blood_hawk_nest","blood_lord","blunderbore","bone_fetish","catapult",
    "claw_viper","corrupt_rogue","corrupt_rogue_archer","corrupt_rogue_spearwoman",
    "council_member","death_mauler","demon_imp","fallen","fallen_shaman",
    "fetish","fetish_shaman","fire_tower","flying_scimitar","frog_demon",
    "frozen_horror","gargoyle_trap","giant_mosquito","giant_spider","goatman",
    "leaper","lightning_spire","megademon","minion_of_destruction","mummy",
    "mummy_sarcophagus","oblivion_knight","overseer","pain_worm",
    "reanimated_horde","regurgitator","reziarfg","sabre_cat","sand_maggot",
    "sand_maggot_egg","sand_maggot_young","sand_raider","scarab_demon",
    "siege_beast","skeleton","skeleton_archer","skeleton_mage","slinger",
    "spike_fiend","stygian_fury","succubus","suicide_minion","swarm",
    "tainted","undead_horror","vampire","vile_child","vile_mother",
    "vulture_demon","wendigo","willowisp","wraith","zakarum_priest",
    "zakarum_zealot","zombie",
  ]);

  const VARIANT_SPRITE_MAP: Record<string, string> = {
    dark_hunter: "corrupt_rogue_archer", dark_ranger: "corrupt_rogue_archer",
    dark_spearwoman: "corrupt_rogue_spearwoman", black_rogue: "corrupt_rogue",
    dark_stalker: "corrupt_rogue", vile_hunter: "corrupt_rogue_archer",
    vile_lancer: "corrupt_rogue_spearwoman", flesh_hunter: "corrupt_rogue_archer",
    night_clan: "goatman", blood_clan: "goatman", moon_clan: "goatman",
    hell_clan: "goatman", death_clan: "goatman",
    bone_warrior: "skeleton", bone_archer: "skeleton_archer", bone_mage: "skeleton_mage",
    burning_dead: "skeleton", burning_dead_archer: "skeleton_archer", burning_dead_mage: "skeleton_mage",
    horror: "skeleton", horror_archer: "skeleton_archer", horror_mage: "skeleton_mage",
    returned: "skeleton", returned_archer: "skeleton_archer", returned_mage: "skeleton_mage",
    hungry_dead: "zombie", ghoul: "zombie", drowned_carcass: "zombie",
    plague_bearer: "zombie", cadaver: "zombie",
    brute: "wendigo", gargantuan_beast: "wendigo", yeti: "wendigo",
    carver: "fallen", carver_shaman: "fallen_shaman",
    devilkin: "fallen", devilkin_shaman: "fallen_shaman",
    dark_one: "fallen", dark_one_shaman: "fallen_shaman",
    warped_one: "fallen", warped_shaman: "fallen_shaman",
    quill_rat: "spike_fiend", thorn_beast: "spike_fiend", razor_spine: "spike_fiend",
    foul_crow: "blood_hawk", foul_crow_nest: "blood_hawk_nest",
    black_raptor: "blood_hawk", black_vulture_nest: "blood_hawk_nest",
    cloud_stalker: "blood_hawk", cloud_stalker_nest: "blood_hawk_nest",
    huntress: "sabre_cat", spear_cat: "sabre_cat", night_tiger: "sabre_cat", hell_cat: "sabre_cat",
    cave_leaper: "leaper", tomb_creeper: "leaper", tree_lurker: "leaper", sand_leaper: "leaper",
    dung_soldier: "scarab_demon",
    sand_warrior: "sand_raider", marauder: "sand_raider", invader: "sand_raider",
    infidel: "sand_raider", assailant: "sand_raider",
    itchies: "swarm", black_locusts: "swarm", hell_swarm: "swarm", plague_bugs: "swarm",
    sucker: "giant_mosquito", feeder: "giant_mosquito", blood_hook: "giant_mosquito",
    flayer: "fetish", flayer_shaman: "fetish_shaman",
    soul_killer: "fetish", soul_killer_shaman: "fetish_shaman",
    stygian_doll: "fetish", jungle_hunter: "fetish",
    thorned_hulk: "wendigo", bramble_hulk: "wendigo", thrasher: "wendigo",
    bog_creature: "wendigo", swamp_dweller: "wendigo",
    slime_prince: "frog_demon",
    gloam: "willowisp", burning_soul: "willowisp", black_soul: "willowisp",
    doom_caster: "oblivion_knight", abyss_knight: "oblivion_knight",
    pit_lord: "megademon", venom_lord: "megademon", balrog: "megademon",
    flesh_spawner: "vile_mother", stygian_hag: "vile_mother", grotesque: "vile_mother",
    flesh_beast: "vile_child", stygian_dog: "vile_child", grotesque_wyrm: "vile_child",
    hell_temptress: "succubus", blood_temptress: "succubus", stygian_fury: "succubus",
    cantor: "zakarum_priest", heirophant: "zakarum_priest",
    zealot: "zakarum_zealot", faithful: "zakarum_zealot",
    apparition: "wraith", specter: "wraith",
    banished: "regurgitator", blood_lord: "blood_lord",
    enslaved: "overseer", slayer: "overseer",
    death_mauler: "death_mauler", minion_of_destruction: "minion_of_destruction",
    undead_scavenger: "zombie",
    saber_cat: "sabre_cat", afflicted: "tainted", misshapen: "tainted", disfigured: "tainted",
    albino_roach: "scarab_demon", scarab: "scarab_demon", steel_weevil: "scarab_demon",
    arach: "giant_spider", flame_spider: "giant_spider",
    poison_spinner: "giant_spider", spider_magus: "giant_spider",
    black_archer: "skeleton_archer", dark_archer: "skeleton_archer",
    black_lancer: "corrupt_rogue_spearwoman", dark_lancer: "corrupt_rogue_spearwoman",
    flesh_archer: "corrupt_rogue_archer", vile_archer: "corrupt_rogue_archer",
    blood_boss: "overseer", overlord: "overseer", lasher: "overseer", hell_whip: "overseer",
    blood_bringer: "blood_lord",
    blood_diver: "bat_demon", blood_wing: "bat_demon", dark_familiar: "bat_demon",
    gloombat: "bat_demon", winged_nightmare: "bat_demon",
    carrion_bird: "vulture_demon", hell_buzzard: "vulture_demon",
    corpse_spitter: "regurgitator", putrid_defiler: "regurgitator",
    corpulent: "zombie", gorbelly: "zombie", prowling_dead: "zombie",
    rot_walker: "zombie", unholy_corpse: "zombie",
    crush_beast: "siege_beast", crusher: "siege_beast",
    damned: "wraith", dark_shape: "wraith", ghost: "wraith",
    defiled_warrior: "skeleton",
    dark_lord: "vampire", night_lord: "vampire", ghoul_lord: "vampire",
    devourer: "sand_maggot", rock_worm: "sand_maggot", giant_lamprey: "sand_maggot",
    groper: "sand_maggot", strangler: "sand_maggot", maw_fiend: "sand_maggot",
    doom_ape: "baboon_demon", doom_knight: "oblivion_knight", dominus: "oblivion_knight",
    dried_corpse: "mummy", embalmed: "mummy", preserved_dead: "mummy",
    sexton: "mummy", horadrim_ancient: "mummy", unraveler: "mummy",
    guardian: "mummy_sarcophagus",
    dune_beast: "wendigo", wailing_beast: "wendigo", snow_yeti: "wendigo",
    ancient_barbarian_1: "wendigo", ancient_barbarian_2: "wendigo", ancient_barbarian_3: "wendigo",
    fiend: "spike_fiend", razor_pit_demon: "spike_fiend",
    fire_boar: "demon_imp", imp: "demon_imp", hell_spawn: "demon_imp", greater_hell_spawn: "demon_imp",
    frenzied_ice_spawn: "frozen_horror", ice_spawn: "frozen_horror",
    hell_bovine: "wendigo",
    hell_slinger: "slinger", night_slinger: "slinger",
    night_marauder: "sand_raider",
    hell_witch: "succubus", stygian_harlot: "succubus",
    vile_temptress: "succubus", vile_witch: "succubus",
    baal_taunt: "baal_s_minion", minion: "baal_s_minion",
    mauler: "death_mauler",
    pit_viper: "claw_viper", salamander: "claw_viper",
    serpent_magus: "claw_viper", tomb_viper: "claw_viper",
    storm_caster: "willowisp",
    rat_man: "fetish", undead_flayer: "fetish",
    undead_soul_killer: "fetish", undead_stygian_doll: "fetish",
    dark_shaman: "fallen_shaman",
    urdar: "megademon", world_killer: "megademon",
    temple_guard: "zakarum_zealot", zakarumite: "zakarum_zealot",
  };

  runtimeWindow.__ROUGE_ASSET_MAP_DATA = {
    ICON_BASE,
    SPRITE_BASE,
    PORTRAIT_BASE,
    CARD_ICONS,
    ATTACK_ICONS,
    SKILL_ICONS,
    ENEMY_SVGS,
    UI_ICONS,
    INTENT_ICONS,
    CLASS_PORTRAITS,
    KNOWN_ENEMY_SPRITES,
    VARIANT_SPRITE_MAP,
  };
})();
