(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  const THEMED_ICON_BASE = "./assets/curated/themes/diablo-inspired/icons";
  const THEMED_CARD_ICON_BASE = `${THEMED_ICON_BASE}/cards`;
  const THEMED_ENEMY_ICON_BASE = `${THEMED_ICON_BASE}/enemies`;
  const THEMED_UI_ICON_BASE = `${THEMED_ICON_BASE}/ui`;
  const CARD_ILLUSTRATION_BASE = "./assets/curated/card-illustrations";
  const MINION_ILLUSTRATION_BASE = "./assets/curated/minion-illustrations";
  const CARD_FRAME_BASE = "./assets/curated/card-frames";
  const UNIQUE_ART_BASE = "./assets/curated/rouge-art";
  const SKILL_ICON_BASE = "./assets/curated/skill-icons";
  const SPRITE_BASE = "./assets/curated/sprites";
  const PORTRAIT_BASE = `${UNIQUE_ART_BASE}/portraits`;
  const RUNE_SPRITE_BASE = `${SPRITE_BASE}/runes`;

  // ── Card Icons ──
  const CARD_ICONS: Record<string, string> = {
    strike: `${SKILL_ICON_BASE}/barbarian/bash.png`,
    defend: `${SKILL_ICON_BASE}/paladin/defiance.png`,
    rally_mercenary: `${SKILL_ICON_BASE}/barbarian/battle_command.png`,
    execution_blow: `${SKILL_ICON_BASE}/barbarian/berserk.png`,
    multishot: `${SKILL_ICON_BASE}/amazon/multiple_shot.png`,
    emberstorm: `${SKILL_ICON_BASE}/sorceress/meteor.png`,
    barbarian_bash: `${SKILL_ICON_BASE}/barbarian/bash.png`,
    barbarian_howl: `${SKILL_ICON_BASE}/barbarian/howl.png`,
    barbarian_sword_mastery: `${SKILL_ICON_BASE}/barbarian/sword_mastery.png`,
    barbarian_find_potion: `${SKILL_ICON_BASE}/barbarian/find_potion.png`,
    barbarian_iron_skin: `${SKILL_ICON_BASE}/barbarian/iron_skin.png`,
    barbarian_natural_resistance: `${SKILL_ICON_BASE}/barbarian/natural_resistance.png`,
    barbarian_double_swing: `${SKILL_ICON_BASE}/barbarian/double_swing.png`,
    barbarian_leap: `${SKILL_ICON_BASE}/barbarian/leap.png`,
    barbarian_shout: `${SKILL_ICON_BASE}/barbarian/shout.png`,
    barbarian_weapon_mastery: `${SKILL_ICON_BASE}/barbarian/sword_mastery.png`,
    barbarian_stun: `${SKILL_ICON_BASE}/barbarian/stun.png`,
    barbarian_concentrate: `${SKILL_ICON_BASE}/barbarian/concentrate.png`,
    barbarian_frenzy: `${SKILL_ICON_BASE}/barbarian/frenzy.png`,
    barbarian_battle_orders: `${SKILL_ICON_BASE}/barbarian/battle_orders.png`,
    barbarian_steel_skin: `${SKILL_ICON_BASE}/barbarian/iron_skin.png`,
    barbarian_leap_attack: `${SKILL_ICON_BASE}/barbarian/leap_attack.png`,
    barbarian_whirlwind: `${SKILL_ICON_BASE}/barbarian/whirlwind.png`,
    barbarian_berserk: `${SKILL_ICON_BASE}/barbarian/berserk.png`,
    barbarian_war_cry: `${SKILL_ICON_BASE}/barbarian/war_cry.png`,
    barbarian_battle_instinct: `${SKILL_ICON_BASE}/barbarian/battle_cry.png`,
    barbarian_unyielding: `${SKILL_ICON_BASE}/barbarian/natural_resistance.png`,
    paladin_sacrifice: `${SKILL_ICON_BASE}/paladin/sacrifice.png`,
    paladin_might: `${SKILL_ICON_BASE}/paladin/might.png`,
    paladin_prayer: `${SKILL_ICON_BASE}/paladin/prayer.png`,
    paladin_smite: `${SKILL_ICON_BASE}/paladin/smite.png`,
    paladin_thorns: `${SKILL_ICON_BASE}/paladin/thorns.png`,
    paladin_cleansing: `${SKILL_ICON_BASE}/paladin/cleansing.png`,
    paladin_holy_bolt: `${SKILL_ICON_BASE}/paladin/holy_bolt.png`,
    paladin_holy_fire: `${SKILL_ICON_BASE}/paladin/holy_fire.png`,
    paladin_defiance: `${SKILL_ICON_BASE}/paladin/defiance.png`,
    paladin_zeal: `${SKILL_ICON_BASE}/paladin/zeal.png`,
    paladin_vengeance: `${SKILL_ICON_BASE}/paladin/vengeance.png`,
    paladin_blessed_hammer: `${SKILL_ICON_BASE}/paladin/blessed_hammer.png`,
    paladin_holy_freeze: `${SKILL_ICON_BASE}/paladin/holy_freeze.png`,
    paladin_holy_shield: `${SKILL_ICON_BASE}/paladin/holy_shield.png`,
    paladin_fist_of_the_heavens: `${SKILL_ICON_BASE}/paladin/fist_of_the_heavens.png`,
    paladin_fanaticism: `${SKILL_ICON_BASE}/paladin/fanaticism.png`,
    paladin_conviction: `${SKILL_ICON_BASE}/paladin/conviction.png`,
    amazon_call_the_shot: `${SKILL_ICON_BASE}/amazon/inner_sight.png`,
    amazon_magic_arrow: `${SKILL_ICON_BASE}/amazon/magic_arrow.png`,
    amazon_jab: `${SKILL_ICON_BASE}/amazon/jab.png`,
    amazon_inner_sight: `${SKILL_ICON_BASE}/amazon/inner_sight.png`,
    amazon_fire_arrow: `${SKILL_ICON_BASE}/amazon/fire_arrow.png`,
    amazon_dodge: `${SKILL_ICON_BASE}/amazon/dodge.png`,
    amazon_critical_strike: `${SKILL_ICON_BASE}/amazon/critical_strike.png`,
    amazon_avoid: `${SKILL_ICON_BASE}/amazon/avoid.png`,
    amazon_cold_arrow: `${SKILL_ICON_BASE}/amazon/cold_arrow.png`,
    amazon_decoy: `${SKILL_ICON_BASE}/amazon/decoy.png`,
    amazon_multiple_shot: `${SKILL_ICON_BASE}/amazon/multiple_shot.png`,
    amazon_penetrate: `${SKILL_ICON_BASE}/amazon/penetrate.png`,
    amazon_power_strike: `${SKILL_ICON_BASE}/amazon/power_strike.png`,
    amazon_exploding_arrow: `${SKILL_ICON_BASE}/amazon/exploding_arrow.png`,
    amazon_slow_missiles: `${SKILL_ICON_BASE}/amazon/slow_missiles.png`,
    amazon_guided_arrow: `${SKILL_ICON_BASE}/amazon/guided_arrow.png`,
    amazon_deadly_strike: `${SKILL_ICON_BASE}/amazon/critical_strike.png`,
    amazon_charged_strike: `${SKILL_ICON_BASE}/amazon/charged_strike.png`,
    amazon_evade: `${SKILL_ICON_BASE}/amazon/evade.png`,
    amazon_strafe: `${SKILL_ICON_BASE}/amazon/strafe.png`,
    amazon_valkyrie: `${SKILL_ICON_BASE}/amazon/valkyrie.png`,
    amazon_freezing_arrow: `${SKILL_ICON_BASE}/amazon/freezing_arrow.png`,
    amazon_lightning_fury: `${SKILL_ICON_BASE}/amazon/lightning_fury.png`,
    amazon_pierce: `${SKILL_ICON_BASE}/amazon/pierce.png`,
    assassin_shadow_feint: `${SKILL_ICON_BASE}/assassin/cloak_of_shadows.png`,
    assassin_tiger_strike: `${SKILL_ICON_BASE}/assassin/tiger_strike.png`,
    assassin_fire_blast: `${SKILL_ICON_BASE}/assassin/fire_blast.png`,
    assassin_claw_mastery: `${SKILL_ICON_BASE}/assassin/claw_mastery.png`,
    assassin_psychic_hammer: `${SKILL_ICON_BASE}/assassin/psychic_hammer.png`,
    assassin_blade_shield: `${SKILL_ICON_BASE}/assassin/blade_shield.png`,
    assassin_cloak_of_shadows: `${SKILL_ICON_BASE}/assassin/cloak_of_shadows.png`,
    assassin_fists_of_fire: `${SKILL_ICON_BASE}/assassin/fists_of_fire.png`,
    assassin_burst_of_speed: `${SKILL_ICON_BASE}/assassin/burst_of_speed.png`,
    assassin_wake_of_fire: `${SKILL_ICON_BASE}/assassin/wake_of_fire.png`,
    assassin_cobra_strike: `${SKILL_ICON_BASE}/assassin/cobra_strike.png`,
    assassin_blades_of_ice: `${SKILL_ICON_BASE}/assassin/blades_of_ice.png`,
    assassin_claws_of_thunder: `${SKILL_ICON_BASE}/assassin/claws_of_thunder.png`,
    assassin_fade: `${SKILL_ICON_BASE}/assassin/fade.png`,
    assassin_lightning_sentry: `${SKILL_ICON_BASE}/assassin/lightning_sentry.png`,
    assassin_shadow_warrior: `${SKILL_ICON_BASE}/assassin/shadow_warrior.png`,
    assassin_phoenix_strike: `${SKILL_ICON_BASE}/assassin/phoenix_strike.png`,
    assassin_death_sentry: `${SKILL_ICON_BASE}/assassin/death_sentry.png`,
    barbarian_core_bash: `${SKILL_ICON_BASE}/barbarian/bash.png`,
    druid_firestorm: `${SKILL_ICON_BASE}/druid/firestorm.png`,
    druid_werewolf: `${SKILL_ICON_BASE}/druid/werewolf.png`,
    druid_raven: `${SKILL_ICON_BASE}/druid/raven.png`,
    druid_poison_creeper: `${SKILL_ICON_BASE}/druid/poison_creeper.png`,
    druid_cyclone_armor: `${SKILL_ICON_BASE}/druid/cyclone_armor.png`,
    druid_lycanthropy: `${SKILL_ICON_BASE}/druid/lycanthropy.png`,
    druid_molten_boulder: `${SKILL_ICON_BASE}/druid/molten_boulder.png`,
    druid_werebear: `${SKILL_ICON_BASE}/druid/werebear.png`,
    druid_oak_sage: `${SKILL_ICON_BASE}/druid/oak_sage.png`,
    druid_fissure: `${SKILL_ICON_BASE}/druid/fissure.png`,
    druid_volcano: `${SKILL_ICON_BASE}/druid/volcano.png`,
    druid_fury: `${SKILL_ICON_BASE}/druid/fury.png`,
    druid_heart_of_wolverine: `${SKILL_ICON_BASE}/druid/heart_of_wolverine.png`,
    druid_tornado: `${SKILL_ICON_BASE}/druid/tornado.png`,
    druid_hurricane: `${SKILL_ICON_BASE}/druid/hurricane.png`,
    druid_armageddon: `${SKILL_ICON_BASE}/druid/armageddon.png`,
    druid_summon_grizzly: `${SKILL_ICON_BASE}/druid/summon_grizzly.png`,
    druid_primal_attunement: `${SKILL_ICON_BASE}/druid/oak_sage.png`,
    paladin_sanctify: `${SKILL_ICON_BASE}/paladin/prayer.png`,
    sorceress_ice_bolt: `${SKILL_ICON_BASE}/sorceress/ice_bolt.png`,
    sorceress_core_fire_bolt: `${SKILL_ICON_BASE}/sorceress/fire_bolt.png`,
    sorceress_fire_bolt: `${SKILL_ICON_BASE}/sorceress/fire_bolt.png`,
    sorceress_charged_bolt: `${SKILL_ICON_BASE}/sorceress/charged_bolt.png`,
    sorceress_warmth: `${SKILL_ICON_BASE}/sorceress/warmth.png`,
    sorceress_energy_shield: `${SKILL_ICON_BASE}/sorceress/energy_shield.png`,
    sorceress_frozen_armor: `${SKILL_ICON_BASE}/sorceress/frozen_armor.png`,
    sorceress_frost_nova: `${SKILL_ICON_BASE}/sorceress/frost_nova.png`,
    sorceress_fireball: `${SKILL_ICON_BASE}/sorceress/fire_ball.png`,
    sorceress_static_field: `${SKILL_ICON_BASE}/sorceress/static_field.png`,
    sorceress_inferno: `${SKILL_ICON_BASE}/sorceress/inferno.png`,
    sorceress_blizzard: `${SKILL_ICON_BASE}/sorceress/blizzard.png`,
    sorceress_meteor: `${SKILL_ICON_BASE}/sorceress/meteor.png`,
    sorceress_chain_lightning: `${SKILL_ICON_BASE}/sorceress/chain_lightning.png`,
    sorceress_teleport: `${SKILL_ICON_BASE}/sorceress/teleport.png`,
    sorceress_frozen_orb: `${SKILL_ICON_BASE}/sorceress/frozen_orb.png`,
    sorceress_hydra: `${SKILL_ICON_BASE}/sorceress/hydra.png`,
    sorceress_lightning_mastery: `${SKILL_ICON_BASE}/sorceress/lightning_mastery.png`,
    necromancer_teeth: `${SKILL_ICON_BASE}/necromancer/teeth.png`,
    necromancer_bone_armor: `${SKILL_ICON_BASE}/necromancer/bone_armor.png`,
    necromancer_amplify_damage: `${SKILL_ICON_BASE}/necromancer/amplify_damage.png`,
    necromancer_raise_skeleton: `${SKILL_ICON_BASE}/necromancer/raise_skeleton.png`,
    necromancer_bone_wall: `${SKILL_ICON_BASE}/necromancer/bone_wall.png`,
    necromancer_life_tap: `${SKILL_ICON_BASE}/necromancer/life_tap.png`,
    necromancer_corpse_explosion: `${SKILL_ICON_BASE}/necromancer/corpse_explosion.png`,
    necromancer_clay_golem: `${SKILL_ICON_BASE}/necromancer/clay_golem.png`,
    necromancer_iron_maiden: `${SKILL_ICON_BASE}/necromancer/iron_maiden.png`,
    necromancer_poison_dagger: `${SKILL_ICON_BASE}/necromancer/poison_dagger.png`,
    necromancer_bone_spear: `${SKILL_ICON_BASE}/necromancer/bone_spear.png`,
    necromancer_blood_golem: `${SKILL_ICON_BASE}/necromancer/blood_golem.png`,
    necromancer_decrepify: `${SKILL_ICON_BASE}/necromancer/decrepify.png`,
    necromancer_skeletal_mage: `${SKILL_ICON_BASE}/necromancer/skeletal_mage.png`,
    necromancer_bone_spirit: `${SKILL_ICON_BASE}/necromancer/bone_spirit.png`,
    necromancer_poison_nova: `${SKILL_ICON_BASE}/necromancer/poison_nova.png`,
    necromancer_revive: `${SKILL_ICON_BASE}/necromancer/revive.png`,
    necromancer_raise_servant: `${SKILL_ICON_BASE}/necromancer/raise_skeleton.png`,
    amazon_fend: `${SKILL_ICON_BASE}/amazon/fend.png`,
    amazon_ice_arrow: `${SKILL_ICON_BASE}/amazon/ice_arrow.png`,
    amazon_immolation_arrow: `${SKILL_ICON_BASE}/amazon/immolation_arrow.png`,
    amazon_impale: `${SKILL_ICON_BASE}/amazon/impale.png`,
    amazon_lightning_bolt: `${SKILL_ICON_BASE}/amazon/lightning_bolt.png`,
    amazon_lightning_strike: `${SKILL_ICON_BASE}/amazon/lightning_strike.png`,
    amazon_plague_javelin: `${SKILL_ICON_BASE}/amazon/plague_javelin.png`,
    amazon_poison_javelin: `${SKILL_ICON_BASE}/amazon/poison_javelin.png`,
    assassin_blade_fury: `${SKILL_ICON_BASE}/assassin/blade_fury.png`,
    assassin_blade_sentinel: `${SKILL_ICON_BASE}/assassin/blade_sentinel.png`,
    assassin_charged_bolt_sentry: `${SKILL_ICON_BASE}/assassin/charged_bolt_sentry.png`,
    assassin_dragon_claw: `${SKILL_ICON_BASE}/assassin/dragon_claw.png`,
    assassin_dragon_flight: `${SKILL_ICON_BASE}/assassin/dragon_flight.png`,
    assassin_dragon_tail: `${SKILL_ICON_BASE}/assassin/dragon_tail.png`,
    assassin_dragon_talon: `${SKILL_ICON_BASE}/assassin/dragon_talon.png`,
    assassin_mind_blast: `${SKILL_ICON_BASE}/assassin/mind_blast.png`,
    assassin_shadow_master: `${SKILL_ICON_BASE}/assassin/shadow_master.png`,
    assassin_shock_web: `${SKILL_ICON_BASE}/assassin/shock_web.png`,
    assassin_venom: `${SKILL_ICON_BASE}/assassin/venom.png`,
    assassin_wake_of_inferno: `${SKILL_ICON_BASE}/assassin/wake_of_inferno.png`,
    assassin_weapon_block: `${SKILL_ICON_BASE}/assassin/weapon_block.png`,
    barbarian_battle_command: `${SKILL_ICON_BASE}/barbarian/battle_command.png`,
    barbarian_battle_cry: `${SKILL_ICON_BASE}/barbarian/battle_cry.png`,
    barbarian_double_throw: `${SKILL_ICON_BASE}/barbarian/double_throw.png`,
    barbarian_increased_speed: `${SKILL_ICON_BASE}/barbarian/increased_speed.png`,
    barbarian_increased_stamina: `${SKILL_ICON_BASE}/barbarian/increased_stamina.png`,
    barbarian_taunt: `${SKILL_ICON_BASE}/barbarian/taunt.png`,
    druid_arctic_blast: `${SKILL_ICON_BASE}/druid/arctic_blast.png`,
    druid_carrion_vine: `${SKILL_ICON_BASE}/druid/carrion_vine.png`,
    druid_feral_rage: `${SKILL_ICON_BASE}/druid/feral_rage.png`,
    druid_fire_claws: `${SKILL_ICON_BASE}/druid/fire_claws.png`,
    druid_hunger: `${SKILL_ICON_BASE}/druid/hunger.png`,
    druid_maul: `${SKILL_ICON_BASE}/druid/maul.png`,
    druid_rabies: `${SKILL_ICON_BASE}/druid/rabies.png`,
    druid_shock_wave: `${SKILL_ICON_BASE}/druid/shock_wave.png`,
    druid_solar_creeper: `${SKILL_ICON_BASE}/druid/solar_creeper.png`,
    druid_spirit_of_barbs: `${SKILL_ICON_BASE}/druid/spirit_of_barbs.png`,
    druid_twister: `${SKILL_ICON_BASE}/druid/twister.png`,
    necromancer_attract: `${SKILL_ICON_BASE}/necromancer/attract.png`,
    necromancer_bone_prison: `${SKILL_ICON_BASE}/necromancer/bone_prison.png`,
    necromancer_confuse: `${SKILL_ICON_BASE}/necromancer/confuse.png`,
    necromancer_dim_vision: `${SKILL_ICON_BASE}/necromancer/dim_vision.png`,
    necromancer_fire_golem: `${SKILL_ICON_BASE}/necromancer/fire_golem.png`,
    necromancer_golem_mastery: `${SKILL_ICON_BASE}/necromancer/golem_mastery.png`,
    necromancer_iron_golem: `${SKILL_ICON_BASE}/necromancer/iron_golem.png`,
    necromancer_lower_resist: `${SKILL_ICON_BASE}/necromancer/lower_resist.png`,
    necromancer_poison_explosion: `${SKILL_ICON_BASE}/necromancer/poison_explosion.png`,
    necromancer_skeleton_mastery: `${SKILL_ICON_BASE}/necromancer/skeleton_mastery.png`,
    necromancer_summon_resist: `${SKILL_ICON_BASE}/necromancer/summon_resist.png`,
    necromancer_terror: `${SKILL_ICON_BASE}/necromancer/terror.png`,
    necromancer_weaken: `${SKILL_ICON_BASE}/necromancer/weaken.png`,
    paladin_blessed_aim: `${SKILL_ICON_BASE}/paladin/blessed_aim.png`,
    paladin_charge: `${SKILL_ICON_BASE}/paladin/charge.png`,
    paladin_concentration: `${SKILL_ICON_BASE}/paladin/concentration.png`,
    paladin_conversion: `${SKILL_ICON_BASE}/paladin/conversion.png`,
    paladin_holy_shock: `${SKILL_ICON_BASE}/paladin/holy_shock.png`,
    paladin_meditation: `${SKILL_ICON_BASE}/paladin/meditation.png`,
    paladin_redemption: `${SKILL_ICON_BASE}/paladin/redemption.png`,
    paladin_resist_cold: `${SKILL_ICON_BASE}/paladin/resist_cold.png`,
    paladin_resist_fire: `${SKILL_ICON_BASE}/paladin/resist_fire.png`,
    paladin_salvation: `${SKILL_ICON_BASE}/paladin/salvation.png`,
    paladin_sanctuary: `${SKILL_ICON_BASE}/paladin/sanctuary.png`,
    paladin_vigor: `${SKILL_ICON_BASE}/paladin/vigor.png`,
    sorceress_blaze: `${SKILL_ICON_BASE}/sorceress/blaze.png`,
    sorceress_chilling_armor: `${SKILL_ICON_BASE}/sorceress/chilling_armor.png`,
    sorceress_cold_mastery: `${SKILL_ICON_BASE}/sorceress/cold_mastery.png`,
    sorceress_enchant: `${SKILL_ICON_BASE}/sorceress/enchant.png`,
    sorceress_fire_mastery: `${SKILL_ICON_BASE}/sorceress/fire_mastery.png`,
    sorceress_fire_wall: `${SKILL_ICON_BASE}/sorceress/fire_wall.png`,
    sorceress_glacial_spike: `${SKILL_ICON_BASE}/sorceress/glacial_spike.png`,
    sorceress_ice_blast: `${SKILL_ICON_BASE}/sorceress/ice_blast.png`,
    sorceress_lightning: `${SKILL_ICON_BASE}/sorceress/lightning.png`,
    sorceress_nova: `${SKILL_ICON_BASE}/sorceress/nova.png`,
    sorceress_shiver_armor: `${SKILL_ICON_BASE}/sorceress/shiver_armor.png`,
    sorceress_telekinesis: `${SKILL_ICON_BASE}/sorceress/telekinesis.png`,
    sorceress_thunder_storm: `${SKILL_ICON_BASE}/sorceress/thunder_storm.png`,
  };

  const ATTACK_ICONS = [
    `${THEMED_CARD_ICON_BASE}/01_ember-shot.svg`,
    `${THEMED_CARD_ICON_BASE}/03_broadsword.svg`,
    `${THEMED_CARD_ICON_BASE}/04_crescent-blade.svg`,
    `${THEMED_CARD_ICON_BASE}/06_burning-skull.svg`,
    `${THEMED_CARD_ICON_BASE}/11_blast.svg`,
    `${THEMED_CARD_ICON_BASE}/23_dragon-breath.svg`,
  ];

  const SKILL_ICONS = [
    `${THEMED_CARD_ICON_BASE}/05_life-tap.svg`,
    `${THEMED_CARD_ICON_BASE}/09_candle-holder.svg`,
    `${THEMED_CARD_ICON_BASE}/10_burning-embers.svg`,
    `${THEMED_CARD_ICON_BASE}/13_armor-upgrade.svg`,
    `${THEMED_CARD_ICON_BASE}/15_ghost.svg`,
    `${THEMED_CARD_ICON_BASE}/17_grim-reaper.svg`,
  ];

  const CARD_ILLUSTRATIONS: Record<string, string> = {
    rally_mercenary: `${CARD_ILLUSTRATION_BASE}/rally_mercenary__gpt15low_v1.png`,
    swing: `${CARD_ILLUSTRATION_BASE}/swing__gpt15low_v1.png`,
    measured_swing: `${CARD_ILLUSTRATION_BASE}/measured_swing__gpt15low_v1.png`,
    mark_target: `${CARD_ILLUSTRATION_BASE}/mark_target__gpt15low_v1.png`,
    kick: `${CARD_ILLUSTRATION_BASE}/kick__gpt15low_v1.png`,
    forward_guard: `${CARD_ILLUSTRATION_BASE}/forward_guard__gpt15low_v1.png`,
    shove: `${CARD_ILLUSTRATION_BASE}/shove__gpt15low_v1.png`,
    field_dressing: `${CARD_ILLUSTRATION_BASE}/field_dressing__gpt15low_v1.png`,
    swing_plus: `${CARD_ILLUSTRATION_BASE}/swing_plus__gpt15low_v1.png`,
    measured_swing_plus: `${CARD_ILLUSTRATION_BASE}/measured_swing_plus__gpt15low_v1.png`,
    mark_target_plus: `${CARD_ILLUSTRATION_BASE}/mark_target_plus__gpt15low_v1.png`,
    kick_plus: `${CARD_ILLUSTRATION_BASE}/kick_plus__gpt15low_v1.png`,
    forward_guard_plus: `${CARD_ILLUSTRATION_BASE}/forward_guard_plus__gpt15low_v1.png`,
    shove_plus: `${CARD_ILLUSTRATION_BASE}/shove_plus__gpt15low_v1.png`,
    rally_mercenary_plus: `${CARD_ILLUSTRATION_BASE}/rally_mercenary_plus__gpt15low_v1.png`,
    field_dressing_plus: `${CARD_ILLUSTRATION_BASE}/field_dressing_plus__gpt15low_v1.png`,
    guard_stance: `${CARD_ILLUSTRATION_BASE}/guard_stance__gpt15low_v1.png`,
    crushing_blow: `${CARD_ILLUSTRATION_BASE}/crushing_blow__gpt15low_v1.png`,
    press_the_attack: `${CARD_ILLUSTRATION_BASE}/press_the_attack__gpt15low_v1.png`,
    throw_oil: `${CARD_ILLUSTRATION_BASE}/throw_oil__gpt15low_v1.png`,
    brace: `${CARD_ILLUSTRATION_BASE}/brace__gpt15low_v1.png`,
    scout_ahead: `${CARD_ILLUSTRATION_BASE}/scout_ahead__gpt15low_v1.png`,
    hold_the_line: `${CARD_ILLUSTRATION_BASE}/hold_the_line__gpt15low_v1.png`,
    triage: `${CARD_ILLUSTRATION_BASE}/triage__gpt15low_v1.png`,
    regroup: `${CARD_ILLUSTRATION_BASE}/regroup__gpt15low_v1.png`,
    blood_moor_raiders: `${CARD_ILLUSTRATION_BASE}/blood_moor_raiders__gpt15low_v1.png`,
    burial_grounds: `${CARD_ILLUSTRATION_BASE}/burial_grounds__gpt15low_v1.png`,
    catacombs_gate: `${CARD_ILLUSTRATION_BASE}/catacombs_gate__gpt15low_v1.png`,
    amazon_call_the_shot: `${CARD_ILLUSTRATION_BASE}/amazon_inner_sight_v2.png`,
    amazon_magic_arrow: `${CARD_ILLUSTRATION_BASE}/amazon_magic_arrow.png`,
    amazon_jab: `${CARD_ILLUSTRATION_BASE}/amazon_jab__gpt15high_ability_v1.png`,
    amazon_inner_sight: `${CARD_ILLUSTRATION_BASE}/amazon_inner_sight_v2.png`,
    amazon_fire_arrow: `${CARD_ILLUSTRATION_BASE}/amazon_fire_arrow.png`,
    amazon_dodge: `${CARD_ILLUSTRATION_BASE}/amazon_dodge__gpt15high_ability_v1.png`,
    amazon_critical_strike: `${CARD_ILLUSTRATION_BASE}/amazon_critical_strike__gpt15high_ability_v1.png`,
    amazon_slow_missiles: `${CARD_ILLUSTRATION_BASE}/amazon_slow_missiles__gpt15low_v1.png`,
    amazon_avoid: `${CARD_ILLUSTRATION_BASE}/amazon_avoid__gpt15high_ability_v1.png`,
    amazon_penetrate: `${CARD_ILLUSTRATION_BASE}/amazon_penetrate__gpt15high_ability_v1.png`,
    amazon_decoy: `${CARD_ILLUSTRATION_BASE}/amazon_decoy__gpt15low_v2.png`,
    amazon_cold_arrow: `${CARD_ILLUSTRATION_BASE}/amazon_cold_arrow__gpt15low_v1.png`,
    amazon_multiple_shot: `${CARD_ILLUSTRATION_BASE}/amazon_multiple_shot__gpt15low_v1.png`,
    amazon_power_strike: `${CARD_ILLUSTRATION_BASE}/amazon_power_strike__gpt15low_v1.png`,
    amazon_exploding_arrow: `${CARD_ILLUSTRATION_BASE}/amazon_exploding_arrow__gpt15low_v1.png`,
    amazon_guided_arrow: `${CARD_ILLUSTRATION_BASE}/amazon_guided_arrow__gpt15low_v1.png`,
    amazon_evade: `${CARD_ILLUSTRATION_BASE}/amazon_evade__gpt15high_ability_v1.png`,
    amazon_deadly_strike: `${CARD_ILLUSTRATION_BASE}/amazon_deadly_strike__gpt15high_ability_v1.png`,
    amazon_charged_strike: `${CARD_ILLUSTRATION_BASE}/amazon_charged_strike__gpt15low_v1.png`,
    amazon_strafe: `${CARD_ILLUSTRATION_BASE}/amazon_strafe__gpt15low_v1.png`,
    amazon_valkyrie: `${CARD_ILLUSTRATION_BASE}/amazon_valkyrie__gpt15low_v1.png`,
    amazon_pierce: `${CARD_ILLUSTRATION_BASE}/amazon_pierce__gpt15low_v1.png`,
    amazon_freezing_arrow: `${CARD_ILLUSTRATION_BASE}/amazon_freezing_arrow__gpt15low_v1.png`,
    amazon_lightning_fury: `${CARD_ILLUSTRATION_BASE}/amazon_lightning_fury__gpt15low_v1.png`,
    assassin_shadow_feint: `${CARD_ILLUSTRATION_BASE}/assassin_cloak_of_shadows__gpt15high_ability_v1.png`,
    assassin_tiger_strike: `${CARD_ILLUSTRATION_BASE}/assassin_tiger_strike__gpt15high_ability_v1.png`,
    assassin_fire_blast: `${CARD_ILLUSTRATION_BASE}/assassin_fire_blast__gpt15low_v1.png`,
    assassin_claw_mastery: `${CARD_ILLUSTRATION_BASE}/assassin_claw_mastery__gpt15low_v1.png`,
    assassin_psychic_hammer: `${CARD_ILLUSTRATION_BASE}/assassin_psychic_hammer__gpt15low_v1.png`,
    assassin_blade_shield: `${CARD_ILLUSTRATION_BASE}/assassin_blade_shield__gpt15high_ability_v1.png`,
    assassin_cloak_of_shadows: `${CARD_ILLUSTRATION_BASE}/assassin_cloak_of_shadows__gpt15high_ability_v1.png`,
    assassin_fists_of_fire: `${CARD_ILLUSTRATION_BASE}/assassin_fists_of_fire__gpt15low_v1.png`,
    assassin_burst_of_speed: `${CARD_ILLUSTRATION_BASE}/assassin_burst_of_speed__gpt15high_ability_v2.png`,
    assassin_wake_of_fire: `${CARD_ILLUSTRATION_BASE}/assassin_wake_of_fire__gpt15low_v1.png`,
    assassin_cobra_strike: `${CARD_ILLUSTRATION_BASE}/assassin_cobra_strike__gpt15high_ability_v1.png`,
    assassin_claws_of_thunder: `${CARD_ILLUSTRATION_BASE}/assassin_claws_of_thunder__gpt15low_v1.png`,
    assassin_blades_of_ice: `${CARD_ILLUSTRATION_BASE}/assassin_blades_of_ice__gpt15low_v1.png`,
    assassin_fade: `${CARD_ILLUSTRATION_BASE}/assassin_fade__gpt15high_ability_v2.png`,
    assassin_lightning_sentry: `${CARD_ILLUSTRATION_BASE}/assassin_lightning_sentry__gpt15low_v1.png`,
    assassin_shadow_warrior: `${CARD_ILLUSTRATION_BASE}/assassin_shadow_warrior__gpt15high_ability_v1.png`,
    assassin_phoenix_strike: `${CARD_ILLUSTRATION_BASE}/assassin_phoenix_strike__gpt15low_v1.png`,
    assassin_death_sentry: `${CARD_ILLUSTRATION_BASE}/assassin_death_sentry__gpt15low_v1.png`,
    barbarian_core_bash: `${CARD_ILLUSTRATION_BASE}/barbarian_bash__gpt15high_ability_v1.png`,
    barbarian_bash: `${CARD_ILLUSTRATION_BASE}/barbarian_bash__gpt15high_ability_v1.png`,
    barbarian_howl: `${CARD_ILLUSTRATION_BASE}/barbarian_howl__gpt15low_v1.png`,
    barbarian_sword_mastery: `${CARD_ILLUSTRATION_BASE}/barbarian_sword_mastery__gpt15low_v1.png`,
    barbarian_find_potion: `${CARD_ILLUSTRATION_BASE}/barbarian_find_potion__gpt15low_v1.png`,
    barbarian_iron_skin: `${CARD_ILLUSTRATION_BASE}/barbarian_iron_skin__gpt15low_v1.png`,
    barbarian_natural_resistance: `${CARD_ILLUSTRATION_BASE}/barbarian_natural_resistance__gpt15high_ability_v2.png`,
    barbarian_double_swing: `${CARD_ILLUSTRATION_BASE}/barbarian_double_swing__gpt15high_ability_v1.png`,
    barbarian_leap: `${CARD_ILLUSTRATION_BASE}/barbarian_leap__gpt15low_v1.png`,
    barbarian_shout: `${CARD_ILLUSTRATION_BASE}/barbarian_shout__gpt15low_v1.png`,
    barbarian_weapon_mastery: `${CARD_ILLUSTRATION_BASE}/barbarian_weapon_mastery__gpt15low_v1.png`,
    barbarian_stun: `${CARD_ILLUSTRATION_BASE}/barbarian_stun__gpt15high_ability_v1.png`,
    barbarian_concentrate: `${CARD_ILLUSTRATION_BASE}/barbarian_concentrate__gpt15high_ability_v1.png`,
    barbarian_frenzy: `${CARD_ILLUSTRATION_BASE}/barbarian_frenzy__gpt15high_ability_v1.png`,
    barbarian_battle_orders: `${CARD_ILLUSTRATION_BASE}/barbarian_battle_orders__gpt15high_ability_v1.png`,
    barbarian_steel_skin: `${CARD_ILLUSTRATION_BASE}/barbarian_steel_skin__gpt15low_v1.png`,
    barbarian_leap_attack: `${CARD_ILLUSTRATION_BASE}/barbarian_leap_attack__gpt15low_v1.png`,
    barbarian_whirlwind: `${CARD_ILLUSTRATION_BASE}/barbarian_whirlwind__gpt15low_v1.png`,
    barbarian_berserk: `${CARD_ILLUSTRATION_BASE}/barbarian_berserk__gpt15low_v1.png`,
    barbarian_war_cry: `${CARD_ILLUSTRATION_BASE}/barbarian_war_cry__gpt15low_v1.png`,
    barbarian_battle_instinct: `${CARD_ILLUSTRATION_BASE}/barbarian_battle_instinct__gpt15low_v2.png`,
    barbarian_unyielding: `${CARD_ILLUSTRATION_BASE}/barbarian_unyielding__gpt15low_v1.png`,
    druid_firestorm: `${CARD_ILLUSTRATION_BASE}/druid_firestorm__gpt15low_v1.png`,
    druid_werewolf: `${CARD_ILLUSTRATION_BASE}/druid_werewolf__gpt15low_v1.png`,
    druid_raven: `${CARD_ILLUSTRATION_BASE}/druid_raven__gpt15low_v1.png`,
    druid_poison_creeper: `${CARD_ILLUSTRATION_BASE}/druid_poison_creeper__gpt15low_v1.png`,
    druid_cyclone_armor: `${CARD_ILLUSTRATION_BASE}/druid_cyclone_armor__gpt15high_ability_v1.png`,
    druid_lycanthropy: `${CARD_ILLUSTRATION_BASE}/druid_lycanthropy__gpt15low_v1.png`,
    druid_molten_boulder: `${CARD_ILLUSTRATION_BASE}/druid_molten_boulder__gpt15low_v1.png`,
    druid_werebear: `${CARD_ILLUSTRATION_BASE}/druid_werebear__gpt15low_v1.png`,
    druid_oak_sage: `${CARD_ILLUSTRATION_BASE}/druid_oak_sage__gpt15low_v1.png`,
    druid_fissure: `${CARD_ILLUSTRATION_BASE}/druid_fissure__gpt15low_v1.png`,
    druid_volcano: `${CARD_ILLUSTRATION_BASE}/druid_volcano__gpt15low_v1.png`,
    druid_fury: `${CARD_ILLUSTRATION_BASE}/druid_fury__gpt15low_v1.png`,
    druid_heart_of_wolverine: `${CARD_ILLUSTRATION_BASE}/druid_heart_of_wolverine__gpt15low_v1.png`,
    druid_tornado: `${CARD_ILLUSTRATION_BASE}/druid_tornado__gpt15low_v1.png`,
    druid_hurricane: `${CARD_ILLUSTRATION_BASE}/druid_hurricane__gpt15high_ability_v1.png`,
    druid_armageddon: `${CARD_ILLUSTRATION_BASE}/druid_armageddon__gpt15low_v1.png`,
    druid_summon_grizzly: `${CARD_ILLUSTRATION_BASE}/druid_summon_grizzly__gpt15low_v1.png`,
    druid_primal_attunement: `${CARD_ILLUSTRATION_BASE}/druid_oak_sage__gpt15low_v1.png`,
    necromancer_teeth: `${CARD_ILLUSTRATION_BASE}/necromancer_teeth__gpt15low_v1.png`,
    necromancer_bone_armor: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_armor__gpt15low_v1.png`,
    necromancer_amplify_damage: `${CARD_ILLUSTRATION_BASE}/necromancer_amplify_damage__gpt15high_ability_v1.png`,
    necromancer_raise_skeleton: `${CARD_ILLUSTRATION_BASE}/necromancer_raise_skeleton__gpt15low_v1.png`,
    necromancer_bone_wall: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_wall__gpt15low_v1.png`,
    necromancer_life_tap: `${CARD_ILLUSTRATION_BASE}/necromancer_life_tap__gpt15low_v1.png`,
    necromancer_corpse_explosion: `${CARD_ILLUSTRATION_BASE}/necromancer_corpse_explosion__gpt15low_v1.png`,
    necromancer_clay_golem: `${CARD_ILLUSTRATION_BASE}/necromancer_clay_golem__gpt15low_v1.png`,
    necromancer_iron_maiden: `${CARD_ILLUSTRATION_BASE}/necromancer_iron_maiden__gpt15low_v1.png`,
    necromancer_poison_dagger: `${CARD_ILLUSTRATION_BASE}/necromancer_poison_dagger__gpt15low_v1.png`,
    necromancer_bone_spear: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_spear__gpt15low_v1.png`,
    necromancer_blood_golem: `${CARD_ILLUSTRATION_BASE}/necromancer_blood_golem__gpt15low_v1.png`,
    necromancer_decrepify: `${CARD_ILLUSTRATION_BASE}/necromancer_decrepify__gpt15low_v1.png`,
    necromancer_skeletal_mage: `${CARD_ILLUSTRATION_BASE}/necromancer_skeletal_mage__gpt15low_v1.png`,
    necromancer_bone_spirit: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_spirit__gpt15low_v1.png`,
    necromancer_poison_nova: `${CARD_ILLUSTRATION_BASE}/necromancer_poison_nova__gpt15low_v1.png`,
    necromancer_revive: `${CARD_ILLUSTRATION_BASE}/necromancer_revive__gpt15low_v1.png`,
    necromancer_raise_servant: `${CARD_ILLUSTRATION_BASE}/necromancer_raise_skeleton__gpt15low_v1.png`,
    paladin_sanctify: `${CARD_ILLUSTRATION_BASE}/paladin_prayer__gpt15high_ability_v1.png`,
    paladin_sacrifice: `${CARD_ILLUSTRATION_BASE}/paladin_sacrifice__gpt15low_v1.png`,
    paladin_might: `${CARD_ILLUSTRATION_BASE}/paladin_might__gpt15low_v1.png`,
    paladin_prayer: `${CARD_ILLUSTRATION_BASE}/paladin_prayer__gpt15high_ability_v1.png`,
    paladin_smite: `${CARD_ILLUSTRATION_BASE}/paladin_smite__gpt15high_ability_v1.png`,
    paladin_thorns: `${CARD_ILLUSTRATION_BASE}/paladin_thorns__gpt15low_v1.png`,
    paladin_cleansing: `${CARD_ILLUSTRATION_BASE}/paladin_cleansing__gpt15high_ability_v1.png`,
    paladin_holy_bolt: `${CARD_ILLUSTRATION_BASE}/paladin_holy_bolt__gpt15low_v1.png`,
    paladin_holy_fire: `${CARD_ILLUSTRATION_BASE}/paladin_holy_fire__gpt15low_v1.png`,
    paladin_defiance: `${CARD_ILLUSTRATION_BASE}/paladin_defiance__gpt15low_v1.png`,
    paladin_zeal: `${CARD_ILLUSTRATION_BASE}/paladin_zeal__gpt15high_ability_v1.png`,
    paladin_vengeance: `${CARD_ILLUSTRATION_BASE}/paladin_vengeance__gpt15high_ability_v1.png`,
    paladin_blessed_hammer: `${CARD_ILLUSTRATION_BASE}/paladin_blessed_hammer__gpt15low_v1.png`,
    paladin_holy_freeze: `${CARD_ILLUSTRATION_BASE}/paladin_holy_freeze__gpt15low_v1.png`,
    paladin_holy_shield: `${CARD_ILLUSTRATION_BASE}/paladin_holy_shield__gpt15low_v1.png`,
    paladin_fist_of_the_heavens: `${CARD_ILLUSTRATION_BASE}/paladin_fist_of_the_heavens__gpt15low_v1.png`,
    paladin_fanaticism: `${CARD_ILLUSTRATION_BASE}/paladin_fanaticism__gpt15low_v1.png`,
    paladin_conviction: `${CARD_ILLUSTRATION_BASE}/paladin_conviction__gpt15low_v1.png`,
    sorceress_ice_bolt: `${CARD_ILLUSTRATION_BASE}/sorceress_ice_bolt__gpt15low_v1.png`,
    sorceress_core_fire_bolt: `${CARD_ILLUSTRATION_BASE}/sorceress_fire_bolt__gpt15low_v1.png`,
    sorceress_fire_bolt: `${CARD_ILLUSTRATION_BASE}/sorceress_fire_bolt__gpt15low_v1.png`,
    sorceress_charged_bolt: `${CARD_ILLUSTRATION_BASE}/sorceress_charged_bolt__gpt15low_v1.png`,
    sorceress_warmth: `${CARD_ILLUSTRATION_BASE}/sorceress_warmth__gpt15high_ability_v1.png`,
    sorceress_energy_shield: `${CARD_ILLUSTRATION_BASE}/sorceress_energy_shield__gpt15low_v1.png`,
    sorceress_frozen_armor: `${CARD_ILLUSTRATION_BASE}/sorceress_frozen_armor__gpt15high_ability_v1.png`,
    sorceress_frost_nova: `${CARD_ILLUSTRATION_BASE}/sorceress_frost_nova__gpt15low_v1.png`,
    sorceress_fireball: `${CARD_ILLUSTRATION_BASE}/sorceress_fireball__gpt15low_v1.png`,
    sorceress_static_field: `${CARD_ILLUSTRATION_BASE}/sorceress_static_field__gpt15high_ability_v1.png`,
    sorceress_inferno: `${CARD_ILLUSTRATION_BASE}/sorceress_inferno__gpt15high_ability_v1.png`,
    sorceress_blizzard: `${CARD_ILLUSTRATION_BASE}/sorceress_blizzard__gpt15low_v1.png`,
    sorceress_meteor: `${CARD_ILLUSTRATION_BASE}/sorceress_meteor__gpt15low_v1.png`,
    sorceress_chain_lightning: `${CARD_ILLUSTRATION_BASE}/sorceress_chain_lightning__gpt15low_v1.png`,
    sorceress_teleport: `${CARD_ILLUSTRATION_BASE}/sorceress_teleport__gpt15high_ability_v1.png`,
    sorceress_frozen_orb: `${CARD_ILLUSTRATION_BASE}/sorceress_frozen_orb__gpt15low_v1.png`,
    sorceress_hydra: `${CARD_ILLUSTRATION_BASE}/sorceress_hydra__gpt15low_v1.png`,
    sorceress_lightning_mastery: `${CARD_ILLUSTRATION_BASE}/sorceress_lightning_mastery__gpt15low_v1.png`,
    amazon_amazonian_guard: `${CARD_ILLUSTRATION_BASE}/amazon_amazonian_guard__gpt15low_v1.png`,
    amazon_arrow_mastery: `${CARD_ILLUSTRATION_BASE}/amazon_arrow_mastery__gpt15low_v1.png`,
    amazon_battle_focus: `${CARD_ILLUSTRATION_BASE}/amazon_battle_focus__gpt15low_v1.png`,
    amazon_fend: `${CARD_ILLUSTRATION_BASE}/amazon_fend__gpt15high_ability_v1.png`,
    amazon_flame_javelin: `${CARD_ILLUSTRATION_BASE}/amazon_flame_javelin__gpt15low_v1.png`,
    amazon_fury_of_the_hunt: `${CARD_ILLUSTRATION_BASE}/amazon_fury_of_the_hunt__gpt15low_v1.png`,
    amazon_huntress_mark: `${CARD_ILLUSTRATION_BASE}/amazon_huntress_mark__gpt15low_v1.png`,
    amazon_ice_arrow: `${CARD_ILLUSTRATION_BASE}/amazon_ice_arrow__gpt15low_v1.png`,
    amazon_immolation_arrow: `${CARD_ILLUSTRATION_BASE}/amazon_immolation_arrow__gpt15low_v1.png`,
    amazon_impale: `${CARD_ILLUSTRATION_BASE}/amazon_impale__gpt15low_v1.png`,
    amazon_inner_calm: `${CARD_ILLUSTRATION_BASE}/amazon_inner_calm__gpt15low_v1.png`,
    amazon_javelin_mastery: `${CARD_ILLUSTRATION_BASE}/amazon_javelin_mastery__gpt15low_v1.png`,
    amazon_javelin_rush: `${CARD_ILLUSTRATION_BASE}/amazon_javelin_rush__gpt15low_v1.png`,
    amazon_lightning_bolt: `${CARD_ILLUSTRATION_BASE}/amazon_lightning_bolt__gpt15low_v1.png`,
    amazon_lightning_strike: `${CARD_ILLUSTRATION_BASE}/amazon_lightning_strike__gpt15low_v1.png`,
    amazon_plague_javelin: `${CARD_ILLUSTRATION_BASE}/amazon_plague_javelin__gpt15low_v1.png`,
    amazon_poison_javelin: `${CARD_ILLUSTRATION_BASE}/amazon_poison_javelin__gpt15low_v1.png`,
    amazon_precision: `${CARD_ILLUSTRATION_BASE}/amazon_precision__gpt15low_v1.png`,
    amazon_renewal: `${CARD_ILLUSTRATION_BASE}/amazon_renewal__gpt15low_v1.png`,
    amazon_storm_javelin: `${CARD_ILLUSTRATION_BASE}/amazon_storm_javelin__gpt15low_v1.png`,
    amazon_thunder_volley: `${CARD_ILLUSTRATION_BASE}/amazon_thunder_volley__gpt15low_v1.png`,
    amazon_war_maiden: `${CARD_ILLUSTRATION_BASE}/amazon_war_maiden__gpt15low_v1.png`,
    amazon_war_pike: `${CARD_ILLUSTRATION_BASE}/amazon_war_pike__gpt15low_v1.png`,
    assassin_blade_fury: `${CARD_ILLUSTRATION_BASE}/assassin_blade_fury__gpt15low_v1.png`,
    assassin_blade_sentinel: `${CARD_ILLUSTRATION_BASE}/assassin_blade_sentinel__gpt15low_v1.png`,
    assassin_charged_bolt_sentry: `${CARD_ILLUSTRATION_BASE}/assassin_charged_bolt_sentry__gpt15low_v1.png`,
    assassin_combo_mastery: `${CARD_ILLUSTRATION_BASE}/assassin_combo_mastery__gpt15low_v1.png`,
    assassin_dark_discipline: `${CARD_ILLUSTRATION_BASE}/assassin_dark_discipline__gpt15low_v1.png`,
    assassin_dark_recovery: `${CARD_ILLUSTRATION_BASE}/assassin_dark_recovery__gpt15low_v1.png`,
    assassin_death_blossom: `${CARD_ILLUSTRATION_BASE}/assassin_death_blossom__gpt15low_v1.png`,
    assassin_dragon_claw: `${CARD_ILLUSTRATION_BASE}/assassin_dragon_claw__gpt15low_v1.png`,
    assassin_dragon_flight: `${CARD_ILLUSTRATION_BASE}/assassin_dragon_flight__gpt15low_v1.png`,
    assassin_dragon_tail: `${CARD_ILLUSTRATION_BASE}/assassin_dragon_tail__gpt15low_v1.png`,
    assassin_dragon_talon: `${CARD_ILLUSTRATION_BASE}/assassin_dragon_talon__gpt15low_v1.png`,
    assassin_escape_artist: `${CARD_ILLUSTRATION_BASE}/assassin_escape_artist__gpt15low_v1.png`,
    assassin_fatal_cascade: `${CARD_ILLUSTRATION_BASE}/assassin_fatal_cascade__gpt15low_v1.png`,
    assassin_lethal_tempo: `${CARD_ILLUSTRATION_BASE}/assassin_lethal_tempo__gpt15low_v1.png`,
    assassin_mind_blast: `${CARD_ILLUSTRATION_BASE}/assassin_mind_blast__gpt15low_v1.png`,
    assassin_natalyas_guard: `${CARD_ILLUSTRATION_BASE}/assassin_natalyas_guard__gpt15low_v1.png`,
    assassin_shadow_master: `${CARD_ILLUSTRATION_BASE}/assassin_shadow_master__gpt15high_ability_v1.png`,
    assassin_shadow_shroud: `${CARD_ILLUSTRATION_BASE}/assassin_shadow_shroud__gpt15low_v1.png`,
    assassin_shadow_storm: `${CARD_ILLUSTRATION_BASE}/assassin_shadow_storm__gpt15low_v1.png`,
    assassin_shadow_trap: `${CARD_ILLUSTRATION_BASE}/assassin_shadow_trap__gpt15low_v1.png`,
    assassin_shadow_veil: `${CARD_ILLUSTRATION_BASE}/assassin_shadow_veil__gpt15low_v1.png`,
    assassin_shock_web: `${CARD_ILLUSTRATION_BASE}/assassin_shock_web__gpt15low_v1.png`,
    assassin_trap_mastery: `${CARD_ILLUSTRATION_BASE}/assassin_trap_mastery__gpt15low_v1.png`,
    assassin_venom: `${CARD_ILLUSTRATION_BASE}/assassin_venom__gpt15high_ability_v1.png`,
    assassin_venom_strike: `${CARD_ILLUSTRATION_BASE}/assassin_venom_strike__gpt15low_v1.png`,
    assassin_wake_of_inferno: `${CARD_ILLUSTRATION_BASE}/assassin_wake_of_inferno__gpt15low_v1.png`,
    assassin_weapon_block: `${CARD_ILLUSTRATION_BASE}/assassin_weapon_block__gpt15high_ability_v1.png`,
    barbarian_ancient_vow: `${CARD_ILLUSTRATION_BASE}/barbarian_ancient_vow__gpt15low_v1.png`,
    barbarian_axe_mastery: `${CARD_ILLUSTRATION_BASE}/barbarian_axe_mastery__gpt15low_v1.png`,
    barbarian_battle_charge: `${CARD_ILLUSTRATION_BASE}/barbarian_battle_charge__gpt15low_v1.png`,
    barbarian_battle_command: `${CARD_ILLUSTRATION_BASE}/barbarian_battle_command__gpt15high_ability_v1.png`,
    barbarian_battle_cry: `${CARD_ILLUSTRATION_BASE}/barbarian_battle_cry__gpt15high_ability_v1.png`,
    barbarian_bulwark: `${CARD_ILLUSTRATION_BASE}/barbarian_bulwark__gpt15low_v1.png`,
    barbarian_combat_mastery: `${CARD_ILLUSTRATION_BASE}/barbarian_combat_mastery__gpt15low_v1.png`,
    barbarian_double_throw: `${CARD_ILLUSTRATION_BASE}/barbarian_double_throw__gpt15high_ability_v1.png`,
    barbarian_find_item: `${CARD_ILLUSTRATION_BASE}/barbarian_find_item__gpt15low_v1.png`,
    barbarian_frenzy_rush: `${CARD_ILLUSTRATION_BASE}/barbarian_frenzy_rush__gpt15low_v1.png`,
    barbarian_fury_howl: `${CARD_ILLUSTRATION_BASE}/barbarian_fury_howl__gpt15low_v1.png`,
    barbarian_fury_mastery: `${CARD_ILLUSTRATION_BASE}/barbarian_fury_mastery__gpt15low_v1.png`,
    barbarian_grim_ward: `${CARD_ILLUSTRATION_BASE}/barbarian_grim_ward__gpt15low_v1.png`,
    barbarian_guard_slam: `${CARD_ILLUSTRATION_BASE}/barbarian_guard_slam__gpt15low_v1.png`,
    barbarian_increased_speed: `${CARD_ILLUSTRATION_BASE}/barbarian_increased_speed__gpt15low_v1.png`,
    barbarian_increased_stamina: `${CARD_ILLUSTRATION_BASE}/barbarian_increased_stamina__gpt15low_v1.png`,
    barbarian_iron_fortress: `${CARD_ILLUSTRATION_BASE}/barbarian_iron_fortress__gpt15low_v1.png`,
    barbarian_mace_mastery: `${CARD_ILLUSTRATION_BASE}/barbarian_mace_mastery__gpt15low_v1.png`,
    barbarian_polearm_mastery: `${CARD_ILLUSTRATION_BASE}/barbarian_polearm_mastery__gpt15low_v1.png`,
    barbarian_raging_cleave: `${CARD_ILLUSTRATION_BASE}/barbarian_raging_cleave__gpt15low_v1.png`,
    barbarian_second_wind: `${CARD_ILLUSTRATION_BASE}/barbarian_second_wind__gpt15low_v1.png`,
    barbarian_taunt: `${CARD_ILLUSTRATION_BASE}/barbarian_taunt__gpt15low_v1.png`,
    barbarian_war_stance: `${CARD_ILLUSTRATION_BASE}/barbarian_war_stance__gpt15low_v1.png`,
    barbarian_war_stomp: `${CARD_ILLUSTRATION_BASE}/barbarian_war_stomp__gpt15low_v1.png`,
    barbarian_warcry_strike: `${CARD_ILLUSTRATION_BASE}/barbarian_warcry_strike__gpt15low_v1.png`,
    barbarian_warlord_shout: `${CARD_ILLUSTRATION_BASE}/barbarian_warlord_shout__gpt15low_v1.png`,
    druid_arctic_blast: `${CARD_ILLUSTRATION_BASE}/druid_arctic_blast__gpt15low_v1.png`,
    druid_carrion_vine: `${CARD_ILLUSTRATION_BASE}/druid_carrion_vine__gpt15high_ability_v1.png`,
    druid_dire_wolf: `${CARD_ILLUSTRATION_BASE}/druid_dire_wolf__gpt15low_v1.png`,
    druid_elemental_mastery: `${CARD_ILLUSTRATION_BASE}/druid_elemental_mastery__gpt15low_v1.png`,
    druid_elemental_pack: `${CARD_ILLUSTRATION_BASE}/druid_elemental_pack__gpt15low_v1.png`,
    druid_eruption: `${CARD_ILLUSTRATION_BASE}/druid_eruption__gpt15low_v1.png`,
    druid_feral_rage: `${CARD_ILLUSTRATION_BASE}/druid_feral_rage__gpt15low_v1.png`,
    druid_feral_storm: `${CARD_ILLUSTRATION_BASE}/druid_feral_storm__gpt15low_v1.png`,
    druid_fire_claws: `${CARD_ILLUSTRATION_BASE}/druid_fire_claws__gpt15low_v1.png`,
    druid_force_of_nature: `${CARD_ILLUSTRATION_BASE}/druid_force_of_nature__gpt15low_v1.png`,
    druid_gale_force: `${CARD_ILLUSTRATION_BASE}/druid_gale_force__gpt15low_v1.png`,
    druid_grove_sentinel: `${CARD_ILLUSTRATION_BASE}/druid_grove_sentinel__gpt15low_v1.png`,
    druid_hibernation: `${CARD_ILLUSTRATION_BASE}/druid_hibernation__gpt15low_v1.png`,
    druid_hunger: `${CARD_ILLUSTRATION_BASE}/druid_hunger__gpt15low_v1.png`,
    druid_maul: `${CARD_ILLUSTRATION_BASE}/druid_maul__gpt15low_v1.png`,
    druid_natures_balance: `${CARD_ILLUSTRATION_BASE}/druid_natures_balance__gpt15low_v1.png`,
    druid_natures_guardian: `${CARD_ILLUSTRATION_BASE}/druid_natures_guardian__gpt15low_v1.png`,
    druid_natures_wrath: `${CARD_ILLUSTRATION_BASE}/druid_natures_wrath__gpt15low_v1.png`,
    druid_pack_howl: `${CARD_ILLUSTRATION_BASE}/druid_pack_howl__gpt15low_v1.png`,
    druid_primal_fury: `${CARD_ILLUSTRATION_BASE}/druid_primal_fury__gpt15low_v1.png`,
    druid_primal_roar: `${CARD_ILLUSTRATION_BASE}/druid_primal_roar__gpt15low_v1.png`,
    druid_rabies: `${CARD_ILLUSTRATION_BASE}/druid_rabies__gpt15low_v1.png`,
    druid_renewal: `${CARD_ILLUSTRATION_BASE}/druid_renewal__gpt15low_v1.png`,
    druid_savage_pounce: `${CARD_ILLUSTRATION_BASE}/druid_savage_pounce__gpt15low_v1.png`,
    druid_shock_wave: `${CARD_ILLUSTRATION_BASE}/druid_shock_wave__gpt15low_v1.png`,
    druid_solar_creeper: `${CARD_ILLUSTRATION_BASE}/druid_solar_creeper__gpt15high_ability_v1.png`,
    druid_spirit_of_barbs: `${CARD_ILLUSTRATION_BASE}/druid_spirit_of_barbs__gpt15low_v1.png`,
    druid_spirit_wolf: `${CARD_ILLUSTRATION_BASE}/druid_spirit_wolf__gpt15low_v1.png`,
    druid_summon_spirit_wolf_pack: `${CARD_ILLUSTRATION_BASE}/druid_summon_spirit_wolf_pack__gpt15low_v1.png`,
    druid_twister: `${CARD_ILLUSTRATION_BASE}/druid_twister__gpt15high_ability_v1.png`,
    druid_wild_convergence: `${CARD_ILLUSTRATION_BASE}/druid_wild_convergence__gpt15low_v1.png`,
    druid_wild_stampede: `${CARD_ILLUSTRATION_BASE}/druid_wild_stampede__gpt15low_v1.png`,
    necromancer_army_of_dead: `${CARD_ILLUSTRATION_BASE}/necromancer_army_of_dead__gpt15low_v1.png`,
    necromancer_attract: `${CARD_ILLUSTRATION_BASE}/necromancer_attract__gpt15high_ability_v1.png`,
    necromancer_blood_ritual: `${CARD_ILLUSTRATION_BASE}/necromancer_blood_ritual__gpt15low_v1.png`,
    necromancer_bone_offering: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_offering__gpt15low_v1.png`,
    necromancer_bone_plague: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_plague__gpt15low_v1.png`,
    necromancer_bone_prison: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_prison__gpt15low_v1.png`,
    necromancer_bone_shield: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_shield__gpt15low_v1.png`,
    necromancer_bone_shrapnel: `${CARD_ILLUSTRATION_BASE}/necromancer_bone_shrapnel__gpt15low_v1.png`,
    necromancer_confuse: `${CARD_ILLUSTRATION_BASE}/necromancer_confuse__gpt15high_ability_v1.png`,
    necromancer_corpse_harvest: `${CARD_ILLUSTRATION_BASE}/necromancer_corpse_harvest__gpt15low_v1.png`,
    necromancer_corpse_lance: `${CARD_ILLUSTRATION_BASE}/necromancer_corpse_lance__gpt15low_v1.png`,
    necromancer_curse_mastery: `${CARD_ILLUSTRATION_BASE}/necromancer_curse_mastery__gpt15low_v1.png`,
    necromancer_dark_pact: `${CARD_ILLUSTRATION_BASE}/necromancer_dark_pact__gpt15low_v1.png`,
    necromancer_dark_ward: `${CARD_ILLUSTRATION_BASE}/necromancer_dark_ward__gpt15low_v1.png`,
    necromancer_death_pact: `${CARD_ILLUSTRATION_BASE}/necromancer_death_pact__gpt15low_v1.png`,
    necromancer_desecrate: `${CARD_ILLUSTRATION_BASE}/necromancer_desecrate__gpt15low_v1.png`,
    necromancer_dim_vision: `${CARD_ILLUSTRATION_BASE}/necromancer_dim_vision__gpt15high_ability_v1.png`,
    necromancer_fire_golem: `${CARD_ILLUSTRATION_BASE}/necromancer_fire_golem__gpt15low_v1.png`,
    necromancer_golem_mastery: `${CARD_ILLUSTRATION_BASE}/necromancer_golem_mastery__gpt15low_v1.png`,
    necromancer_iron_golem: `${CARD_ILLUSTRATION_BASE}/necromancer_iron_golem__gpt15low_v1.png`,
    necromancer_lower_resist: `${CARD_ILLUSTRATION_BASE}/necromancer_lower_resist__gpt15low_v1.png`,
    necromancer_mass_curse: `${CARD_ILLUSTRATION_BASE}/necromancer_mass_curse__gpt15low_v1.png`,
    necromancer_plague_wind: `${CARD_ILLUSTRATION_BASE}/necromancer_plague_wind__gpt15low_v1.png`,
    necromancer_poison_explosion: `${CARD_ILLUSTRATION_BASE}/necromancer_poison_explosion__gpt15low_v1.png`,
    necromancer_skeleton_mastery: `${CARD_ILLUSTRATION_BASE}/necromancer_skeleton_mastery__gpt15low_v1.png`,
    necromancer_soul_harvest: `${CARD_ILLUSTRATION_BASE}/necromancer_soul_harvest__gpt15low_v1.png`,
    necromancer_summon_resist: `${CARD_ILLUSTRATION_BASE}/necromancer_summon_resist__gpt15low_v1.png`,
    necromancer_terror: `${CARD_ILLUSTRATION_BASE}/necromancer_terror__gpt15high_ability_v1.png`,
    necromancer_weaken: `${CARD_ILLUSTRATION_BASE}/necromancer_weaken__gpt15high_ability_v1.png`,
    paladin_aura_mastery: `${CARD_ILLUSTRATION_BASE}/paladin_aura_mastery__gpt15low_v1.png`,
    paladin_blessed_aim: `${CARD_ILLUSTRATION_BASE}/paladin_blessed_aim__gpt15low_v1.png`,
    paladin_blessed_hammer_storm: `${CARD_ILLUSTRATION_BASE}/paladin_blessed_hammer_storm__gpt15low_v1.png`,
    paladin_blessed_ward: `${CARD_ILLUSTRATION_BASE}/paladin_blessed_ward__gpt15low_v1.png`,
    paladin_charge: `${CARD_ILLUSTRATION_BASE}/paladin_charge__gpt15high_ability_v1.png`,
    paladin_combat_mastery: `${CARD_ILLUSTRATION_BASE}/paladin_combat_mastery__gpt15low_v1.png`,
    paladin_concentration: `${CARD_ILLUSTRATION_BASE}/paladin_concentration__gpt15low_v1.png`,
    paladin_conversion: `${CARD_ILLUSTRATION_BASE}/paladin_conversion__gpt15low_v1.png`,
    paladin_crusade: `${CARD_ILLUSTRATION_BASE}/paladin_crusade__gpt15low_v1.png`,
    paladin_divine_command: `${CARD_ILLUSTRATION_BASE}/paladin_divine_command__gpt15low_v1.png`,
    paladin_divine_renewal: `${CARD_ILLUSTRATION_BASE}/paladin_divine_renewal__gpt15low_v1.png`,
    paladin_divine_shield: `${CARD_ILLUSTRATION_BASE}/paladin_divine_shield__gpt15low_v1.png`,
    paladin_holy_fortress: `${CARD_ILLUSTRATION_BASE}/paladin_holy_fortress__gpt15low_v1.png`,
    paladin_holy_judgment: `${CARD_ILLUSTRATION_BASE}/paladin_holy_judgment__gpt15low_v1.png`,
    paladin_holy_resolve: `${CARD_ILLUSTRATION_BASE}/paladin_holy_resolve__gpt15low_v1.png`,
    paladin_holy_shock: `${CARD_ILLUSTRATION_BASE}/paladin_holy_shock__gpt15low_v1.png`,
    paladin_holy_strike: `${CARD_ILLUSTRATION_BASE}/paladin_holy_strike__gpt15low_v1.png`,
    paladin_holy_war: `${CARD_ILLUSTRATION_BASE}/paladin_holy_war__gpt15low_v1.png`,
    paladin_meditation: `${CARD_ILLUSTRATION_BASE}/paladin_meditation__gpt15high_ability_v1.png`,
    paladin_redemption: `${CARD_ILLUSTRATION_BASE}/paladin_redemption__gpt15high_ability_v1.png`,
    paladin_resist_cold: `${CARD_ILLUSTRATION_BASE}/paladin_resist_cold__gpt15low_v1.png`,
    paladin_resist_fire: `${CARD_ILLUSTRATION_BASE}/paladin_resist_fire__gpt15low_v1.png`,
    paladin_righteous_guard: `${CARD_ILLUSTRATION_BASE}/paladin_righteous_guard__gpt15low_v1.png`,
    paladin_righteous_wrath: `${CARD_ILLUSTRATION_BASE}/paladin_righteous_wrath__gpt15low_v1.png`,
    paladin_salvation: `${CARD_ILLUSTRATION_BASE}/paladin_salvation__gpt15low_v1.png`,
    paladin_sanctuary: `${CARD_ILLUSTRATION_BASE}/paladin_sanctuary__gpt15high_ability_v1.png`,
    paladin_vigor: `${CARD_ILLUSTRATION_BASE}/paladin_vigor__gpt15high_ability_v1.png`,
    paladin_zealous_fury: `${CARD_ILLUSTRATION_BASE}/paladin_zealous_fury__gpt15low_v1.png`,
    sorceress_arc_mastery: `${CARD_ILLUSTRATION_BASE}/sorceress_arc_mastery__gpt15low_v1.png`,
    sorceress_arcane_barrage: `${CARD_ILLUSTRATION_BASE}/sorceress_arcane_barrage__gpt15low_v1.png`,
    sorceress_arcane_focus: `${CARD_ILLUSTRATION_BASE}/sorceress_arcane_focus__gpt15low_v1.png`,
    sorceress_arcane_ward: `${CARD_ILLUSTRATION_BASE}/sorceress_arcane_ward__gpt15low_v1.png`,
    sorceress_blaze: `${CARD_ILLUSTRATION_BASE}/sorceress_blaze__gpt15high_ability_v1.png`,
    sorceress_chilling_armor: `${CARD_ILLUSTRATION_BASE}/sorceress_chilling_armor__gpt15high_ability_v1.png`,
    sorceress_cold_mastery: `${CARD_ILLUSTRATION_BASE}/sorceress_cold_mastery__gpt15low_v1.png`,
    sorceress_combustion: `${CARD_ILLUSTRATION_BASE}/sorceress_combustion__gpt15low_v1.png`,
    sorceress_conflagration: `${CARD_ILLUSTRATION_BASE}/sorceress_conflagration__gpt15low_v1.png`,
    sorceress_elemental_mastery: `${CARD_ILLUSTRATION_BASE}/sorceress_elemental_mastery__gpt15low_v1.png`,
    sorceress_enchant: `${CARD_ILLUSTRATION_BASE}/sorceress_enchant__gpt15high_ability_v1.png`,
    sorceress_fire_mastery: `${CARD_ILLUSTRATION_BASE}/sorceress_fire_mastery__gpt15low_v1.png`,
    sorceress_fire_wall: `${CARD_ILLUSTRATION_BASE}/sorceress_fire_wall__gpt15low_v1.png`,
    sorceress_frost_bolt: `${CARD_ILLUSTRATION_BASE}/sorceress_frost_bolt__gpt15low_v1.png`,
    sorceress_glacial_spike: `${CARD_ILLUSTRATION_BASE}/sorceress_glacial_spike__gpt15low_v1.png`,
    sorceress_ice_blast: `${CARD_ILLUSTRATION_BASE}/sorceress_ice_blast__gpt15low_v1.png`,
    sorceress_lightning: `${CARD_ILLUSTRATION_BASE}/sorceress_lightning__gpt15low_v1.png`,
    sorceress_mana_shield: `${CARD_ILLUSTRATION_BASE}/sorceress_mana_shield__gpt15low_v1.png`,
    sorceress_nova: `${CARD_ILLUSTRATION_BASE}/sorceress_nova__gpt15low_v1.png`,
    sorceress_overcharge: `${CARD_ILLUSTRATION_BASE}/sorceress_overcharge__gpt15low_v1.png`,
    sorceress_renewal: `${CARD_ILLUSTRATION_BASE}/sorceress_renewal__gpt15low_v1.png`,
    sorceress_shiver_armor: `${CARD_ILLUSTRATION_BASE}/sorceress_shiver_armor__gpt15high_ability_v1.png`,
    sorceress_spell_cascade: `${CARD_ILLUSTRATION_BASE}/sorceress_spell_cascade__gpt15low_v1.png`,
    sorceress_spell_surge: `${CARD_ILLUSTRATION_BASE}/sorceress_spell_surge__gpt15low_v1.png`,
    sorceress_telekinesis: `${CARD_ILLUSTRATION_BASE}/sorceress_telekinesis__gpt15low_v1.png`,
    sorceress_tempest: `${CARD_ILLUSTRATION_BASE}/sorceress_tempest__gpt15low_v1.png`,
    sorceress_thunder_storm: `${CARD_ILLUSTRATION_BASE}/sorceress_thunder_storm__gpt15high_ability_v1.png`,
  };

  const MINION_ILLUSTRATIONS: Record<string, string> = {
    necro_army_t1: `${MINION_ILLUSTRATION_BASE}/skeleton_army_t1__gpt15high_final.png`,
    necro_army_t2: `${MINION_ILLUSTRATION_BASE}/skeleton_army_t2__gpt15high_final.png`,
    necro_army_t3: `${MINION_ILLUSTRATION_BASE}/skeleton_army_t3__gpt15high_final.png`,
    necro_army_t4: `${MINION_ILLUSTRATION_BASE}/skeleton_army_t4__gpt15high_final.png`,
    necro_army_t5: `${MINION_ILLUSTRATION_BASE}/skeleton_army_t5__gpt15high_final.png`,
    druid_pack_t1: `${MINION_ILLUSTRATION_BASE}/wolf_pack_t1__gpt15high_final.png`,
    druid_pack_t2: `${MINION_ILLUSTRATION_BASE}/wolf_pack_t2__gpt15high_final.png`,
    druid_pack_t3: `${MINION_ILLUSTRATION_BASE}/wolf_pack_t3__gpt15high_final.png`,
    druid_pack_t4: `${MINION_ILLUSTRATION_BASE}/wolf_pack_t4__gpt15high_final.png`,
    druid_pack_t5: `${MINION_ILLUSTRATION_BASE}/wolf_pack_t5__gpt15high_final.png`,
    necro_golem_t1: `${MINION_ILLUSTRATION_BASE}/necromancer_golem_t1__gpt15high_final.png`,
    necro_golem_t2: `${MINION_ILLUSTRATION_BASE}/necromancer_golem_t2__gpt15high_final.png`,
    necro_golem_t3: `${MINION_ILLUSTRATION_BASE}/necromancer_golem_t3__gpt15high_final.png`,
    necro_golem_t4: `${MINION_ILLUSTRATION_BASE}/necromancer_golem_t4__gpt15high_final.png`,
    necro_golem_t5: `${MINION_ILLUSTRATION_BASE}/necromancer_golem_t5__gpt15high_final.png`,
    assassin_wake_of_fire_t1: `${MINION_ILLUSTRATION_BASE}/assassin_wake_of_fire_t1__gpt15high_final.png`,
    assassin_wake_of_fire_t2: `${MINION_ILLUSTRATION_BASE}/assassin_wake_of_fire_t2__gpt15high_final.png`,
    assassin_wake_of_fire_t3: `${MINION_ILLUSTRATION_BASE}/assassin_wake_of_fire_t3__gpt15high_final.png`,
    assassin_blade_sentinel_t1: `${MINION_ILLUSTRATION_BASE}/assassin_blade_sentinel_t1__gpt15high_final.png`,
    assassin_blade_sentinel_t2: `${MINION_ILLUSTRATION_BASE}/assassin_blade_sentinel_t2__gpt15high_final.png`,
    assassin_blade_sentinel_t3: `${MINION_ILLUSTRATION_BASE}/assassin_blade_sentinel_t3__gpt15high_final.png`,
    assassin_charged_bolt_sentry_t1: `${MINION_ILLUSTRATION_BASE}/assassin_charged_bolt_sentry_t1__gpt15high_final.png`,
    assassin_charged_bolt_sentry_t2: `${MINION_ILLUSTRATION_BASE}/assassin_charged_bolt_sentry_t2__gpt15high_final.png`,
    assassin_charged_bolt_sentry_t3: `${MINION_ILLUSTRATION_BASE}/assassin_charged_bolt_sentry_t3__gpt15high_final.png`,
    assassin_lightning_sentry_t1: `${MINION_ILLUSTRATION_BASE}/assassin_lightning_sentry_t1__gpt15high_final.png`,
    assassin_lightning_sentry_t2: `${MINION_ILLUSTRATION_BASE}/assassin_lightning_sentry_t2__gpt15high_final.png`,
    assassin_lightning_sentry_t3: `${MINION_ILLUSTRATION_BASE}/assassin_lightning_sentry_t3__gpt15high_final.png`,
    assassin_death_sentry_t1: `${MINION_ILLUSTRATION_BASE}/assassin_death_sentry_t1__gpt15high_final.png`,
    assassin_death_sentry_t2: `${MINION_ILLUSTRATION_BASE}/assassin_death_sentry_t2__gpt15high_final.png`,
    assassin_death_sentry_t3: `${MINION_ILLUSTRATION_BASE}/assassin_death_sentry_t3__gpt15high_final.png`,
    assassin_shadow_trap_t1: `${MINION_ILLUSTRATION_BASE}/assassin_shadow_trap_t1__gpt15high_final.png`,
    assassin_shadow_trap_t2: `${MINION_ILLUSTRATION_BASE}/assassin_shadow_trap_t2__gpt15high_final.png`,
    assassin_shadow_trap_t3: `${MINION_ILLUSTRATION_BASE}/assassin_shadow_trap_t3__gpt15high_final.png`,
    assassin_wake_of_inferno_t1: `${MINION_ILLUSTRATION_BASE}/assassin_wake_of_inferno_t1__gpt15high_final.png`,
    assassin_wake_of_inferno_t2: `${MINION_ILLUSTRATION_BASE}/assassin_wake_of_inferno_t2__gpt15high_final.png`,
    assassin_wake_of_inferno_t3: `${MINION_ILLUSTRATION_BASE}/assassin_wake_of_inferno_t3__gpt15high_final.png`,
    necromancer_revive: `${MINION_ILLUSTRATION_BASE}/necromancer_revive__gpt15high_v1.png`,
    amazon_valkyrie: `${MINION_ILLUSTRATION_BASE}/amazon_valkyrie__gpt15high_v1.png`,
    amazon_decoy: `${MINION_ILLUSTRATION_BASE}/amazon_decoy__gpt15high_v1.png`,
    druid_raven: `${MINION_ILLUSTRATION_BASE}/druid_raven__gpt15high_v1.png`,
    druid_poison_creeper: `${MINION_ILLUSTRATION_BASE}/druid_poison_creeper__gpt15high_v1.png`,
    druid_oak_sage: `${MINION_ILLUSTRATION_BASE}/druid_oak_sage__gpt15high_v2.png`,
    druid_heart_of_wolverine: `${MINION_ILLUSTRATION_BASE}/druid_heart_of_wolverine__gpt15high_v2.png`,
    druid_grizzly: `${MINION_ILLUSTRATION_BASE}/druid_grizzly__gpt15high_v1.png`,
    assassin_shadow_master: `${MINION_ILLUSTRATION_BASE}/assassin_shadow_master__gpt15high_v1.png`,
    druid_solar_creeper: `${MINION_ILLUSTRATION_BASE}/druid_solar_creeper__gpt15high_v1.png`,
    druid_spirit_of_barbs: `${MINION_ILLUSTRATION_BASE}/druid_spirit_of_barbs__gpt15high_v2.png`,
    druid_carrion_vine: `${MINION_ILLUSTRATION_BASE}/druid_carrion_vine__gpt15high_v1.png`,
    druid_treant: `${MINION_ILLUSTRATION_BASE}/druid_treant__gpt15high_v1.png`,
    sorceress_hydra: `${MINION_ILLUSTRATION_BASE}/sorceress_hydra__gpt15high_v1.png`,
  };

  const CARD_FRAMES: Record<string, string> = {
    attack: `${CARD_FRAME_BASE}/frame_assault_shortlist_b.png`,
    summon: `${CARD_FRAME_BASE}/frame_assault_shortlist_b.png`,
    guard: `${CARD_FRAME_BASE}/frame_assault_shortlist_b.png`,
    affliction: `${CARD_FRAME_BASE}/frame_assault_shortlist_b.png`,
    draw: `${CARD_FRAME_BASE}/frame_assault_shortlist_b.png`,
    setup: `${CARD_FRAME_BASE}/frame_assault_shortlist_b.png`,
    support: `${CARD_FRAME_BASE}/frame_assault_shortlist_b.png`,
    utility: `${CARD_FRAME_BASE}/frame_assault_shortlist_b.png`,
  };

  const ENEMY_SVGS = [
    `${THEMED_ENEMY_ICON_BASE}/01_diablo-skull.svg`,
    `${THEMED_ENEMY_ICON_BASE}/02_cultist.svg`,
    `${THEMED_ENEMY_ICON_BASE}/03_warlock-hood.svg`,
    `${THEMED_ENEMY_ICON_BASE}/04_ogre.svg`,
    `${THEMED_ENEMY_ICON_BASE}/05_troll.svg`,
    `${THEMED_ENEMY_ICON_BASE}/06_vampire-dracula.svg`,
    `${THEMED_ENEMY_ICON_BASE}/07_shambling-zombie.svg`,
    `${THEMED_ENEMY_ICON_BASE}/08_grim-reaper.svg`,
    `${THEMED_ENEMY_ICON_BASE}/09_devil-mask.svg`,
    `${THEMED_ENEMY_ICON_BASE}/10_death-skull.svg`,
    `${THEMED_ENEMY_ICON_BASE}/11_dragon-head.svg`,
    `${THEMED_ENEMY_ICON_BASE}/12_crowned-skull.svg`,
  ];

  const ENEMY_FALLBACK_DEFAULTS = {
    regular: `${THEMED_ENEMY_ICON_BASE}/01_diablo-skull.svg`,
    boss: `${THEMED_ENEMY_ICON_BASE}/12_crowned-skull.svg`,
  };

  const ENEMY_FALLBACK_RULES = [
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/07_shambling-zombie.svg`,
      keywords: ["zombie", "mummy", "corpse", "reanimated", "cadaver", "putrid", "pindle"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/10_death-skull.svg`,
      keywords: ["skeleton", "bone", "wraith", "ghost", "willowisp", "undead", "specter", "apparition"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/02_cultist.svg`,
      keywords: ["rogue", "priest", "shaman", "witch", "countess", "summoner", "council", "zakarum"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/03_warlock-hood.svg`,
      keywords: ["mage", "warlock", "oblivion", "succubus", "vampire", "andariel", "mephisto", "baal"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/04_ogre.svg`,
      keywords: ["goatman", "blunderbore", "abominable", "mauler", "overseer", "tainted"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/05_troll.svg`,
      keywords: ["wendigo", "hulk", "defiler", "siege_beast", "minion_of_destruction", "blood_lord"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/06_vampire-dracula.svg`,
      keywords: ["vampire", "succubus", "lilith"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/09_devil-mask.svg`,
      keywords: ["fallen", "carver", "imp", "fetish", "frog_demon", "baboon_demon", "devilkin"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/11_dragon-head.svg`,
      keywords: ["hawk", "bat", "vulture", "scarab", "viper", "spider", "maggot", "mosquito", "swarm"],
    },
    {
      icon: `${THEMED_ENEMY_ICON_BASE}/12_crowned-skull.svg`,
      keywords: ["boss", "super_unique", "uber", "diablo", "duriel", "andariel", "izual", "nihlathak"],
    },
  ];

  const BROKEN_ENEMY_SPRITES = new Set<string>();

  const BROKEN_BOSS_SPRITES = new Set<string>();

  const UI_ICONS: Record<string, string> = {
    hp: `${THEMED_UI_ICON_BASE}/hp_heart-drop.svg`,
    energy: `${THEMED_UI_ICON_BASE}/energy_chalice-drops.svg`,
    guard: `${THEMED_UI_ICON_BASE}/block_chest-armor.svg`,
    burn: `${THEMED_UI_ICON_BASE}/heat_burning-eye.svg`,
    poison: `${THEMED_UI_ICON_BASE}/poison_poison-bottle.svg`,
    slow: `${THEMED_UI_ICON_BASE}/slow_hourglass.svg`,
    freeze: `${THEMED_UI_ICON_BASE}/freeze_snowflake.svg`,
    stun: `${THEMED_UI_ICON_BASE}/stun_star-burst.svg`,
    paralyze: `${THEMED_UI_ICON_BASE}/paralyze_shock-bolt.svg`,
    chill: `${THEMED_UI_ICON_BASE}/chill_frost-wind.svg`,
    amplify: `${THEMED_UI_ICON_BASE}/amplify_armor-upgrade.svg`,
    weaken: `${THEMED_UI_ICON_BASE}/weaken_armor-downgrade.svg`,
    drain: `${THEMED_UI_ICON_BASE}/drain_life-tap.svg`,
    turn: `${THEMED_UI_ICON_BASE}/turn_grim-reaper.svg`,
    alert: `${THEMED_UI_ICON_BASE}/alert_death-skull.svg`,
    crit: `${THEMED_CARD_ICON_BASE}/19_fangs.svg`,
    idea: `${THEMED_UI_ICON_BASE}/info_candle-holder.svg`,
  };

  const INTENT_ICONS: Record<string, string> = {
    attack: `${THEMED_UI_ICON_BASE}/intent_attack_blade.svg`,
    guard: `${THEMED_UI_ICON_BASE}/intent_guard_shield.svg`,
    buff: `${THEMED_UI_ICON_BASE}/intent_buff_aura.svg`,
    debuff: `${THEMED_UI_ICON_BASE}/intent_debuff_hex.svg`,
    heal: `${THEMED_UI_ICON_BASE}/intent_heal_vitality.svg`,
    unknown: `${THEMED_UI_ICON_BASE}/intent_unknown_omen.svg`,
  };

  const CLASS_PORTRAITS: Record<string, string> = {
    amazon: `${PORTRAIT_BASE}/amazon.png`,
    assassin: `${PORTRAIT_BASE}/assassin.png`,
    barbarian: `${PORTRAIT_BASE}/barbarian.png`,
    druid: `${PORTRAIT_BASE}/druid.png`,
    necromancer: `${PORTRAIT_BASE}/necromancer.png`,
    paladin: `${PORTRAIT_BASE}/paladin.png`,
    sorceress: `${PORTRAIT_BASE}/sorceress.png`,
  };

  const KNOWN_ENEMY_SPRITES = new Set([
    "abominable","baal_s_minion","baboon_demon","bat_demon","blood_hawk",
    "blood_hawk_nest","blood_lord","blunderbore","bone_fetish","catapult",
    "claw_viper","corrupt_rogue","corrupt_rogue_archer","corrupt_rogue_spearwoman",
    "council_member","death_mauler","demon_imp","fallen","fallen_shaman",
    "fetish","fetish_shaman","fire_tower","flying_scimitar","frog_demon",
    "frozen_horror","gargoyle_trap","giant_mosquito","giant_spider","goatman",
    "leaper","lightning_spire","megademon","minion_of_destruction","mummy",
    "mummy_sarcophagus","oblivion_knight","overseer","pain_worm",
    "reanimated_horde","regurgitator","reziarfg","sabre_cat","sand_maggot",
    "sand_maggot_egg","sand_maggot_young","sand_raider","scarab_demon",
    "siege_beast","skeleton","skeleton_archer","skeleton_mage","slinger",
    "spike_fiend","stygian_fury","succubus","suicide_minion","swarm",
    "tainted","undead_horror","vampire","vile_child","vile_mother",
    "vulture_demon","wendigo","willowisp","wraith","zakarum_priest",
    "zakarum_zealot","zombie",
  ]);

  const VARIANT_SPRITE_MAP: Record<string, string> = {
    dark_hunter: "corrupt_rogue_archer", dark_ranger: "corrupt_rogue_archer",
    dark_spearwoman: "corrupt_rogue_spearwoman", black_rogue: "corrupt_rogue",
    dark_stalker: "corrupt_rogue", vile_hunter: "corrupt_rogue_archer",
    vile_lancer: "corrupt_rogue_spearwoman", flesh_hunter: "corrupt_rogue_archer",
    night_clan: "goatman", blood_clan: "goatman", moon_clan: "goatman",
    hell_clan: "goatman", death_clan: "goatman",
    bone_warrior: "skeleton", bone_archer: "skeleton_archer", bone_mage: "skeleton_mage",
    burning_dead: "skeleton", burning_dead_archer: "skeleton_archer", burning_dead_mage: "skeleton_mage",
    horror: "skeleton", horror_archer: "skeleton_archer", horror_mage: "skeleton_mage",
    returned: "skeleton", returned_archer: "skeleton_archer", returned_mage: "skeleton_mage",
    hungry_dead: "zombie", ghoul: "zombie", drowned_carcass: "zombie",
    plague_bearer: "zombie", cadaver: "zombie",
    brute: "wendigo", gargantuan_beast: "wendigo", yeti: "wendigo",
    carver: "fallen", carver_shaman: "fallen_shaman",
    devilkin: "fallen", devilkin_shaman: "fallen_shaman",
    dark_one: "fallen", dark_one_shaman: "fallen_shaman",
    warped_one: "fallen", warped_shaman: "fallen_shaman",
    quill_rat: "spike_fiend", thorn_beast: "spike_fiend", razor_spine: "spike_fiend",
    foul_crow: "blood_hawk", foul_crow_nest: "blood_hawk_nest",
    black_raptor: "blood_hawk", black_vulture_nest: "blood_hawk_nest",
    cloud_stalker: "blood_hawk", cloud_stalker_nest: "blood_hawk_nest",
    huntress: "sabre_cat", spear_cat: "sabre_cat", night_tiger: "sabre_cat", hell_cat: "sabre_cat",
    cave_leaper: "leaper", tomb_creeper: "leaper", tree_lurker: "leaper", sand_leaper: "leaper",
    dung_soldier: "scarab_demon",
    sand_warrior: "sand_raider", marauder: "sand_raider", invader: "sand_raider",
    infidel: "sand_raider", assailant: "sand_raider",
    itchies: "swarm", black_locusts: "swarm", hell_swarm: "swarm", plague_bugs: "swarm",
    sucker: "giant_mosquito", feeder: "giant_mosquito", blood_hook: "giant_mosquito",
    flayer: "fetish", flayer_shaman: "fetish_shaman",
    soul_killer: "fetish", soul_killer_shaman: "fetish_shaman",
    stygian_doll: "fetish", jungle_hunter: "fetish",
    thorned_hulk: "wendigo", bramble_hulk: "wendigo", thrasher: "wendigo",
    bog_creature: "wendigo", swamp_dweller: "wendigo",
    slime_prince: "frog_demon",
    gloam: "willowisp", burning_soul: "willowisp", black_soul: "willowisp",
    doom_caster: "oblivion_knight", abyss_knight: "oblivion_knight",
    pit_lord: "megademon", venom_lord: "megademon", balrog: "megademon",
    flesh_spawner: "vile_mother", stygian_hag: "vile_mother", grotesque: "vile_mother",
    flesh_beast: "vile_child", stygian_dog: "vile_child", grotesque_wyrm: "vile_child",
    hell_temptress: "succubus", blood_temptress: "succubus", stygian_fury: "succubus",
    cantor: "zakarum_priest", heirophant: "zakarum_priest",
    zealot: "zakarum_zealot", faithful: "zakarum_zealot",
    apparition: "wraith", specter: "wraith",
    banished: "regurgitator", blood_lord: "blood_lord",
    enslaved: "overseer", slayer: "overseer",
    death_mauler: "death_mauler", minion_of_destruction: "minion_of_destruction",
    undead_scavenger: "zombie",
    saber_cat: "sabre_cat", afflicted: "tainted", misshapen: "tainted", disfigured: "tainted",
    albino_roach: "scarab_demon", scarab: "scarab_demon", steel_weevil: "scarab_demon",
    arach: "giant_spider", flame_spider: "giant_spider",
    poison_spinner: "giant_spider", spider_magus: "giant_spider",
    black_archer: "skeleton_archer", dark_archer: "skeleton_archer",
    black_lancer: "corrupt_rogue_spearwoman", dark_lancer: "corrupt_rogue_spearwoman",
    flesh_archer: "corrupt_rogue_archer", vile_archer: "corrupt_rogue_archer",
    blood_boss: "overseer", overlord: "overseer", lasher: "overseer", hell_whip: "overseer",
    blood_bringer: "blood_lord",
    blood_diver: "bat_demon", blood_wing: "bat_demon", dark_familiar: "bat_demon",
    gloombat: "bat_demon", winged_nightmare: "bat_demon",
    carrion_bird: "vulture_demon", hell_buzzard: "vulture_demon",
    corpse_spitter: "regurgitator", putrid_defiler: "regurgitator",
    corpulent: "zombie", gorbelly: "zombie", prowling_dead: "zombie",
    rot_walker: "zombie", unholy_corpse: "zombie",
    crush_beast: "siege_beast", crusher: "siege_beast",
    damned: "wraith", dark_shape: "wraith", ghost: "wraith",
    defiled_warrior: "skeleton",
    dark_lord: "vampire", night_lord: "vampire", ghoul_lord: "vampire",
    devourer: "sand_maggot", rock_worm: "sand_maggot", giant_lamprey: "sand_maggot",
    groper: "sand_maggot", strangler: "sand_maggot", maw_fiend: "sand_maggot",
    doom_ape: "baboon_demon", doom_knight: "oblivion_knight", dominus: "oblivion_knight",
    dried_corpse: "mummy", embalmed: "mummy", preserved_dead: "mummy",
    sexton: "mummy", horadrim_ancient: "mummy", unraveler: "mummy",
    guardian: "mummy_sarcophagus",
    dune_beast: "wendigo", wailing_beast: "wendigo", snow_yeti: "wendigo",
    ancient_barbarian_1: "wendigo", ancient_barbarian_2: "wendigo", ancient_barbarian_3: "wendigo",
    fiend: "spike_fiend", razor_pit_demon: "spike_fiend",
    fire_boar: "demon_imp", imp: "demon_imp", hell_spawn: "demon_imp", greater_hell_spawn: "demon_imp",
    frenzied_ice_spawn: "frozen_horror", ice_spawn: "frozen_horror",
    hell_bovine: "wendigo",
    hell_slinger: "slinger", night_slinger: "slinger",
    night_marauder: "sand_raider",
    hell_witch: "succubus", stygian_harlot: "succubus",
    vile_temptress: "succubus", vile_witch: "succubus",
    baal_taunt: "baal_s_minion", minion: "baal_s_minion",
    mauler: "death_mauler",
    pit_viper: "claw_viper", salamander: "claw_viper",
    serpent_magus: "claw_viper", tomb_viper: "claw_viper",
    storm_caster: "willowisp",
    rat_man: "fetish", undead_flayer: "fetish",
    undead_soul_killer: "fetish", undead_stygian_doll: "fetish",
    dark_shaman: "fallen_shaman",
    urdar: "megademon", world_killer: "megademon",
    temple_guard: "zakarum_zealot", zakarumite: "zakarum_zealot",
  };

  const ITEM_SPRITE_BASE = `${SPRITE_BASE}/items`;

  const ITEM_SPRITES: Record<string, string> = {
    // Swords
    short_sword: `${ITEM_SPRITE_BASE}/short_sword.png`,
    scimitar: `${ITEM_SPRITE_BASE}/scimitar.png`,
    sabre: `${ITEM_SPRITE_BASE}/sabre.png`,
    long_sword: `${ITEM_SPRITE_BASE}/long_sword.png`,
    falchion: `${ITEM_SPRITE_BASE}/falchion.png`,
    crystal_sword: `${ITEM_SPRITE_BASE}/crystal_sword.png`,
    bastard_sword: `${ITEM_SPRITE_BASE}/bastard_sword.png`,
    broad_sword: `${ITEM_SPRITE_BASE}/broad_sword.png`,
    war_sword: `${ITEM_SPRITE_BASE}/war_sword.png`,
    rune_sword: `${ITEM_SPRITE_BASE}/rune_sword.png`,
    legend_sword: `${ITEM_SPRITE_BASE}/legend_sword.png`,
    zweihander: `${ITEM_SPRITE_BASE}/zweihander.png`,
    balrog_blade: `${ITEM_SPRITE_BASE}/balrog_blade.png`,
    colossus_blade: `${ITEM_SPRITE_BASE}/colossus_blade.png`,
    // Maces
    mace: `${ITEM_SPRITE_BASE}/mace.png`,
    war_hammer: `${ITEM_SPRITE_BASE}/war_hammer.png`,
    morning_star: `${ITEM_SPRITE_BASE}/morning_star.png`,
    flail: `${ITEM_SPRITE_BASE}/flail.png`,
    maul: `${ITEM_SPRITE_BASE}/maul.png`,
    // Polearms
    partizan: `${ITEM_SPRITE_BASE}/partizan.png`,
    grim_scythe: `${ITEM_SPRITE_BASE}/grim_scythe.png`,
    // Bows / Crossbows
    short_bow: `${ITEM_SPRITE_BASE}/composite_bow.png`,
    long_bow: `${ITEM_SPRITE_BASE}/long_bow.png`,
    composite_bow: `${ITEM_SPRITE_BASE}/composite_bow.png`,
    crossbow: `${ITEM_SPRITE_BASE}/crossbow.png`,
    ashwood_bow: `${ITEM_SPRITE_BASE}/ashwood_bow.png`,
    cedar_bow: `${ITEM_SPRITE_BASE}/cedar_bow.png`,
    stag_bow: `${ITEM_SPRITE_BASE}/stag_bow.png`,
    edge_bow: `${ITEM_SPRITE_BASE}/edge_bow.png`,
    siege_crossbow: `${ITEM_SPRITE_BASE}/siege_crossbow.png`,
    hydra_bow: `${ITEM_SPRITE_BASE}/hydra_bow.png`,
    gorgon_crossbow: `${ITEM_SPRITE_BASE}/gorgon_crossbow.png`,
    // Javelins / Spears
    javelin: `${ITEM_SPRITE_BASE}/javelin.png`,
    spear: `${ITEM_SPRITE_BASE}/spear.png`,
    war_javelin: `${ITEM_SPRITE_BASE}/war_javelin.png`,
    war_spear: `${ITEM_SPRITE_BASE}/war_spear.png`,
    hyperion_javelin: `${ITEM_SPRITE_BASE}/hyperion_javelin.png`,
    ghost_spear: `${ITEM_SPRITE_BASE}/ghost_spear.png`,
    // Wands
    wand: `${ITEM_SPRITE_BASE}/wand.png`,
    yew_wand: `${ITEM_SPRITE_BASE}/yew_wand.png`,
    bone_wand: `${ITEM_SPRITE_BASE}/bone_wand.png`,
    lich_wand: `${ITEM_SPRITE_BASE}/lich_wand.png`,
    // Staves
    battle_staff: `${ITEM_SPRITE_BASE}/battle_staff.png`,
    gnarled_staff: `${ITEM_SPRITE_BASE}/gnarled_staff.png`,
    war_staff: `${ITEM_SPRITE_BASE}/war_staff.png`,
    // Body Armor
    quilted_armor: `${ITEM_SPRITE_BASE}/quilted_armor.png`,
    breast_plate: `${ITEM_SPRITE_BASE}/breast_plate.png`,
    leather_armor: `${ITEM_SPRITE_BASE}/leather_armor.png`,
    scale_mail: `${ITEM_SPRITE_BASE}/scale_mail.png`,
    chain_mail: `${ITEM_SPRITE_BASE}/chain_mail.png`,
    ring_mail: `${ITEM_SPRITE_BASE}/ring_mail.png`,
    splint_mail: `${ITEM_SPRITE_BASE}/splint_mail.png`,
    plate_mail: `${ITEM_SPRITE_BASE}/plate_mail.png`,
    field_plate: `${ITEM_SPRITE_BASE}/field_plate.png`,
    gothic_plate: `${ITEM_SPRITE_BASE}/gothic_plate.png`,
    light_plate: `${ITEM_SPRITE_BASE}/light_plate.png`,
    ghost_armor: `${ITEM_SPRITE_BASE}/ghost_armor.png`,
    mage_plate: `${ITEM_SPRITE_BASE}/mage_plate.png`,
    ancient_armor: `${ITEM_SPRITE_BASE}/ancient_armor.png`,
    ornate_plate: `${ITEM_SPRITE_BASE}/ornate_plate.png`,
    boneweave: `${ITEM_SPRITE_BASE}/boneweave.png`,
    chaos_armor: `${ITEM_SPRITE_BASE}/chaos_armor.png`,
    hellforge_plate: `${ITEM_SPRITE_BASE}/hellforge_plate.png`,
    archon_plate: `${ITEM_SPRITE_BASE}/archon_plate.png`,
    full_plate_mail: `${ITEM_SPRITE_BASE}/full_plate_mail.png`,
    // Helms
    cap: `${ITEM_SPRITE_BASE}/cap.png`,
    skull_cap: `${ITEM_SPRITE_BASE}/skull_cap.png`,
    helm: `${ITEM_SPRITE_BASE}/helm.png`,
    great_helm: `${ITEM_SPRITE_BASE}/great_helm.png`,
    crown: `${ITEM_SPRITE_BASE}/crown.png`,
    // Shields
    buckler: `${ITEM_SPRITE_BASE}/buckler.png`,
    small_shield: `${ITEM_SPRITE_BASE}/small_shield.png`,
    large_shield: `${ITEM_SPRITE_BASE}/large_shield.png`,
    tower_shield: `${ITEM_SPRITE_BASE}/tower_shield.png`,
    monarch: `${ITEM_SPRITE_BASE}/monarch.png`,
    // Gloves
    leather_gloves: `${ITEM_SPRITE_BASE}/leather_gloves.png`,
    heavy_gloves: `${ITEM_SPRITE_BASE}/heavy_gloves.png`,
    chain_gloves: `${ITEM_SPRITE_BASE}/chain_gloves.png`,
    gauntlets: `${ITEM_SPRITE_BASE}/gauntlets.png`,
    // Boots
    boots: `${ITEM_SPRITE_BASE}/boots.png`,
    heavy_boots: `${ITEM_SPRITE_BASE}/heavy_boots.png`,
    chain_boots: `${ITEM_SPRITE_BASE}/chain_boots.png`,
    war_boots: `${ITEM_SPRITE_BASE}/war_boots.png`,
    // Belts
    sash: `${ITEM_SPRITE_BASE}/sash.png`,
    light_belt: `${ITEM_SPRITE_BASE}/light_belt.png`,
    heavy_belt: `${ITEM_SPRITE_BASE}/heavy_belt.png`,
    war_belt: `${ITEM_SPRITE_BASE}/war_belt.png`,
    // Rings
    ring: `${ITEM_SPRITE_BASE}/ring.png`,
    coral_ring: `${ITEM_SPRITE_BASE}/coral_ring.png`,
    jade_ring: `${ITEM_SPRITE_BASE}/jade_ring.png`,
    diamond_ring: `${ITEM_SPRITE_BASE}/diamond_ring.png`,
    // Amulets
    amulet: `${ITEM_SPRITE_BASE}/amulet.png`,
    jade_amulet: `${ITEM_SPRITE_BASE}/jade_amulet.png`,
    prismatic_amulet: `${ITEM_SPRITE_BASE}/prismatic_amulet.png`,
    highlords_amulet: `${ITEM_SPRITE_BASE}/highlords_amulet.png`,
  };

  const RUNE_SPRITES: Record<string, string> = {
    el: `${RUNE_SPRITE_BASE}/el.png`,
    eld: `${RUNE_SPRITE_BASE}/eld.png`,
    tir: `${RUNE_SPRITE_BASE}/tir.png`,
    eth: `${RUNE_SPRITE_BASE}/eth.png`,
    ith: `${RUNE_SPRITE_BASE}/ith.png`,
    nef: `${RUNE_SPRITE_BASE}/nef.png`,
    tal: `${RUNE_SPRITE_BASE}/tal.png`,
    ral: `${RUNE_SPRITE_BASE}/ral.png`,
    ort: `${RUNE_SPRITE_BASE}/ort.png`,
    thul: `${RUNE_SPRITE_BASE}/thul.png`,
    amn: `${RUNE_SPRITE_BASE}/amn.png`,
    sol: `${RUNE_SPRITE_BASE}/sol.png`,
    shael: `${RUNE_SPRITE_BASE}/shael.png`,
    hel: `${RUNE_SPRITE_BASE}/hel.png`,
    lum: `${RUNE_SPRITE_BASE}/lum.png`,
    dol: `${RUNE_SPRITE_BASE}/dol.png`,
    io: `${RUNE_SPRITE_BASE}/io.png`,
    ko: `${RUNE_SPRITE_BASE}/ko.png`,
    fal: `${RUNE_SPRITE_BASE}/fal.png`,
    lem: `${RUNE_SPRITE_BASE}/lem.png`,
    pul: `${RUNE_SPRITE_BASE}/pul.png`,
    um: `${RUNE_SPRITE_BASE}/um.png`,
    mal: `${RUNE_SPRITE_BASE}/mal.png`,
  };

  runtimeWindow.__ROUGE_ASSET_MAP_DATA = {
    UNIQUE_ART_BASE,
    CARD_ILLUSTRATION_BASE,
    MINION_ILLUSTRATION_BASE,
    CARD_FRAME_BASE,
    SPRITE_BASE,
    PORTRAIT_BASE,
    CARD_ICONS,
    CARD_ILLUSTRATIONS,
    MINION_ILLUSTRATIONS,
    CARD_FRAMES,
    ATTACK_ICONS,
    SKILL_ICONS,
    ENEMY_SVGS,
    UI_ICONS,
    INTENT_ICONS,
    CLASS_PORTRAITS,
    KNOWN_ENEMY_SPRITES,
    VARIANT_SPRITE_MAP,
    ENEMY_FALLBACK_DEFAULTS,
    ENEMY_FALLBACK_RULES,
    BROKEN_ENEMY_SPRITES,
    BROKEN_BOSS_SPRITES,
    ITEM_SPRITES,
    RUNE_SPRITES,
  };
})();
