(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Necromancer Cards ─────────────────────────────────────────────────
  // Curses: debuffs that mark enemies and weaken them
  // Poison and Bone: direct damage spells and bone barriers
  // Summoning: raise minions for sustained mercenary-like pressure

  const NECROMANCER_CARDS: Record<string, ClassCardDefinition> = {
    // ── Tier 1 ──
    necromancer_teeth: {
      id: "necromancer_teeth",
      title: "Teeth",
      cost: 1,
      target: "enemy",
      text: "Deal 7 magic damage.",
      effects: [{ kind: "damage", value: 7 }],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_teeth",
      tier: 1,
    },
    necromancer_bone_armor: {
      id: "necromancer_bone_armor",
      title: "Bone Armor",
      cost: 1,
      target: "none",
      text: "Gain 8 Guard.",
      effects: [{ kind: "gain_guard_self", value: 8 }],
      behaviorTags: ["mitigation", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_bone_armor",
      tier: 1,
    },
    necromancer_amplify_damage: {
      id: "necromancer_amplify_damage",
      title: "Amplify Damage",
      cost: 1,
      target: "enemy",
      text: "Deal 2 damage. Your mercenary deals +8 to this target. Draw 1 card.",
      effects: [
        { kind: "damage", value: 2 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "salvage", "conversion"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_amplify_damage",
      tier: 1,
    },
    necromancer_raise_skeleton: {
      id: "necromancer_raise_skeleton",
      title: "Raise Skeleton",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. Gain 5 Guard. Summon Skeleton. Each ally phase it slashes for 7.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "gain_guard_self", value: 5 },
        { kind: "summon_minion", value: 7, minionId: "necromancer_skeleton" },
      ],
      behaviorTags: ["setup", "scaling", "pressure"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_raise_skeleton",
      tier: 1,
    },
    necromancer_bone_wall: {
      id: "necromancer_bone_wall",
      title: "Bone Wall",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. Gain 5 Guard.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "gain_guard_self", value: 5 },
      ],
      behaviorTags: ["pressure", "mitigation", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_bone_wall",
      tier: 1,
    },
    necromancer_life_tap: {
      id: "necromancer_life_tap",
      title: "Life Tap",
      cost: 1,
      target: "none",
      text: "Heal 4. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 4 },
        { kind: "gain_guard_self", value: 5 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "mitigation", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_life_tap",
      tier: 1,
    },

    // ── Tier 2 ──
    necromancer_corpse_explosion: {
      id: "necromancer_corpse_explosion",
      title: "Corpse Explosion",
      cost: 2,
      target: "none",
      text: "Deal 6 fire damage to all enemies. Gain 5 Guard.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "gain_guard_self", value: 5 },
      ],
      behaviorTags: ["pressure", "mitigation", "support"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_corpse_explosion",
      tier: 2,
    },
    necromancer_clay_golem: {
      id: "necromancer_clay_golem",
      title: "Clay Golem",
      cost: 1,
      target: "none",
      text: "Deal 4 damage to all enemies. You and your mercenary gain 8 Guard. Apply 1 Slow to all enemies. Summon Clay Golem. Each ally phase it hits for 7 and grants 6 Guard to the party.",
      effects: [
        { kind: "damage_all", value: 4 },
        { kind: "gain_guard_party", value: 8 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "summon_minion", value: 7, secondaryValue: 6, minionId: "necromancer_clay_golem" },
      ],
      behaviorTags: ["setup", "scaling", "protection", "mitigation", "disruption"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "necromancer_clay_golem",
      tier: 2,
    },
    necromancer_iron_maiden: {
      id: "necromancer_iron_maiden",
      title: "Iron Maiden",
      cost: 1,
      target: "enemy",
      text: "Deal 5 damage. Your mercenary deals +8 to this target.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
      ],
      behaviorTags: ["setup", "support", "conversion"],
      roleTag: "support",
      rewardRole: "tech",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_iron_maiden",
      tier: 2,
    },
    necromancer_poison_dagger: {
      id: "necromancer_poison_dagger",
      title: "Poison Dagger",
      cost: 1,
      target: "enemy",
      text: "Deal 6 poison damage. Apply 4 Poison. Draw 1 card.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "apply_poison", value: 4 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_poison_dagger",
      tier: 2,
    },

    // ── Tier 3 ──
    necromancer_bone_spear: {
      id: "necromancer_bone_spear",
      title: "Bone Spear",
      cost: 2,
      target: "enemy",
      text: "Deal 16 magic damage.",
      effects: [{ kind: "damage", value: 16 }],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_bone_spear",
      tier: 3,
    },
    necromancer_blood_golem: {
      id: "necromancer_blood_golem",
      title: "Blood Golem",
      cost: 2,
      target: "enemy",
      text: "Deal 7 damage. You and your mercenary gain 8 Guard. Heal 9. Draw 1 card. Summon Blood Golem. Each ally phase it hits for 8 and heals you 5.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "gain_guard_party", value: 8 },
        { kind: "heal_hero", value: 9 },
        { kind: "draw", value: 1 },
        { kind: "summon_minion", value: 8, secondaryValue: 5, minionId: "necromancer_blood_golem" },
      ],
      behaviorTags: ["setup", "scaling", "protection", "conversion", "mitigation", "salvage"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "necromancer_blood_golem",
      tier: 3,
    },
    necromancer_decrepify: {
      id: "necromancer_decrepify",
      title: "Decrepify",
      cost: 1,
      target: "enemy",
      text: "Deal 11 damage. Your mercenary deals +14 to this target. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 11 },
        { kind: "mark_enemy_for_mercenary", value: 14 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "conversion", "mitigation"],
      roleTag: "support",
      rewardRole: "tech",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_decrepify",
      tier: 3,
    },
    necromancer_skeletal_mage: {
      id: "necromancer_skeletal_mage",
      title: "Skeletal Mage",
      cost: 1,
      target: "enemy",
      text: "Deal 5 poison damage. Apply 2 Poison to all enemies. Heal 3. Gain 6 Guard. Draw 1 card. Summon Skeletal Mage. Each ally phase it fires for 8 and applies 6 Poison.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "apply_poison_all", value: 2 },
        { kind: "heal_hero", value: 3 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
        { kind: "summon_minion", value: 8, secondaryValue: 6, minionId: "necromancer_skeletal_mage" },
      ],
      behaviorTags: ["setup", "scaling", "pressure", "payoff", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "necromancer_skeletal_mage",
      tier: 2,
    },

    // ── Tier 4 ──
    necromancer_bone_spirit: {
      id: "necromancer_bone_spirit",
      title: "Bone Spirit",
      cost: 2,
      target: "enemy",
      text: "Deal 24 magic damage. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 24 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_bone_spirit",
      tier: 4,
    },
    necromancer_poison_nova: {
      id: "necromancer_poison_nova",
      title: "Poison Nova",
      cost: 2,
      target: "none",
      text: "Deal 8 poison damage to all enemies. Apply 5 Poison to all.",
      effects: [
        { kind: "damage_all", value: 8 },
        { kind: "apply_poison_all", value: 5 },
      ],
      behaviorTags: ["pressure", "payoff", "setup"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_poison_nova",
      tier: 4,
    },
    necromancer_revive: {
      id: "necromancer_revive",
      title: "Revive",
      cost: 2,
      target: "enemy",
      text: "Deal 9 damage. Gain 12 Guard. Draw 1 card. Summon Revived Horror. Each ally phase it smashes for 13 and grants 6 Guard to the party.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "gain_guard_self", value: 12 },
        { kind: "draw", value: 1 },
        { kind: "summon_minion", value: 13, secondaryValue: 6, minionId: "necromancer_revive" },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "protection", "pressure", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_revive",
      tier: 4,
    },
  };

  const NECROMANCER_STARTER_DECK = [
    "necromancer_teeth",
    "necromancer_bone_wall",
    "necromancer_amplify_damage", "necromancer_amplify_damage",
    "necromancer_bone_armor",
    "necromancer_raise_skeleton", "necromancer_raise_skeleton", "necromancer_raise_skeleton",
    "rally_mercenary",
    "necromancer_life_tap",
    "necromancer_skeletal_mage",
    "necromancer_clay_golem", "necromancer_clay_golem",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const NECROMANCER_REWARD_POOL = {
    early: [...new Set([
      ...getCardIdsByTier(NECROMANCER_CARDS, 2),
      "necromancer_raise_skeleton",
    ])],
    mid: getCardIdsByTier(NECROMANCER_CARDS, 3),
    late: getCardIdsByTier(NECROMANCER_CARDS, 4),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.necromancer = {
    cards: NECROMANCER_CARDS,
    starterDeck: NECROMANCER_STARTER_DECK,
    rewardPool: NECROMANCER_REWARD_POOL,
  };
})();
