(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Druid Cards ───────────────────────────────────────────────────────
  // Elemental: fire/wind AoE spells
  // Shape Shifting: melee damage + self-healing + guard
  // Summoning: companion support and nature spirits

  const DRUID_CARDS: Record<string, ClassCardDefinition> = {
    // ── Tier 1 ──
    druid_firestorm: {
      id: "druid_firestorm",
      title: "Firestorm",
      cost: 1,
      target: "enemy",
      text: "Deal 5 fire damage. Apply 4 Burn. Gain 3 Guard.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "apply_burn", value: 4 },
        { kind: "gain_guard_self", value: 3 },
      ],
      behaviorTags: ["setup", "pressure", "mitigation"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "druid_firestorm",
      tier: 1,
    },
    druid_werewolf: {
      id: "druid_werewolf",
      title: "Werewolf",
      cost: 1,
      target: "enemy",
      text: "Deal 11 damage. Heal 5. Gain 4 Guard.",
      effects: [
        { kind: "damage", value: 11 },
        { kind: "heal_hero", value: 5 },
        { kind: "gain_guard_self", value: 4 },
      ],
      behaviorTags: ["pressure", "mitigation", "payoff"],
      roleTag: "payoff",
      rewardRole: "foundation",
      splashRole: "primary_only",
      skillRef: "druid_werewolf",
      tier: 1,
    },
    druid_raven: {
      id: "druid_raven",
      title: "Raven",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 4 Guard. Summon Raven. Each ally phase it pecks for 4 and marks for +4 mercenary damage.",
      effects: [
        { kind: "gain_guard_party", value: 4 },
        { kind: "summon_minion", value: 4, secondaryValue: 4, minionId: "druid_raven" },
      ],
      behaviorTags: ["setup", "scaling", "support", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_control"],
      skillRef: "druid_raven",
      tier: 1,
    },
    druid_poison_creeper: {
      id: "druid_poison_creeper",
      title: "Poison Creeper",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 4 Guard. Summon Poison Creeper. Each ally phase it bites for 4 and applies 4 Poison.",
      effects: [
        { kind: "gain_guard_party", value: 4 },
        { kind: "summon_minion", value: 4, secondaryValue: 4, minionId: "druid_poison_creeper" },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_control"],
      skillRef: "druid_poison_creeper",
      tier: 1,
    },
    druid_cyclone_armor: {
      id: "druid_cyclone_armor",
      title: "Cyclone Armor",
      cost: 1,
      target: "none",
      text: "Gain 8 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "druid_cyclone_armor",
      tier: 1,
    },
    druid_lycanthropy: {
      id: "druid_lycanthropy",
      title: "Lycanthropy",
      cost: 1,
      target: "none",
      text: "Heal 5. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 5 },
        { kind: "gain_guard_self", value: 5 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "druid_lycanthropy",
      tier: 1,
    },

    // ── Tier 2 ──
    druid_molten_boulder: {
      id: "druid_molten_boulder",
      title: "Molten Boulder",
      cost: 2,
      target: "enemy",
      text: "Deal 11 fire damage. Apply 3 Burn. Gain 4 Guard.",
      effects: [
        { kind: "damage", value: 11 },
        { kind: "apply_burn", value: 3 },
        { kind: "gain_guard_self", value: 4 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_molten_boulder",
      tier: 2,
    },
    druid_werebear: {
      id: "druid_werebear",
      title: "Werebear",
      cost: 1,
      target: "enemy",
      text: "Deal 9 damage. Apply 1 Slow. Gain 6 Guard. Grant 6 Guard to the party. Draw 1 card.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "apply_slow", value: 1 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "gain_guard_party", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "conversion", "salvage", "disruption"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_werebear",
      tier: 2,
    },
    druid_oak_sage: {
      id: "druid_oak_sage",
      title: "Oak Sage",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 6 Guard. Summon Oak Sage. Each ally phase it heals you and your mercenary for 4.",
      effects: [
        { kind: "gain_guard_party", value: 6 },
        { kind: "summon_minion", value: 4, minionId: "druid_oak_sage" },
      ],
      behaviorTags: ["setup", "protection", "salvage", "support"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "druid_oak_sage",
      tier: 2,
    },
    druid_fissure: {
      id: "druid_fissure",
      title: "Fissure",
      cost: 2,
      target: "none",
      text: "Deal 6 fire damage to all enemies. Apply 2 Burn to all. Gain 4 Guard.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "apply_burn_all", value: 2 },
        { kind: "gain_guard_self", value: 4 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_fissure",
      tier: 2,
    },

    // ── Tier 3 ──
    druid_volcano: {
      id: "druid_volcano",
      title: "Volcano",
      cost: 2,
      target: "none",
      text: "Deal 8 fire damage to all enemies. Apply 4 Burn to all. Gain 6 Guard.",
      effects: [
        { kind: "damage_all", value: 8 },
        { kind: "apply_burn_all", value: 4 },
        { kind: "gain_guard_self", value: 6 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_volcano",
      tier: 3,
    },
    druid_fury: {
      id: "druid_fury",
      title: "Fury",
      cost: 2,
      target: "enemy",
      text: "Deal 12 damage. Deal 11 damage. Deal 10 damage. Apply 1 Slow. Gain 12 Guard. Grant 8 Guard to the party. Draw 1 card.",
      effects: [
        { kind: "damage", value: 12 },
        { kind: "damage", value: 11 },
        { kind: "damage", value: 10 },
        { kind: "apply_slow", value: 1 },
        { kind: "gain_guard_self", value: 12 },
        { kind: "gain_guard_party", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation", "salvage", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_fury",
      tier: 3,
    },
    druid_heart_of_wolverine: {
      id: "druid_heart_of_wolverine",
      title: "Heart of Wolverine",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 8 Guard. Draw 1 card. Summon Heart of Wolverine. Each ally phase it strikes for 6 and marks for +7 mercenary damage.",
      effects: [
        { kind: "gain_guard_party", value: 8 },
        { kind: "draw", value: 1 },
        { kind: "summon_minion", value: 6, secondaryValue: 7, minionId: "druid_heart_of_wolverine" },
      ],
      behaviorTags: ["setup", "payoff", "scaling", "support", "salvage"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_heart_of_wolverine",
      tier: 3,
    },
    druid_tornado: {
      id: "druid_tornado",
      title: "Tornado",
      cost: 2,
      target: "none",
      text: "Deal 12 damage to all enemies.",
      effects: [{ kind: "damage_all", value: 12 }],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_tornado",
      tier: 3,
    },

    // ── Tier 4 ──
    druid_hurricane: {
      id: "druid_hurricane",
      title: "Hurricane",
      cost: 2,
      target: "none",
      text: "Deal 15 cold damage to all enemies. Gain 18 Guard.",
      effects: [
        { kind: "damage_all", value: 15 },
        { kind: "gain_guard_self", value: 18 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_hurricane",
      tier: 4,
    },
    druid_armageddon: {
      id: "druid_armageddon",
      title: "Armageddon",
      cost: 2,
      target: "none",
      text: "Deal 19 fire damage to all enemies. Apply 12 Burn to all. Gain 20 Guard.",
      effects: [
        { kind: "damage_all", value: 19 },
        { kind: "apply_burn_all", value: 12 },
        { kind: "gain_guard_self", value: 20 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_armageddon",
      tier: 4,
    },
    druid_summon_grizzly: {
      id: "druid_summon_grizzly",
      title: "Summon Grizzly",
      cost: 2,
      target: "enemy",
      text: "Deal 8 damage. Heal 8. Heal your mercenary 6. Summon Grizzly. Each ally phase it mauls for 10 and grants 8 Guard to the party.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "heal_hero", value: 8 },
        { kind: "heal_mercenary", value: 6 },
        { kind: "summon_minion", value: 10, secondaryValue: 8, minionId: "druid_grizzly" },
      ],
      behaviorTags: ["setup", "protection", "scaling", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect", "anti_summon"],
      skillRef: "druid_summon_grizzly",
      tier: 4,
    },
  };

  const DRUID_STARTER_DECK = [
    "druid_firestorm", "druid_firestorm",
    "druid_werewolf", "druid_werewolf",
    "druid_raven", "druid_raven",
    "druid_poison_creeper", "druid_poison_creeper",
    "rally_mercenary",
    "druid_lycanthropy",
    "druid_cyclone_armor",
    "druid_werebear",
    "druid_oak_sage",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const DRUID_REWARD_POOL = {
    early: getCardIdsByTier(DRUID_CARDS, 2),
    mid: getCardIdsByTier(DRUID_CARDS, 3),
    late: getCardIdsByTier(DRUID_CARDS, 4),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.druid = {
    cards: DRUID_CARDS,
    starterDeck: DRUID_STARTER_DECK,
    rewardPool: DRUID_REWARD_POOL,
  };
})();
