(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Barbarian Cards ───────────────────────────────────────────────────
  // Combat Pressure: Frenzy stacking → Whirlwind AoE — escalating melee aggression
  // Mastery Frontline: weapon reliability + guard accumulation → defense-to-offense conversion
  // Warcry Tempo: party buffs + enemy debuffs — persistent aura stacking
  // Class Glue: multi-lane utility
  // Hybrid Bridges: cross-lane support cards

  const BARBARIAN_CARDS: Record<string, ClassCardDefinition> = {

    // ════════════════════════════════════════════════════════════════════
    // TIER 1 — Starter shell and identity cards
    // ════════════════════════════════════════════════════════════════════

    // ── Combat Pressure ──
    barbarian_bash: {
      id: "barbarian_bash",
      title: "Bash",
      cost: 2,
      target: "enemy",
      text: "Deal 14 damage.",
      effects: [{ kind: "damage", value: 14 }],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "foundation",
      splashRole: "primary_only",
      skillRef: "barbarian_bash",
      tier: 1,
    },
    barbarian_howl: {
      id: "barbarian_howl",
      title: "Howl",
      cost: 1,
      target: "none",
      text: "Apply 1 Slow to all enemies. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["disruption", "protection", "salvage"],
      roleTag: "answer",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_howl",
      tier: 1,
    },
    barbarian_sword_mastery: {
      id: "barbarian_sword_mastery",
      title: "Sword Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 8 damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "salvage", "support"],
      roleTag: "support",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_sword_mastery",
      tier: 1,
    },
    barbarian_find_potion: {
      id: "barbarian_find_potion",
      title: "Find Potion",
      cost: 1,
      target: "none",
      text: "Heal 6. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_find_potion",
      tier: 1,
    },
    barbarian_iron_skin: {
      id: "barbarian_iron_skin",
      title: "Iron Skin",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_iron_skin",
      tier: 1,
    },
    barbarian_natural_resistance: {
      id: "barbarian_natural_resistance",
      title: "Natural Resistance",
      cost: 1,
      target: "none",
      text: "Heal 6. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_natural_resistance",
      tier: 1,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 2 — Early reward pool: lane formation begins
    // ════════════════════════════════════════════════════════════════════

    // ── Combat Pressure ──
    barbarian_double_swing: {
      id: "barbarian_double_swing",
      title: "Double Swing",
      cost: 1,
      target: "enemy",
      text: "Deal 6 damage. Deal 5 damage.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "damage", value: 5 },
      ],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_double_swing",
      tier: 2,
    },
    barbarian_leap: {
      id: "barbarian_leap",
      title: "Leap",
      cost: 1,
      target: "enemy",
      text: "Deal 8 damage.",
      effects: [
        { kind: "damage", value: 8 },
      ],
      behaviorTags: ["pressure", "mitigation", "setup"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_leap",
      tier: 2,
    },
    barbarian_shout: {
      id: "barbarian_shout",
      title: "Shout",
      cost: 1,
      target: "none",
      text: "Apply 1 Slow to all enemies. You and your mercenary gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_party", value: 14 },
        { kind: "draw", value: 1 },
        { kind: "apply_taunt", value: 1 },
      ],
      behaviorTags: ["disruption", "protection", "salvage", "support"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_shout",
      tier: 2,
    },
    barbarian_weapon_mastery: {
      id: "barbarian_weapon_mastery",
      title: "Weapon Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Mercenary next attack +8. Draw 1 card.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "buff_mercenary_next_attack", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "salvage", "support", "scaling"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_weapon_mastery",
      tier: 2,
    },
    barbarian_stun: {
      id: "barbarian_stun",
      title: "Stun",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Apply 1 Stun.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "apply_stun", value: 1 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_stun",
      tier: 2,
    },

    // ── Mastery Frontline ──
    barbarian_axe_mastery: {
      id: "barbarian_axe_mastery",
      title: "Axe Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Your next Attack this turn deals +3 damage.",
      effects: [
        { kind: "damage", value: 10 },
      ],
      behaviorTags: ["pressure", "mitigation", "setup"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },
    barbarian_increased_speed: {
      id: "barbarian_increased_speed",
      title: "Increased Speed",
      cost: 0,
      target: "none",
      text: "Draw 1 card. Your next Attack this turn costs 1 less. Exhaust.",
      effects: [{ kind: "draw", value: 1 }],
      behaviorTags: ["salvage", "setup", "conversion"],
      roleTag: "salvage",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ── Warcry Tempo ──
    barbarian_taunt: {
      id: "barbarian_taunt",
      title: "Taunt",
      cost: 0,
      target: "enemy",
      text: "Your next Attack against this target deals +6 damage. Your mercenary deals +6 to this target. Draw 1 card. Exhaust.",
      effects: [
        { kind: "mark_enemy_for_mercenary", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },
    barbarian_battle_cry: {
      id: "barbarian_battle_cry",
      title: "Battle Cry",
      cost: 1,
      target: "none",
      text: "All enemies deal 3 less damage next turn. Your next Attack this turn deals +4 damage. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["disruption", "setup", "mitigation", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ── Class Glue ──
    barbarian_battle_charge: {
      id: "barbarian_battle_charge",
      title: "Battle Charge",
      cost: 1,
      target: "enemy",
      text: "Deal 9 damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "salvage"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 3 — Mid reward pool: lane engines come online
    // ════════════════════════════════════════════════════════════════════

    // ── Combat Pressure ──
    barbarian_concentrate: {
      id: "barbarian_concentrate",
      title: "Concentrate",
      cost: 1,
      target: "enemy",
      text: "Heal 4. Deal 14 damage. Gain 12 Guard.",
      effects: [
        { kind: "heal_hero", value: 4 },
        { kind: "damage", value: 14 },
        { kind: "gain_guard_self", value: 12 },
      ],
      behaviorTags: ["pressure", "mitigation", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_concentrate",
      tier: 3,
    },
    barbarian_frenzy: {
      id: "barbarian_frenzy",
      title: "Frenzy",
      cost: 2,
      target: "enemy",
      text: "Deal 10 damage. Deal 9 damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "damage", value: 9 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_frenzy",
      tier: 3,
    },
    barbarian_battle_orders: {
      id: "barbarian_battle_orders",
      title: "Battle Orders",
      cost: 2,
      target: "none",
      text: "Heal 10. Apply 1 Slow to all enemies. You and your mercenary gain 22 Guard. Mercenary next attack +16. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 10 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_party", value: 22 },
        { kind: "buff_mercenary_next_attack", value: 16 },
      ],
      behaviorTags: ["protection", "support", "salvage", "scaling", "disruption"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_battle_orders",
      tier: 3,
    },
    barbarian_steel_skin: {
      id: "barbarian_steel_skin",
      title: "Steel Skin",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 16 Guard. Heal 6. Draw 1 card.",
      effects: [
        { kind: "gain_guard_party", value: 16 },
        { kind: "heal_hero", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support", "scaling", "protection"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_steel_skin",
      tier: 3,
    },
    barbarian_leap_attack: {
      id: "barbarian_leap_attack",
      title: "Leap Attack",
      cost: 2,
      target: "none",
      text: "Deal 9 damage to all enemies.",
      effects: [{ kind: "damage_all", value: 9 }],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_leap_attack",
      tier: 3,
    },

    barbarian_double_throw: {
      id: "barbarian_double_throw",
      title: "Double Throw",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage. Deal 7 damage to a random other enemy.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "damage_all", value: 4 },
      ],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Mastery Frontline ──
    barbarian_mace_mastery: {
      id: "barbarian_mace_mastery",
      title: "Mace Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 12 damage. Apply 1 Stun. Gain 8 Guard.",
      effects: [
        { kind: "damage", value: 12 },
        { kind: "apply_stun", value: 1 },
        { kind: "gain_guard_self", value: 8 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    barbarian_increased_stamina: {
      id: "barbarian_increased_stamina",
      title: "Increased Stamina",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Heal 6. Your next 2 Attacks this turn each deal +3 damage.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "heal_hero", value: 6 },
      ],
      behaviorTags: ["mitigation", "setup", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    barbarian_guard_slam: {
      id: "barbarian_guard_slam",
      title: "Guard Slam",
      cost: 2,
      target: "enemy",
      text: "Deal 10 damage. Deal bonus damage equal to half your current Guard (max 10 bonus). Gain 6 Guard.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "gain_guard_self", value: 6 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Warcry Tempo ──
    barbarian_find_item: {
      id: "barbarian_find_item",
      title: "Find Item",
      cost: 1,
      target: "none",
      text: "Heal 6. Gain 14 Guard. Draw 2 cards.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 2 },
      ],
      behaviorTags: ["salvage", "mitigation"],
      roleTag: "salvage",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    barbarian_grim_ward: {
      id: "barbarian_grim_ward",
      title: "Grim Ward",
      cost: 1,
      target: "none",
      text: "All non-boss enemies deal 4 less damage next turn. Your mercenary deals +8 to all enemies. Gain 14 Guard.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
      ],
      behaviorTags: ["disruption", "support", "mitigation"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect"],
      skillRef: "",
      tier: 3,
    },

    // ── Class Glue ──
    barbarian_war_stance: {
      id: "barbarian_war_stance",
      title: "War Stance",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. The next enemy attack against you this turn deals 5 less damage. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "protection"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_guard_break"],
      skillRef: "",
      tier: 3,
    },

    // ── Hybrid Bridges ──
    barbarian_fury_howl: {
      id: "barbarian_fury_howl",
      title: "Fury Howl",
      cost: 1,
      target: "none",
      text: "Apply 1 Slow to all enemies. Your next 2 Attacks this turn each deal +4 damage. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "disruption", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    barbarian_war_stomp: {
      id: "barbarian_war_stomp",
      title: "War Stomp",
      cost: 1,
      target: "none",
      text: "Deal 6 damage to all enemies. Apply 1 Stun to all non-boss enemies.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "apply_stun_all", value: 1 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect"],
      skillRef: "",
      tier: 3,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 4 — Late reward pool: lane capstones and closers
    // ════════════════════════════════════════════════════════════════════

    // ── Combat Pressure ──
    barbarian_whirlwind: {
      id: "barbarian_whirlwind",
      title: "Whirlwind",
      cost: 2,
      target: "none",
      text: "Deal 16 damage to all enemies. Apply 1 Slow to all enemies.",
      effects: [
        { kind: "damage_all", value: 16 },
        { kind: "apply_slow_all", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_whirlwind",
      tier: 4,
    },
    barbarian_berserk: {
      id: "barbarian_berserk",
      title: "Berserk",
      cost: 2,
      target: "enemy",
      text: "Deal 28 magic damage.",
      effects: [
        { kind: "damage", value: 28 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_berserk",
      tier: 4,
    },
    barbarian_war_cry: {
      id: "barbarian_war_cry",
      title: "War Cry",
      cost: 2,
      target: "none",
      text: "Deal 14 damage to all enemies. Apply 1 Stun to all.",
      effects: [
        { kind: "damage_all", value: 14 },
        { kind: "apply_stun_all", value: 1 },
      ],
      behaviorTags: ["disruption", "pressure", "protection", "payoff"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_war_cry",
      tier: 4,
    },
    barbarian_battle_instinct: {
      id: "barbarian_battle_instinct",
      title: "Battle Instinct",
      cost: 2,
      target: "enemy",
      text: "Deal 22 damage. Deal 8 damage to all enemies. Apply 1 Slow to all enemies.",
      effects: [
        { kind: "damage", value: 22 },
        { kind: "damage_all", value: 8 },
        { kind: "apply_slow_all", value: 1 },
      ],
      behaviorTags: ["pressure", "disruption", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_battle_instinct",
      tier: 4,
    },
    barbarian_unyielding: {
      id: "barbarian_unyielding",
      title: "Unyielding",
      cost: 2,
      target: "none",
      text: "Apply 2 Slow to all enemies. You and your mercenary gain 24 Guard. Heal 10. Draw 1 card.",
      effects: [
        { kind: "apply_slow_all", value: 2 },
        { kind: "gain_guard_party", value: 24 },
        { kind: "heal_hero", value: 10 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "disruption", "salvage", "support", "scaling", "protection"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_unyielding",
      tier: 4,
    },
    barbarian_frenzy_rush: {
      id: "barbarian_frenzy_rush",
      title: "Frenzy Rush",
      cost: 2,
      target: "enemy",
      text: "Deal 9 damage 3 times. Heal 3 per hit.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "damage", value: 9 },
        { kind: "damage", value: 9 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },

    // ── Mastery Frontline ──
    barbarian_combat_mastery: {
      id: "barbarian_combat_mastery",
      title: "Combat Mastery",
      cost: 1,
      target: "none",
      text: "This combat, your Attacks deal +3 damage and gain +3 Guard. Draw 2 cards. Exhaust.",
      effects: [{ kind: "draw", value: 2 }],
      behaviorTags: ["scaling", "setup", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "barbarian_combat_mastery",
      tier: 4,
    },
    barbarian_iron_fortress: {
      id: "barbarian_iron_fortress",
      title: "Iron Fortress",
      cost: 2,
      target: "none",
      text: "Gain 20 Guard. Deal bonus damage to all enemies equal to half your current Guard (max 12). Heal 6.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "heal_hero", value: 6 },
      ],
      behaviorTags: ["mitigation", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    barbarian_polearm_mastery: {
      id: "barbarian_polearm_mastery",
      title: "Polearm Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 14 damage. Deal 7 damage to all other enemies.",
      effects: [
        { kind: "damage", value: 14 },
        { kind: "damage_all", value: 7 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },

    // ── Warcry Tempo ──
    barbarian_battle_command: {
      id: "barbarian_battle_command",
      title: "Battle Command",
      cost: 1,
      target: "none",
      text: "This combat, your Warcry cards draw 1 extra card and gain +4 Guard. Draw 1 card. Exhaust.",
      effects: [{ kind: "draw", value: 1 }],
      behaviorTags: ["scaling", "setup"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "barbarian_battle_command",
      tier: 4,
    },
    barbarian_warlord_shout: {
      id: "barbarian_warlord_shout",
      title: "Warlord Shout",
      cost: 2,
      target: "none",
      text: "All enemies deal 5 less damage next turn. You and your mercenary gain +5 damage this turn. You and your mercenary gain 22 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_party", value: 22 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["disruption", "support", "conversion", "protection"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },

    // ── Class Glue ──
    barbarian_bulwark: {
      id: "barbarian_bulwark",
      title: "Bulwark",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Heal your mercenary 6. The next enemy attack against you or your mercenary this turn deals 6 less damage.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "heal_mercenary", value: 6 },
      ],
      behaviorTags: ["mitigation", "protection", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_fire_pressure"],
      skillRef: "",
      tier: 4,
    },
    barbarian_second_wind: {
      id: "barbarian_second_wind",
      title: "Second Wind",
      cost: 1,
      target: "none",
      text: "Heal 10. Heal your mercenary 6. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 10 },
        { kind: "heal_mercenary", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "support", "mitigation"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },

    // ── Hybrid Bridges ──
    barbarian_raging_cleave: {
      id: "barbarian_raging_cleave",
      title: "Raging Cleave",
      cost: 2,
      target: "none",
      text: "Deal 12 damage to all enemies. Apply 1 Slow to all. If you have 10+ Guard, deal 5 more to all.",
      effects: [
        { kind: "damage_all", value: 12 },
        { kind: "apply_slow_all", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    barbarian_warcry_strike: {
      id: "barbarian_warcry_strike",
      title: "Warcry Strike",
      cost: 2,
      target: "enemy",
      text: "Deal 18 damage. All enemies deal 3 less damage next turn. Draw 1 card.",
      effects: [
        { kind: "damage", value: 18 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "disruption", "protection"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    barbarian_fury_mastery: {
      id: "barbarian_fury_mastery",
      title: "Fury Mastery",
      cost: 2,
      target: "enemy",
      text: "Deal 10 damage twice. If either hit lands on a Stunned or Slowed target, deal 6 more per hit.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "damage", value: 10 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    barbarian_ancient_vow: {
      id: "barbarian_ancient_vow",
      title: "Ancient Vow",
      cost: 2,
      target: "none",
      text: "Heal 10. You and your mercenary gain 22 Guard. Your next 3 Attacks this turn each deal +4 damage. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 10 },
        { kind: "gain_guard_party", value: 22 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "mitigation", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
  };

  const BARBARIAN_STARTER_DECK = [
    "barbarian_bash", "barbarian_bash",
    "barbarian_sword_mastery", "barbarian_sword_mastery",
    "barbarian_howl", "barbarian_howl",
    "barbarian_find_potion", "barbarian_find_potion",
    "rally_mercenary",
    "barbarian_natural_resistance",
    "barbarian_iron_skin",
    "barbarian_double_swing",
    "barbarian_stun",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const BARBARIAN_REWARD_POOL = {
    early: getCardIdsByTier(BARBARIAN_CARDS, 2),
    mid: getCardIdsByTier(BARBARIAN_CARDS, 3),
    late: getCardIdsByTier(BARBARIAN_CARDS, 4),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.barbarian = {
    cards: BARBARIAN_CARDS,
    starterDeck: BARBARIAN_STARTER_DECK,
    rewardPool: BARBARIAN_REWARD_POOL,
  };
})();
