(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Amazon Cards ──────────────────────────────────────────────────────
  // Bow Volley: ranged multi-hit + per-hit scaling — precision volleys
  // Javelin Storm: charge buildup → lightning/poison burst — screen-clearing AoE
  // Passive Tempo: evasion + passive buffs + mercenary coordination
  // Class Glue: multi-lane utility
  // Hybrid Bridges: cross-lane support cards

  const AMAZON_CARDS: Record<string, ClassCardDefinition> = {

    // ════════════════════════════════════════════════════════════════════
    // TIER 1 — Starter shell and identity cards
    // ════════════════════════════════════════════════════════════════════

    // ── Bow Volley ──
    amazon_magic_arrow: {
      id: "amazon_magic_arrow",
      title: "Magic Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 7 magic damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "salvage", "payoff"],
      roleTag: "support",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_backline"],
      skillRef: "amazon_magic_arrow",
      tier: 1,
    },
    amazon_jab: {
      id: "amazon_jab",
      title: "Jab",
      cost: 2,
      target: "enemy",
      text: "Deal 7 damage. Deal 6 damage.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "damage", value: 6 },
      ],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "foundation",
      splashRole: "primary_only",
      skillRef: "amazon_jab",
      tier: 1,
    },
    amazon_inner_sight: {
      id: "amazon_inner_sight",
      title: "Inner Sight",
      cost: 1,
      target: "enemy",
      text: "Apply 1 Slow. Your mercenary deals +8 to this target. Draw 1 card.",
      effects: [
        { kind: "apply_slow", value: 1 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "disruption"],
      roleTag: "support",
      rewardRole: "foundation",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "telegraph_respect"],
      skillRef: "amazon_inner_sight",
      tier: 1,
    },
    amazon_fire_arrow: {
      id: "amazon_fire_arrow",
      title: "Fire Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. Apply 4 Burn.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "apply_burn", value: 4 },
      ],
      behaviorTags: ["setup", "payoff", "pressure"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "amazon_fire_arrow",
      tier: 1,
    },
    amazon_dodge: {
      id: "amazon_dodge",
      title: "Dodge",
      cost: 1,
      target: "none",
      text: "Gain 9 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "support", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      skillRef: "amazon_dodge",
      tier: 1,
    },
    amazon_critical_strike: {
      id: "amazon_critical_strike",
      title: "Critical Strike",
      cost: 2,
      target: "enemy",
      text: "Deal 14 damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "amazon_critical_strike",
      tier: 1,
    },

    amazon_slow_missiles: {
      id: "amazon_slow_missiles",
      title: "Slow Missiles",
      cost: 1,
      target: "none",
      text: "Gain 10 Guard. Apply 3 Slow to all enemies. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "apply_slow_all", value: 3 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "disruption", "salvage", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      skillRef: "amazon_slow_missiles",
      tier: 2,
    },
    amazon_avoid: {
      id: "amazon_avoid",
      title: "Avoid",
      cost: 1,
      target: "none",
      text: "Gain 12 Guard. Draw 2 cards.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 2 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "primary_only",
      skillRef: "amazon_avoid",
      tier: 2,
    },
    amazon_penetrate: {
      id: "amazon_penetrate",
      title: "Penetrate",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Apply 1 Slow. Your mercenary deals +10 to this target.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "apply_slow", value: 1 },
        { kind: "mark_enemy_for_mercenary", value: 10 },
      ],
      behaviorTags: ["setup", "support", "disruption"],
      roleTag: "setup",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_penetrate",
      tier: 2,
    },
    amazon_decoy: {
      id: "amazon_decoy",
      title: "Decoy",
      cost: 1,
      target: "enemy",
      text: "You and your mercenary gain 8 Guard. Mercenary next attack +10.",
      effects: [
        { kind: "gain_guard_party", value: 14 },
        { kind: "buff_mercenary_next_attack", value: 10 },
      ],
      behaviorTags: ["support", "mitigation", "protection"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_decoy",
      tier: 2,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 2 — Early reward pool: lane formation begins
    // ════════════════════════════════════════════════════════════════════

    // ── Bow Volley ──
    amazon_cold_arrow: {
      id: "amazon_cold_arrow",
      title: "Cold Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 7 cold damage. Apply 1 Slow.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "apply_slow", value: 1 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation", "payoff"],
      roleTag: "payoff",
      rewardRole: "tech",
      skillRef: "amazon_cold_arrow",
      tier: 2,
    },
    amazon_multiple_shot: {
      id: "amazon_multiple_shot",
      title: "Multiple Shot",
      cost: 2,
      target: "none",
      text: "Deal 7 damage to all enemies. Apply 1 Slow to all enemies.",
      effects: [
        { kind: "damage_all", value: 7 },
        { kind: "apply_slow_all", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "setup", "disruption"],
      roleTag: "support",
      rewardRole: "support",
      counterTags: ["anti_summon", "telegraph_respect"],
      skillRef: "amazon_multiple_shot",
      tier: 2,
    },
    amazon_power_strike: {
      id: "amazon_power_strike",
      title: "Power Strike",
      cost: 1,
      target: "enemy",
      text: "Deal 11 lightning damage. Apply 2 Paralyze.",
      effects: [
        { kind: "damage", value: 11 },
        { kind: "apply_paralyze", value: 2 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_power_strike",
      tier: 2,
    },
    amazon_exploding_arrow: {
      id: "amazon_exploding_arrow",
      title: "Exploding Arrow",
      cost: 2,
      target: "enemy",
      text: "Deal 8 fire damage. Apply 3 Burn. Draw 1 card.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "apply_burn", value: 3 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage", "setup"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "amazon_exploding_arrow",
      tier: 2,
    },

    // ── Javelin Storm ──
    amazon_lightning_bolt: {
      id: "amazon_lightning_bolt",
      title: "Lightning Bolt",
      cost: 1,
      target: "enemy",
      text: "Deal 8 lightning damage. Apply 1 Paralyze.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "apply_paralyze", value: 1 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },
    amazon_poison_javelin: {
      id: "amazon_poison_javelin",
      title: "Poison Javelin",
      cost: 1,
      target: "enemy",
      text: "Deal 6 damage. Apply 5 Poison. Draw 1 card.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "apply_poison", value: 5 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "setup", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },
    amazon_impale: {
      id: "amazon_impale",
      title: "Impale",
      cost: 1,
      target: "enemy",
      text: "Deal 14 damage. If the target is Paralyzed or Slowed, deal 5 more.",
      effects: [{ kind: "damage", value: 14 }],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },

    // ── Class Glue ──
    amazon_inner_calm: {
      id: "amazon_inner_calm",
      title: "Inner Calm",
      cost: 1,
      target: "none",
      text: "Heal 4. Gain 7 Guard. Draw 1 card. Your next ranged card this turn deals +3 damage.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "mitigation", "setup"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 3 — Mid reward pool: lane engines come online
    // ════════════════════════════════════════════════════════════════════

    // ── Bow Volley ──
    amazon_guided_arrow: {
      id: "amazon_guided_arrow",
      title: "Guided Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 16 damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 16 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "amazon_guided_arrow",
      tier: 3,
    },
    amazon_evade: {
      id: "amazon_evade",
      title: "Evade",
      cost: 1,
      target: "enemy",
      text: "Gain 10 Guard. Apply 2 Slow. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "apply_slow", value: 2 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "disruption", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_evade",
      tier: 3,
    },
    amazon_deadly_strike: {
      id: "amazon_deadly_strike",
      title: "Deadly Strike",
      cost: 2,
      target: "enemy",
      text: "Deal 22 damage. Your mercenary deals +16 to this target.",
      effects: [
        { kind: "damage", value: 22 },
        { kind: "mark_enemy_for_mercenary", value: 16 },
      ],
      behaviorTags: ["pressure", "payoff", "setup"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_deadly_strike",
      tier: 3,
    },
    amazon_charged_strike: {
      id: "amazon_charged_strike",
      title: "Charged Strike",
      cost: 2,
      target: "enemy",
      text: "Deal 12 lightning damage. Deal 12 lightning damage. Apply 3 Paralyze.",
      effects: [
        { kind: "damage", value: 12 },
        { kind: "damage", value: 12 },
        { kind: "apply_paralyze", value: 3 },
      ],
      behaviorTags: ["pressure", "payoff", "setup"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_charged_strike",
      tier: 3,
    },
    amazon_strafe: {
      id: "amazon_strafe",
      title: "Strafe",
      cost: 2,
      target: "none",
      text: "Deal 9 damage to all enemies. Apply 1 Slow to all enemies. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage_all", value: 9 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "salvage", "setup", "mitigation", "disruption"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_summon", "telegraph_respect"],
      skillRef: "amazon_strafe",
      tier: 3,
    },
    amazon_valkyrie: {
      id: "amazon_valkyrie",
      title: "Valkyrie",
      cost: 2,
      target: "enemy",
      text: "Gain 6 Guard. Summon Valkyrie. Each ally phase it strikes for 10 and grants 6 Guard to the party.",
      effects: [
        { kind: "gain_guard_self", value: 22 },
        { kind: "summon_minion", value: 10, secondaryValue: 6, minionId: "amazon_valkyrie" },
      ],
      behaviorTags: ["setup", "protection", "scaling"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_valkyrie",
      tier: 3,
    },

    amazon_immolation_arrow: {
      id: "amazon_immolation_arrow",
      title: "Immolation Arrow",
      cost: 2,
      target: "enemy",
      text: "Deal 10 fire damage. Apply 5 Burn. Deal 5 fire damage to all other enemies. Apply 2 Burn to all.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "apply_burn", value: 5 },
        { kind: "damage_all", value: 5 },
        { kind: "apply_burn_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "setup", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    amazon_arrow_mastery: {
      id: "amazon_arrow_mastery",
      title: "Arrow Mastery",
      cost: 1,
      target: "none",
      text: "This combat, your ranged cards deal +3 damage. Draw 2 cards. Exhaust.",
      effects: [{ kind: "draw", value: 2 }],
      behaviorTags: ["scaling", "setup", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "amazon_ranged_mastery",
      tier: 3,
    },

    // ── Javelin Storm ──
    amazon_lightning_strike: {
      id: "amazon_lightning_strike",
      title: "Lightning Strike",
      cost: 2,
      target: "enemy",
      text: "Deal 14 lightning damage. Deal 7 lightning damage to all other enemies. Apply 2 Paralyze to all.",
      effects: [
        { kind: "damage", value: 14 },
        { kind: "damage_all", value: 7 },
        { kind: "apply_paralyze_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    amazon_plague_javelin: {
      id: "amazon_plague_javelin",
      title: "Plague Javelin",
      cost: 1,
      target: "none",
      text: "Deal 5 poison damage to all enemies. Apply 4 Poison to all.",
      effects: [
        { kind: "damage_all", value: 5 },
        { kind: "apply_poison_all", value: 4 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    amazon_fend: {
      id: "amazon_fend",
      title: "Fend",
      cost: 2,
      target: "enemy",
      text: "Deal 8 damage 3 times.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "damage", value: 8 },
        { kind: "damage", value: 8 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Passive Tempo ──
    amazon_precision: {
      id: "amazon_precision",
      title: "Precision",
      cost: 1,
      target: "enemy",
      text: "Deal 12 damage. If the target is Slowed or Paralyzed, deal 5 more and draw 1 card.",
      effects: [{ kind: "damage", value: 12 }],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Class Glue ──
    amazon_war_maiden: {
      id: "amazon_war_maiden",
      title: "War Maiden",
      cost: 1,
      target: "none",
      text: "Heal 6. Gain 10 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "mitigation"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    amazon_battle_focus: {
      id: "amazon_battle_focus",
      title: "Battle Focus",
      cost: 1,
      target: "none",
      text: "All non-boss enemies deal 3 less damage next turn. Gain 7 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "disruption", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect"],
      skillRef: "",
      tier: 3,
    },

    // ── Hybrid Bridges ──
    amazon_ice_arrow: {
      id: "amazon_ice_arrow",
      title: "Ice Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 9 cold damage. Apply 1 Freeze. Apply 1 Slow.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "apply_freeze", value: 1 },
        { kind: "apply_slow", value: 1 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation"],
      roleTag: "answer",
      rewardRole: "tech",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    amazon_javelin_rush: {
      id: "amazon_javelin_rush",
      title: "Javelin Rush",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Your mercenary deals +8 to this target. If the target has Paralyze, deal 5 more.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
      ],
      behaviorTags: ["pressure", "conversion", "setup"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 4 — Late reward pool: lane capstones and closers
    // ════════════════════════════════════════════════════════════════════

    // ── Bow Volley ──
    amazon_pierce: {
      id: "amazon_pierce",
      title: "Pierce",
      cost: 2,
      target: "enemy",
      text: "Deal 26 damage. Apply 2 Slow. Your mercenary deals +18 to this target.",
      effects: [
        { kind: "damage", value: 26 },
        { kind: "apply_slow", value: 2 },
        { kind: "mark_enemy_for_mercenary", value: 18 },
      ],
      behaviorTags: ["pressure", "payoff", "setup", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_pierce",
      tier: 4,
    },
    amazon_freezing_arrow: {
      id: "amazon_freezing_arrow",
      title: "Freezing Arrow",
      cost: 2,
      target: "none",
      text: "Deal 9 cold damage to all enemies. Apply 1 Freeze and 1 Slow to all. Gain 5 Guard.",
      effects: [
        { kind: "damage_all", value: 9 },
        { kind: "apply_freeze_all", value: 1 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 5 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "amazon_freezing_arrow",
      tier: 4,
    },
    amazon_lightning_fury: {
      id: "amazon_lightning_fury",
      title: "Lightning Fury",
      cost: 2,
      target: "none",
      text: "Deal 13 lightning damage to all enemies. Apply 3 Paralyze to all.",
      effects: [
        { kind: "damage_all", value: 13 },
        { kind: "apply_paralyze_all", value: 3 },
      ],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_lightning_fury",
      tier: 4,
    },
    amazon_storm_javelin: {
      id: "amazon_storm_javelin",
      title: "Storm Javelin",
      cost: 2,
      target: "enemy",
      text: "Deal 18 lightning damage. Deal 10 lightning damage to all other enemies. Apply 3 Paralyze. If the target already has Paralyze, deal 8 more.",
      effects: [
        { kind: "damage", value: 18 },
        { kind: "damage_all", value: 10 },
        { kind: "apply_paralyze", value: 3 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    amazon_javelin_mastery: {
      id: "amazon_javelin_mastery",
      title: "Javelin Mastery",
      cost: 1,
      target: "none",
      text: "This combat, your javelin and spear cards deal +3 damage and apply +1 Paralyze. Draw 2 cards. Exhaust.",
      effects: [{ kind: "draw", value: 2 }],
      behaviorTags: ["scaling", "setup", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "amazon_javelin_mastery",
      tier: 4,
    },

    // ── Passive Tempo ──
    amazon_war_pike: {
      id: "amazon_war_pike",
      title: "War Pike",
      cost: 2,
      target: "enemy",
      text: "Deal 22 damage. Your mercenary deals +16 to this target. If the target is Slowed, apply 1 Stun.",
      effects: [
        { kind: "damage", value: 22 },
        { kind: "mark_enemy_for_mercenary", value: 16 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "setup"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["telegraph_respect"],
      skillRef: "",
      tier: 4,
    },

    // ── Class Glue ──
    amazon_amazonian_guard: {
      id: "amazon_amazonian_guard",
      title: "Amazonian Guard",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Heal your mercenary 6. The next enemy attack against you or your mercenary this turn deals 6 less damage.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "heal_mercenary", value: 6 },
      ],
      behaviorTags: ["mitigation", "protection", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_fire_pressure"],
      skillRef: "",
      tier: 4,
    },
    amazon_renewal: {
      id: "amazon_renewal",
      title: "Renewal",
      cost: 1,
      target: "none",
      text: "Heal 8. Heal your mercenary 6. Gain 8 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 8 },
        { kind: "heal_mercenary", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "support", "mitigation"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },

    // ── Hybrid Bridges ──
    amazon_thunder_volley: {
      id: "amazon_thunder_volley",
      title: "Thunder Volley",
      cost: 2,
      target: "none",
      text: "Deal 9 lightning damage to all enemies. Apply 2 Paralyze to all. Your next ranged card this turn deals +6 damage.",
      effects: [
        { kind: "damage_all", value: 9 },
        { kind: "apply_paralyze_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "setup", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    amazon_flame_javelin: {
      id: "amazon_flame_javelin",
      title: "Flame Javelin",
      cost: 2,
      target: "enemy",
      text: "Deal 16 fire damage. Apply 5 Burn. Deal 8 fire damage to all other enemies. Apply 2 Burn to all.",
      effects: [
        { kind: "damage", value: 16 },
        { kind: "apply_burn", value: 5 },
        { kind: "damage_all", value: 8 },
        { kind: "apply_burn_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "setup", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    amazon_huntress_mark: {
      id: "amazon_huntress_mark",
      title: "Huntress Mark",
      cost: 1,
      target: "enemy",
      text: "Deal 8 damage. Your mercenary deals +12 to this target. Your next 2 cards that hit this target each deal +4 damage.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "mark_enemy_for_mercenary", value: 12 },
      ],
      behaviorTags: ["setup", "support", "conversion"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    amazon_fury_of_the_hunt: {
      id: "amazon_fury_of_the_hunt",
      title: "Fury of the Hunt",
      cost: 2,
      target: "enemy",
      text: "Deal 12 damage. Deal 10 damage. Deal 8 damage. If any hit lands on a Slowed or Paralyzed target, deal 4 more per hit.",
      effects: [
        { kind: "damage", value: 12 },
        { kind: "damage", value: 10 },
        { kind: "damage", value: 8 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
  };

  const AMAZON_STARTER_DECK = [
    "amazon_magic_arrow", "amazon_magic_arrow",
    "amazon_jab", "amazon_jab",
    "amazon_fire_arrow", "amazon_fire_arrow",
    "amazon_inner_sight", "amazon_inner_sight",
    "rally_mercenary",
    "amazon_critical_strike", "amazon_critical_strike",
    "amazon_dodge", "amazon_dodge",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const AMAZON_REWARD_POOL = {
    early: getCardIdsByTier(AMAZON_CARDS, 2),
    mid: getCardIdsByTier(AMAZON_CARDS, 3),
    late: getCardIdsByTier(AMAZON_CARDS, 4),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.amazon = {
    cards: AMAZON_CARDS,
    starterDeck: AMAZON_STARTER_DECK,
    rewardPool: AMAZON_REWARD_POOL,
  };
})();
