(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Assassin Cards ────────────────────────────────────────────────────
  // Martial Burst: charge-up → finisher combos — multi-element burst cycles
  // Trap Field: autonomous turret placement — persistent damage + corpse chain
  // Shadow Tempo: speed, evasion, clones — hand cycling + status exploitation
  // Class Glue: multi-lane utility
  // Hybrid Bridges: cross-lane support cards

  const ASSASSIN_CARDS: Record<string, ClassCardDefinition> = {

    // ════════════════════════════════════════════════════════════════════
    // TIER 1 — Starter shell and identity cards
    // ════════════════════════════════════════════════════════════════════

    // ── Martial Burst ──
    assassin_tiger_strike: {
      id: "assassin_tiger_strike",
      title: "Tiger Strike",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage. Your next Assassin melee card this turn deals +3 damage.",
      effects: [{ kind: "damage", value: 7 }],
      behaviorTags: ["pressure", "setup"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break"],
      skillRef: "assassin_tiger_strike",
      tier: 1,
    },
    assassin_claw_mastery: {
      id: "assassin_claw_mastery",
      title: "Claw Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 8 damage. Mark an enemy for your mercenary for 10.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "mark_enemy_for_mercenary", value: 10 },
      ],
      behaviorTags: ["setup", "mitigation", "support", "payoff"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_backline"],
      skillRef: "assassin_claw_mastery",
      tier: 1,
    },

    // ── Trap Field ──
    assassin_fire_blast: {
      id: "assassin_fire_blast",
      title: "Fire Blast",
      cost: 1,
      target: "enemy",
      text: "Deal 6 fire damage. Apply 5 Burn.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "apply_burn", value: 5 },
      ],
      behaviorTags: ["setup", "payoff", "pressure"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline"],
      skillRef: "assassin_fire_blast",
      tier: 1,
    },

    // ── Shadow Tempo ──
    assassin_psychic_hammer: {
      id: "assassin_psychic_hammer",
      title: "Psychic Hammer",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. Apply 1 Paralyze. Mark an enemy for your mercenary for 8.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "apply_paralyze", value: 1 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
      ],
      behaviorTags: ["mitigation", "disruption", "support", "setup"],
      roleTag: "answer",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_backline"],
      skillRef: "assassin_psychic_hammer",
      tier: 1,
    },

    // ── Class Glue ──
    assassin_cloak_of_shadows: {
      id: "assassin_cloak_of_shadows",
      title: "Cloak of Shadows",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "disruption"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_control"],
      skillRef: "assassin_cloak_of_shadows",
      tier: 1,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 2 — Early reward pool: lane formation begins
    // ════════════════════════════════════════════════════════════════════

    // ── Martial Burst ──
    assassin_fists_of_fire: {
      id: "assassin_fists_of_fire",
      title: "Fists of Fire",
      cost: 1,
      target: "enemy",
      text: "Deal 8 fire damage. Apply 3 Burn. Draw 1 card.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "apply_burn", value: 3 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break"],
      skillRef: "assassin_fists_of_fire",
      tier: 2,
    },
    assassin_cobra_strike: {
      id: "assassin_cobra_strike",
      title: "Cobra Strike",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "conversion", "support", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition"],
      skillRef: "assassin_cobra_strike",
      tier: 2,
    },
    assassin_dragon_talon: {
      id: "assassin_dragon_talon",
      title: "Dragon Talon",
      cost: 1,
      target: "enemy",
      text: "Deal 5 damage 3 times.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "damage", value: 5 },
        { kind: "damage", value: 5 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },

    // ── Trap Field ──
    assassin_wake_of_fire: {
      id: "assassin_wake_of_fire",
      title: "Wake of Fire",
      cost: 2,
      target: "none",
      text: "Scorch all enemies for 6 and apply 3 Burn. Set Wake of Fire for 4 turns. Each ally phase it scorches all enemies for 7 and applies 4 Burn.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "apply_burn_all", value: 3 },
        { kind: "summon_minion", value: 7, secondaryValue: 4, duration: 4, minionId: "assassin_wake_of_fire" },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "tax", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "assassin_wake_of_fire",
      tier: 2,
    },
    assassin_blade_shield: {
      id: "assassin_blade_shield",
      title: "Blade Shield",
      cost: 1,
      target: "none",
      text: "Deal 6 damage to all enemies. Apply 1 Slow to all enemies. Mercenary next attack +8. Draw 1 card.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "buff_mercenary_next_attack", value: 8 },
      ],
      behaviorTags: ["pressure", "mitigation", "salvage", "support", "setup", "disruption", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "assassin_blade_shield",
      tier: 2,
    },
    assassin_shock_web: {
      id: "assassin_shock_web",
      title: "Shock Web",
      cost: 1,
      target: "none",
      text: "Deal 5 lightning damage to all enemies. Apply 1 Paralyze to all.",
      effects: [
        { kind: "damage_all", value: 5 },
        { kind: "apply_paralyze_all", value: 1 },
      ],
      behaviorTags: ["setup", "disruption", "mitigation"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },
    assassin_blade_sentinel: {
      id: "assassin_blade_sentinel",
      title: "Blade Sentinel",
      cost: 1,
      target: "none",
      text: "Deal 4 damage to all enemies. Set Blade Sentinel for 3 turns. Each ally phase it slashes all enemies for 5.",
      effects: [
        { kind: "damage_all", value: 4 },
        { kind: "summon_minion", value: 5, minionId: "assassin_blade_sentinel" },
      ],
      behaviorTags: ["setup", "scaling", "pressure"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },

    // ── Shadow Tempo ──
    assassin_burst_of_speed: {
      id: "assassin_burst_of_speed",
      title: "Burst of Speed",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Mercenary next attack +10. Draw 2 cards.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "buff_mercenary_next_attack", value: 10 },
        { kind: "draw", value: 2 },
      ],
      behaviorTags: ["salvage", "mitigation", "support", "setup"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_tax", "anti_attrition"],
      skillRef: "assassin_burst_of_speed",
      tier: 2,
    },
    assassin_venom: {
      id: "assassin_venom",
      title: "Venom",
      cost: 1,
      target: "enemy",
      text: "Deal 6 damage. Apply 4 Poison. Your next melee card this turn deals +4 damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "apply_poison", value: 4 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "pressure", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },
    assassin_weapon_block: {
      id: "assassin_weapon_block",
      title: "Weapon Block",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. The next enemy attack against you this turn deals 5 less damage. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "protection"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect"],
      skillRef: "",
      tier: 2,
    },

    // ── Class Glue ──
    assassin_shadow_shroud: {
      id: "assassin_shadow_shroud",
      title: "Shadow Shroud",
      cost: 1,
      target: "none",
      text: "Heal 6. Gain 14 Guard. Draw 1 card. Your next Assassin card this turn costs 1 less.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "mitigation", "conversion"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 3 — Mid reward pool: lane engines come online
    // ════════════════════════════════════════════════════════════════════

    // ── Martial Burst ──
    assassin_claws_of_thunder: {
      id: "assassin_claws_of_thunder",
      title: "Claws of Thunder",
      cost: 2,
      target: "enemy",
      text: "Deal 17 lightning damage. Apply 1 Paralyze. Draw 1 card.",
      effects: [
        { kind: "damage", value: 17 },
        { kind: "apply_paralyze", value: 1 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break", "anti_backline"],
      skillRef: "assassin_claws_of_thunder",
      tier: 3,
    },
    assassin_blades_of_ice: {
      id: "assassin_blades_of_ice",
      title: "Blades of Ice",
      cost: 2,
      target: "enemy",
      text: "Deal 15 cold damage. Apply 1 Freeze and 1 Slow. Draw 1 card.",
      effects: [
        { kind: "damage", value: 15 },
        { kind: "apply_freeze", value: 1 },
        { kind: "apply_slow", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "disruption", "mitigation", "salvage", "protection"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["telegraph_respect", "anti_backline", "anti_fire_pressure"],
      skillRef: "assassin_blades_of_ice",
      tier: 3,
    },
    assassin_dragon_tail: {
      id: "assassin_dragon_tail",
      title: "Dragon Tail",
      cost: 2,
      target: "none",
      text: "Deal 12 fire damage to all enemies. Apply 3 Burn to all. If you played a melee card earlier this turn, deal 5 more to all.",
      effects: [
        { kind: "damage_all", value: 12 },
        { kind: "apply_burn_all", value: 3 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    assassin_dragon_claw: {
      id: "assassin_dragon_claw",
      title: "Dragon Claw",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage twice. If the target has Burn, Poison, or Paralyze, deal 3 more per hit.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "damage", value: 7 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Trap Field ──
    assassin_lightning_sentry: {
      id: "assassin_lightning_sentry",
      title: "Lightning Sentry",
      cost: 2,
      target: "none",
      text: "Shock all enemies for 7 and apply 1 Paralyze. Set Lightning Sentry for 4 turns. Each ally phase it shocks all enemies for 8 and applies 3 Paralyze.",
      effects: [
        { kind: "damage_all", value: 7 },
        { kind: "apply_paralyze_all", value: 1 },
        { kind: "summon_minion", value: 8, secondaryValue: 3, duration: 4, minionId: "assassin_lightning_sentry" },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "tax"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_support_disruption"],
      skillRef: "assassin_lightning_sentry",
      tier: 3,
    },
    assassin_charged_bolt_sentry: {
      id: "assassin_charged_bolt_sentry",
      title: "Charged Bolt Sentry",
      cost: 1,
      target: "none",
      text: "Deal 4 lightning damage to all enemies. Set Charged Bolt Sentry for 3 turns. Each ally phase it zaps all enemies for 5 and applies 1 Paralyze.",
      effects: [
        { kind: "damage_all", value: 4 },
        { kind: "summon_minion", value: 5, secondaryValue: 1, minionId: "assassin_charged_bolt_sentry" },
      ],
      behaviorTags: ["setup", "scaling", "disruption"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    assassin_blade_fury: {
      id: "assassin_blade_fury",
      title: "Blade Fury",
      cost: 1,
      target: "none",
      text: "Deal 4 damage 3 times to random enemies.",
      effects: [
        { kind: "damage_all", value: 4 },
      ],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    assassin_mind_blast: {
      id: "assassin_mind_blast",
      title: "Mind Blast",
      cost: 1,
      target: "none",
      text: "Apply 1 Stun to all non-boss enemies. All enemies deal 3 less damage next turn. Gain 14 Guard.",
      effects: [
        { kind: "apply_stun_all", value: 1 },
        { kind: "gain_guard_self", value: 14 },
      ],
      behaviorTags: ["disruption", "mitigation", "tax"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_guard_break"],
      skillRef: "",
      tier: 3,
    },

    // ── Shadow Tempo ──
    assassin_fade: {
      id: "assassin_fade",
      title: "Fade",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 24 Guard. Heal 8. Apply 1 Slow to all enemies. Draw 1 card.",
      effects: [
        { kind: "gain_guard_party", value: 24 },
        { kind: "heal_hero", value: 8 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "support", "protection", "disruption", "salvage"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_attrition", "anti_control", "telegraph_respect"],
      skillRef: "assassin_fade",
      tier: 3,
    },
    assassin_shadow_warrior: {
      id: "assassin_shadow_warrior",
      title: "Shadow Warrior",
      cost: 1,
      target: "enemy",
      text: "Mark an enemy for your mercenary for 16. Mercenary next attack +16. Gain 14 Guard.",
      effects: [
        { kind: "mark_enemy_for_mercenary", value: 16 },
        { kind: "buff_mercenary_next_attack", value: 16 },
        { kind: "gain_guard_self", value: 14 },
      ],
      behaviorTags: ["support", "setup"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_control", "anti_backline"],
      skillRef: "assassin_shadow_warrior",
      tier: 3,
    },
    assassin_shadow_veil: {
      id: "assassin_shadow_veil",
      title: "Shadow Veil",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Your next 2 Assassin cards this turn each cost 1 less. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "conversion", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Class Glue ──
    assassin_escape_artist: {
      id: "assassin_escape_artist",
      title: "Escape Artist",
      cost: 1,
      target: "none",
      text: "Heal 6. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "mitigation"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    assassin_dark_discipline: {
      id: "assassin_dark_discipline",
      title: "Dark Discipline",
      cost: 1,
      target: "none",
      text: "All non-boss enemies deal 3 less damage next turn. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "disruption", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect"],
      skillRef: "",
      tier: 3,
    },

    // ── Hybrid Bridges ──
    assassin_venom_strike: {
      id: "assassin_venom_strike",
      title: "Venom Strike",
      cost: 1,
      target: "enemy",
      text: "Deal 9 damage. Apply 3 Poison. If the target has Burn or Paralyze, apply 3 more Poison.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "apply_poison", value: 3 },
      ],
      behaviorTags: ["pressure", "setup", "conversion"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    assassin_shadow_trap: {
      id: "assassin_shadow_trap",
      title: "Shadow Trap",
      cost: 1,
      target: "none",
      text: "Deal 5 damage to all enemies. Apply 1 Slow to all. Set Shadow Trap for 3 turns. Each ally phase it deals 4 damage to all enemies. Draw 1 card.",
      effects: [
        { kind: "damage_all", value: 5 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "summon_minion", value: 4, minionId: "assassin_shadow_trap" },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "disruption", "scaling", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 4 — Late reward pool: lane capstones and closers
    // ════════════════════════════════════════════════════════════════════

    // ── Martial Burst ──
    assassin_phoenix_strike: {
      id: "assassin_phoenix_strike",
      title: "Phoenix Strike",
      cost: 2,
      target: "enemy",
      text: "Deal 22 damage. Apply 5 Burn. Draw 1 card.",
      effects: [
        { kind: "damage", value: 22 },
        { kind: "apply_burn", value: 5 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "protection"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break", "telegraph_respect", "anti_fire_pressure"],
      skillRef: "assassin_phoenix_strike",
      tier: 4,
    },
    assassin_dragon_flight: {
      id: "assassin_dragon_flight",
      title: "Dragon Flight",
      cost: 2,
      target: "enemy",
      text: "Deal 20 damage. If you played a melee card earlier this turn, deal 10 more.",
      effects: [
        { kind: "damage", value: 20 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    assassin_combo_mastery: {
      id: "assassin_combo_mastery",
      title: "Combo Mastery",
      cost: 1,
      target: "none",
      text: "This combat, your Assassin melee cards deal +3 damage and gain +2 Guard. Draw 2 cards. Exhaust.",
      effects: [{ kind: "draw", value: 2 }],
      behaviorTags: ["scaling", "setup", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "assassin_combo_mastery",
      tier: 4,
    },

    // ── Trap Field ──
    assassin_death_sentry: {
      id: "assassin_death_sentry",
      title: "Death Sentry",
      cost: 2,
      target: "none",
      text: "Blast all enemies for 10 and apply 1 Paralyze. Set Death Sentry for 4 turns. Each ally phase it blasts all enemies for 12 and applies 3 Paralyze.",
      effects: [
        { kind: "damage_all", value: 10 },
        { kind: "apply_paralyze_all", value: 1 },
        { kind: "summon_minion", value: 12, secondaryValue: 3, duration: 4, minionId: "assassin_death_sentry" },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "tax", "protection"],
      roleTag: "payoff",
      rewardRole: "tech",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_support_disruption", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "assassin_death_sentry",
      tier: 4,
    },
    assassin_wake_of_inferno: {
      id: "assassin_wake_of_inferno",
      title: "Wake of Inferno",
      cost: 2,
      target: "none",
      text: "Deal 8 fire damage to all enemies. Apply 4 Burn to all. Set Wake of Inferno for 3 turns. Each ally phase it scorches all enemies for 9 and applies 5 Burn.",
      effects: [
        { kind: "damage_all", value: 8 },
        { kind: "apply_burn_all", value: 4 },
        { kind: "summon_minion", value: 9, secondaryValue: 5, minionId: "assassin_wake_of_inferno" },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "tax"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    assassin_trap_mastery: {
      id: "assassin_trap_mastery",
      title: "Trap Mastery",
      cost: 1,
      target: "none",
      text: "This combat, your traps deal +3 damage each ally phase. All active traps gain +1 turn. Draw 1 card. Exhaust.",
      effects: [{ kind: "draw", value: 1 }],
      behaviorTags: ["scaling", "setup"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "assassin_trap_mastery",
      tier: 4,
    },

    // ── Shadow Tempo ──
    assassin_shadow_master: {
      id: "assassin_shadow_master",
      title: "Shadow Master",
      cost: 2,
      target: "enemy",
      text: "Deal 12 damage. Your mercenary deals +18 to this target. Draw 1 card.",
      effects: [
        { kind: "damage", value: 12 },
        { kind: "mark_enemy_for_mercenary", value: 18 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "support", "protection"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    assassin_lethal_tempo: {
      id: "assassin_lethal_tempo",
      title: "Lethal Tempo",
      cost: 1,
      target: "none",
      text: "This combat, your Assassin cards draw 1 extra card when they draw. Draw 1 card. Exhaust.",
      effects: [{ kind: "draw", value: 1 }],
      behaviorTags: ["scaling", "salvage", "conversion"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "assassin_lethal_tempo",
      tier: 4,
    },

    // ── Class Glue ──
    assassin_natalyas_guard: {
      id: "assassin_natalyas_guard",
      title: "Natalya's Guard",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Heal your mercenary 6. The next enemy attack against you or your mercenary this turn deals 6 less damage.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "heal_mercenary", value: 6 },
      ],
      behaviorTags: ["mitigation", "protection", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_fire_pressure"],
      skillRef: "",
      tier: 4,
    },
    assassin_dark_recovery: {
      id: "assassin_dark_recovery",
      title: "Dark Recovery",
      cost: 1,
      target: "none",
      text: "Heal 8. Heal your mercenary 6. Gain 14 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 8 },
        { kind: "heal_mercenary", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "support", "mitigation"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },

    // ── Hybrid Bridges ──
    assassin_shadow_storm: {
      id: "assassin_shadow_storm",
      title: "Shadow Storm",
      cost: 2,
      target: "none",
      text: "Deal 8 damage to all enemies. Apply 2 Poison to all. Each active trap deals 4 bonus damage this turn.",
      effects: [
        { kind: "damage_all", value: 8 },
        { kind: "apply_poison_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    assassin_fatal_cascade: {
      id: "assassin_fatal_cascade",
      title: "Fatal Cascade",
      cost: 2,
      target: "enemy",
      text: "Deal 14 damage. Deal 7 damage to all other enemies. If the target has Burn or Poison, deal 6 more to it.",
      effects: [
        { kind: "damage", value: 14 },
        { kind: "damage_all", value: 7 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    assassin_death_blossom: {
      id: "assassin_death_blossom",
      title: "Death Blossom",
      cost: 2,
      target: "enemy",
      text: "Deal 10 damage 3 times. Apply 1 Slow. If any hit lands on a target with Burn, Poison, or Paralyze, deal 4 more per hit.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "damage", value: 10 },
        { kind: "damage", value: 10 },
        { kind: "apply_slow", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
  };

  const ASSASSIN_STARTER_DECK = [
    "assassin_tiger_strike", "assassin_tiger_strike",
    "assassin_fire_blast", "assassin_fire_blast",
    "assassin_claw_mastery",
    "assassin_psychic_hammer",
    "assassin_blade_shield",
    "assassin_cobra_strike",
    "rally_mercenary",
    "assassin_fists_of_fire",
    "assassin_wake_of_fire",
    "assassin_burst_of_speed",
    "assassin_cloak_of_shadows", "assassin_cloak_of_shadows",
    "assassin_weapon_block",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const ASSASSIN_REWARD_POOL = {
    early: [...new Set([
      ...getCardIdsByTier(ASSASSIN_CARDS, 2),
      "assassin_claw_mastery",
    ])],
    mid: getCardIdsByTier(ASSASSIN_CARDS, 3),
    // Death Sentry is intentionally evolution-led rather than a freely draftable late reward.
    late: getCardIdsByTier(ASSASSIN_CARDS, 4).filter((cardId) => cardId !== "assassin_death_sentry"),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.assassin = {
    cards: ASSASSIN_CARDS,
    starterDeck: ASSASSIN_STARTER_DECK,
    rewardPool: ASSASSIN_REWARD_POOL,
  };
})();
