(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Assassin Cards ────────────────────────────────────────────────────
  // Martial Arts: combo hits that build up damage
  // Shadow Disciplines: buffs, evasion, shadow clones
  // Traps: fire/lightning AoE and burn effects

  const ASSASSIN_CARDS: Record<string, ClassCardDefinition> = {
    // ── Tier 1 ──
    assassin_tiger_strike: {
      id: "assassin_tiger_strike",
      title: "Tiger Strike",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage.",
      effects: [
        { kind: "damage", value: 7 },
      ],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break"],
      skillRef: "assassin_tiger_strike",
      tier: 1,
    },
    assassin_fire_blast: {
      id: "assassin_fire_blast",
      title: "Fire Blast",
      cost: 1,
      target: "enemy",
      text: "Deal 6 fire damage. Apply 5 Burn.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "apply_burn", value: 5 },
      ],
      behaviorTags: ["setup", "payoff", "pressure"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline"],
      skillRef: "assassin_fire_blast",
      tier: 1,
    },
    assassin_claw_mastery: {
      id: "assassin_claw_mastery",
      title: "Claw Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 8 damage. Mark an enemy for your mercenary for 10. Gain 7 Guard.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "mark_enemy_for_mercenary", value: 10 },
        { kind: "gain_guard_self", value: 7 },
      ],
      behaviorTags: ["setup", "mitigation", "support", "payoff"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_backline"],
      skillRef: "assassin_claw_mastery",
      tier: 1,
    },
    assassin_psychic_hammer: {
      id: "assassin_psychic_hammer",
      title: "Psychic Hammer",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. Apply 1 Paralyze. Mark an enemy for your mercenary for 8. Gain 5 Guard.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "apply_paralyze", value: 1 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
        { kind: "gain_guard_self", value: 5 },
      ],
      behaviorTags: ["mitigation", "disruption", "support", "setup"],
      roleTag: "answer",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_backline"],
      skillRef: "assassin_psychic_hammer",
      tier: 1,
    },
    assassin_blade_shield: {
      id: "assassin_blade_shield",
      title: "Blade Shield",
      cost: 1,
      target: "none",
      text: "Deal 6 damage to all enemies. You and your mercenary gain 8 Guard. Apply 1 Slow to all enemies. Mercenary next attack +8. Draw 1 card.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "gain_guard_party", value: 8 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "buff_mercenary_next_attack", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "salvage", "support", "setup", "disruption", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "assassin_blade_shield",
      tier: 2,
    },
    assassin_cloak_of_shadows: {
      id: "assassin_cloak_of_shadows",
      title: "Cloak of Shadows",
      cost: 1,
      target: "none",
      text: "Gain 7 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 7 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "disruption"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_control"],
      skillRef: "assassin_cloak_of_shadows",
      tier: 1,
    },

    // ── Tier 2 ──
    assassin_fists_of_fire: {
      id: "assassin_fists_of_fire",
      title: "Fists of Fire",
      cost: 1,
      target: "enemy",
      text: "Deal 8 fire damage. Apply 3 Burn. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "apply_burn", value: 3 },
        { kind: "gain_guard_self", value: 5 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break"],
      skillRef: "assassin_fists_of_fire",
      tier: 2,
    },
    assassin_burst_of_speed: {
      id: "assassin_burst_of_speed",
      title: "Burst of Speed",
      cost: 1,
      target: "none",
      text: "Gain 7 Guard. Mercenary next attack +10. Draw 2 cards.",
      effects: [
        { kind: "gain_guard_self", value: 7 },
        { kind: "buff_mercenary_next_attack", value: 10 },
        { kind: "draw", value: 2 },
      ],
      behaviorTags: ["salvage", "mitigation", "support", "setup"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_tax", "anti_attrition"],
      skillRef: "assassin_burst_of_speed",
      tier: 2,
    },
    assassin_wake_of_fire: {
      id: "assassin_wake_of_fire",
      title: "Wake of Fire",
      cost: 2,
      target: "none",
      text: "Scorch all enemies for 6 and apply 3 Burn. Set Wake of Fire for 4 turns. Each ally phase it scorches all enemies for 7 and applies 4 Burn. You and your mercenary gain 8 Guard.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "apply_burn_all", value: 3 },
        { kind: "summon_minion", value: 7, secondaryValue: 4, duration: 4, minionId: "assassin_wake_of_fire" },
        { kind: "gain_guard_party", value: 8 },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "tax", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "assassin_wake_of_fire",
      tier: 2,
    },
    assassin_cobra_strike: {
      id: "assassin_cobra_strike",
      title: "Cobra Strike",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Heal 8. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "heal_hero", value: 8 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "conversion", "support", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition"],
      skillRef: "assassin_cobra_strike",
      tier: 2,
    },

    // ── Tier 3 ──
    assassin_claws_of_thunder: {
      id: "assassin_claws_of_thunder",
      title: "Claws of Thunder",
      cost: 2,
      target: "enemy",
      text: "Deal 17 lightning damage. Apply 1 Paralyze. Gain 8 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 17 },
        { kind: "apply_paralyze", value: 1 },
        { kind: "gain_guard_self", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break", "anti_backline"],
      skillRef: "assassin_claws_of_thunder",
      tier: 3,
    },
    assassin_blades_of_ice: {
      id: "assassin_blades_of_ice",
      title: "Blades of Ice",
      cost: 2,
      target: "enemy",
      text: "Deal 15 cold damage. Apply 1 Freeze and 1 Slow. Gain 4 Guard. You and your mercenary gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 15 },
        { kind: "apply_freeze", value: 1 },
        { kind: "apply_slow", value: 1 },
        { kind: "gain_guard_self", value: 4 },
        { kind: "gain_guard_party", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "disruption", "mitigation", "salvage", "protection"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["telegraph_respect", "anti_backline", "anti_fire_pressure"],
      skillRef: "assassin_blades_of_ice",
      tier: 3,
    },
    assassin_fade: {
      id: "assassin_fade",
      title: "Fade",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 20 Guard. Heal 6. Apply 1 Slow to all enemies.",
      effects: [
        { kind: "gain_guard_party", value: 20 },
        { kind: "heal_hero", value: 6 },
        { kind: "apply_slow_all", value: 1 },
      ],
      behaviorTags: ["mitigation", "support", "protection", "disruption"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_attrition", "anti_control", "telegraph_respect"],
      skillRef: "assassin_fade",
      tier: 3,
    },
    assassin_lightning_sentry: {
      id: "assassin_lightning_sentry",
      title: "Lightning Sentry",
      cost: 2,
      target: "none",
      text: "Shock all enemies for 7 and apply 1 Paralyze. Set Lightning Sentry for 4 turns. Each ally phase it shocks all enemies for 8 and applies 3 Paralyze. Gain 10 Guard.",
      effects: [
        { kind: "damage_all", value: 7 },
        { kind: "apply_paralyze_all", value: 1 },
        { kind: "summon_minion", value: 8, secondaryValue: 3, duration: 4, minionId: "assassin_lightning_sentry" },
        { kind: "gain_guard_self", value: 10 },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "tax"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_support_disruption"],
      skillRef: "assassin_lightning_sentry",
      tier: 2,
    },
    assassin_shadow_warrior: {
      id: "assassin_shadow_warrior",
      title: "Shadow Warrior",
      cost: 1,
      target: "enemy",
      text: "Deal 6 damage. You and your mercenary gain 10 Guard. Heal your mercenary 16. Mark an enemy for your mercenary for 16. Mercenary next attack +16.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "gain_guard_party", value: 10 },
        { kind: "heal_mercenary", value: 16 },
        { kind: "mark_enemy_for_mercenary", value: 16 },
        { kind: "buff_mercenary_next_attack", value: 16 },
      ],
      behaviorTags: ["protection", "support", "mitigation", "payoff", "setup", "pressure"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_control", "anti_backline"],
      skillRef: "assassin_shadow_warrior",
      tier: 4,
    },

    // ── Tier 4 ──
    assassin_phoenix_strike: {
      id: "assassin_phoenix_strike",
      title: "Phoenix Strike",
      cost: 2,
      target: "enemy",
      text: "Deal 22 damage. Apply 5 Burn. Gain 8 Guard. You and your mercenary gain 8 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 22 },
        { kind: "apply_burn", value: 5 },
        { kind: "gain_guard_self", value: 8 },
        { kind: "gain_guard_party", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "protection"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break", "telegraph_respect", "anti_fire_pressure"],
      skillRef: "assassin_phoenix_strike",
      tier: 4,
    },
    assassin_death_sentry: {
      id: "assassin_death_sentry",
      title: "Death Sentry",
      cost: 2,
      target: "none",
      text: "Blast all enemies for 10 and apply 1 Paralyze. Set Death Sentry for 4 turns. Each ally phase it blasts all enemies for 12 and applies 3 Paralyze. You and your mercenary gain 12 Guard.",
      effects: [
        { kind: "damage_all", value: 10 },
        { kind: "apply_paralyze_all", value: 1 },
        { kind: "summon_minion", value: 12, secondaryValue: 3, duration: 4, minionId: "assassin_death_sentry" },
        { kind: "gain_guard_party", value: 12 },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "tax", "protection"],
      roleTag: "payoff",
      rewardRole: "tech",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_support_disruption", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "assassin_death_sentry",
      tier: 4,
    },
  };

  const ASSASSIN_STARTER_DECK = [
    "assassin_tiger_strike", "assassin_tiger_strike",
    "assassin_fire_blast", "assassin_fire_blast",
    "assassin_claw_mastery",
    "assassin_psychic_hammer",
    "assassin_blade_shield",
    "assassin_cobra_strike",
    "rally_mercenary",
    "assassin_fists_of_fire",
    "assassin_wake_of_fire",
    "assassin_burst_of_speed",
    "assassin_cloak_of_shadows",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const ASSASSIN_REWARD_POOL = {
    early: [...new Set([
      ...getCardIdsByTier(ASSASSIN_CARDS, 2),
      "assassin_claw_mastery",
    ])],
    mid: getCardIdsByTier(ASSASSIN_CARDS, 3),
    // Death Sentry is intentionally evolution-led rather than a freely draftable late reward.
    late: getCardIdsByTier(ASSASSIN_CARDS, 4).filter((cardId) => cardId !== "assassin_death_sentry"),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.assassin = {
    cards: ASSASSIN_CARDS,
    starterDeck: ASSASSIN_STARTER_DECK,
    rewardPool: ASSASSIN_REWARD_POOL,
  };
})();
