(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Amazon Cards ──────────────────────────────────────────────────────
  // Bow & Crossbow: ranged single-target and AoE arrow attacks
  // Javelin & Spear: lightning/poison melee-range damage
  // Passive & Magic: evasion, utility, and summoned support

  const AMAZON_CARDS: Record<string, ClassCardDefinition> = {
    // ── Tier 1 (Lv 1) ── Starter cards
    amazon_magic_arrow: {
      id: "amazon_magic_arrow",
      title: "Magic Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 7 magic damage. Gain 3 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "gain_guard_self", value: 3 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "salvage", "payoff"],
      roleTag: "support",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_backline"],
      skillRef: "amazon_magic_arrow",
      tier: 1,
    },
    amazon_jab: {
      id: "amazon_jab",
      title: "Jab",
      cost: 2,
      target: "enemy",
      text: "Deal 7 damage. Deal 6 damage.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "damage", value: 6 },
      ],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "foundation",
      splashRole: "primary_only",
      skillRef: "amazon_jab",
      tier: 1,
    },
    amazon_inner_sight: {
      id: "amazon_inner_sight",
      title: "Inner Sight",
      cost: 1,
      target: "enemy",
      text: "Deal 5 damage. Apply 1 Slow. Your mercenary deals +8 to this target. Mercenary next attack +6. You and your mercenary gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "apply_slow", value: 1 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
        { kind: "buff_mercenary_next_attack", value: 6 },
        { kind: "gain_guard_party", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "salvage", "mitigation", "conversion", "disruption", "protection"],
      roleTag: "support",
      rewardRole: "foundation",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "telegraph_respect"],
      skillRef: "amazon_inner_sight",
      tier: 1,
    },
    amazon_fire_arrow: {
      id: "amazon_fire_arrow",
      title: "Fire Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. Apply 4 Burn.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "apply_burn", value: 4 },
      ],
      behaviorTags: ["setup", "payoff", "pressure"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "amazon_fire_arrow",
      tier: 1,
    },
    amazon_dodge: {
      id: "amazon_dodge",
      title: "Dodge",
      cost: 1,
      target: "none",
      text: "Gain 9 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 9 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "support", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      skillRef: "amazon_dodge",
      tier: 1,
    },
    amazon_critical_strike: {
      id: "amazon_critical_strike",
      title: "Critical Strike",
      cost: 2,
      target: "enemy",
      text: "Deal 14 damage. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 14 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "amazon_critical_strike",
      tier: 1,
    },

    amazon_slow_missiles: {
      id: "amazon_slow_missiles",
      title: "Slow Missiles",
      cost: 1,
      target: "none",
      text: "Gain 10 Guard. Apply 3 Slow to all enemies. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 10 },
        { kind: "apply_slow_all", value: 3 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "disruption", "salvage", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      skillRef: "amazon_slow_missiles",
      tier: 2,
    },
    amazon_avoid: {
      id: "amazon_avoid",
      title: "Avoid",
      cost: 1,
      target: "none",
      text: "Gain 12 Guard. Draw 2 cards.",
      effects: [
        { kind: "gain_guard_self", value: 12 },
        { kind: "draw", value: 2 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "primary_only",
      skillRef: "amazon_avoid",
      tier: 2,
    },
    amazon_penetrate: {
      id: "amazon_penetrate",
      title: "Penetrate",
      cost: 1,
      target: "enemy",
      text: "Heal 4. Deal 8 damage. Apply 1 Slow. Your mercenary deals +10 to this target. Mercenary next attack +8. You and your mercenary gain 8 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 4 },
        { kind: "damage", value: 8 },
        { kind: "apply_slow", value: 1 },
        { kind: "mark_enemy_for_mercenary", value: 10 },
        { kind: "buff_mercenary_next_attack", value: 8 },
        { kind: "gain_guard_party", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "conversion", "mitigation", "salvage", "disruption", "protection"],
      roleTag: "setup",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_penetrate",
      tier: 2,
    },
    amazon_decoy: {
      id: "amazon_decoy",
      title: "Decoy",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. You and your mercenary gain 12 Guard. Mercenary next attack +10. Draw 1 card.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "gain_guard_party", value: 12 },
        { kind: "buff_mercenary_next_attack", value: 10 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "mitigation", "conversion", "protection", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_decoy",
      tier: 2,
    },

    // ── Tier 2 (Lv 6-12) ── Early rewards
    amazon_cold_arrow: {
      id: "amazon_cold_arrow",
      title: "Cold Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 7 cold damage. Apply 1 Slow. Gain 4 Guard.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "apply_slow", value: 1 },
        { kind: "gain_guard_self", value: 4 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation", "payoff"],
      roleTag: "payoff",
      rewardRole: "tech",
      skillRef: "amazon_cold_arrow",
      tier: 2,
    },
    amazon_multiple_shot: {
      id: "amazon_multiple_shot",
      title: "Multiple Shot",
      cost: 2,
      target: "none",
      text: "Deal 7 damage to all enemies. Apply 1 Slow to all enemies. Gain 7 Guard.",
      effects: [
        { kind: "damage_all", value: 7 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 7 },
      ],
      behaviorTags: ["pressure", "mitigation", "setup", "disruption"],
      roleTag: "support",
      rewardRole: "support",
      counterTags: ["anti_summon", "telegraph_respect"],
      skillRef: "amazon_multiple_shot",
      tier: 2,
    },
    amazon_power_strike: {
      id: "amazon_power_strike",
      title: "Power Strike",
      cost: 1,
      target: "enemy",
      text: "Heal 3. Deal 11 lightning damage. Apply 2 Paralyze. Gain 7 Guard.",
      effects: [
        { kind: "heal_hero", value: 3 },
        { kind: "damage", value: 11 },
        { kind: "apply_paralyze", value: 2 },
        { kind: "gain_guard_self", value: 7 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_power_strike",
      tier: 2,
    },
    amazon_exploding_arrow: {
      id: "amazon_exploding_arrow",
      title: "Exploding Arrow",
      cost: 2,
      target: "enemy",
      text: "Deal 8 fire damage. Apply 3 Burn. Draw 1 card.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "apply_burn", value: 3 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage", "setup"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "amazon_exploding_arrow",
      tier: 2,
    },

    // ── Tier 3 (Lv 18-24) ── Mid-game
    amazon_guided_arrow: {
      id: "amazon_guided_arrow",
      title: "Guided Arrow",
      cost: 1,
      target: "enemy",
      text: "Deal 16 damage. Draw 1 card. Gain 5 Guard.",
      effects: [
        { kind: "damage", value: 16 },
        { kind: "draw", value: 1 },
        { kind: "gain_guard_self", value: 5 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "amazon_guided_arrow",
      tier: 3,
    },
    amazon_evade: {
      id: "amazon_evade",
      title: "Evade",
      cost: 1,
      target: "enemy",
      text: "Heal 5. Deal 11 damage. Apply 2 Slow. You and your mercenary gain 10 Guard.",
      effects: [
        { kind: "heal_hero", value: 5 },
        { kind: "damage", value: 11 },
        { kind: "apply_slow", value: 2 },
        { kind: "gain_guard_party", value: 10 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation", "disruption", "protection", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_evade",
      tier: 3,
    },
    amazon_deadly_strike: {
      id: "amazon_deadly_strike",
      title: "Deadly Strike",
      cost: 2,
      target: "enemy",
      text: "Heal 4. Deal 20 damage. Your mercenary deals +16 to this target. Mercenary next attack +14. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 4 },
        { kind: "damage", value: 20 },
        { kind: "mark_enemy_for_mercenary", value: 16 },
        { kind: "buff_mercenary_next_attack", value: 14 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "salvage", "setup", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_deadly_strike",
      tier: 3,
    },
    amazon_charged_strike: {
      id: "amazon_charged_strike",
      title: "Charged Strike",
      cost: 2,
      target: "enemy",
      text: "Heal 4. Deal 12 lightning damage. Deal 12 lightning damage. Apply 3 Paralyze. Gain 12 Guard.",
      effects: [
        { kind: "heal_hero", value: 4 },
        { kind: "damage", value: 12 },
        { kind: "damage", value: 12 },
        { kind: "apply_paralyze", value: 3 },
        { kind: "gain_guard_self", value: 12 },
      ],
      behaviorTags: ["pressure", "payoff", "setup", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_charged_strike",
      tier: 3,
    },
    amazon_strafe: {
      id: "amazon_strafe",
      title: "Strafe",
      cost: 2,
      target: "none",
      text: "Deal 9 damage to all enemies. Apply 1 Slow to all enemies. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage_all", value: 9 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "salvage", "setup", "mitigation", "disruption"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_summon", "telegraph_respect"],
      skillRef: "amazon_strafe",
      tier: 3,
    },
    amazon_valkyrie: {
      id: "amazon_valkyrie",
      title: "Valkyrie",
      cost: 2,
      target: "enemy",
      text: "Heal 6. Deal 9 damage. You and your mercenary gain 10 Guard. Draw 1 card. Summon Valkyrie. Each ally phase it strikes for 10 and grants 10 Guard to the party.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "damage", value: 9 },
        { kind: "gain_guard_party", value: 10 },
        { kind: "draw", value: 1 },
        { kind: "summon_minion", value: 10, secondaryValue: 10, minionId: "amazon_valkyrie" },
      ],
      behaviorTags: ["setup", "protection", "scaling", "payoff", "salvage", "mitigation"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_valkyrie",
      tier: 3,
    },

    // ── Tier 4 (Lv 30) ── Late-game power cards
    amazon_pierce: {
      id: "amazon_pierce",
      title: "Pierce",
      cost: 2,
      target: "enemy",
      text: "Heal 5. Deal 24 damage. Apply 2 Slow. Your mercenary deals +18 to this target. Mercenary next attack +14. You and your mercenary gain 10 Guard.",
      effects: [
        { kind: "heal_hero", value: 5 },
        { kind: "damage", value: 24 },
        { kind: "apply_slow", value: 2 },
        { kind: "mark_enemy_for_mercenary", value: 18 },
        { kind: "buff_mercenary_next_attack", value: 14 },
        { kind: "gain_guard_party", value: 10 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "setup", "disruption", "protection", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_pierce",
      tier: 4,
    },
    amazon_freezing_arrow: {
      id: "amazon_freezing_arrow",
      title: "Freezing Arrow",
      cost: 2,
      target: "none",
      text: "Deal 9 cold damage to all enemies. Apply 1 Freeze and 1 Slow to all. Gain 5 Guard.",
      effects: [
        { kind: "damage_all", value: 9 },
        { kind: "apply_freeze_all", value: 1 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 5 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "amazon_freezing_arrow",
      tier: 4,
    },
    amazon_lightning_fury: {
      id: "amazon_lightning_fury",
      title: "Lightning Fury",
      cost: 2,
      target: "none",
      text: "Heal 5. Deal 13 lightning damage to all enemies. Apply 3 Paralyze to all. Gain 10 Guard.",
      effects: [
        { kind: "heal_hero", value: 5 },
        { kind: "damage_all", value: 13 },
        { kind: "apply_paralyze_all", value: 3 },
        { kind: "gain_guard_self", value: 10 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "amazon_lightning_fury",
      tier: 4,
    },
  };

  const AMAZON_STARTER_DECK = [
    "amazon_magic_arrow", "amazon_magic_arrow",
    "amazon_jab", "amazon_jab",
    "amazon_fire_arrow", "amazon_fire_arrow",
    "amazon_inner_sight", "amazon_inner_sight",
    "rally_mercenary",
    "amazon_critical_strike", "amazon_critical_strike",
    "amazon_dodge", "amazon_dodge",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const AMAZON_REWARD_POOL = {
    early: getCardIdsByTier(AMAZON_CARDS, 2),
    mid: getCardIdsByTier(AMAZON_CARDS, 3),
    late: getCardIdsByTier(AMAZON_CARDS, 4),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.amazon = {
    cards: AMAZON_CARDS,
    starterDeck: AMAZON_STARTER_DECK,
    rewardPool: AMAZON_REWARD_POOL,
  };
})();
