(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Druid Cards ───────────────────────────────────────────────────────
  // Elemental Storm: fire/wind/cold AoE spells — Burn setup → elemental burst payoff
  // Shifter Bruiser: shapeshift melee — form-enhanced multi-hit + sustain
  // Summoner Engine: companion army — persistent board presence + pack scaling
  // Class Glue: multi-lane utility
  // Hybrid Bridges: cross-lane support cards

  const DRUID_CARDS: Record<string, ClassCardDefinition> = {

    // ════════════════════════════════════════════════════════════════════
    // TIER 1 — Starter shell and identity cards
    // ════════════════════════════════════════════════════════════════════

    // ── Elemental Storm ──
    druid_firestorm: {
      id: "druid_firestorm",
      title: "Firestorm",
      cost: 1,
      target: "enemy",
      text: "Deal 5 fire damage. Apply 4 Burn.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "apply_burn", value: 4 },
      ],
      behaviorTags: ["setup", "pressure", "mitigation"],
      roleTag: "setup",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "druid_firestorm",
      tier: 1,
    },

    // ── Shifter Bruiser ──
    druid_werewolf: {
      id: "druid_werewolf",
      title: "Werewolf",
      cost: 1,
      target: "enemy",
      text: "Deal 11 damage. Heal 5.",
      effects: [
        { kind: "damage", value: 11 },
        { kind: "heal_hero", value: 5 },
      ],
      behaviorTags: ["pressure", "mitigation", "payoff"],
      roleTag: "payoff",
      rewardRole: "foundation",
      splashRole: "primary_only",
      skillRef: "druid_werewolf",
      tier: 1,
    },

    // ── Summoner Engine ──
    druid_raven: {
      id: "druid_raven",
      title: "Raven",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 4 Guard. Summon Raven. Each ally phase it pecks for 4 and marks for +4 mercenary damage.",
      effects: [
        { kind: "gain_guard_party", value: 14 },
        { kind: "summon_minion", value: 4, minionId: "druid_raven" },
      ],
      behaviorTags: ["setup", "scaling", "support", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_control"],
      skillRef: "druid_raven",
      tier: 1,
    },
    druid_poison_creeper: {
      id: "druid_poison_creeper",
      title: "Poison Creeper",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 4 Guard. Summon Poison Creeper. Each ally phase it bites for 4 and applies 4 Poison.",
      effects: [
        { kind: "gain_guard_party", value: 14 },
        { kind: "summon_minion", value: 4, minionId: "druid_poison_creeper" },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_attrition", "anti_control"],
      skillRef: "druid_poison_creeper",
      tier: 1,
    },

    // ── Class Glue ──
    druid_cyclone_armor: {
      id: "druid_cyclone_armor",
      title: "Cyclone Armor",
      cost: 1,
      target: "none",
      text: "Gain 8 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "druid_cyclone_armor",
      tier: 1,
    },
    druid_lycanthropy: {
      id: "druid_lycanthropy",
      title: "Lycanthropy",
      cost: 1,
      target: "none",
      text: "Heal 5. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "druid_lycanthropy",
      tier: 1,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 2 — Early reward pool: lane formation begins
    // ════════════════════════════════════════════════════════════════════

    // ── Elemental Storm ──
    druid_molten_boulder: {
      id: "druid_molten_boulder",
      title: "Molten Boulder",
      cost: 2,
      target: "enemy",
      text: "Deal 11 fire damage. Apply 3 Burn.",
      effects: [
        { kind: "damage", value: 11 },
        { kind: "apply_burn", value: 3 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_molten_boulder",
      tier: 2,
    },
    druid_fissure: {
      id: "druid_fissure",
      title: "Fissure",
      cost: 2,
      target: "none",
      text: "Deal 6 fire damage to all enemies. Apply 2 Burn to all.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "apply_burn_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_fissure",
      tier: 2,
    },
    druid_twister: {
      id: "druid_twister",
      title: "Twister",
      cost: 1,
      target: "none",
      text: "Deal 5 damage to all enemies. Apply 1 Slow to all. Draw 1 card.",
      effects: [
        { kind: "damage_all", value: 5 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "disruption", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },
    druid_arctic_blast: {
      id: "druid_arctic_blast",
      title: "Arctic Blast",
      cost: 1,
      target: "none",
      text: "Deal 6 cold damage to all enemies. Apply 1 Slow to all.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "apply_slow_all", value: 1 },
      ],
      behaviorTags: ["setup", "disruption", "mitigation"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ── Shifter Bruiser ──
    druid_werebear: {
      id: "druid_werebear",
      title: "Werebear",
      cost: 1,
      target: "enemy",
      text: "Deal 9 damage. Apply 1 Slow. Gain 6 Guard. Grant 6 Guard to the party. Draw 1 card.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "apply_slow", value: 1 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "gain_guard_party", value: 6 },
        { kind: "apply_taunt", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "conversion", "salvage", "disruption"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_werebear",
      tier: 2,
    },
    druid_feral_rage: {
      id: "druid_feral_rage",
      title: "Feral Rage",
      cost: 1,
      target: "enemy",
      text: "Deal 8 damage. Heal 4. Your next melee card this turn deals +3 damage.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "heal_hero", value: 4 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },
    druid_maul: {
      id: "druid_maul",
      title: "Maul",
      cost: 2,
      target: "enemy",
      text: "Deal 16 damage. Apply 1 Stun. Gain 6 Guard.",
      effects: [
        { kind: "damage", value: 16 },
        { kind: "apply_stun", value: 1 },
        { kind: "gain_guard_self", value: 6 },
      ],
      behaviorTags: ["pressure", "payoff", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },

    // ── Summoner Engine ──
    druid_oak_sage: {
      id: "druid_oak_sage",
      title: "Oak Sage",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 6 Guard. Summon Oak Sage. Each ally phase it heals you and your mercenary for 4.",
      effects: [
        { kind: "gain_guard_party", value: 14 },
        { kind: "summon_minion", value: 4, minionId: "druid_oak_sage" },
      ],
      behaviorTags: ["setup", "protection", "salvage", "support"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "druid_oak_sage",
      tier: 2,
    },
    druid_spirit_wolf: {
      id: "druid_spirit_wolf",
      title: "Spirit Wolf",
      cost: 1,
      target: "none",
      text: "Gain 5 Guard. Summon Spirit Wolf. Each ally phase it bites for 5 cold damage and applies 1 Slow.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "summon_minion", value: 5, minionId: "druid_spirit_wolf" },
      ],
      behaviorTags: ["setup", "disruption", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },
    druid_carrion_vine: {
      id: "druid_carrion_vine",
      title: "Carrion Vine",
      cost: 1,
      target: "none",
      text: "Gain 4 Guard. Summon Carrion Vine. Each ally phase it heals you for 3. If an enemy died last turn, heal 6 instead.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "summon_minion", value: 3, minionId: "druid_carrion_vine" },
      ],
      behaviorTags: ["setup", "salvage", "protection"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },

    // ── Class Glue ──
    druid_natures_balance: {
      id: "druid_natures_balance",
      title: "Nature's Balance",
      cost: 1,
      target: "none",
      text: "Heal 3. Gain 6 Guard. If you control a summon, draw 1 card. If an enemy has Burn, gain 3 more Guard.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
      ],
      behaviorTags: ["mitigation", "salvage", "conversion"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 3 — Mid reward pool: lane engines come online
    // ════════════════════════════════════════════════════════════════════

    // ── Elemental Storm ──
    druid_volcano: {
      id: "druid_volcano",
      title: "Volcano",
      cost: 2,
      target: "none",
      text: "Deal 8 fire damage to all enemies. Apply 4 Burn to all.",
      effects: [
        { kind: "damage_all", value: 8 },
        { kind: "apply_burn_all", value: 4 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_volcano",
      tier: 3,
    },
    druid_tornado: {
      id: "druid_tornado",
      title: "Tornado",
      cost: 2,
      target: "none",
      text: "Deal 12 damage to all enemies. If any enemy is Slowed, deal 4 more to it.",
      effects: [{ kind: "damage_all", value: 12 }],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_tornado",
      tier: 3,
    },
    druid_eruption: {
      id: "druid_eruption",
      title: "Eruption",
      cost: 2,
      target: "none",
      text: "Deal 6 fire damage to all enemies. Each enemy with Burn takes 4 additional damage per Burn stack (max 5 stacks).",
      effects: [{ kind: "damage_all", value: 6 }],
      behaviorTags: ["payoff", "conversion", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    druid_gale_force: {
      id: "druid_gale_force",
      title: "Gale Force",
      cost: 1,
      target: "none",
      text: "Deal 4 damage to all enemies. Deal 3 more for each Slowed enemy. Apply 1 Slow to all.",
      effects: [
        { kind: "damage_all", value: 4 },
        { kind: "apply_slow_all", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Shifter Bruiser ──
    druid_fury: {
      id: "druid_fury",
      title: "Fury",
      cost: 2,
      target: "enemy",
      text: "Deal 12 damage. Deal 11 damage. Deal 10 damage. Apply 1 Slow. Draw 1 card.",
      effects: [
        { kind: "damage", value: 12 },
        { kind: "damage", value: 11 },
        { kind: "damage", value: 10 },
        { kind: "apply_slow", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation", "salvage", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_fury",
      tier: 3,
    },
    druid_fire_claws: {
      id: "druid_fire_claws",
      title: "Fire Claws",
      cost: 1,
      target: "enemy",
      text: "Deal 9 fire damage. Apply 3 Burn. Gain 5 Guard.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "apply_burn", value: 3 },
        { kind: "gain_guard_self", value: 5 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    druid_rabies: {
      id: "druid_rabies",
      title: "Rabies",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage. Apply 5 Poison. Apply 5 Poison to all other enemies.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "apply_poison", value: 5 },
        { kind: "apply_poison_all", value: 5 },
      ],
      behaviorTags: ["pressure", "setup", "scaling"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    druid_shock_wave: {
      id: "druid_shock_wave",
      title: "Shock Wave",
      cost: 2,
      target: "none",
      text: "Deal 10 damage to all enemies. Apply 1 Stun to all non-boss enemies. Gain 8 Guard.",
      effects: [
        { kind: "damage_all", value: 10 },
        { kind: "apply_stun_all", value: 1 },
        { kind: "gain_guard_self", value: 8 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break", "telegraph_respect"],
      skillRef: "",
      tier: 3,
    },

    // ── Summoner Engine ──
    druid_heart_of_wolverine: {
      id: "druid_heart_of_wolverine",
      title: "Heart of Wolverine",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 8 Guard. Draw 1 card. Summon Heart of Wolverine. Each ally phase it strikes for 6 and marks for +7 mercenary damage.",
      effects: [
        { kind: "gain_guard_party", value: 14 },
        { kind: "draw", value: 1 },
        { kind: "summon_minion", value: 6, minionId: "druid_heart_of_wolverine" },
      ],
      behaviorTags: ["setup", "payoff", "scaling", "support", "salvage"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_heart_of_wolverine",
      tier: 3,
    },
    druid_dire_wolf: {
      id: "druid_dire_wolf",
      title: "Dire Wolf",
      cost: 2,
      target: "none",
      text: "Gain 6 Guard. Summon Dire Wolf. Each ally phase it mauls for 7 and grants 4 Guard to the party. If you control 2+ summons, it deals +3.",
      effects: [
        { kind: "gain_guard_self", value: 22 },
        { kind: "summon_minion", value: 7, minionId: "druid_dire_wolf" },
      ],
      behaviorTags: ["setup", "scaling", "protection"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    druid_spirit_of_barbs: {
      id: "druid_spirit_of_barbs",
      title: "Spirit of Barbs",
      cost: 1,
      target: "none",
      text: "Gain 6 Guard. Summon Spirit of Barbs. Each ally phase it deals 3 damage to all enemies and applies 1 Burn to all.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "summon_minion", value: 3, minionId: "druid_spirit_of_barbs" },
      ],
      behaviorTags: ["setup", "pressure", "scaling", "tax"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    druid_pack_howl: {
      id: "druid_pack_howl",
      title: "Pack Howl",
      cost: 1,
      target: "none",
      text: "Gain 5 Guard. Each of your summons deals 4 bonus damage on its next hit. If you control 3+ summons, draw 1 card.",
      effects: [{ kind: "gain_guard_self", value: 5 }],
      behaviorTags: ["support", "scaling", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Class Glue ──
    druid_primal_roar: {
      id: "druid_primal_roar",
      title: "Primal Roar",
      cost: 1,
      target: "none",
      text: "All non-boss enemies deal 3 less damage next turn. Gain 6 Guard. Draw 1 card.",
      effects: [{ kind: "gain_guard_self", value: 6 }, { kind: "draw", value: 1 }],
      behaviorTags: ["mitigation", "disruption", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_guard_break"],
      skillRef: "",
      tier: 3,
    },
    druid_hibernation: {
      id: "druid_hibernation",
      title: "Hibernation",
      cost: 1,
      target: "none",
      text: "Heal 8. Gain 10 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 8 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },

    // ── Hybrid Bridges ──
    druid_solar_creeper: {
      id: "druid_solar_creeper",
      title: "Solar Creeper",
      cost: 1,
      target: "none",
      text: "Gain 5 Guard. Summon Solar Creeper. Each ally phase it drains 3 from all enemies and heals you for 2.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "summon_minion", value: 3, secondaryValue: 2, minionId: "druid_solar_creeper" },
      ],
      behaviorTags: ["setup", "tax", "salvage"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    druid_summon_spirit_wolf_pack: {
      id: "druid_summon_spirit_wolf_pack",
      title: "Summon Spirit Wolves",
      cost: 2,
      target: "none",
      text: "Gain 6 Guard. Summon 2 Spirit Wolves. Each ally phase they bite for 4 cold damage and apply 1 Slow.",
      effects: [
        { kind: "gain_guard_self", value: 22 },
        { kind: "summon_minion", value: 4, minionId: "druid_spirit_wolf" },
        { kind: "summon_minion", value: 4, minionId: "druid_spirit_wolf_2" },
      ],
      behaviorTags: ["setup", "disruption", "protection", "scaling"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    druid_natures_wrath: {
      id: "druid_natures_wrath",
      title: "Nature's Wrath",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage. Apply 2 Burn. Apply 1 Slow. If you control a summon, deal 4 more damage.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "apply_burn", value: 2 },
        { kind: "apply_slow", value: 1 },
      ],
      behaviorTags: ["pressure", "setup", "conversion"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 4 — Late reward pool: lane capstones and closers
    // ════════════════════════════════════════════════════════════════════

    // ── Elemental Storm ──
    druid_hurricane: {
      id: "druid_hurricane",
      title: "Hurricane",
      cost: 2,
      target: "none",
      text: "Deal 15 cold damage to all enemies. Apply 2 Slow to all.",
      effects: [
        { kind: "damage_all", value: 15 },
        { kind: "apply_slow_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_hurricane",
      tier: 4,
    },
    druid_armageddon: {
      id: "druid_armageddon",
      title: "Armageddon",
      cost: 2,
      target: "none",
      text: "Deal 16 fire damage to all enemies. Apply 8 Burn to all.",
      effects: [
        { kind: "damage_all", value: 16 },
        { kind: "apply_burn_all", value: 8 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "druid_armageddon",
      tier: 4,
    },
    druid_elemental_mastery: {
      id: "druid_elemental_mastery",
      title: "Elemental Mastery",
      cost: 1,
      target: "none",
      text: "This combat, your Burn applications deal +2 and your Slow applications last +1 turn. Draw 2 cards. Exhaust.",
      effects: [{ kind: "draw", value: 2 }],
      behaviorTags: ["scaling", "setup", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "druid_elemental_mastery",
      tier: 4,
    },

    // ── Shifter Bruiser ──
    druid_hunger: {
      id: "druid_hunger",
      title: "Hunger",
      cost: 2,
      target: "enemy",
      text: "Deal 18 damage. Heal 10. If the target is Slowed, deal 6 more.",
      effects: [
        { kind: "damage", value: 18 },
        { kind: "heal_hero", value: 10 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    druid_primal_fury: {
      id: "druid_primal_fury",
      title: "Primal Fury",
      cost: 2,
      target: "enemy",
      text: "Deal 10 damage 3 times. Heal 3 for each hit.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "damage", value: 10 },
        { kind: "damage", value: 10 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    druid_savage_pounce: {
      id: "druid_savage_pounce",
      title: "Savage Pounce",
      cost: 1,
      target: "enemy",
      text: "Deal 14 damage. If the target is Slowed or Stunned, deal 8 more and apply 1 Stun.",
      effects: [{ kind: "damage", value: 14 }],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_guard_break"],
      skillRef: "",
      tier: 4,
    },

    // ── Summoner Engine ──
    druid_summon_grizzly: {
      id: "druid_summon_grizzly",
      title: "Summon Grizzly",
      cost: 2,
      target: "enemy",
      text: "Deal 8 damage. Heal 8. Heal your mercenary 6. Summon Grizzly. Each ally phase it mauls for 10 and grants 8 Guard to the party.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "heal_hero", value: 8 },
        { kind: "heal_mercenary", value: 6 },
        { kind: "summon_minion", value: 10, minionId: "druid_grizzly" },
      ],
      behaviorTags: ["setup", "protection", "scaling", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect", "anti_summon"],
      skillRef: "druid_summon_grizzly",
      tier: 4,
    },
    druid_wild_stampede: {
      id: "druid_wild_stampede",
      title: "Wild Stampede",
      cost: 2,
      target: "none",
      text: "Deal 5 damage to all enemies for each summon you control (max 4). Gain 6 Guard.",
      effects: [{ kind: "damage_all", value: 0 }, { kind: "gain_guard_self", value: 6 }],
      behaviorTags: ["payoff", "pressure", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    druid_force_of_nature: {
      id: "druid_force_of_nature",
      title: "Force of Nature",
      cost: 2,
      target: "none",
      text: "Reinforce all your summons by +3. Each summon deals 5 damage to a random enemy. Draw 1 card.",
      effects: [{ kind: "draw", value: 1 }],
      behaviorTags: ["scaling", "payoff", "support"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },

    // ── Class Glue ──
    druid_natures_guardian: {
      id: "druid_natures_guardian",
      title: "Nature's Guardian",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Heal your mercenary 6. The next enemy attack against you or your mercenary this turn deals 6 less damage.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "heal_mercenary", value: 6 },
      ],
      behaviorTags: ["mitigation", "protection", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_fire_pressure"],
      skillRef: "",
      tier: 4,
    },
    druid_renewal: {
      id: "druid_renewal",
      title: "Renewal",
      cost: 1,
      target: "none",
      text: "Heal 6. Heal your mercenary 6. Gain 8 Guard. If you control a summon, reinforce it by +2. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "heal_mercenary", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "support", "mitigation"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },

    // ── Hybrid Bridges ──
    druid_elemental_pack: {
      id: "druid_elemental_pack",
      title: "Elemental Pack",
      cost: 2,
      target: "none",
      text: "Deal 7 fire damage to all enemies. Apply 2 Burn to all. Each summon you control deals 3 bonus damage to a random enemy.",
      effects: [
        { kind: "damage_all", value: 7 },
        { kind: "apply_burn_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    druid_feral_storm: {
      id: "druid_feral_storm",
      title: "Feral Storm",
      cost: 2,
      target: "enemy",
      text: "Deal 14 damage. Deal 6 damage to all other enemies. Apply 1 Slow to all.",
      effects: [
        { kind: "damage", value: 14 },
        { kind: "damage_all", value: 6 },
        { kind: "apply_slow_all", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "disruption", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    druid_wild_convergence: {
      id: "druid_wild_convergence",
      title: "Wild Convergence",
      cost: 2,
      target: "none",
      text: "Deal 6 damage to all enemies. Apply 2 Burn to all. If you control a summon, deal 6 more to all. If any enemy is Slowed, apply 2 more Burn to all.",
      effects: [
        { kind: "damage_all", value: 6 },
        { kind: "apply_burn_all", value: 2 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    druid_grove_sentinel: {
      id: "druid_grove_sentinel",
      title: "Grove Sentinel",
      cost: 2,
      target: "none",
      text: "Gain 12 Guard. Grant 8 Guard to the party. Summon Treant. Each ally phase it strikes for 6 and grants 4 Guard to the party.",
      effects: [
        { kind: "gain_guard_self", value: 22 },
        { kind: "gain_guard_party", value: 22 },
        { kind: "summon_minion", value: 6, secondaryValue: 4, minionId: "druid_treant" },
      ],
      behaviorTags: ["protection", "mitigation", "setup"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "",
      tier: 4,
    },
  };

  const DRUID_STARTER_DECK = [
    "druid_firestorm", "druid_firestorm",
    "druid_werewolf", "druid_werewolf",
    "druid_raven", "druid_raven",
    "druid_poison_creeper", "druid_poison_creeper",
    "rally_mercenary",
    "druid_lycanthropy",
    "druid_cyclone_armor",
    "druid_werebear",
    "druid_oak_sage",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const DRUID_REWARD_POOL = {
    early: getCardIdsByTier(DRUID_CARDS, 2),
    mid: getCardIdsByTier(DRUID_CARDS, 3),
    late: getCardIdsByTier(DRUID_CARDS, 4),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.druid = {
    cards: DRUID_CARDS,
    starterDeck: DRUID_STARTER_DECK,
    rewardPool: DRUID_REWARD_POOL,
  };
})();
