(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Barbarian Cards ───────────────────────────────────────────────────
  // Combat: heavy melee damage, multi-hit, AoE
  // Masteries: passive weapon bonuses (guard, toughness)
  // Warcries: party-wide buffs and debuffs

  const BARBARIAN_CARDS: Record<string, ClassCardDefinition> = {
    // ── Tier 1 ──
    barbarian_bash: {
      id: "barbarian_bash",
      title: "Bash",
      cost: 2,
      target: "enemy",
      text: "Deal 14 damage.",
      effects: [{ kind: "damage", value: 14 }],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "foundation",
      splashRole: "primary_only",
      skillRef: "barbarian_bash",
      tier: 1,
    },
    barbarian_howl: {
      id: "barbarian_howl",
      title: "Howl",
      cost: 1,
      target: "none",
      text: "Apply 1 Slow to all enemies. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 5 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["disruption", "protection", "salvage"],
      roleTag: "answer",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_howl",
      tier: 1,
    },
    barbarian_sword_mastery: {
      id: "barbarian_sword_mastery",
      title: "Sword Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 8 damage. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "salvage", "support"],
      roleTag: "support",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_sword_mastery",
      tier: 1,
    },
    barbarian_find_potion: {
      id: "barbarian_find_potion",
      title: "Find Potion",
      cost: 1,
      target: "none",
      text: "Heal 5. Gain 4 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 5 },
        { kind: "gain_guard_self", value: 4 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_find_potion",
      tier: 1,
    },
    barbarian_iron_skin: {
      id: "barbarian_iron_skin",
      title: "Iron Skin",
      cost: 1,
      target: "none",
      text: "Gain 10 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 10 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_iron_skin",
      tier: 1,
    },
    barbarian_natural_resistance: {
      id: "barbarian_natural_resistance",
      title: "Natural Resistance",
      cost: 1,
      target: "none",
      text: "Heal 5. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 5 },
        { kind: "gain_guard_self", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_natural_resistance",
      tier: 1,
    },

    // ── Tier 2 ──
    barbarian_double_swing: {
      id: "barbarian_double_swing",
      title: "Double Swing",
      cost: 1,
      target: "enemy",
      text: "Deal 6 damage. Deal 5 damage.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "damage", value: 5 },
      ],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_double_swing",
      tier: 2,
    },
    barbarian_leap: {
      id: "barbarian_leap",
      title: "Leap",
      cost: 1,
      target: "enemy",
      text: "Deal 8 damage. Gain 4 Guard.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "gain_guard_self", value: 4 },
      ],
      behaviorTags: ["pressure", "mitigation", "setup"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_leap",
      tier: 2,
    },
    barbarian_shout: {
      id: "barbarian_shout",
      title: "Shout",
      cost: 1,
      target: "none",
      text: "Apply 1 Slow to all enemies. You and your mercenary gain 10 Guard. Draw 1 card.",
      effects: [
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_party", value: 10 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["disruption", "protection", "salvage", "support"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "barbarian_shout",
      tier: 2,
    },
    barbarian_weapon_mastery: {
      id: "barbarian_weapon_mastery",
      title: "Weapon Mastery",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Gain 8 Guard. Mercenary next attack +8. Draw 1 card.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "gain_guard_self", value: 8 },
        { kind: "buff_mercenary_next_attack", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "salvage", "support", "scaling"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_weapon_mastery",
      tier: 2,
    },
    barbarian_stun: {
      id: "barbarian_stun",
      title: "Stun",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage. Apply 1 Stun.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "apply_stun", value: 1 },
      ],
      behaviorTags: ["pressure", "disruption", "mitigation"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_stun",
      tier: 2,
    },

    // ── Tier 3 ──
    barbarian_concentrate: {
      id: "barbarian_concentrate",
      title: "Concentrate",
      cost: 1,
      target: "enemy",
      text: "Heal 4. Deal 14 damage. Gain 12 Guard.",
      effects: [
        { kind: "heal_hero", value: 4 },
        { kind: "damage", value: 14 },
        { kind: "gain_guard_self", value: 12 },
      ],
      behaviorTags: ["pressure", "mitigation", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_concentrate",
      tier: 3,
    },
    barbarian_frenzy: {
      id: "barbarian_frenzy",
      title: "Frenzy",
      cost: 2,
      target: "enemy",
      text: "Deal 10 damage. Deal 9 damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 10 },
        { kind: "damage", value: 9 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_frenzy",
      tier: 3,
    },
    barbarian_battle_orders: {
      id: "barbarian_battle_orders",
      title: "Battle Orders",
      cost: 2,
      target: "none",
      text: "Heal 6. Apply 1 Slow to all enemies. You and your mercenary gain 22 Guard. Mercenary next attack +16. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_party", value: 22 },
        { kind: "buff_mercenary_next_attack", value: 16 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["protection", "support", "salvage", "scaling", "disruption"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_battle_orders",
      tier: 3,
    },
    barbarian_steel_skin: {
      id: "barbarian_steel_skin",
      title: "Steel Skin",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 16 Guard. Heal 6. Draw 1 card.",
      effects: [
        { kind: "gain_guard_party", value: 16 },
        { kind: "heal_hero", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage", "support", "scaling", "protection"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_steel_skin",
      tier: 3,
    },
    barbarian_leap_attack: {
      id: "barbarian_leap_attack",
      title: "Leap Attack",
      cost: 2,
      target: "none",
      text: "Deal 9 damage to all enemies.",
      effects: [{ kind: "damage_all", value: 9 }],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_leap_attack",
      tier: 3,
    },

    // ── Tier 4 ──
    barbarian_whirlwind: {
      id: "barbarian_whirlwind",
      title: "Whirlwind",
      cost: 2,
      target: "none",
      text: "Heal 5. Deal 16 damage to all enemies. Apply 1 Slow to all enemies. Gain 12 Guard.",
      effects: [
        { kind: "heal_hero", value: 5 },
        { kind: "damage_all", value: 16 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_self", value: 12 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation", "disruption"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_whirlwind",
      tier: 4,
    },
    barbarian_berserk: {
      id: "barbarian_berserk",
      title: "Berserk",
      cost: 2,
      target: "enemy",
      text: "Deal 28 magic damage. Gain 16 Guard.",
      effects: [
        { kind: "damage", value: 28 },
        { kind: "gain_guard_self", value: 16 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_berserk",
      tier: 4,
    },
    barbarian_war_cry: {
      id: "barbarian_war_cry",
      title: "War Cry",
      cost: 2,
      target: "none",
      text: "Heal 6. Deal 14 damage to all enemies. Apply 1 Stun to all. You and your mercenary gain 22 Guard.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "damage_all", value: 14 },
        { kind: "apply_stun_all", value: 1 },
        { kind: "gain_guard_party", value: 22 },
      ],
      behaviorTags: ["disruption", "pressure", "protection", "payoff"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_war_cry",
      tier: 4,
    },
    barbarian_battle_instinct: {
      id: "barbarian_battle_instinct",
      title: "Battle Instinct",
      cost: 2,
      target: "enemy",
      text: "Deal 22 damage. Deal 8 damage to all enemies. Apply 1 Slow to all enemies. You and your mercenary gain 16 Guard. Mercenary next attack +14. Draw 1 card.",
      effects: [
        { kind: "damage", value: 22 },
        { kind: "damage_all", value: 8 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "gain_guard_party", value: 16 },
        { kind: "buff_mercenary_next_attack", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "mitigation", "disruption", "salvage", "payoff", "scaling", "protection"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "barbarian_battle_instinct",
      tier: 4,
    },
    barbarian_unyielding: {
      id: "barbarian_unyielding",
      title: "Unyielding",
      cost: 2,
      target: "none",
      text: "Apply 2 Slow to all enemies. You and your mercenary gain 24 Guard. Heal 10. Draw 1 card.",
      effects: [
        { kind: "apply_slow_all", value: 2 },
        { kind: "gain_guard_party", value: 24 },
        { kind: "heal_hero", value: 10 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "disruption", "salvage", "support", "scaling", "protection"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "barbarian_unyielding",
      tier: 4,
    },
  };

  const BARBARIAN_STARTER_DECK = [
    "barbarian_bash", "barbarian_bash",
    "barbarian_sword_mastery", "barbarian_sword_mastery",
    "barbarian_howl", "barbarian_howl",
    "barbarian_find_potion", "barbarian_find_potion",
    "rally_mercenary",
    "barbarian_natural_resistance",
    "barbarian_iron_skin",
    "barbarian_double_swing",
    "barbarian_stun",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const BARBARIAN_REWARD_POOL = {
    early: getCardIdsByTier(BARBARIAN_CARDS, 2),
    mid: getCardIdsByTier(BARBARIAN_CARDS, 3),
    late: getCardIdsByTier(BARBARIAN_CARDS, 4),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.barbarian = {
    cards: BARBARIAN_CARDS,
    starterDeck: BARBARIAN_STARTER_DECK,
    rewardPool: BARBARIAN_REWARD_POOL,
  };
})();
