(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  // ── Necromancer Cards ─────────────────────────────────────────────────
  // Bone Burst: magic-damage projectiles + bone defense — pierce payoff + CE chain
  // Curse Control: debuff stacking — amplify all damage sources + crowd manipulation
  // Summon Swarm: undead army — persistent board + corpse-to-value conversion
  // Class Glue: multi-lane utility
  // Hybrid Bridges: cross-lane support cards

  const NECROMANCER_CARDS: Record<string, ClassCardDefinition> = {

    // ════════════════════════════════════════════════════════════════════
    // TIER 1 — Starter shell and identity cards
    // ════════════════════════════════════════════════════════════════════

    // ── Bone Burst ──
    necromancer_teeth: {
      id: "necromancer_teeth",
      title: "Teeth",
      cost: 1,
      target: "enemy",
      text: "Deal 7 magic damage.",
      effects: [{ kind: "damage", value: 7 }],
      behaviorTags: ["pressure", "payoff"],
      roleTag: "payoff",
      rewardRole: "foundation",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_teeth",
      tier: 1,
    },
    necromancer_bone_armor: {
      id: "necromancer_bone_armor",
      title: "Bone Armor",
      cost: 1,
      target: "none",
      text: "Gain 16 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 16 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_bone_armor",
      tier: 1,
    },
    necromancer_bone_wall: {
      id: "necromancer_bone_wall",
      title: "Bone Wall",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage.",
      effects: [
        { kind: "damage", value: 4 },
      ],
      behaviorTags: ["pressure", "mitigation", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_bone_wall",
      tier: 1,
    },

    // ── Curse Control ──
    necromancer_amplify_damage: {
      id: "necromancer_amplify_damage",
      title: "Amplify Damage",
      cost: 1,
      target: "enemy",
      text: "Deal 2 damage. Your mercenary deals +8 to this target. Draw 1 card.",
      effects: [
        { kind: "damage", value: 2 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "support", "salvage", "conversion"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_amplify_damage",
      tier: 1,
    },

    // ── Summon Swarm ──
    necromancer_raise_skeleton: {
      id: "necromancer_raise_skeleton",
      title: "Raise Skeleton",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. Summon Skeleton. Each ally phase it slashes for 7.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "summon_minion", value: 7, minionId: "necromancer_skeleton" },
      ],
      behaviorTags: ["setup", "scaling", "pressure"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_raise_skeleton",
      tier: 1,
    },

    // ── Class Glue ──
    necromancer_life_tap: {
      id: "necromancer_life_tap",
      title: "Life Tap",
      cost: 1,
      target: "none",
      text: "Heal 4. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["salvage", "mitigation", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_life_tap",
      tier: 1,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 2 — Early reward pool: lane formation begins
    // ════════════════════════════════════════════════════════════════════

    // ── Bone Burst ──
    necromancer_poison_dagger: {
      id: "necromancer_poison_dagger",
      title: "Poison Dagger",
      cost: 1,
      target: "enemy",
      text: "Deal 6 poison damage. Apply 4 Poison. Draw 1 card.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "apply_poison", value: 4 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_poison_dagger",
      tier: 2,
    },
    necromancer_corpse_explosion: {
      id: "necromancer_corpse_explosion",
      title: "Corpse Explosion",
      cost: 2,
      target: "none",
      text: "Deal 6 fire damage to all enemies. If an enemy died last turn, deal 6 more to all.",
      effects: [
        { kind: "damage_all", value: 6 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_corpse_explosion",
      tier: 2,
    },
    necromancer_poison_explosion: {
      id: "necromancer_poison_explosion",
      title: "Poison Explosion",
      cost: 1,
      target: "none",
      text: "Deal 4 poison damage to all enemies. Apply 3 Poison to all.",
      effects: [
        { kind: "damage_all", value: 4 },
        { kind: "apply_poison_all", value: 3 },
      ],
      behaviorTags: ["pressure", "setup", "mitigation"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },

    // ── Curse Control ──
    necromancer_iron_maiden: {
      id: "necromancer_iron_maiden",
      title: "Iron Maiden",
      cost: 1,
      target: "enemy",
      text: "Deal 5 damage. Your mercenary deals +8 to this target.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
      ],
      behaviorTags: ["setup", "support", "conversion"],
      roleTag: "support",
      rewardRole: "tech",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_iron_maiden",
      tier: 2,
    },
    necromancer_weaken: {
      id: "necromancer_weaken",
      title: "Weaken",
      cost: 1,
      target: "none",
      text: "All enemies deal 3 less damage next turn. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "disruption", "salvage"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },
    necromancer_dim_vision: {
      id: "necromancer_dim_vision",
      title: "Dim Vision",
      cost: 1,
      target: "enemy",
      text: "The target deals 5 less damage next turn. Apply 1 Slow. Gain 6 Guard.",
      effects: [
        { kind: "apply_slow", value: 1 },
        { kind: "gain_guard_self", value: 14 },
      ],
      behaviorTags: ["disruption", "mitigation", "setup"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ── Summon Swarm ──
    necromancer_clay_golem: {
      id: "necromancer_clay_golem",
      title: "Clay Golem",
      cost: 1,
      target: "none",
      text: "Deal 4 damage to all enemies. Apply 1 Slow to all enemies. Summon Clay Golem. Each ally phase it hits for 7 and grants 6 Guard to the party.",
      effects: [
        { kind: "damage_all", value: 4 },
        { kind: "apply_slow_all", value: 1 },
        { kind: "summon_minion", value: 7, secondaryValue: 6, minionId: "necromancer_clay_golem" },
      ],
      behaviorTags: ["setup", "scaling", "protection", "mitigation", "disruption"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "necromancer_clay_golem",
      tier: 2,
    },
    necromancer_skeletal_mage: {
      id: "necromancer_skeletal_mage",
      title: "Skeletal Mage",
      cost: 1,
      target: "enemy",
      text: "Deal 5 poison damage. Apply 2 Poison to all enemies. Draw 1 card. Summon Skeletal Mage. Each ally phase it fires for 8 and applies 6 Poison.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "apply_poison_all", value: 2 },
        { kind: "summon_minion", value: 8, minionId: "necromancer_skeletal_mage" },
      ],
      behaviorTags: ["setup", "scaling", "pressure", "payoff", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["anti_summon", "anti_backline", "anti_fire_pressure", "telegraph_respect"],
      skillRef: "necromancer_skeletal_mage",
      tier: 2,
    },
    necromancer_skeleton_mastery: {
      id: "necromancer_skeleton_mastery",
      title: "Skeleton Mastery",
      cost: 1,
      target: "none",
      text: "Each of your summons deals 4 bonus damage on its next hit. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["scaling", "support", "salvage"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 2,
    },

    // ── Class Glue ──
    necromancer_dark_pact: {
      id: "necromancer_dark_pact",
      title: "Dark Pact",
      cost: 1,
      target: "none",
      text: "Lose 3 HP. Gain 10 Guard. Draw 2 cards.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 2 },
      ],
      behaviorTags: ["salvage", "mitigation", "conversion"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 2,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 3 — Mid reward pool: lane engines come online
    // ════════════════════════════════════════════════════════════════════

    // ── Bone Burst ──
    necromancer_bone_spear: {
      id: "necromancer_bone_spear",
      title: "Bone Spear",
      cost: 2,
      target: "enemy",
      text: "Deal 16 magic damage. If the target has Poison, deal 6 more.",
      effects: [{ kind: "damage", value: 16 }],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_bone_spear",
      tier: 3,
    },
    necromancer_bone_prison: {
      id: "necromancer_bone_prison",
      title: "Bone Prison",
      cost: 1,
      target: "enemy",
      text: "The target deals 6 less damage next turn. Apply 1 Slow. Gain 8 Guard. Your next bone card this turn deals +4 damage.",
      effects: [
        { kind: "apply_slow", value: 1 },
        { kind: "gain_guard_self", value: 14 },
      ],
      behaviorTags: ["setup", "disruption", "mitigation"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      counterTags: ["telegraph_respect", "anti_guard_break"],
      skillRef: "",
      tier: 3,
    },
    necromancer_bone_shrapnel: {
      id: "necromancer_bone_shrapnel",
      title: "Bone Shrapnel",
      cost: 2,
      target: "none",
      text: "Deal 10 magic damage to all enemies.",
      effects: [
        { kind: "damage_all", value: 10 },
      ],
      behaviorTags: ["pressure", "payoff", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Curse Control ──
    necromancer_decrepify: {
      id: "necromancer_decrepify",
      title: "Decrepify",
      cost: 1,
      target: "enemy",
      text: "Deal 11 damage. Your mercenary deals +14 to this target. Apply 1 Slow. Draw 1 card.",
      effects: [
        { kind: "damage", value: 11 },
        { kind: "mark_enemy_for_mercenary", value: 14 },
        { kind: "apply_slow", value: 1 },
      ],
      behaviorTags: ["setup", "support", "conversion", "disruption", "mitigation"],
      roleTag: "support",
      rewardRole: "tech",
      splashRole: "utility_splash_ok",
      skillRef: "necromancer_decrepify",
      tier: 3,
    },
    necromancer_terror: {
      id: "necromancer_terror",
      title: "Terror",
      cost: 1,
      target: "none",
      text: "All non-boss enemies deal 4 less damage next turn. Gain 7 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["disruption", "mitigation", "salvage"],
      roleTag: "answer",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_guard_break"],
      skillRef: "",
      tier: 3,
    },
    necromancer_lower_resist: {
      id: "necromancer_lower_resist",
      title: "Lower Resist",
      cost: 1,
      target: "enemy",
      text: "Your next 2 Poison or Burn applications against this target deal +3 each. Your mercenary deals +10 to this target. Draw 1 card.",
      effects: [
        { kind: "mark_enemy_for_mercenary", value: 10 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["setup", "conversion", "scaling"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    necromancer_confuse: {
      id: "necromancer_confuse",
      title: "Confuse",
      cost: 1,
      target: "enemy",
      text: "The target attacks a random enemy instead of you next turn. Gain 6 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["disruption", "tax", "salvage"],
      roleTag: "answer",
      rewardRole: "tech",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect"],
      skillRef: "",
      tier: 3,
    },

    // ── Summon Swarm ──
    necromancer_blood_golem: {
      id: "necromancer_blood_golem",
      title: "Blood Golem",
      cost: 2,
      target: "enemy",
      text: "Deal 7 damage. Draw 1 card. Summon Blood Golem. Each ally phase it hits for 8 and heals you 5.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "draw", value: 1 },
        { kind: "summon_minion", value: 8, secondaryValue: 6, minionId: "necromancer_blood_golem" },
      ],
      behaviorTags: ["setup", "scaling", "protection", "conversion", "mitigation", "salvage"],
      roleTag: "support",
      rewardRole: "support",
      splashRole: "primary_only",
      counterTags: ["anti_fire_pressure", "telegraph_respect"],
      skillRef: "necromancer_blood_golem",
      tier: 3,
    },
    necromancer_golem_mastery: {
      id: "necromancer_golem_mastery",
      title: "Golem Mastery",
      cost: 1,
      target: "none",
      text: "Reinforce all your summons by +2. If you control a golem, it gains +3 instead. Gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["scaling", "support", "salvage"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },
    necromancer_summon_resist: {
      id: "necromancer_summon_resist",
      title: "Summon Resist",
      cost: 1,
      target: "none",
      text: "All your summons gain +1 turn. You and your mercenary gain 8 Guard. Heal 4.",
      effects: [
        { kind: "gain_guard_party", value: 14 },
        { kind: "heal_hero", value: 6 },
      ],
      behaviorTags: ["protection", "support", "mitigation"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 3,
    },

    // ── Class Glue ──
    necromancer_bone_shield: {
      id: "necromancer_bone_shield",
      title: "Bone Shield",
      cost: 1,
      target: "none",
      text: "Gain 18 Guard. Heal 6. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 18 },
        { kind: "heal_hero", value: 6 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["mitigation", "protection"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_guard_break"],
      skillRef: "",
      tier: 3,
    },
    necromancer_soul_harvest: {
      id: "necromancer_soul_harvest",
      title: "Soul Harvest",
      cost: 1,
      target: "none",
      text: "Heal 6. Gain 6 Guard. If you control a summon, draw 1 card. If an enemy has Poison, heal 3 more.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 14 },
      ],
      behaviorTags: ["salvage", "mitigation", "conversion"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },

    // ── Hybrid Bridges ──
    necromancer_attract: {
      id: "necromancer_attract",
      title: "Attract",
      cost: 1,
      target: "enemy",
      text: "The target takes 4 more damage from summons and mercenary this turn. Apply 1 Slow. Gain 5 Guard.",
      effects: [
        { kind: "apply_slow", value: 1 },
        { kind: "gain_guard_self", value: 14 },
      ],
      behaviorTags: ["setup", "disruption", "support"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },
    necromancer_desecrate: {
      id: "necromancer_desecrate",
      title: "Desecrate",
      cost: 1,
      target: "none",
      text: "Deal 5 damage to all enemies. Apply 2 Poison to all. If you control a summon, apply 1 more Poison to all.",
      effects: [
        { kind: "damage_all", value: 5 },
        { kind: "apply_poison_all", value: 2 },
      ],
      behaviorTags: ["pressure", "setup", "scaling"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 3,
    },

    // ════════════════════════════════════════════════════════════════════
    // TIER 4 — Late reward pool: lane capstones and closers
    // ════════════════════════════════════════════════════════════════════

    // ── Bone Burst ──
    necromancer_bone_spirit: {
      id: "necromancer_bone_spirit",
      title: "Bone Spirit",
      cost: 2,
      target: "enemy",
      text: "Deal 24 magic damage. Draw 1 card.",
      effects: [
        { kind: "damage", value: 24 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["pressure", "payoff", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_bone_spirit",
      tier: 4,
    },
    necromancer_poison_nova: {
      id: "necromancer_poison_nova",
      title: "Poison Nova",
      cost: 2,
      target: "none",
      text: "Deal 8 poison damage to all enemies. Apply 5 Poison to all. If any enemy already has Poison, deal 4 more to it.",
      effects: [
        { kind: "damage_all", value: 8 },
        { kind: "apply_poison_all", value: 5 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_poison_nova",
      tier: 4,
    },
    necromancer_corpse_lance: {
      id: "necromancer_corpse_lance",
      title: "Corpse Lance",
      cost: 2,
      target: "enemy",
      text: "Deal 20 damage. If an enemy died last turn, deal 10 more and apply 3 Poison.",
      effects: [{ kind: "damage", value: 20 }],
      behaviorTags: ["pressure", "payoff", "conversion"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    necromancer_bone_plague: {
      id: "necromancer_bone_plague",
      title: "Bone Plague",
      cost: 1,
      target: "none",
      text: "This combat, your bone and poison cards deal +3 damage. Draw 2 cards. Exhaust.",
      effects: [{ kind: "draw", value: 2 }],
      behaviorTags: ["scaling", "setup", "salvage"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "necromancer_bone_plague",
      tier: 4,
    },

    // ── Curse Control ──
    necromancer_curse_mastery: {
      id: "necromancer_curse_mastery",
      title: "Curse Mastery",
      cost: 1,
      target: "none",
      text: "This combat, your curse cards apply +2 mercenary mark damage and draw 1 extra card. Draw 1 card. Exhaust.",
      effects: [{ kind: "draw", value: 1 }],
      behaviorTags: ["scaling", "setup"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      auraId: "necromancer_curse_mastery",
      tier: 4,
    },
    necromancer_mass_curse: {
      id: "necromancer_mass_curse",
      title: "Mass Curse",
      cost: 2,
      target: "none",
      text: "All enemies deal 5 less damage next turn. Your mercenary deals +12 to all enemies. Gain 8 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 22 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["disruption", "support", "conversion", "mitigation"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },

    // ── Summon Swarm ──
    necromancer_revive: {
      id: "necromancer_revive",
      title: "Revive",
      cost: 2,
      target: "enemy",
      text: "Deal 9 damage. Draw 1 card. Summon Revived Horror. Each ally phase it smashes for 13 and grants 6 Guard to the party.",
      effects: [
        { kind: "damage", value: 9 },
        { kind: "draw", value: 1 },
        { kind: "summon_minion", value: 13, minionId: "necromancer_revive" },
      ],
      behaviorTags: ["setup", "scaling", "payoff", "protection", "pressure", "salvage"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "necromancer_revive",
      tier: 4,
    },
    necromancer_iron_golem: {
      id: "necromancer_iron_golem",
      title: "Iron Golem",
      cost: 2,
      target: "none",
      text: "Gain 10 Guard. Summon Iron Golem. Each ally phase it strikes for 9, grants 6 Guard to the party, and applies 1 Slow.",
      effects: [
        { kind: "gain_guard_self", value: 22 },
        { kind: "summon_minion", value: 9, minionId: "necromancer_iron_golem" },
      ],
      behaviorTags: ["setup", "protection", "scaling", "disruption"],
      roleTag: "setup",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    necromancer_fire_golem: {
      id: "necromancer_fire_golem",
      title: "Fire Golem",
      cost: 2,
      target: "none",
      text: "Deal 8 fire damage to all enemies. Apply 3 Burn to all. Summon Fire Golem. Each ally phase it strikes for 8 and applies 3 Burn.",
      effects: [
        { kind: "damage_all", value: 8 },
        { kind: "apply_burn_all", value: 3 },
        { kind: "summon_minion", value: 8, minionId: "necromancer_fire_golem" },
      ],
      behaviorTags: ["setup", "pressure", "scaling", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },
    necromancer_army_of_dead: {
      id: "necromancer_army_of_dead",
      title: "Army of the Dead",
      cost: 2,
      target: "none",
      text: "Deal 5 damage to all enemies for each summon you control (max 4). Reinforce all your summons by +2.",
      effects: [
        { kind: "damage_all", value: 0 },
      ],
      behaviorTags: ["payoff", "scaling", "pressure"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "primary_only",
      skillRef: "",
      tier: 4,
    },

    // ── Class Glue ──
    necromancer_dark_ward: {
      id: "necromancer_dark_ward",
      title: "Dark Ward",
      cost: 1,
      target: "none",
      text: "Gain 14 Guard. Heal your mercenary 6. The next enemy attack against you or your mercenary this turn deals 6 less damage.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "heal_mercenary", value: 6 },
      ],
      behaviorTags: ["mitigation", "protection", "support"],
      roleTag: "answer",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      counterTags: ["telegraph_respect", "anti_fire_pressure"],
      skillRef: "",
      tier: 4,
    },
    necromancer_blood_ritual: {
      id: "necromancer_blood_ritual",
      title: "Blood Ritual",
      cost: 1,
      target: "none",
      text: "Lose 4 HP. Heal your mercenary 8. Gain 8 Guard. Draw 2 cards.",
      effects: [
        { kind: "heal_mercenary", value: 8 },
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 2 },
      ],
      behaviorTags: ["salvage", "conversion", "support"],
      roleTag: "salvage",
      rewardRole: "support",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },

    // ── Hybrid Bridges ──
    necromancer_corpse_harvest: {
      id: "necromancer_corpse_harvest",
      title: "Corpse Harvest",
      cost: 2,
      target: "none",
      text: "Deal 8 damage to all enemies. If an enemy died last turn, summon a Skeleton and heal 6.",
      effects: [{ kind: "damage_all", value: 8 }],
      behaviorTags: ["pressure", "conversion", "payoff"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    necromancer_plague_wind: {
      id: "necromancer_plague_wind",
      title: "Plague Wind",
      cost: 2,
      target: "none",
      text: "Deal 7 poison damage to all enemies. Apply 4 Poison to all. Your summons each deal 3 bonus damage on their next hit.",
      effects: [
        { kind: "damage_all", value: 7 },
        { kind: "apply_poison_all", value: 4 },
      ],
      behaviorTags: ["pressure", "setup", "scaling"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    necromancer_bone_offering: {
      id: "necromancer_bone_offering",
      title: "Bone Offering",
      cost: 1,
      target: "none",
      text: "Gain 8 Guard. If you control a summon, it deals 5 bonus damage and gains +1 turn. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 14 },
        { kind: "draw", value: 1 },
      ],
      behaviorTags: ["support", "scaling", "mitigation"],
      roleTag: "support",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
    necromancer_death_pact: {
      id: "necromancer_death_pact",
      title: "Death Pact",
      cost: 2,
      target: "enemy",
      text: "Deal 14 damage. Your mercenary deals +14 to this target. If the target dies this turn, heal 10 and gain 10 Guard.",
      effects: [
        { kind: "damage", value: 14 },
        { kind: "mark_enemy_for_mercenary", value: 14 },
      ],
      behaviorTags: ["pressure", "payoff", "conversion", "support"],
      roleTag: "payoff",
      rewardRole: "engine",
      splashRole: "utility_splash_ok",
      skillRef: "",
      tier: 4,
    },
  };

  const NECROMANCER_STARTER_DECK = [
    "necromancer_teeth",
    "necromancer_bone_wall",
    "necromancer_amplify_damage", "necromancer_amplify_damage",
    "necromancer_bone_armor", "necromancer_bone_armor",
    "necromancer_raise_skeleton", "necromancer_raise_skeleton",
    "rally_mercenary",
    "necromancer_life_tap", "necromancer_life_tap",
    "necromancer_skeletal_mage",
    "necromancer_clay_golem", "necromancer_clay_golem",
  ];

  function getCardIdsByTier(cards: Record<string, { id: string; tier: number }>, tier: number): string[] {
    return Object.values(cards)
      .filter((card) => card.tier === tier)
      .map((card) => card.id);
  }

  const NECROMANCER_REWARD_POOL = {
    early: [...new Set([
      ...getCardIdsByTier(NECROMANCER_CARDS, 2),
      "necromancer_raise_skeleton",
    ])],
    mid: getCardIdsByTier(NECROMANCER_CARDS, 3),
    late: getCardIdsByTier(NECROMANCER_CARDS, 4),
  };

  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING = runtimeWindow.__ROUGE_CLASS_CARDS_STAGING || {};
  runtimeWindow.__ROUGE_CLASS_CARDS_STAGING.necromancer = {
    cards: NECROMANCER_CARDS,
    starterDeck: NECROMANCER_STARTER_DECK,
    rewardPool: NECROMANCER_REWARD_POOL,
  };
})();
