(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;
  const registryWindow = runtimeWindow as Window & Record<string, unknown>;

  const ACT_ENCOUNTER_RECIPES = [
    {
      idSuffix: "opening_skirmish",
      bucket: "opening",
      title: { kind: "flavorLabel", labelKey: "openingLabel", suffix: "Skirmish" },
      description: { kind: "flavor", key: "openingDescription" },
      enemyVariants: [{ enemyRefs: ["raiderA", "raiderB", "supportA"] }],
    },
    {
      idSuffix: "opening_pressure",
      bucket: "opening",
      title: { kind: "flavorLabel", labelKey: "openingLabel", suffix: "Pressure Pack" },
      description: { kind: "flavorAppend", key: "openingDescription", suffix: "The ranged line forces tighter target priority." },
      enemyVariants: [{ enemyRefs: ["raiderA", "rangedA", "supportA"] }],
      modifiers: [{ kindKey: "BACKLINE_SCREEN", value: { kind: "act", min: 2 } }],
    },
    {
      idSuffix: "opening_horde",
      bucket: "opening",
      title: { kind: "flavorLabel", labelKey: "openingLabel", suffix: "Horde" },
      description: { kind: "flavorAppend", key: "openingDescription", suffix: "The pack density is higher, so area zones take more repeated clears." },
      enemyVariants: [{ enemyRefs: ["raiderA", "raiderB", "rangedA", "supportA"] }],
      modifiers: [{ kindKey: "VANGUARD_RUSH", value: 1 }],
    },
    {
      idSuffix: "opening_crossfire",
      bucket: "opening",
      title: { kind: "flavorLabel", labelKey: "openingLabel", suffix: "Crossfire" },
      description: { kind: "flavorAppend", key: "openingDescription", suffix: "This route angle leans on layered ranged fire and awkward target priority." },
      enemyVariants: [{ enemyRefs: ["rangedA", "rangedB", "raiderA"] }],
      modifiers: [{ kindKey: "CROSSFIRE_LANES", value: 1 }],
    },
    {
      idSuffix: "opening_screen",
      bucket: "opening",
      title: { kind: "flavorLabel", labelKey: "openingLabel", suffix: "Screen" },
      description: { kind: "flavorAppend", key: "openingDescription", suffix: "A tougher screen forces you through a guarded front before the backline breaks." },
      enemyVariants: [{ enemyRefs: ["supportA", "bruteA", "rangedB"] }],
      modifiers: [{ kindKey: "FORTIFIED_LINE", value: { kind: "act", min: 2 } }],
    },
    {
      idSuffix: "opening_raid",
      bucket: "opening",
      title: { kind: "flavorLabel", labelKey: "openingLabel", suffix: "Raid" },
      description: { kind: "flavorAppend", key: "openingDescription", suffix: "A larger raiding party mixes brute pressure with a live backline immediately." },
      enemyVariants: [{ enemyRefs: ["raiderA", "bruteA", "rangedA", "supportB"] }],
      modifiers: [{ kindKey: "AMBUSH_OPENING", value: 1 }],
    },
    {
      idSuffix: "opening_nest",
      bucket: "opening",
      title: { kind: "flavorLabel", labelKey: "openingLabel", suffix: "Sniper Nest" },
      description: { kind: "flavorAppend", key: "openingDescription", suffix: "Elevated lanes and clear sightlines turn the opener into a ranged damage check." },
      enemyVariants: [{ enemyRefs: ["rangedA", "rangedB", "raiderA"] }],
      modifiers: [{ kindKey: "SNIPER_NEST", value: { kind: "act", min: 2 } }],
    },
    {
      idSuffix: "branch_battle",
      bucket: "branchBattle",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Hold" },
      description: { kind: "flavor", key: "branchBattleDescription" },
      enemyVariants: [{ enemyRefs: ["bruteA", "rangedA", "supportA"] }],
      modifiers: [{ kindKey: "WAR_DRUMS", value: 1 }],
    },
    {
      idSuffix: "branch_ambush",
      bucket: "branchBattle",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Ambush" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "This branch leans harder on ranged pressure and guarded fronts." },
      enemyVariants: [
        { minAct: 3, enemyRefs: ["eliteB", "rangedA", "rangedB", "supportA"] },
        { enemyRefs: ["eliteB", "rangedA", "rangedB"] },
      ],
      modifiers: [
        { kindKey: "AMBUSH_OPENING", value: 1 },
        { kindKey: "BACKLINE_SCREEN", value: { kind: "act", min: 2 }, minAct: 2 },
        { kindKey: "SNIPER_NEST", value: { kind: "act", min: 2, max: 4 }, minAct: 4 },
      ],
    },
    {
      idSuffix: "branch_bulwark",
      bucket: "branchBattle",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Bulwark" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "Durable fronts and recovery support drag the branch into attrition." },
      enemyVariants: [
        { minAct: 3, enemyRefs: ["eliteA", "bruteA", "bruteB", "supportB"] },
        { enemyRefs: ["bruteA", "bruteB", "supportB"] },
      ],
      modifiers: [
        { kindKey: "TRIAGE_SCREEN", value: { kind: "act", min: 2, max: 4, offset: 1 } },
        { kindKey: "BOSS_ONSLAUGHT", value: 1 },
        { kindKey: "BOSS_SALVO", value: 1 },
        { kindKey: "FORTIFIED_LINE", value: { kind: "act", min: 2 }, minAct: 3 },
      ],
    },
    {
      idSuffix: "branch_counterpush",
      bucket: "branchBattle",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Counterpush" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "An elite support package turns the branch into a live counterattack." },
      enemyVariants: [
        { minAct: 2, enemyRefs: ["eliteC", "supportA", "raiderA", "rangedA"] },
        { enemyRefs: ["eliteC", "supportA", "raiderA"] },
      ],
      modifiers: [
        { kindKey: "TRIAGE_COMMAND", value: 1 },
        { kindKey: "BACKLINE_SCREEN", value: { kind: "act", min: 2 }, minAct: 3 },
      ],
    },
    {
      idSuffix: "branch_siege",
      bucket: "branchBattle",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Siege" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "A fourth elite package keeps the branch identity from collapsing into one repeated escort script." },
      enemyVariants: [
        { minAct: 3, enemyRefs: ["eliteD", "bruteA", "supportA", "rangedA"] },
        { enemyRefs: ["eliteD", "bruteA", "supportA"] },
      ],
      modifiers: [
        { kindKey: "FORTIFIED_LINE", value: { kind: "act", min: 3, offset: 1 } },
        { kindKey: "ESCORT_COMMAND", value: 1, minAct: 2 },
      ],
    },
    {
      idSuffix: "branch_breach",
      bucket: "branchBattle",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Breach" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "A drilled breach team opens on line-breaking charges instead of another slower front-line trade." },
      enemyVariants: [
        { minAct: 4, enemyRefs: ["eliteA", "eliteB", "bruteA", "supportA"] },
        { enemyRefs: ["eliteA", "bruteA", "bruteB", "supportA"] },
      ],
      modifiers: [
        { kindKey: "LINEBREAKER_CHARGE", value: { kind: "halfCeilAct", min: 1, max: 3 } },
        { kindKey: "ELITE_ONSLAUGHT", value: 1, minAct: 3 },
      ],
    },
    {
      idSuffix: "branch_miniboss",
      bucket: "branchMiniboss",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Champion" },
      description: { kind: "flavor", key: "branchMinibossDescription" },
      enemyVariants: [
        { minAct: 3, enemyRefs: ["eliteA", "eliteB", "supportB"] },
        { enemyRefs: ["eliteA", "supportB", "bruteA"] },
      ],
      modifiers: [
        { kindKey: "ELITE_ONSLAUGHT", value: 1, minAct: 2 },
        { kindKey: "ESCORT_BULWARK", value: { kind: "act", min: 2, offset: -1 }, minAct: 4 },
      ],
    },
    {
      idSuffix: "branch_retinue",
      bucket: "branchMiniboss",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Retinue" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "A second elite escort package keeps the branch from collapsing into one repeated script." },
      enemyVariants: [{ enemyRefs: ["eliteB", "eliteC", "bruteA", "supportA"] }],
      modifiers: [
        { kindKey: "ESCORT_BULWARK", value: { kind: "act", min: 4, offset: 1 } },
        { kindKey: "TRIAGE_SCREEN", value: { kind: "act", min: 2, max: 4 }, minAct: 2 },
        { kindKey: "ESCORT_COMMAND", value: 1, minAct: 3 },
        { kindKey: "FORTIFIED_LINE", value: { kind: "act", min: 2 }, minAct: 4 },
        { kindKey: "COURT_RESERVES", value: 1, minAct: 5 },
      ],
    },
    {
      idSuffix: "branch_sanctum",
      bucket: "branchMiniboss",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Sanctum" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "The sanctum package doubles down on elite layering and a live backline." },
      enemyVariants: [{ enemyRefs: ["eliteA", "eliteC", "supportA", "rangedA"] }],
      modifiers: [
        { kindKey: "ESCORT_BULWARK", value: { kind: "act", min: 3 } },
        { kindKey: "ESCORT_COMMAND", value: 1 },
        { kindKey: "TRIAGE_SCREEN", value: { kind: "act", min: 2, max: 4 }, minAct: 3 },
        { kindKey: "SNIPER_NEST", value: 1, minAct: 5 },
      ],
    },
    {
      idSuffix: "branch_warhost",
      bucket: "branchMiniboss",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "War Host" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "A larger war host pushes multiple elite identities into the same branch fight." },
      enemyVariants: [{ enemyRefs: ["eliteB", "eliteC", "eliteD", "bruteB"] }],
      modifiers: [
        { kindKey: "ESCORT_BULWARK", value: { kind: "act", min: 4, offset: 1 } },
        { kindKey: "ELITE_ONSLAUGHT", value: 1 },
        { kindKey: "WAR_DRUMS", value: 1, minAct: 3 },
        { kindKey: "PHALANX_MARCH", value: { kind: "act", min: 3 }, minAct: 4 },
      ],
    },
    {
      idSuffix: "branch_phalanx",
      bucket: "branchMiniboss",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Phalanx" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "A drilled elite front advances with brute escorts instead of leaning on another support pocket." },
      enemyVariants: [{ enemyRefs: ["eliteA", "bruteA", "bruteB", "supportA"] }],
      modifiers: [
        { kindKey: "PHALANX_MARCH", value: { kind: "act", min: 3 } },
        { kindKey: "FORTIFIED_LINE", value: { kind: "act", min: 2 }, minAct: 2 },
        { kindKey: "ELITE_ONSLAUGHT", value: 1, minAct: 4 },
      ],
    },
    {
      idSuffix: "branch_conclave",
      bucket: "branchMiniboss",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Conclave" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "A warding conclave opens on recovery rites and shield calls instead of another straight escort rush." },
      enemyVariants: [{ enemyRefs: ["eliteA", "supportA", "supportB", "rangedA"] }],
      modifiers: [
        { kindKey: "RITUAL_CADENCE", value: { kind: "halfCeilAct", min: 1, max: 3 } },
        { kindKey: "BACKLINE_SCREEN", value: { kind: "act", min: 2 }, minAct: 2 },
        { kindKey: "TRIAGE_SCREEN", value: { kind: "act", min: 2, max: 4 }, minAct: 3 },
      ],
    },
    {
      idSuffix: "branch_recovery",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Recovery Line" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "Route-side recovery efforts change the next branch fight into a screened counterline instead of the default patrol mix." },
      enemyVariants: [{ enemyRefs: ["eliteA", "rangedA", "supportB", "bruteA"] }],
      modifiers: [
        { kindKey: "BACKLINE_SCREEN", value: { kind: "act", min: 2 } },
        { kindKey: "TRIAGE_COMMAND", value: 1 },
        { kindKey: "ESCORT_COMMAND", value: 1, minAct: 3 },
      ],
    },
    {
      idSuffix: "branch_detour",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Detour Line" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "A hidden post-covenant detour turns the next branch into a screened supply run instead of a direct hold." },
      enemyVariants: [{ enemyRefs: ["supportA", "bruteA", "rangedA", "bruteB"] }],
      modifiers: [
        { kindKey: "FORTIFIED_LINE", value: { kind: "act", min: 3, offset: 1 } },
        { kindKey: "BACKLINE_SCREEN", value: { kind: "act", min: 2 } },
        { kindKey: "ESCORT_COMMAND", value: 1, minAct: 3 },
      ],
    },
    {
      idSuffix: "branch_detour_guided",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Guarded Detour" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "A guided sidepass from the detour lane turns the next branch into a guarded flank instead of another default counterline." },
      enemyVariants: [{ enemyRefs: ["eliteA", "supportA", "rangedA", "bruteA"] }],
      modifiers: [
        { kindKey: "FORTIFIED_LINE", value: { kind: "act", min: 2 } },
        { kindKey: "TRIAGE_SCREEN", value: { kind: "act", min: 2, max: 4, offset: 1 } },
        { kindKey: "COURT_RESERVES", value: 1, minAct: 4 },
      ],
    },
    {
      idSuffix: "branch_detour_signal",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Signal Detour" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "Earlier shrine signals carry through the full detour and turn the next branch into a screened beacon line instead of a plain convoy flank." },
      enemyVariants: [{ enemyRefs: ["rangedA", "rangedB", "supportA", "bruteA"] }],
      modifiers: [
        { kindKey: "BACKLINE_SCREEN", value: { kind: "act", min: 2 } },
        { kindKey: "SNIPER_NEST", value: { kind: "act", min: 2 } },
        { kindKey: "ESCORT_COMMAND", value: 1, minAct: 3 },
      ],
    },
    {
      idSuffix: "branch_detour_mobilized",
      title: { kind: "flavorLabel", labelKey: "branchBattleLabel", suffix: "Mobilized Detour" },
      description: { kind: "flavorAppend", key: "branchBattleDescription", suffix: "Earlier accord musters now carry through the full signaled detour and turn the next branch into a reserve-backed beacon line instead of a looser routed flank." },
      enemyVariants: [{ enemyRefs: ["eliteA", "rangedA", "rangedB", "supportA"] }],
      modifiers: [
        { kindKey: "BACKLINE_SCREEN", value: { kind: "act", min: 2 } },
        { kindKey: "SNIPER_NEST", value: { kind: "act", min: 2 } },
        { kindKey: "COURT_RESERVES", value: 1 },
        { kindKey: "TRIAGE_COMMAND", value: 1, minAct: 3 },
      ],
    },
    {
      idSuffix: "miniboss_accord",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Accord Host" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "A full accord lane turns the next elite branch into a coordinated host with scripted escort pressure." },
      enemyVariants: [{ enemyRefs: ["eliteA", "eliteC", "rangedA", "supportA"] }],
      modifiers: [
        { kindKey: "ESCORT_COMMAND", value: 1 },
        { kindKey: "ELITE_ONSLAUGHT", value: 1 },
        { kindKey: "ESCORT_BULWARK", value: { kind: "act", min: 2, offset: -1 }, minAct: 3 },
      ],
    },
    {
      idSuffix: "miniboss_escalation",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Escalation Host" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "A post-covenant escalation turns the next elite branch into a direct strike package instead of a steadier escort shell." },
      enemyVariants: [{ enemyRefs: ["eliteB", "eliteD", "bruteA", "supportA"] }],
      modifiers: [
        { kindKey: "LINEBREAKER_CHARGE", value: { kind: "halfCeilAct", min: 1, max: 3 } },
        { kindKey: "ELITE_ONSLAUGHT", value: 1 },
        { kindKey: "WAR_DRUMS", value: 1, minAct: 2 },
      ],
    },
    {
      idSuffix: "miniboss_escalation_breach",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Breach Host" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "A guided escalation breach turns the next elite branch into a drilled pressure push instead of the default accord host." },
      enemyVariants: [{ enemyRefs: ["eliteA", "eliteB", "bruteA", "rangedA"] }],
      modifiers: [
        { kindKey: "LINEBREAKER_CHARGE", value: { kind: "halfCeilAct", min: 1, max: 3 } },
        { kindKey: "WAR_DRUMS", value: 1 },
        { kindKey: "ELITE_ONSLAUGHT", value: 1, minAct: 3 },
      ],
    },
    {
      idSuffix: "miniboss_escalation_directed",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Directed Surge" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "Earlier crossroads guidance carries through the full escalation and turns the next elite branch into a routed strike package instead of a generic late surge." },
      enemyVariants: [{ enemyRefs: ["eliteA", "eliteD", "rangedA", "supportA"] }],
      modifiers: [
        { kindKey: "LINEBREAKER_CHARGE", value: { kind: "halfCeilAct", min: 1, max: 3 } },
        { kindKey: "ESCORT_COMMAND", value: 1 },
        { kindKey: "SNIPER_NEST", value: 1, minAct: 3 },
      ],
    },
    {
      idSuffix: "miniboss_escalation_mobilized",
      title: { kind: "flavorLabel", labelKey: "branchMinibossLabel", suffix: "Mobilized Surge" },
      description: { kind: "flavorAppend", key: "branchMinibossDescription", suffix: "Earlier accord musters now carry through the full directed escalation and turn the next elite branch into a reserve-backed strike package instead of a looser late surge." },
      enemyVariants: [{ enemyRefs: ["eliteA", "eliteD", "supportA", "supportB"] }],
      modifiers: [
        { kindKey: "LINEBREAKER_CHARGE", value: { kind: "halfCeilAct", min: 1, max: 3 } },
        { kindKey: "ESCORT_COMMAND", value: 1 },
        { kindKey: "COURT_RESERVES", value: 1 },
        { kindKey: "WAR_DRUMS", value: 1, minAct: 4 },
      ],
    },
    {
      idSuffix: "boss",
      bucket: "boss",
      title: { kind: "bossName" },
      description: { kind: "flavor", key: "bossDescription" },
      bossConfigKey: "bossBaseConfig",
    },
    {
      idSuffix: "boss_covenant",
      title: { kind: "flavorLabel", labelKey: "bossLabel", suffix: "Covenant" },
      description: { kind: "flavorAppend", key: "bossDescription", suffix: "A resolved covenant route turns the act boss into a coordinated closing court instead of the default escort line." },
      bossConfigKey: "covenantBossConfig",
    },
    {
      idSuffix: "boss_aftermath",
      title: { kind: "flavorLabel", labelKey: "bossLabel", suffix: "Aftermath" },
      description: { kind: "flavorAppend", key: "bossDescription", suffix: "A full post-covenant detour and escalation turns the boss into a harsher aftermath fight instead of the default closing court." },
      bossConfigKey: "aftermathBossConfig",
    },
    {
      idSuffix: "boss_aftermath_directed",
      title: { kind: "flavorLabel", labelKey: "bossLabel", suffix: "Directed Aftermath" },
      description: { kind: "flavorAppend", key: "bossDescription", suffix: "Earlier route guidance carries through the full aftermath and turns the boss into a directed closing court instead of a generic late-route collapse." },
      bossConfigKey: "aftermathBossConfig",
      modifierExtensions: [
        { kindKey: "ESCORT_BULWARK", value: 2, minAct: 4, maxAct: 4 },
        { kindKey: "ESCORT_COMMAND", value: 1, maxAct: 3 },
        { kindKey: "ESCORT_COMMAND", value: 1, minAct: 5 },
      ],
    },
    {
      idSuffix: "boss_aftermath_signaled",
      title: { kind: "flavorLabel", labelKey: "bossLabel", suffix: "Signaled Aftermath" },
      description: { kind: "flavorAppend", key: "bossDescription", suffix: "Earlier shrine signals and crossroads guidance both carry through the full aftermath and turn the boss into a fully signaled closing court instead of a looser routed collapse." },
      bossConfigKey: "aftermathBossConfig",
      modifierExtensions: [
        { kindKey: "COURT_RESERVES", value: 1, minAct: 4, maxAct: 4 },
        { kindKey: "TRIAGE_COMMAND", value: 1, minAct: 4, maxAct: 4 },
        { kindKey: "ESCORT_COMMAND", value: 1, maxAct: 3 },
        { kindKey: "ESCORT_COMMAND", value: 1, minAct: 5 },
        { kindKey: "TRIAGE_COMMAND", value: 1, maxAct: 3 },
        { kindKey: "TRIAGE_COMMAND", value: 1, minAct: 5 },
      ],
    },
    {
      idSuffix: "boss_aftermath_drilled",
      title: { kind: "flavorLabel", labelKey: "bossLabel", suffix: "Drilled Aftermath" },
      description: { kind: "flavorAppend", key: "bossDescription", suffix: "Earlier route drilling and an alternate crossroads court both carry through the full aftermath and harden the escort screen into a more martial closing court." },
      bossConfigKey: "drilledAftermathBossConfig",
    },
    {
      idSuffix: "boss_aftermath_mobilized",
      title: { kind: "flavorLabel", labelKey: "bossLabel", suffix: "Mobilized Aftermath" },
      description: { kind: "flavorAppend", key: "bossDescription", suffix: "Earlier accord musters, route drilling, and alternate crossroads pressure all carry through the full aftermath and mobilize the boss court into a reserve-backed closing assault." },
      bossConfigKey: "mobilizedAftermathBossConfig",
    },
    {
      idSuffix: "boss_aftermath_posted",
      title: { kind: "flavorLabel", labelKey: "bossLabel", suffix: "Posted Aftermath" },
      description: { kind: "flavorAppend", key: "bossDescription", suffix: "The alternate sidepass and breach route now settle behind bell or banner posts, turning the boss court into a steadier escort-led aftermath instead of the sharper convoy collapse." },
      bossConfigKey: "postedAftermathBossConfig",
    },
  ];

  registryWindow.__ROUGE_ENCOUNTER_REGISTRY_BUILDERS_RECIPES = {
    ACT_ENCOUNTER_RECIPES,
  };
})();
