(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  function routePerk(id: string, title: string, requiredFlagIds: string[], bonuses: Record<string, number> = {}) {
    return {
      id,
      title,
      requiredFlagIds: [...requiredFlagIds],
      ...bonuses,
    };
  }

  const hero = {
    id: "hero",
    name: "Wanderer",
    className: "Rogue",
    maxLife: 42,
    maxEnergy: 3,
    handSize: 5,
    potionHeal: 12,
  };

  const mercenaryCatalog = {
    rogue_scout: {
      id: "rogue_scout",
      name: "Rogue Scout",
      role: "Act I Hunter",
      maxLife: 28,
      attack: 5,
      behavior: "mark_hunter",
      passiveText: "Consumes hero marks for extra damage.",
      routePerks: [
        routePerk("forward_spotters", "Forward Spotters", ["rogue_route_forward_spotters"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
        }),
        routePerk("flank_trails", "Flank Trails", ["rogue_route_flank_trails"], {
          attackBonus: 1,
          behaviorBonus: 1,
          openingDraw: 1,
        }),
        routePerk("hidden_wayfinders", "Hidden Wayfinders", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroDamageBonusPerAct: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 1,
        }),
        routePerk("ridge_countermarch", "Ridge Countermarch", ["rogue_vigil_beacons", "rogue_crossroads_countermarch"], {
          attackBonus: 1,
          startGuard: 1,
          behaviorBonusPerAct: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 1,
        }),
        routePerk("hidden_reserve_network", "Hidden Reserve Network", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          openingDrawPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("ghost_relay", "Ghost Relay", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("last_wayfinders", "Last Wayfinders", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroDamageBonusPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("wayfinder_legacy", "Wayfinder Legacy", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_legacy_wayfinder_chain"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          openingDrawPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("chapel_reckoning", "Chapel Reckoning", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_reckoning_chapel_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("lantern_recovery", "Lantern Recovery", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_recovery_chapel_lanterns"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("cloister_accord", "Cloister Accord", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_accord_cloister_paths"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          openingDrawPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("wayfinder_covenant", "Wayfinder Covenant", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_covenant_wayfinder_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroDamageBonusPerAct: 1,
          scalingStartAct: 1,
        }),
      ],
    },
    desert_guard: {
      id: "desert_guard",
      name: "Desert Guard",
      role: "Act II Spearwall",
      maxLife: 34,
      attack: 4,
      behavior: "guard_after_attack",
      passiveText: "Gains Guard after attacking.",
      routePerks: [
        routePerk("spearwall_posts", "Spearwall Posts", ["sunwell_spearwall_posts"], {
          behaviorBonus: 1,
          startGuard: 2,
          startGuardPerAct: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("shield_train", "Shield Train", ["sunwell_shield_train"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
        }),
        routePerk("spearwall_pylons", "Spearwall Pylons", ["sunwell_welltrain", "sunwell_crossroads_spearwall_pylons"], {
          behaviorBonus: 1,
          startGuard: 1,
          startGuardPerAct: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("contract_guard_column", "Contract Guard Column", ["sunwell_welltrain", "sunwell_crossroads_contract_guard"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          scalingStartAct: 2,
        }),
        routePerk("reserve_lance_column", "Reserve Lance Column", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          scalingStartAct: 2,
        }),
        routePerk("relay_lance_dispatch", "Relay Lance Dispatch", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 2,
        }),
        routePerk("final_spearline", "Final Spearline", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroStartGuard: 1,
          startGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("legacy_spear_posts", "Legacy Spear Posts", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_legacy_last_spear_posts"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("spearline_reckoning", "Spearline Reckoning", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_reckoning_lance_wards"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          startGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("spearline_recovery", "Spearline Recovery", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_recovery_spearline_wards"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("reliquary_accord", "Reliquary Accord", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_accord_spear_posts"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          startGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("reliquary_covenant", "Reliquary Covenant", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_covenant_final_lance_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
      ],
    },
    iron_wolf: {
      id: "iron_wolf",
      name: "Iron Wolf",
      role: "Act III Spellblade",
      maxLife: 26,
      attack: 4,
      behavior: "burn_finisher",
      passiveText: "Deals extra damage to burning enemies.",
      routePerks: [
        routePerk("dock_wards", "Dock Wards", ["kurast_dock_wards_laced"], {
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
        }),
        routePerk("shadow_barges", "Shadow Barges", ["kurast_shadow_barges"], {
          attackBonus: 1,
          behaviorBonus: 1,
          openingDraw: 1,
        }),
        routePerk("shadow_pilots", "Shadow Pilots", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          scalingStartAct: 3,
        }),
        routePerk("night_berths", "Night Berths", ["jade_shrine_trade_winds", "kurast_crossroads_night_berths"], {
          behaviorBonus: 1,
          behaviorBonusPerAct: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("pilot_cache_network", "Pilot Cache Network", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches"], {
          attackBonus: 1,
          heroDamageBonus: 1,
          heroDamageBonusPerAct: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("harbor_ledger_chain", "Harbor Ledger Chain", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_harbor_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroDamageBonusPerAct: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("spellblade_wards", "Spellblade Wards", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroDamageBonusPerAct: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("final_spellward", "Final Spellward", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_legacy_last_spellward"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          heroDamageBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("harbor_reckoning", "Harbor Reckoning", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_reckoning_harbor_seals"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("spellward_recovery", "Spellward Recovery", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_recovery_spellward_bins"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          heroDamageBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("channel_accord", "Channel Accord", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_accord_channel_marks"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("spellward_covenant", "Spellward Covenant", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_covenant_spellward_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 3,
        }),
      ],
    },
    kurast_shadow: {
      id: "kurast_shadow",
      name: "Kurast Shadow",
      role: "Act III Cutthroat",
      maxLife: 27,
      attack: 5,
      behavior: "backline_hunter",
      passiveText: "Prioritizes support and ranged enemies and cuts them down harder.",
      routePerks: [
        routePerk("dock_wards", "Dock Wards", ["kurast_dock_wards_laced"], {
          attackBonus: 1,
          behaviorBonus: 1,
          openingDraw: 1,
        }),
        routePerk("shadow_barges", "Shadow Barges", ["kurast_shadow_barges"], {
          attackBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
        }),
        routePerk("shadow_pilots", "Shadow Pilots", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("night_berths", "Night Berths", ["jade_shrine_trade_winds", "kurast_crossroads_night_berths"], {
          attackBonus: 1,
          behaviorBonusPerAct: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          scalingStartAct: 3,
        }),
        routePerk("night_convoy_knives", "Night Convoy Knives", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_night_convoys"], {
          attackBonus: 1,
          behaviorBonus: 1,
          behaviorBonusPerAct: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("pilot_chain_knives", "Pilot Chain Knives", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain"], {
          attackBonus: 1,
          behaviorBonus: 1,
          behaviorBonusPerAct: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("shadow_ledgers", "Shadow Ledgers", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          attackBonusPerAct: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("ledger_knives", "Ledger Knives", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_legacy_harbor_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("pilot_reckoning", "Pilot Reckoning", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_reckoning_pilot_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("channel_recovery", "Channel Recovery", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_recovery_channel_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("pilot_accord", "Pilot Accord", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_accord_pilot_chain"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("channel_covenant", "Channel Covenant", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_covenant_spellward_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
      ],
    },
  };

  const { mercenaryCatalogLate } = runtimeWindow.__ROUGE_GC_MERCENARIES_LATE;
  Object.assign(mercenaryCatalog, mercenaryCatalogLate);

  runtimeWindow.__ROUGE_GC_MERCENARIES = {
    hero,
    mercenaryCatalog,
  };
})();
