(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  function routePerk(id, title, requiredFlagIds, bonuses = {}) {
    return {
      id,
      title,
      requiredFlagIds: [...requiredFlagIds],
      ...bonuses,
    };
  }

  const mercenaryCatalogLate = {
    templar_vanguard: {
      id: "templar_vanguard",
      name: "Templar Vanguard",
      role: "Act IV Bulwark",
      maxLife: 32,
      attack: 4,
      behavior: "guard_breaker",
      passiveText: "Prioritizes guarded targets, shatters their Guard, and strikes harder.",
      routePerks: [
        routePerk("phalanx_steps", "Phalanx Steps", ["hellforge_phalanx_steps_locked"], {
          behaviorBonus: 1,
          startGuard: 2,
          startGuardPerAct: 1,
          heroStartGuard: 2,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("hellward_screen", "Hellward Screen", ["hellforge_hellward_screen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
        }),
        routePerk("hellward_turn", "Hellward Turn", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          scalingStartAct: 4,
        }),
        routePerk("phalanx_reliefs", "Phalanx Reliefs", ["infernal_altar_cinder_screen", "hellforge_crossroads_phalanx_reliefs"], {
          behaviorBonus: 1,
          startGuard: 1,
          startGuardPerAct: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("relief_wall", "Relief Wall", ["infernal_altar_cinder_screen", "hellforge_crossroads_phalanx_reliefs", "hellforge_reserve_relief_wall"], {
          behaviorBonus: 1,
          startGuard: 1,
          startGuardPerAct: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("turning_relay", "Turning Relay", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          scalingStartAct: 4,
        }),
        routePerk("breachscreen", "Breachscreen", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroStartGuard: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("last_breachscreen", "Last Breachscreen", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_legacy_last_breachscreen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("sanctuary_reckoning", "Sanctuary Reckoning", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_reckoning_sanctuary_screens"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          startGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("hellward_recovery", "Hellward Recovery", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_recovery_hellward_screen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("hellward_accord", "Hellward Accord", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_accord_hellward_relief"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          startGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("breachscreen_covenant", "Breachscreen Covenant", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_covenant_breachscreen_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
      ],
    },
    harrogath_captain: {
      id: "harrogath_captain",
      name: "Harrogath Captain",
      role: "Act V Warleader",
      maxLife: 36,
      attack: 5,
      behavior: "boss_hunter",
      passiveText: "Prioritizes elite and boss enemies and deals extra damage to them.",
      routePerks: [
        routePerk("peak_guard", "Peak Guard", ["harrogath_peak_guard_drilled"], {
          attackBonus: 1,
          behaviorBonus: 2,
          startGuard: 2,
          heroStartGuard: 1,
        }),
        routePerk("summit_reserve", "Summit Reserve", ["harrogath_summit_reserve_marshaled"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 2,
          openingDraw: 1,
        }),
        routePerk("captains_switchbacks", "Captain's Switchbacks", ["ancients_way_watchfires", "harrogath_crossroads_switchbacks"], {
          attackBonus: 1,
          behaviorBonus: 1,
          attackBonusPerAct: 1,
          startGuard: 1,
          heroStartGuard: 1,
          scalingStartAct: 5,
        }),
        routePerk("summit_reserve_column", "Summit Reserve Column", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("last_column", "Last Column", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("switchback_relay", "Switchback Relay", ["ancients_way_watchfires", "harrogath_crossroads_switchbacks", "harrogath_reserve_switchback_guard", "harrogath_relay_switchback_line"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("ancients_guard", "Ancients Guard", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("legacy_guard_ranks", "Legacy Guard Ranks", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_legacy_last_guard_ranks"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("summit_reckoning", "Summit Reckoning", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_reckoning_oath_rations"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("banner_recovery", "Banner Recovery", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_recovery_guard_banners"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("ancients_accord", "Ancients Accord", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_accord_ancients_posts"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("ancients_covenant", "Ancients Covenant", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_covenant_ancients_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 5,
        }),
      ],
    },
    pandemonium_scout: {
      id: "pandemonium_scout",
      name: "Pandemonium Scout",
      role: "Act IV Interdictor",
      maxLife: 31,
      attack: 5,
      behavior: "wounded_hunter",
      passiveText: "Prioritizes wounded enemies and deals extra damage once they are faltering.",
      routePerks: [
        routePerk("phalanx_steps", "Phalanx Steps", ["hellforge_phalanx_steps_locked"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
        }),
        routePerk("hellward_screen", "Hellward Screen", ["hellforge_hellward_screen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          openingDraw: 1,
        }),
        routePerk("hellward_turn", "Hellward Turn", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn"], {
          attackBonus: 1,
          behaviorBonus: 1,
          behaviorBonusPerAct: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("phalanx_reliefs", "Phalanx Reliefs", ["infernal_altar_cinder_screen", "hellforge_crossroads_phalanx_reliefs"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("turning_reserve", "Turning Reserve", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("turning_pursuit", "Turning Pursuit", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("pandemonium_cuts", "Pandemonium Cuts", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("final_cutmarks", "Final Cutmarks", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_legacy_final_cutmarks"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("cutmark_reckoning", "Cutmark Reckoning", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_reckoning_furnace_cuts"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("sconce_recovery", "Sconce Recovery", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_recovery_sconce_paths"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("breach_accord", "Breach Accord", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_accord_breach_rivets"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("breach_covenant", "Breach Covenant", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_covenant_breachscreen_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 4,
        }),
      ],
    },
  };

  runtimeWindow.__ROUGE_GC_MERCENARIES_LATE = {
    mercenaryCatalogLate,
  };
})();
