/* eslint-disable max-lines */
(() => {
  function routePerk(id, title, requiredFlagIds, bonuses = {}) {
    return {
      id,
      title,
      requiredFlagIds: [...requiredFlagIds],
      ...bonuses,
    };
  }

  function consequenceRewardPackage(id, title, zoneRole, requiredFlagIds, grants, bonusLines = []) {
    return {
      id,
      title,
      zoneRole,
      requiredFlagIds: [...requiredFlagIds],
      grants: {
        gold: grants?.gold || 0,
        xp: grants?.xp || 0,
        potions: grants?.potions || 0,
      },
      bonusLines: Array.isArray(bonusLines) ? [...bonusLines] : [],
    };
  }

  const hero = {
    id: "hero",
    name: "Wanderer",
    className: "Rogue",
    maxLife: 42,
    maxEnergy: 3,
    handSize: 5,
    potionHeal: 12,
  };

  const mercenaryCatalog = {
    rogue_scout: {
      id: "rogue_scout",
      name: "Rogue Scout",
      role: "Act I Hunter",
      maxLife: 28,
      attack: 5,
      behavior: "mark_hunter",
      passiveText: "Consumes hero marks for extra damage.",
      routePerks: [
        routePerk("forward_spotters", "Forward Spotters", ["rogue_route_forward_spotters"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
        }),
        routePerk("flank_trails", "Flank Trails", ["rogue_route_flank_trails"], {
          attackBonus: 1,
          behaviorBonus: 1,
          openingDraw: 1,
        }),
        routePerk("hidden_wayfinders", "Hidden Wayfinders", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroDamageBonusPerAct: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 1,
        }),
        routePerk("ridge_countermarch", "Ridge Countermarch", ["rogue_vigil_beacons", "rogue_crossroads_countermarch"], {
          attackBonus: 1,
          startGuard: 1,
          behaviorBonusPerAct: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 1,
        }),
        routePerk("hidden_reserve_network", "Hidden Reserve Network", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          openingDrawPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("ghost_relay", "Ghost Relay", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("last_wayfinders", "Last Wayfinders", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroDamageBonusPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("wayfinder_legacy", "Wayfinder Legacy", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_legacy_wayfinder_chain"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          openingDrawPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("chapel_reckoning", "Chapel Reckoning", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_reckoning_chapel_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("lantern_recovery", "Lantern Recovery", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_recovery_chapel_lanterns"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("cloister_accord", "Cloister Accord", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_accord_cloister_paths"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          openingDrawPerAct: 1,
          scalingStartAct: 1,
        }),
        routePerk("wayfinder_covenant", "Wayfinder Covenant", ["rogue_vigil_beacons", "rogue_crossroads_hidden_wayfinders", "rogue_reserve_hidden_cache", "rogue_relay_hidden_chain", "rogue_culmination_last_wayfinders", "rogue_covenant_wayfinder_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroDamageBonusPerAct: 1,
          scalingStartAct: 1,
        }),
      ],
    },
    desert_guard: {
      id: "desert_guard",
      name: "Desert Guard",
      role: "Act II Spearwall",
      maxLife: 34,
      attack: 4,
      behavior: "guard_after_attack",
      passiveText: "Gains Guard after attacking.",
      routePerks: [
        routePerk("spearwall_posts", "Spearwall Posts", ["sunwell_spearwall_posts"], {
          behaviorBonus: 1,
          startGuard: 2,
          startGuardPerAct: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("shield_train", "Shield Train", ["sunwell_shield_train"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
        }),
        routePerk("spearwall_pylons", "Spearwall Pylons", ["sunwell_welltrain", "sunwell_crossroads_spearwall_pylons"], {
          behaviorBonus: 1,
          startGuard: 1,
          startGuardPerAct: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("contract_guard_column", "Contract Guard Column", ["sunwell_welltrain", "sunwell_crossroads_contract_guard"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          scalingStartAct: 2,
        }),
        routePerk("reserve_lance_column", "Reserve Lance Column", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          scalingStartAct: 2,
        }),
        routePerk("relay_lance_dispatch", "Relay Lance Dispatch", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 2,
        }),
        routePerk("final_spearline", "Final Spearline", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroStartGuard: 1,
          startGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("legacy_spear_posts", "Legacy Spear Posts", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_legacy_last_spear_posts"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("spearline_reckoning", "Spearline Reckoning", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_reckoning_lance_wards"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          startGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("spearline_recovery", "Spearline Recovery", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_recovery_spearline_wards"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("reliquary_accord", "Reliquary Accord", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_accord_spear_posts"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          startGuardPerAct: 1,
          scalingStartAct: 2,
        }),
        routePerk("reliquary_covenant", "Reliquary Covenant", ["sunwell_welltrain", "sunwell_crossroads_contract_guard", "sunwell_reserve_lances", "sunwell_relay_lance_dispatch", "sunwell_culmination_final_spearline", "sunwell_covenant_final_lance_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 2,
        }),
      ],
    },
    iron_wolf: {
      id: "iron_wolf",
      name: "Iron Wolf",
      role: "Act III Spellblade",
      maxLife: 26,
      attack: 4,
      behavior: "burn_finisher",
      passiveText: "Deals extra damage to burning enemies.",
      routePerks: [
        routePerk("dock_wards", "Dock Wards", ["kurast_dock_wards_laced"], {
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
        }),
        routePerk("shadow_barges", "Shadow Barges", ["kurast_shadow_barges"], {
          attackBonus: 1,
          behaviorBonus: 1,
          openingDraw: 1,
        }),
        routePerk("shadow_pilots", "Shadow Pilots", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          scalingStartAct: 3,
        }),
        routePerk("night_berths", "Night Berths", ["jade_shrine_trade_winds", "kurast_crossroads_night_berths"], {
          behaviorBonus: 1,
          behaviorBonusPerAct: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("pilot_cache_network", "Pilot Cache Network", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches"], {
          attackBonus: 1,
          heroDamageBonus: 1,
          heroDamageBonusPerAct: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("harbor_ledger_chain", "Harbor Ledger Chain", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_harbor_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroDamageBonusPerAct: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("spellblade_wards", "Spellblade Wards", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroDamageBonusPerAct: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("final_spellward", "Final Spellward", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_legacy_last_spellward"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          heroDamageBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("harbor_reckoning", "Harbor Reckoning", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_reckoning_harbor_seals"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("spellward_recovery", "Spellward Recovery", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_recovery_spellward_bins"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          heroDamageBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("channel_accord", "Channel Accord", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_accord_channel_marks"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("spellward_covenant", "Spellward Covenant", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_spellblade_wards", "kurast_covenant_spellward_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 3,
        }),
      ],
    },
    kurast_shadow: {
      id: "kurast_shadow",
      name: "Kurast Shadow",
      role: "Act III Cutthroat",
      maxLife: 27,
      attack: 5,
      behavior: "backline_hunter",
      passiveText: "Prioritizes support and ranged enemies and cuts them down harder.",
      routePerks: [
        routePerk("dock_wards", "Dock Wards", ["kurast_dock_wards_laced"], {
          attackBonus: 1,
          behaviorBonus: 1,
          openingDraw: 1,
        }),
        routePerk("shadow_barges", "Shadow Barges", ["kurast_shadow_barges"], {
          attackBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
        }),
        routePerk("shadow_pilots", "Shadow Pilots", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("night_berths", "Night Berths", ["jade_shrine_trade_winds", "kurast_crossroads_night_berths"], {
          attackBonus: 1,
          behaviorBonusPerAct: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          scalingStartAct: 3,
        }),
        routePerk("night_convoy_knives", "Night Convoy Knives", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_night_convoys"], {
          attackBonus: 1,
          behaviorBonus: 1,
          behaviorBonusPerAct: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("pilot_chain_knives", "Pilot Chain Knives", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain"], {
          attackBonus: 1,
          behaviorBonus: 1,
          behaviorBonusPerAct: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("shadow_ledgers", "Shadow Ledgers", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          attackBonusPerAct: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 3,
        }),
        routePerk("ledger_knives", "Ledger Knives", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_legacy_harbor_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("pilot_reckoning", "Pilot Reckoning", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_reckoning_pilot_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("channel_recovery", "Channel Recovery", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_recovery_channel_ledgers"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("pilot_accord", "Pilot Accord", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_accord_pilot_chain"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 3,
        }),
        routePerk("channel_covenant", "Channel Covenant", ["jade_shrine_trade_winds", "kurast_crossroads_shadow_pilots", "kurast_reserve_pilot_caches", "kurast_relay_pilot_chain", "kurast_culmination_shadow_ledgers", "kurast_covenant_spellward_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 3,
        }),
      ],
    },
    templar_vanguard: {
      id: "templar_vanguard",
      name: "Templar Vanguard",
      role: "Act IV Bulwark",
      maxLife: 32,
      attack: 4,
      behavior: "guard_breaker",
      passiveText: "Prioritizes guarded targets, shatters their Guard, and strikes harder.",
      routePerks: [
        routePerk("phalanx_steps", "Phalanx Steps", ["hellforge_phalanx_steps_locked"], {
          behaviorBonus: 1,
          startGuard: 2,
          startGuardPerAct: 1,
          heroStartGuard: 2,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("hellward_screen", "Hellward Screen", ["hellforge_hellward_screen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
        }),
        routePerk("hellward_turn", "Hellward Turn", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          scalingStartAct: 4,
        }),
        routePerk("phalanx_reliefs", "Phalanx Reliefs", ["infernal_altar_cinder_screen", "hellforge_crossroads_phalanx_reliefs"], {
          behaviorBonus: 1,
          startGuard: 1,
          startGuardPerAct: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("relief_wall", "Relief Wall", ["infernal_altar_cinder_screen", "hellforge_crossroads_phalanx_reliefs", "hellforge_reserve_relief_wall"], {
          behaviorBonus: 1,
          startGuard: 1,
          startGuardPerAct: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("turning_relay", "Turning Relay", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          scalingStartAct: 4,
        }),
        routePerk("breachscreen", "Breachscreen", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroStartGuard: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("last_breachscreen", "Last Breachscreen", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_legacy_last_breachscreen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("sanctuary_reckoning", "Sanctuary Reckoning", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_reckoning_sanctuary_screens"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          startGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("hellward_recovery", "Hellward Recovery", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_recovery_hellward_screen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("hellward_accord", "Hellward Accord", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_accord_hellward_relief"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          startGuardPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("breachscreen_covenant", "Breachscreen Covenant", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_breachscreen", "hellforge_covenant_breachscreen_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          heroStartGuardPerAct: 1,
          scalingStartAct: 4,
        }),
      ],
    },
    harrogath_captain: {
      id: "harrogath_captain",
      name: "Harrogath Captain",
      role: "Act V Warleader",
      maxLife: 36,
      attack: 5,
      behavior: "boss_hunter",
      passiveText: "Prioritizes elite and boss enemies and deals extra damage to them.",
      routePerks: [
        routePerk("peak_guard", "Peak Guard", ["harrogath_peak_guard_drilled"], {
          attackBonus: 1,
          behaviorBonus: 2,
          startGuard: 2,
          heroStartGuard: 1,
        }),
        routePerk("summit_reserve", "Summit Reserve", ["harrogath_summit_reserve_marshaled"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 2,
          openingDraw: 1,
        }),
        routePerk("captains_switchbacks", "Captain's Switchbacks", ["ancients_way_watchfires", "harrogath_crossroads_switchbacks"], {
          attackBonus: 1,
          behaviorBonus: 1,
          attackBonusPerAct: 1,
          startGuard: 1,
          heroStartGuard: 1,
          scalingStartAct: 5,
        }),
        routePerk("summit_reserve_column", "Summit Reserve Column", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("last_column", "Last Column", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("switchback_relay", "Switchback Relay", ["ancients_way_watchfires", "harrogath_crossroads_switchbacks", "harrogath_reserve_switchback_guard", "harrogath_relay_switchback_line"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("ancients_guard", "Ancients Guard", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("legacy_guard_ranks", "Legacy Guard Ranks", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_legacy_last_guard_ranks"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("summit_reckoning", "Summit Reckoning", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_reckoning_oath_rations"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("banner_recovery", "Banner Recovery", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_recovery_guard_banners"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("ancients_accord", "Ancients Accord", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_accord_ancients_posts"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 5,
        }),
        routePerk("ancients_covenant", "Ancients Covenant", ["ancients_way_watchfires", "harrogath_crossroads_summit_reserve", "harrogath_reserve_last_column", "harrogath_relay_last_column", "harrogath_culmination_ancients_guard", "harrogath_covenant_ancients_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 5,
        }),
      ],
    },
    pandemonium_scout: {
      id: "pandemonium_scout",
      name: "Pandemonium Scout",
      role: "Act IV Interdictor",
      maxLife: 31,
      attack: 5,
      behavior: "wounded_hunter",
      passiveText: "Prioritizes wounded enemies and deals extra damage once they are faltering.",
      routePerks: [
        routePerk("phalanx_steps", "Phalanx Steps", ["hellforge_phalanx_steps_locked"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
        }),
        routePerk("hellward_screen", "Hellward Screen", ["hellforge_hellward_screen"], {
          attackBonus: 1,
          behaviorBonus: 1,
          startGuard: 1,
          openingDraw: 1,
        }),
        routePerk("hellward_turn", "Hellward Turn", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn"], {
          attackBonus: 1,
          behaviorBonus: 1,
          behaviorBonusPerAct: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("phalanx_reliefs", "Phalanx Reliefs", ["infernal_altar_cinder_screen", "hellforge_crossroads_phalanx_reliefs"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          startGuard: 1,
          heroStartGuard: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("turning_reserve", "Turning Reserve", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("turning_pursuit", "Turning Pursuit", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("pandemonium_cuts", "Pandemonium Cuts", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts"], {
          attackBonus: 1,
          attackBonusPerAct: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          scalingStartAct: 4,
        }),
        routePerk("final_cutmarks", "Final Cutmarks", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_legacy_final_cutmarks"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("cutmark_reckoning", "Cutmark Reckoning", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_reckoning_furnace_cuts"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("sconce_recovery", "Sconce Recovery", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_recovery_sconce_paths"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("breach_accord", "Breach Accord", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_accord_breach_rivets"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          behaviorBonusPerAct: 1,
          scalingStartAct: 4,
        }),
        routePerk("breach_covenant", "Breach Covenant", ["infernal_altar_cinder_screen", "hellforge_crossroads_hellward_turn", "hellforge_reserve_turning_line", "hellforge_relay_turning_line", "hellforge_culmination_pandemonium_cuts", "hellforge_covenant_breachscreen_ledger"], {
          attackBonus: 1,
          behaviorBonus: 1,
          heroDamageBonus: 1,
          openingDraw: 1,
          attackBonusPerAct: 1,
          scalingStartAct: 4,
        }),
      ],
    },
  };

  const cardCatalog = {
    quick_slash: {
      id: "quick_slash",
      title: "Quick Slash",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage.",
      effects: [{ kind: "damage", value: 7 }],
    },
    shield_slam: {
      id: "shield_slam",
      title: "Shield Slam",
      cost: 1,
      target: "enemy",
      text: "Deal 5 damage. Gain 4 Guard.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "gain_guard_self", value: 4 },
      ],
    },
    focus_fire: {
      id: "focus_fire",
      title: "Focus Fire",
      cost: 1,
      target: "enemy",
      text: "Deal 4 damage. Your mercenary deals +4 to this target.",
      effects: [
        { kind: "damage", value: 4 },
        { kind: "mark_enemy_for_mercenary", value: 4 },
      ],
    },
    fire_bolt: {
      id: "fire_bolt",
      title: "Fire Bolt",
      cost: 1,
      target: "enemy",
      text: "Deal 5 damage. Apply 2 Burn.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "apply_burn", value: 2 },
      ],
    },
    battle_orders: {
      id: "battle_orders",
      title: "Battle Orders",
      cost: 2,
      target: "none",
      text: "You and your mercenary gain 6 Guard. Mercenary next attack +3.",
      effects: [
        { kind: "gain_guard_party", value: 6 },
        { kind: "buff_mercenary_next_attack", value: 3 },
      ],
    },
    multishot: {
      id: "multishot",
      title: "Multishot",
      cost: 2,
      target: "none",
      text: "Deal 4 damage to all enemies.",
      effects: [{ kind: "damage_all", value: 4 }],
    },
    rally_mercenary: {
      id: "rally_mercenary",
      title: "Rally Mercenary",
      cost: 1,
      target: "none",
      text: "Heal your mercenary 5. Draw 1 card.",
      effects: [
        { kind: "heal_mercenary", value: 5 },
        { kind: "draw", value: 1 },
      ],
    },
    second_wind: {
      id: "second_wind",
      title: "Second Wind",
      cost: 1,
      target: "none",
      text: "Heal 6. Gain 3 Guard.",
      effects: [
        { kind: "heal_hero", value: 6 },
        { kind: "gain_guard_self", value: 3 },
      ],
    },
    quick_slash_plus: {
      id: "quick_slash_plus",
      title: "Quick Slash+",
      cost: 1,
      target: "enemy",
      text: "Deal 10 damage.",
      effects: [{ kind: "damage", value: 10 }],
    },
    shield_slam_plus: {
      id: "shield_slam_plus",
      title: "Shield Slam+",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage. Gain 6 Guard.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "gain_guard_self", value: 6 },
      ],
    },
    focus_fire_plus: {
      id: "focus_fire_plus",
      title: "Focus Fire+",
      cost: 1,
      target: "enemy",
      text: "Deal 6 damage. Your mercenary deals +6 to this target.",
      effects: [
        { kind: "damage", value: 6 },
        { kind: "mark_enemy_for_mercenary", value: 6 },
      ],
    },
    fire_bolt_plus: {
      id: "fire_bolt_plus",
      title: "Fire Bolt+",
      cost: 1,
      target: "enemy",
      text: "Deal 7 damage. Apply 3 Burn.",
      effects: [
        { kind: "damage", value: 7 },
        { kind: "apply_burn", value: 3 },
      ],
    },
    battle_orders_plus: {
      id: "battle_orders_plus",
      title: "Battle Orders+",
      cost: 2,
      target: "none",
      text: "You and your mercenary gain 8 Guard. Mercenary next attack +4.",
      effects: [
        { kind: "gain_guard_party", value: 8 },
        { kind: "buff_mercenary_next_attack", value: 4 },
      ],
    },
    multishot_plus: {
      id: "multishot_plus",
      title: "Multishot+",
      cost: 2,
      target: "none",
      text: "Deal 6 damage to all enemies.",
      effects: [{ kind: "damage_all", value: 6 }],
    },
    rally_mercenary_plus: {
      id: "rally_mercenary_plus",
      title: "Rally Mercenary+",
      cost: 1,
      target: "none",
      text: "Heal your mercenary 8. Draw 1 card.",
      effects: [
        { kind: "heal_mercenary", value: 8 },
        { kind: "draw", value: 1 },
      ],
    },
    second_wind_plus: {
      id: "second_wind_plus",
      title: "Second Wind+",
      cost: 1,
      target: "none",
      text: "Heal 9. Gain 5 Guard.",
      effects: [
        { kind: "heal_hero", value: 9 },
        { kind: "gain_guard_self", value: 5 },
      ],
    },
    guard_stance: {
      id: "guard_stance",
      title: "Guard Stance",
      cost: 1,
      target: "none",
      text: "Gain 8 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_self", value: 8 },
        { kind: "draw", value: 1 },
      ],
    },
    sweeping_strike: {
      id: "sweeping_strike",
      title: "Sweeping Strike",
      cost: 2,
      target: "none",
      text: "Deal 6 damage to all enemies.",
      effects: [{ kind: "damage_all", value: 6 }],
    },
    execution_blow: {
      id: "execution_blow",
      title: "Execution Blow",
      cost: 2,
      target: "enemy",
      text: "Deal 12 damage.",
      effects: [{ kind: "damage", value: 12 }],
    },
    merciless_command: {
      id: "merciless_command",
      title: "Merciless Command",
      cost: 1,
      target: "enemy",
      text: "Deal 5 damage. Your mercenary deals +8 to this target.",
      effects: [
        { kind: "damage", value: 5 },
        { kind: "mark_enemy_for_mercenary", value: 8 },
      ],
    },
    volley_fire: {
      id: "volley_fire",
      title: "Volley Fire",
      cost: 2,
      target: "none",
      text: "Deal 5 damage to all enemies.",
      effects: [{ kind: "damage_all", value: 5 }],
    },
    ashen_orb: {
      id: "ashen_orb",
      title: "Ashen Orb",
      cost: 2,
      target: "enemy",
      text: "Deal 8 damage. Apply 3 Burn.",
      effects: [
        { kind: "damage", value: 8 },
        { kind: "apply_burn", value: 3 },
      ],
    },
    emberstorm: {
      id: "emberstorm",
      title: "Emberstorm",
      cost: 2,
      target: "none",
      text: "Deal 5 damage to all enemies. Draw 1 card.",
      effects: [
        { kind: "damage_all", value: 5 },
        { kind: "draw", value: 1 },
      ],
    },
    war_cry: {
      id: "war_cry",
      title: "War Cry",
      cost: 1,
      target: "none",
      text: "You and your mercenary gain 5 Guard. Draw 1 card.",
      effects: [
        { kind: "gain_guard_party", value: 5 },
        { kind: "draw", value: 1 },
      ],
    },
    triage: {
      id: "triage",
      title: "Triage",
      cost: 1,
      target: "none",
      text: "Heal 5. Heal your mercenary 5.",
      effects: [
        { kind: "heal_hero", value: 5 },
        { kind: "heal_mercenary", value: 5 },
      ],
    },
  };

  const starterDeck = [
    "quick_slash",
    "quick_slash",
    "quick_slash",
    "shield_slam",
    "shield_slam",
    "focus_fire",
    "focus_fire",
    "fire_bolt",
    "fire_bolt",
    "battle_orders",
    "multishot",
    "rally_mercenary",
    "second_wind",
  ];

  const starterDeckProfiles = {
    warrior: [
      "quick_slash",
      "quick_slash",
      "quick_slash",
      "shield_slam",
      "shield_slam",
      "shield_slam",
      "battle_orders",
      "battle_orders",
      "focus_fire",
      "multishot",
      "rally_mercenary",
      "second_wind",
      "second_wind",
    ],
    hunter: [
      "quick_slash",
      "quick_slash",
      "quick_slash",
      "focus_fire",
      "focus_fire",
      "focus_fire",
      "shield_slam",
      "fire_bolt",
      "multishot",
      "multishot",
      "rally_mercenary",
      "second_wind",
      "battle_orders",
    ],
    caster: [
      "quick_slash",
      "quick_slash",
      "shield_slam",
      "focus_fire",
      "fire_bolt",
      "fire_bolt",
      "fire_bolt",
      "multishot",
      "multishot",
      "rally_mercenary",
      "rally_mercenary",
      "second_wind",
      "battle_orders",
    ],
  };

  const classDeckProfiles = {
    amazon: "hunter",
    assassin: "hunter",
    barbarian: "warrior",
    druid: "warrior",
    necromancer: "caster",
    paladin: "warrior",
    sorceress: "caster",
  };

  const rewardPools = {
    profileCards: {
      warrior: [
        "guard_stance",
        "sweeping_strike",
        "execution_blow",
        "shield_slam_plus",
        "battle_orders_plus",
      ],
      hunter: [
        "merciless_command",
        "volley_fire",
        "quick_slash_plus",
        "focus_fire_plus",
        "triage",
      ],
      caster: [
        "ashen_orb",
        "emberstorm",
        "fire_bolt_plus",
        "second_wind_plus",
        "war_cry",
      ],
    },
    zoneRoleCards: {
      opening: [
        "guard_stance",
        "triage",
        "quick_slash_plus",
      ],
      branchBattle: [
        "sweeping_strike",
        "war_cry",
        "merciless_command",
      ],
      branchMiniboss: [
        "execution_blow",
        "ashen_orb",
        "battle_orders_plus",
      ],
      boss: [
        "multishot_plus",
        "battle_orders_plus",
        "second_wind_plus",
      ],
    },
    bossCards: [
      "execution_blow",
      "battle_orders_plus",
      "multishot_plus",
      "emberstorm",
      "rally_mercenary_plus",
    ],
  };

  const consequenceEncounterPackages = {
    1: [
      {
        id: "rogue_recovery_counterline",
        title: "Lantern Counterline",
        zoneRole: "branchBattle",
        requiredFlagIds: ["rogue_recovery_chapel_lanterns"],
        encounterId: "act_1_branch_recovery",
      },
      {
        id: "rogue_accord_cloister_host",
        title: "Cloister Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["rogue_accord_cloister_paths"],
        encounterId: "act_1_miniboss_accord",
      },
      {
        id: "rogue_covenant_catacomb_host",
        title: "Catacomb Covenant Host",
        zoneRole: "boss",
        requiredFlagIds: ["rogue_covenant_wayfinder_ledger"],
        encounterId: "act_1_boss_covenant",
      },
      {
        id: "rogue_detour_convoy_line",
        title: "Abbey Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["rogue_recovery_chapel_lanterns", "rogue_detour_hidden_convoy"],
        encounterId: "act_1_branch_detour",
      },
      {
        id: "rogue_detour_chapel_line",
        title: "Chapel Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["rogue_recovery_chapel_lanterns", "rogue_detour_chapel_sidepass"],
        encounterId: "act_1_branch_detour_guided",
      },
      {
        id: "rogue_detour_signal_line",
        title: "Signal Convoy Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["rogue_recovery_chapel_lanterns", "rogue_detour_hidden_convoy", "rogue_vigil_signal_lanterns"],
        encounterId: "act_1_branch_detour_signal",
      },
      {
        id: "rogue_escalation_catacomb_host",
        title: "Catacomb Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["rogue_reckoning_chapel_ledger", "rogue_escalation_catacomb_surge"],
        encounterId: "act_1_miniboss_escalation",
      },
      {
        id: "rogue_escalation_chapel_host",
        title: "Chapel Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["rogue_reckoning_chapel_ledger", "rogue_escalation_chapel_surge"],
        encounterId: "act_1_miniboss_escalation_breach",
      },
      {
        id: "rogue_escalation_wayfinder_host",
        title: "Wayfinder Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["rogue_reckoning_chapel_ledger", "rogue_escalation_catacomb_surge", "rogue_crossroads_hidden_wayfinders"],
        encounterId: "act_1_miniboss_escalation_directed",
      },
      {
        id: "rogue_aftermath_catacomb_host",
        title: "Catacomb Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["rogue_detour_hidden_convoy", "rogue_escalation_catacomb_surge", "rogue_covenant_wayfinder_ledger"],
        encounterId: "act_1_boss_aftermath",
      },
      {
        id: "rogue_aftermath_wayfinder_host",
        title: "Wayfinder Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["rogue_detour_hidden_convoy", "rogue_escalation_catacomb_surge", "rogue_covenant_wayfinder_ledger", "rogue_crossroads_hidden_wayfinders"],
        encounterId: "act_1_boss_aftermath_directed",
      },
      {
        id: "rogue_aftermath_signal_host",
        title: "Signal Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: [
          "rogue_detour_hidden_convoy",
          "rogue_escalation_catacomb_surge",
          "rogue_covenant_wayfinder_ledger",
          "rogue_crossroads_hidden_wayfinders",
          "rogue_vigil_signal_lanterns",
        ],
        encounterId: "act_1_boss_aftermath_signaled",
      },
      {
        id: "rogue_aftermath_vanguard_host",
        title: "Vanguard Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: [
          "rogue_detour_hidden_convoy",
          "rogue_escalation_catacomb_surge",
          "rogue_covenant_wayfinder_ledger",
          "rogue_crossroads_hidden_wayfinders",
          "rogue_route_vanguard",
          "rogue_vigil_signal_lanterns",
        ],
        encounterId: "act_1_boss_aftermath_drilled",
      },
    ],
    2: [
      {
        id: "sunwell_recovery_ward_line",
        title: "Ward Line Recovery",
        zoneRole: "branchBattle",
        requiredFlagIds: ["sunwell_recovery_spearline_wards"],
        encounterId: "act_2_branch_recovery",
      },
      {
        id: "sunwell_accord_reliquary_host",
        title: "Reliquary Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["sunwell_accord_spear_posts"],
        encounterId: "act_2_miniboss_accord",
      },
      {
        id: "sunwell_covenant_chamber_host",
        title: "Reliquary Covenant Chamber",
        zoneRole: "boss",
        requiredFlagIds: ["sunwell_covenant_final_lance_ledger"],
        encounterId: "act_2_boss_covenant",
      },
      {
        id: "sunwell_detour_caravan_line",
        title: "Reliquary Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["sunwell_recovery_spearline_wards", "sunwell_detour_hidden_caravan"],
        encounterId: "act_2_branch_detour",
      },
      {
        id: "sunwell_detour_ward_line",
        title: "Warded Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["sunwell_recovery_spearline_wards", "sunwell_detour_warded_sidepass"],
        encounterId: "act_2_branch_detour_guided",
      },
      {
        id: "sunwell_detour_beacon_line",
        title: "Beacon Caravan Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["sunwell_recovery_spearline_wards", "sunwell_detour_hidden_caravan", "sunwell_water_beacons_aligned"],
        encounterId: "act_2_branch_detour_signal",
      },
      {
        id: "sunwell_escalation_chamber_host",
        title: "Chamber Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["sunwell_reckoning_lance_wards", "sunwell_escalation_chamber_surge"],
        encounterId: "act_2_miniboss_escalation",
      },
      {
        id: "sunwell_escalation_lance_host",
        title: "Lance Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["sunwell_reckoning_lance_wards", "sunwell_escalation_lance_breach"],
        encounterId: "act_2_miniboss_escalation_breach",
      },
      {
        id: "sunwell_escalation_contract_host",
        title: "Contract Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["sunwell_reckoning_lance_wards", "sunwell_escalation_chamber_surge", "sunwell_crossroads_contract_guard"],
        encounterId: "act_2_miniboss_escalation_directed",
      },
      {
        id: "sunwell_aftermath_chamber_host",
        title: "Reliquary Aftermath Chamber",
        zoneRole: "boss",
        requiredFlagIds: ["sunwell_detour_hidden_caravan", "sunwell_escalation_chamber_surge", "sunwell_covenant_final_lance_ledger"],
        encounterId: "act_2_boss_aftermath",
      },
      {
        id: "sunwell_aftermath_lance_host",
        title: "Directed Lance Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["sunwell_detour_hidden_caravan", "sunwell_escalation_chamber_surge", "sunwell_covenant_final_lance_ledger", "sunwell_crossroads_contract_guard"],
        encounterId: "act_2_boss_aftermath_directed",
      },
      {
        id: "sunwell_aftermath_beacon_host",
        title: "Beacon Aftermath Chamber",
        zoneRole: "boss",
        requiredFlagIds: [
          "sunwell_detour_hidden_caravan",
          "sunwell_escalation_chamber_surge",
          "sunwell_covenant_final_lance_ledger",
          "sunwell_crossroads_contract_guard",
          "sunwell_water_beacons_aligned",
        ],
        encounterId: "act_2_boss_aftermath_signaled",
      },
      {
        id: "sunwell_aftermath_pylon_host",
        title: "Pylon Aftermath Chamber",
        zoneRole: "boss",
        requiredFlagIds: [
          "sunwell_detour_hidden_caravan",
          "sunwell_escalation_chamber_surge",
          "sunwell_covenant_final_lance_ledger",
          "sunwell_crossroads_spearwall_pylons",
          "sunwell_shield_train",
        ],
        encounterId: "act_2_boss_aftermath_drilled",
      },
    ],
    3: [
      {
        id: "kurast_recovery_spellward_line",
        title: "Spellward Recovery Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["kurast_recovery_spellward_bins"],
        encounterId: "act_3_branch_recovery",
      },
      {
        id: "kurast_accord_channel_host",
        title: "Channel Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["kurast_accord_channel_marks"],
        encounterId: "act_3_miniboss_accord",
      },
      {
        id: "kurast_covenant_durance_host",
        title: "Harbor Covenant Court",
        zoneRole: "boss",
        requiredFlagIds: ["kurast_covenant_spellward_ledger"],
        encounterId: "act_3_boss_covenant",
      },
      {
        id: "kurast_detour_fleet_line",
        title: "Harbor Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["kurast_recovery_spellward_bins", "kurast_detour_hidden_fleet"],
        encounterId: "act_3_branch_detour",
      },
      {
        id: "kurast_detour_spellward_line",
        title: "Spellward Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["kurast_recovery_spellward_bins", "kurast_detour_spellward_sidepass"],
        encounterId: "act_3_branch_detour_guided",
      },
      {
        id: "kurast_detour_freeport_line",
        title: "Freeport Beacon Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["kurast_recovery_spellward_bins", "kurast_detour_hidden_fleet", "jade_supply_marks_floated"],
        encounterId: "act_3_branch_detour_signal",
      },
      {
        id: "kurast_escalation_durance_host",
        title: "Durance Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["kurast_reckoning_harbor_seals", "kurast_escalation_durance_surge"],
        encounterId: "act_3_miniboss_escalation",
      },
      {
        id: "kurast_escalation_harbor_host",
        title: "Harbor Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["kurast_reckoning_harbor_seals", "kurast_escalation_harbor_push"],
        encounterId: "act_3_miniboss_escalation_breach",
      },
      {
        id: "kurast_escalation_pilot_host",
        title: "Pilot Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["kurast_reckoning_harbor_seals", "kurast_escalation_durance_surge", "kurast_crossroads_shadow_pilots"],
        encounterId: "act_3_miniboss_escalation_directed",
      },
      {
        id: "kurast_aftermath_durance_host",
        title: "Harbor Aftermath Court",
        zoneRole: "boss",
        requiredFlagIds: ["kurast_detour_hidden_fleet", "kurast_escalation_durance_surge", "kurast_covenant_spellward_ledger"],
        encounterId: "act_3_boss_aftermath",
      },
      {
        id: "kurast_aftermath_spellward_host",
        title: "Directed Harbor Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["kurast_detour_hidden_fleet", "kurast_escalation_durance_surge", "kurast_covenant_spellward_ledger", "kurast_crossroads_shadow_pilots"],
        encounterId: "act_3_boss_aftermath_directed",
      },
      {
        id: "kurast_aftermath_beacon_host",
        title: "Signaled Harbor Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "kurast_detour_hidden_fleet",
          "kurast_escalation_durance_surge",
          "kurast_covenant_spellward_ledger",
          "kurast_crossroads_shadow_pilots",
          "jade_supply_marks_floated",
        ],
        encounterId: "act_3_boss_aftermath_signaled",
      },
      {
        id: "kurast_aftermath_berth_host",
        title: "Night Berth Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "kurast_detour_hidden_fleet",
          "kurast_escalation_durance_surge",
          "kurast_covenant_spellward_ledger",
          "kurast_crossroads_night_berths",
          "kurast_shadow_barges",
        ],
        encounterId: "act_3_boss_aftermath_drilled",
      },
    ],
    4: [
      {
        id: "hellforge_recovery_hellward_line",
        title: "Hellward Recovery Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["hellforge_recovery_hellward_screen"],
        encounterId: "act_4_branch_recovery",
      },
      {
        id: "hellforge_accord_breach_host",
        title: "Breach Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["hellforge_accord_breach_rivets"],
        encounterId: "act_4_miniboss_accord",
      },
      {
        id: "hellforge_covenant_sanctuary_host",
        title: "Sanctuary Covenant Host",
        zoneRole: "boss",
        requiredFlagIds: ["hellforge_covenant_breachscreen_ledger"],
        encounterId: "act_4_boss_covenant",
      },
      {
        id: "hellforge_detour_relief_line",
        title: "Sanctuary Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["hellforge_recovery_hellward_screen", "hellforge_detour_hidden_relief"],
        encounterId: "act_4_branch_detour",
      },
      {
        id: "hellforge_detour_hellward_line",
        title: "Hellward Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["hellforge_recovery_hellward_screen", "hellforge_detour_hellward_sidepass"],
        encounterId: "act_4_branch_detour_guided",
      },
      {
        id: "hellforge_detour_cinder_line",
        title: "Cinder Signal Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["hellforge_recovery_hellward_screen", "hellforge_detour_hidden_relief", "infernal_forge_gates_chained"],
        encounterId: "act_4_branch_detour_signal",
      },
      {
        id: "hellforge_escalation_sanctuary_host",
        title: "Sanctuary Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_surge"],
        encounterId: "act_4_miniboss_escalation",
      },
      {
        id: "hellforge_escalation_hellward_host",
        title: "Hellward Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_screen"],
        encounterId: "act_4_miniboss_escalation_breach",
      },
      {
        id: "hellforge_escalation_turn_host",
        title: "Hellward Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_surge", "hellforge_crossroads_hellward_turn"],
        encounterId: "act_4_miniboss_escalation_directed",
      },
      {
        id: "hellforge_aftermath_sanctuary_host",
        title: "Sanctuary Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["hellforge_detour_hidden_relief", "hellforge_escalation_sanctuary_surge", "hellforge_covenant_breachscreen_ledger"],
        encounterId: "act_4_boss_aftermath",
      },
      {
        id: "hellforge_aftermath_breachscreen_host",
        title: "Directed Sanctuary Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["hellforge_detour_hidden_relief", "hellforge_escalation_sanctuary_surge", "hellforge_covenant_breachscreen_ledger", "hellforge_crossroads_hellward_turn"],
        encounterId: "act_4_boss_aftermath_directed",
      },
      {
        id: "hellforge_aftermath_cinder_host",
        title: "Signaled Sanctuary Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "hellforge_detour_hidden_relief",
          "hellforge_escalation_sanctuary_surge",
          "hellforge_covenant_breachscreen_ledger",
          "hellforge_crossroads_hellward_turn",
          "infernal_forge_gates_chained",
        ],
        encounterId: "act_4_boss_aftermath_signaled",
      },
      {
        id: "hellforge_aftermath_relief_host",
        title: "Phalanx Relief Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "hellforge_detour_hidden_relief",
          "hellforge_escalation_sanctuary_surge",
          "hellforge_covenant_breachscreen_ledger",
          "hellforge_crossroads_phalanx_reliefs",
          "hellforge_phalanx_steps_locked",
        ],
        encounterId: "act_4_boss_aftermath_drilled",
      },
    ],
    5: [
      {
        id: "harrogath_recovery_banner_line",
        title: "Banner Recovery Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["harrogath_recovery_guard_banners"],
        encounterId: "act_5_branch_recovery",
      },
      {
        id: "harrogath_accord_ancients_host",
        title: "Ancients Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["harrogath_accord_ancients_posts"],
        encounterId: "act_5_miniboss_accord",
      },
      {
        id: "harrogath_covenant_worldstone_host",
        title: "Summit Covenant Host",
        zoneRole: "boss",
        requiredFlagIds: ["harrogath_covenant_ancients_ledger"],
        encounterId: "act_5_boss_covenant",
      },
      {
        id: "harrogath_detour_sled_line",
        title: "Summit Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["harrogath_recovery_guard_banners", "harrogath_detour_hidden_sleds"],
        encounterId: "act_5_branch_detour",
      },
      {
        id: "harrogath_detour_banner_line",
        title: "Banner Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["harrogath_recovery_guard_banners", "harrogath_detour_banner_sidepass"],
        encounterId: "act_5_branch_detour_guided",
      },
      {
        id: "harrogath_detour_watchfire_line",
        title: "Watchfire Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["harrogath_recovery_guard_banners", "harrogath_detour_hidden_sleds", "ancients_watchfires_ringed"],
        encounterId: "act_5_branch_detour_signal",
      },
      {
        id: "harrogath_escalation_worldstone_host",
        title: "Worldstone Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["harrogath_reckoning_oath_rations", "harrogath_escalation_worldstone_surge"],
        encounterId: "act_5_miniboss_escalation",
      },
      {
        id: "harrogath_escalation_oath_host",
        title: "Oath Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["harrogath_reckoning_oath_rations", "harrogath_escalation_oath_surge"],
        encounterId: "act_5_miniboss_escalation_breach",
      },
      {
        id: "harrogath_escalation_reserve_host",
        title: "Reserve Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["harrogath_reckoning_oath_rations", "harrogath_escalation_worldstone_surge", "harrogath_crossroads_summit_reserve"],
        encounterId: "act_5_miniboss_escalation_directed",
      },
      {
        id: "harrogath_aftermath_worldstone_host",
        title: "Worldstone Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["harrogath_detour_hidden_sleds", "harrogath_escalation_worldstone_surge", "harrogath_covenant_ancients_ledger"],
        encounterId: "act_5_boss_aftermath",
      },
      {
        id: "harrogath_aftermath_ancients_host",
        title: "Directed Summit Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["harrogath_detour_hidden_sleds", "harrogath_escalation_worldstone_surge", "harrogath_covenant_ancients_ledger", "harrogath_crossroads_summit_reserve"],
        encounterId: "act_5_boss_aftermath_directed",
      },
      {
        id: "harrogath_aftermath_watchfire_host",
        title: "Signaled Summit Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "harrogath_detour_hidden_sleds",
          "harrogath_escalation_worldstone_surge",
          "harrogath_covenant_ancients_ledger",
          "harrogath_crossroads_summit_reserve",
          "ancients_watchfires_ringed",
        ],
        encounterId: "act_5_boss_aftermath_signaled",
      },
      {
        id: "harrogath_aftermath_switchback_host",
        title: "Switchback Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "harrogath_detour_hidden_sleds",
          "harrogath_escalation_worldstone_surge",
          "harrogath_covenant_ancients_ledger",
          "harrogath_crossroads_switchbacks",
          "harrogath_peak_guard_drilled",
        ],
        encounterId: "act_5_boss_aftermath_drilled",
      },
    ],
  };

  const consequenceRewardPackages = {
    1: [
      consequenceRewardPackage(
        "rogue_recovery_lantern_dividend",
        "Lantern Dividend",
        "branchBattle",
        ["rogue_recovery_chapel_lanterns"],
        { gold: 6, xp: 4, potions: 1 },
        ["Recovery stores from the chapel lantern line reach the next battle payout."]
      ),
      consequenceRewardPackage(
        "rogue_accord_cloister_dividend",
        "Cloister Dividend",
        "branchMiniboss",
        ["rogue_accord_cloister_paths"],
        { gold: 8, xp: 4, potions: 1 },
        ["The cloister accord turns the next miniboss clear into a richer contract payout."]
      ),
      consequenceRewardPackage(
        "rogue_covenant_wayfinder_dividend",
        "Wayfinder Dividend",
        "boss",
        ["rogue_covenant_wayfinder_ledger"],
        { gold: 12, xp: 8, potions: 1 },
        ["The wayfinder covenant turns the act boss reward into a true late-route settlement."]
      ),
      consequenceRewardPackage(
        "rogue_detour_convoy_dividend",
        "Abbey Convoy Dividend",
        "branchBattle",
        ["rogue_recovery_chapel_lanterns", "rogue_detour_hidden_convoy"],
        { gold: 10, xp: 5, potions: 1 },
        ["The hidden abbey convoy turns the next branch clear into a safer but richer monastery payout."]
      ),
      consequenceRewardPackage(
        "rogue_detour_chapel_dividend",
        "Chapel Sidepass Dividend",
        "branchBattle",
        ["rogue_recovery_chapel_lanterns", "rogue_detour_chapel_sidepass"],
        { gold: 8, xp: 5, potions: 1 },
        ["The chapel sidepass turns the next branch into a guided monastery payout instead of stopping at the recovery screen."]
      ),
      consequenceRewardPackage(
        "rogue_detour_signal_dividend",
        "Signal Convoy Dividend",
        "branchBattle",
        ["rogue_recovery_chapel_lanterns", "rogue_detour_hidden_convoy", "rogue_vigil_signal_lanterns"],
        { gold: 12, xp: 6, potions: 1 },
        ["The earlier signal lanterns now carry through the full abbey convoy and turn the next branch into a sharper monastery payout."]
      ),
      consequenceRewardPackage(
        "rogue_escalation_catacomb_dividend",
        "Catacomb Surge Dividend",
        "branchMiniboss",
        ["rogue_reckoning_chapel_ledger", "rogue_escalation_catacomb_surge"],
        { gold: 10, xp: 6, potions: 1 },
        ["The catacomb surge turns the next elite branch into a harsher contract payout instead of the steadier accord."]
      ),
      consequenceRewardPackage(
        "rogue_escalation_chapel_dividend",
        "Chapel Breach Dividend",
        "branchMiniboss",
        ["rogue_reckoning_chapel_ledger", "rogue_escalation_chapel_surge"],
        { gold: 9, xp: 5, potions: 1 },
        ["The chapel surge turns the next elite branch into a sharper breach payout before the full catacomb rush exists."]
      ),
      consequenceRewardPackage(
        "rogue_escalation_wayfinder_dividend",
        "Wayfinder Surge Dividend",
        "branchMiniboss",
        ["rogue_reckoning_chapel_ledger", "rogue_escalation_catacomb_surge", "rogue_crossroads_hidden_wayfinders"],
        { gold: 12, xp: 7, potions: 1 },
        ["The earlier hidden wayfinders now route the full catacomb surge into a more directed elite payout."]
      ),
      consequenceRewardPackage(
        "rogue_aftermath_catacomb_dividend",
        "Catacomb Aftermath Dividend",
        "boss",
        ["rogue_detour_hidden_convoy", "rogue_escalation_catacomb_surge", "rogue_covenant_wayfinder_ledger"],
        { gold: 16, xp: 10, potions: 1 },
        ["Detour, escalation, and covenant now settle together at the act boss instead of stopping at the first covenant close."]
      ),
      consequenceRewardPackage(
        "rogue_aftermath_wayfinder_dividend",
        "Wayfinder Aftermath Dividend",
        "boss",
        ["rogue_detour_hidden_convoy", "rogue_escalation_catacomb_surge", "rogue_covenant_wayfinder_ledger", "rogue_crossroads_hidden_wayfinders"],
        { gold: 18, xp: 11, potions: 1 },
        ["The earlier hidden wayfinders now steer the full catacomb aftermath into a more directed late-route boss settlement."]
      ),
      consequenceRewardPackage(
        "rogue_aftermath_signal_dividend",
        "Signal Aftermath Dividend",
        "boss",
        [
          "rogue_detour_hidden_convoy",
          "rogue_escalation_catacomb_surge",
          "rogue_covenant_wayfinder_ledger",
          "rogue_crossroads_hidden_wayfinders",
          "rogue_vigil_signal_lanterns",
        ],
        { gold: 20, xp: 12, potions: 1 },
        ["The shrine signal line and hidden wayfinders now settle the full catacomb aftermath into the sharpest rogue boss payout."]
      ),
      consequenceRewardPackage(
        "rogue_aftermath_vanguard_dividend",
        "Vanguard Aftermath Dividend",
        "boss",
        [
          "rogue_detour_hidden_convoy",
          "rogue_escalation_catacomb_surge",
          "rogue_covenant_wayfinder_ledger",
          "rogue_crossroads_hidden_wayfinders",
          "rogue_route_vanguard",
          "rogue_vigil_signal_lanterns",
        ],
        { gold: 19, xp: 12, potions: 1 },
        ["The armed vanguard, hidden wayfinders, and signal lanterns now settle the full catacomb aftermath into a drilled rogue boss payout."]
      ),
    ],
    2: [
      consequenceRewardPackage(
        "sunwell_recovery_ward_dividend",
        "Ward Dividend",
        "branchBattle",
        ["sunwell_recovery_spearline_wards"],
        { gold: 8, xp: 4, potions: 1 },
        ["Recovered spearline wards widen the next battle payout and refill the march."]
      ),
      consequenceRewardPackage(
        "sunwell_accord_reliquary_dividend",
        "Reliquary Dividend",
        "branchMiniboss",
        ["sunwell_accord_spear_posts"],
        { gold: 10, xp: 5, potions: 1 },
        ["The reliquary accord pays out directly when the next miniboss line breaks."]
      ),
      consequenceRewardPackage(
        "sunwell_covenant_lance_dividend",
        "Lance Dividend",
        "boss",
        ["sunwell_covenant_final_lance_ledger"],
        { gold: 14, xp: 8, potions: 1 },
        ["Your final lance covenant settles at the chamber doors with a stronger boss reward."]
      ),
      consequenceRewardPackage(
        "sunwell_detour_caravan_dividend",
        "Hidden Caravan Dividend",
        "branchBattle",
        ["sunwell_recovery_spearline_wards", "sunwell_detour_hidden_caravan"],
        { gold: 12, xp: 5, potions: 1 },
        ["The hidden reliquary caravan widens the next desert branch payout instead of leaving the detour as route text only."]
      ),
      consequenceRewardPackage(
        "sunwell_detour_ward_dividend",
        "Warded Sidepass Dividend",
        "branchBattle",
        ["sunwell_recovery_spearline_wards", "sunwell_detour_warded_sidepass"],
        { gold: 10, xp: 5, potions: 1 },
        ["The warded sidepass turns the next desert branch into a guided reliquary payout instead of stopping at the recovery wards."]
      ),
      consequenceRewardPackage(
        "sunwell_detour_beacon_dividend",
        "Beacon Caravan Dividend",
        "branchBattle",
        ["sunwell_recovery_spearline_wards", "sunwell_detour_hidden_caravan", "sunwell_water_beacons_aligned"],
        { gold: 14, xp: 6, potions: 1 },
        ["Aligned water beacons now carry through the hidden caravan and turn the next desert branch into a sharper reliquary payout."]
      ),
      consequenceRewardPackage(
        "sunwell_escalation_chamber_dividend",
        "Chamber Surge Dividend",
        "branchMiniboss",
        ["sunwell_reckoning_lance_wards", "sunwell_escalation_chamber_surge"],
        { gold: 12, xp: 6, potions: 1 },
        ["The chamber surge pays out directly when the next elite line is forced open."]
      ),
      consequenceRewardPackage(
        "sunwell_escalation_lance_dividend",
        "Lance Breach Dividend",
        "branchMiniboss",
        ["sunwell_reckoning_lance_wards", "sunwell_escalation_lance_breach"],
        { gold: 11, xp: 6, potions: 1 },
        ["The lance breach turns the next elite line into a sharper tomb payout before the full chamber surge lands."]
      ),
      consequenceRewardPackage(
        "sunwell_escalation_contract_dividend",
        "Contract Surge Dividend",
        "branchMiniboss",
        ["sunwell_reckoning_lance_wards", "sunwell_escalation_chamber_surge", "sunwell_crossroads_contract_guard"],
        { gold: 14, xp: 7, potions: 1 },
        ["The earlier contract guard now routes the full chamber surge into a more disciplined elite payout."]
      ),
      consequenceRewardPackage(
        "sunwell_aftermath_chamber_dividend",
        "Reliquary Aftermath Dividend",
        "boss",
        ["sunwell_detour_hidden_caravan", "sunwell_escalation_chamber_surge", "sunwell_covenant_final_lance_ledger"],
        { gold: 18, xp: 10, potions: 1 },
        ["Detour, escalation, and covenant now settle together at the chamber doors as a deeper late-route boss payoff."]
      ),
      consequenceRewardPackage(
        "sunwell_aftermath_lance_dividend",
        "Lance Aftermath Dividend",
        "boss",
        ["sunwell_detour_hidden_caravan", "sunwell_escalation_chamber_surge", "sunwell_covenant_final_lance_ledger", "sunwell_crossroads_contract_guard"],
        { gold: 20, xp: 11, potions: 1 },
        ["The earlier contract guard line now steers the full chamber aftermath into a more directed reliquary settlement."]
      ),
      consequenceRewardPackage(
        "sunwell_aftermath_beacon_dividend",
        "Beacon Aftermath Dividend",
        "boss",
        [
          "sunwell_detour_hidden_caravan",
          "sunwell_escalation_chamber_surge",
          "sunwell_covenant_final_lance_ledger",
          "sunwell_crossroads_contract_guard",
          "sunwell_water_beacons_aligned",
        ],
        { gold: 22, xp: 12, potions: 1 },
        ["Aligned water beacons and the contract guard now settle the full chamber aftermath into the sharpest desert boss payout."]
      ),
      consequenceRewardPackage(
        "sunwell_aftermath_pylon_dividend",
        "Pylon Aftermath Dividend",
        "boss",
        [
          "sunwell_detour_hidden_caravan",
          "sunwell_escalation_chamber_surge",
          "sunwell_covenant_final_lance_ledger",
          "sunwell_crossroads_spearwall_pylons",
          "sunwell_shield_train",
        ],
        { gold: 21, xp: 12, potions: 1 },
        ["The shield train and spearwall pylons now settle the full chamber aftermath into a drilled desert boss payout."]
      ),
    ],
    3: [
      consequenceRewardPackage(
        "kurast_recovery_spellward_dividend",
        "Spellward Dividend",
        "branchBattle",
        ["kurast_recovery_spellward_bins"],
        { gold: 8, xp: 5, potions: 1 },
        ["Recovered spellward bins reach the next jungle battle as a routed cache."]
      ),
      consequenceRewardPackage(
        "kurast_accord_channel_dividend",
        "Channel Dividend",
        "branchMiniboss",
        ["kurast_accord_channel_marks"],
        { gold: 10, xp: 6, potions: 1 },
        ["The channel accord pays out when the next dockside host goes down."]
      ),
      consequenceRewardPackage(
        "kurast_covenant_harbor_dividend",
        "Harbor Dividend",
        "boss",
        ["kurast_covenant_spellward_ledger"],
        { gold: 16, xp: 9, potions: 1 },
        ["The harbor covenant settles in full when the durance boss court falls."]
      ),
      consequenceRewardPackage(
        "kurast_detour_fleet_dividend",
        "Hidden Fleet Dividend",
        "branchBattle",
        ["kurast_recovery_spellward_bins", "kurast_detour_hidden_fleet"],
        { gold: 12, xp: 6, potions: 1 },
        ["The hidden river fleet turns the next harbor branch into a richer routed cache instead of a flatter recovery bonus."]
      ),
      consequenceRewardPackage(
        "kurast_detour_spellward_dividend",
        "Spellward Sidepass Dividend",
        "branchBattle",
        ["kurast_recovery_spellward_bins", "kurast_detour_spellward_sidepass"],
        { gold: 10, xp: 6, potions: 1 },
        ["The spellward sidepass turns the next harbor branch into a guided routed cache before the full fleet detour comes online."]
      ),
      consequenceRewardPackage(
        "kurast_detour_freeport_dividend",
        "Freeport Beacon Dividend",
        "branchBattle",
        ["kurast_recovery_spellward_bins", "kurast_detour_hidden_fleet", "jade_supply_marks_floated"],
        { gold: 14, xp: 7, potions: 1 },
        ["Floated supply marks now carry through the hidden fleet and turn the next harbor branch into a sharper dockside payout."]
      ),
      consequenceRewardPackage(
        "kurast_escalation_durance_dividend",
        "Durance Surge Dividend",
        "branchMiniboss",
        ["kurast_reckoning_harbor_seals", "kurast_escalation_durance_surge"],
        { gold: 14, xp: 7, potions: 1 },
        ["The durance surge pays out when the next elite harbor host is broken by force."]
      ),
      consequenceRewardPackage(
        "kurast_escalation_harbor_dividend",
        "Harbor Breach Dividend",
        "branchMiniboss",
        ["kurast_reckoning_harbor_seals", "kurast_escalation_harbor_push"],
        { gold: 12, xp: 7, potions: 1 },
        ["The harbor push turns the next elite river host into a sharper breach payout before the full durance surge."]
      ),
      consequenceRewardPackage(
        "kurast_escalation_pilot_dividend",
        "Pilot Surge Dividend",
        "branchMiniboss",
        ["kurast_reckoning_harbor_seals", "kurast_escalation_durance_surge", "kurast_crossroads_shadow_pilots"],
        { gold: 16, xp: 8, potions: 1 },
        ["The earlier shadow pilots now route the full durance surge into a more directed elite payout."]
      ),
      consequenceRewardPackage(
        "kurast_aftermath_durance_dividend",
        "Harbor Aftermath Dividend",
        "boss",
        ["kurast_detour_hidden_fleet", "kurast_escalation_durance_surge", "kurast_covenant_spellward_ledger"],
        { gold: 20, xp: 11, potions: 1 },
        ["Detour, escalation, and covenant now settle together when the durance boss court falls."]
      ),
      consequenceRewardPackage(
        "kurast_aftermath_spellward_dividend",
        "Spellward Aftermath Dividend",
        "boss",
        ["kurast_detour_hidden_fleet", "kurast_escalation_durance_surge", "kurast_covenant_spellward_ledger", "kurast_crossroads_shadow_pilots"],
        { gold: 22, xp: 12, potions: 1 },
        ["The earlier shadow pilots now steer the full harbor aftermath into a more directed durance settlement."]
      ),
      consequenceRewardPackage(
        "kurast_aftermath_beacon_dividend",
        "Harbor Beacon Dividend",
        "boss",
        [
          "kurast_detour_hidden_fleet",
          "kurast_escalation_durance_surge",
          "kurast_covenant_spellward_ledger",
          "kurast_crossroads_shadow_pilots",
          "jade_supply_marks_floated",
        ],
        { gold: 24, xp: 13, potions: 1 },
        ["Floated supply marks and shadow pilots now settle the full harbor aftermath into the sharpest durance payout."]
      ),
      consequenceRewardPackage(
        "kurast_aftermath_berth_dividend",
        "Night Berth Dividend",
        "boss",
        [
          "kurast_detour_hidden_fleet",
          "kurast_escalation_durance_surge",
          "kurast_covenant_spellward_ledger",
          "kurast_crossroads_night_berths",
          "kurast_shadow_barges",
        ],
        { gold: 23, xp: 13, potions: 1 },
        ["Shadow barges and the night berths now settle the full harbor aftermath into a drilled durance payout."]
      ),
    ],
    4: [
      consequenceRewardPackage(
        "hellforge_recovery_hellward_dividend",
        "Hellward Dividend",
        "branchBattle",
        ["hellforge_recovery_hellward_screen"],
        { gold: 10, xp: 5, potions: 1 },
        ["Recovered hellward stores push a harsher branch reward out of the forge line."]
      ),
      consequenceRewardPackage(
        "hellforge_accord_breach_dividend",
        "Breach Dividend",
        "branchMiniboss",
        ["hellforge_accord_breach_rivets"],
        { gold: 12, xp: 6, potions: 1 },
        ["The breach accord pays out when the next hellgate host is brought down."]
      ),
      consequenceRewardPackage(
        "hellforge_covenant_sanctuary_dividend",
        "Sanctuary Dividend",
        "boss",
        ["hellforge_covenant_breachscreen_ledger"],
        { gold: 18, xp: 10, potions: 1 },
        ["The sanctuary covenant settles with a harder boss reward once the forge front holds."]
      ),
      consequenceRewardPackage(
        "hellforge_detour_relief_dividend",
        "Hidden Relief Dividend",
        "branchBattle",
        ["hellforge_recovery_hellward_screen", "hellforge_detour_hidden_relief"],
        { gold: 14, xp: 6, potions: 1 },
        ["The hidden relief line pushes a stronger sanctuary branch payout instead of stopping at the recovery screen."]
      ),
      consequenceRewardPackage(
        "hellforge_detour_hellward_dividend",
        "Hellward Sidepass Dividend",
        "branchBattle",
        ["hellforge_recovery_hellward_screen", "hellforge_detour_hellward_sidepass"],
        { gold: 12, xp: 6, potions: 1 },
        ["The hellward sidepass turns the next sanctuary branch into a guided infernal payout before the full relief line appears."]
      ),
      consequenceRewardPackage(
        "hellforge_detour_cinder_dividend",
        "Cinder Signal Dividend",
        "branchBattle",
        ["hellforge_recovery_hellward_screen", "hellforge_detour_hidden_relief", "infernal_forge_gates_chained"],
        { gold: 16, xp: 7, potions: 1 },
        ["Chained forge gates now carry through the hidden relief line and turn the next sanctuary branch into a sharper infernal payout."]
      ),
      consequenceRewardPackage(
        "hellforge_escalation_sanctuary_dividend",
        "Sanctuary Surge Dividend",
        "branchMiniboss",
        ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_surge"],
        { gold: 14, xp: 7, potions: 1 },
        ["The sanctuary surge pays out when the next elite infernal line is forced apart."]
      ),
      consequenceRewardPackage(
        "hellforge_escalation_hellward_dividend",
        "Hellward Breach Dividend",
        "branchMiniboss",
        ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_screen"],
        { gold: 13, xp: 7, potions: 1 },
        ["The hellward breach turns the next elite infernal host into a sharper payout before the full sanctuary surge."]
      ),
      consequenceRewardPackage(
        "hellforge_escalation_turn_dividend",
        "Hellward Surge Dividend",
        "branchMiniboss",
        ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_surge", "hellforge_crossroads_hellward_turn"],
        { gold: 16, xp: 8, potions: 1 },
        ["The earlier hellward turn now routes the full sanctuary surge into a more directed elite payout."]
      ),
      consequenceRewardPackage(
        "hellforge_aftermath_sanctuary_dividend",
        "Sanctuary Aftermath Dividend",
        "boss",
        ["hellforge_detour_hidden_relief", "hellforge_escalation_sanctuary_surge", "hellforge_covenant_breachscreen_ledger"],
        { gold: 22, xp: 12, potions: 1 },
        ["Detour, escalation, and covenant now settle together at Diablo instead of ending at the first covenant pass."]
      ),
      consequenceRewardPackage(
        "hellforge_aftermath_breachscreen_dividend",
        "Breachscreen Aftermath Dividend",
        "boss",
        ["hellforge_detour_hidden_relief", "hellforge_escalation_sanctuary_surge", "hellforge_covenant_breachscreen_ledger", "hellforge_crossroads_hellward_turn"],
        { gold: 24, xp: 13, potions: 1 },
        ["The earlier hellward turn now steers the full sanctuary aftermath into a more directed infernal settlement."]
      ),
      consequenceRewardPackage(
        "hellforge_aftermath_cinder_dividend",
        "Cinder Aftermath Dividend",
        "boss",
        [
          "hellforge_detour_hidden_relief",
          "hellforge_escalation_sanctuary_surge",
          "hellforge_covenant_breachscreen_ledger",
          "hellforge_crossroads_hellward_turn",
          "infernal_forge_gates_chained",
        ],
        { gold: 26, xp: 14, potions: 1 },
        ["Chained forge gates and the hellward turn now settle the full sanctuary aftermath into the sharpest infernal boss payout."]
      ),
      consequenceRewardPackage(
        "hellforge_aftermath_relief_dividend",
        "Phalanx Relief Dividend",
        "boss",
        [
          "hellforge_detour_hidden_relief",
          "hellforge_escalation_sanctuary_surge",
          "hellforge_covenant_breachscreen_ledger",
          "hellforge_crossroads_phalanx_reliefs",
          "hellforge_phalanx_steps_locked",
        ],
        { gold: 25, xp: 14, potions: 1 },
        ["Locked phalanx steps and paced reliefs now settle the full sanctuary aftermath into a drilled Diablo payout."]
      ),
    ],
    5: [
      consequenceRewardPackage(
        "harrogath_recovery_banner_dividend",
        "Banner Dividend",
        "branchBattle",
        ["harrogath_recovery_guard_banners"],
        { gold: 10, xp: 6, potions: 1 },
        ["Recovered guard banners steady the next summit battle and its payout."]
      ),
      consequenceRewardPackage(
        "harrogath_accord_ancients_dividend",
        "Ancients Dividend",
        "branchMiniboss",
        ["harrogath_accord_ancients_posts"],
        { gold: 12, xp: 7, potions: 1 },
        ["The ancients accord pays out when the next summit host breaks."]
      ),
      consequenceRewardPackage(
        "harrogath_covenant_summit_dividend",
        "Summit Dividend",
        "boss",
        ["harrogath_covenant_ancients_ledger"],
        { gold: 20, xp: 12, potions: 1 },
        ["The final summit covenant resolves into a richer boss settlement before Baal falls."]
      ),
      consequenceRewardPackage(
        "harrogath_detour_sled_dividend",
        "Hidden Sled Dividend",
        "branchBattle",
        ["harrogath_recovery_guard_banners", "harrogath_detour_hidden_sleds"],
        { gold: 14, xp: 7, potions: 1 },
        ["The hidden Ancients sled chain turns the next summit branch into a richer supply clear instead of a flat banner bonus."]
      ),
      consequenceRewardPackage(
        "harrogath_detour_banner_dividend",
        "Banner Sidepass Dividend",
        "branchBattle",
        ["harrogath_recovery_guard_banners", "harrogath_detour_banner_sidepass"],
        { gold: 12, xp: 7, potions: 1 },
        ["The banner sidepass turns the next summit branch into a guided supply payout before the full hidden sled chain arrives."]
      ),
      consequenceRewardPackage(
        "harrogath_detour_watchfire_dividend",
        "Watchfire Detour Dividend",
        "branchBattle",
        ["harrogath_recovery_guard_banners", "harrogath_detour_hidden_sleds", "ancients_watchfires_ringed"],
        { gold: 16, xp: 8, potions: 1 },
        ["Ringed watchfires now carry through the hidden sled chain and turn the next summit branch into a sharper mountain payout."]
      ),
      consequenceRewardPackage(
        "harrogath_escalation_worldstone_dividend",
        "Worldstone Surge Dividend",
        "branchMiniboss",
        ["harrogath_reckoning_oath_rations", "harrogath_escalation_worldstone_surge"],
        { gold: 16, xp: 8, potions: 1 },
        ["The Worldstone surge pays out when the next elite summit line breaks under full pressure."]
      ),
      consequenceRewardPackage(
        "harrogath_escalation_oath_dividend",
        "Oath Breach Dividend",
        "branchMiniboss",
        ["harrogath_reckoning_oath_rations", "harrogath_escalation_oath_surge"],
        { gold: 14, xp: 8, potions: 1 },
        ["The oath surge turns the next elite summit host into a sharper breach payout before the full Worldstone rush lands."]
      ),
      consequenceRewardPackage(
        "harrogath_escalation_reserve_dividend",
        "Reserve Surge Dividend",
        "branchMiniboss",
        ["harrogath_reckoning_oath_rations", "harrogath_escalation_worldstone_surge", "harrogath_crossroads_summit_reserve"],
        { gold: 18, xp: 9, potions: 1 },
        ["The earlier summit reserve now routes the full Worldstone surge into a more directed elite payout."]
      ),
      consequenceRewardPackage(
        "harrogath_aftermath_worldstone_dividend",
        "Worldstone Aftermath Dividend",
        "boss",
        ["harrogath_detour_hidden_sleds", "harrogath_escalation_worldstone_surge", "harrogath_covenant_ancients_ledger"],
        { gold: 24, xp: 12, potions: 1 },
        ["Detour, escalation, and covenant now settle together when Baal's host falls instead of stopping at the summit covenant."]
      ),
      consequenceRewardPackage(
        "harrogath_aftermath_ancients_dividend",
        "Ancients Aftermath Dividend",
        "boss",
        ["harrogath_detour_hidden_sleds", "harrogath_escalation_worldstone_surge", "harrogath_covenant_ancients_ledger", "harrogath_crossroads_summit_reserve"],
        { gold: 26, xp: 13, potions: 1 },
        ["The earlier summit reserve line now steers the full Worldstone aftermath into a more directed Ancients settlement."]
      ),
      consequenceRewardPackage(
        "harrogath_aftermath_watchfire_dividend",
        "Watchfire Aftermath Dividend",
        "boss",
        [
          "harrogath_detour_hidden_sleds",
          "harrogath_escalation_worldstone_surge",
          "harrogath_covenant_ancients_ledger",
          "harrogath_crossroads_summit_reserve",
          "ancients_watchfires_ringed",
        ],
        { gold: 28, xp: 14, potions: 1 },
        ["Ringed watchfires and the summit reserve now settle the full Worldstone aftermath into the sharpest mountain boss payout."]
      ),
      consequenceRewardPackage(
        "harrogath_aftermath_switchback_dividend",
        "Switchback Aftermath Dividend",
        "boss",
        [
          "harrogath_detour_hidden_sleds",
          "harrogath_escalation_worldstone_surge",
          "harrogath_covenant_ancients_ledger",
          "harrogath_crossroads_switchbacks",
          "harrogath_peak_guard_drilled",
        ],
        { gold: 27, xp: 15, potions: 1 },
        ["Peak guard drills and the captain's switchbacks now settle the full summit aftermath into a drilled Worldstone payout."]
      ),
    ],
  };

  const enemyCatalog = {
    fallen_cutthroat: {
      templateId: "fallen_cutthroat",
      name: "Fallen Cutthroat",
      maxLife: 16,
      intents: [
        { kind: "attack", label: "Rust Knife", value: 5, target: "hero" },
        { kind: "guard", label: "Scramble", value: 3 },
      ],
    },
    fallen_shaman: {
      templateId: "fallen_shaman",
      name: "Fallen Shaman",
      maxLife: 20,
      intents: [
        { kind: "heal_ally", label: "Dark Prayer", value: 5 },
        { kind: "attack", label: "Cinder Hex", value: 4, target: "hero" },
      ],
    },
    bone_archer: {
      templateId: "bone_archer",
      name: "Bone Archer",
      maxLife: 15,
      intents: [
        { kind: "attack", label: "Aimed Shot", value: 6, target: "lowest_life" },
        { kind: "attack", label: "Barbed Arrow", value: 4, target: "hero" },
      ],
    },
    grave_brute: {
      templateId: "grave_brute",
      name: "Grave Brute",
      maxLife: 28,
      intents: [
        { kind: "guard", label: "Brace", value: 4 },
        { kind: "attack", label: "Maul", value: 8, target: "hero" },
      ],
    },
    corrupted_knight: {
      templateId: "corrupted_knight",
      name: "Corrupted Knight",
      maxLife: 22,
      intents: [
        { kind: "attack", label: "Cleaving Blow", value: 7, target: "hero" },
        { kind: "attack", label: "Shield Rush", value: 5, target: "lowest_life" },
      ],
    },
  };

  const encounterCatalog = {
    blood_moor_raiders: {
      id: "blood_moor_raiders",
      name: "Blood Moor Raiders",
      description: "Two Fallen cutthroats rush the line while a shaman keeps them in the fight.",
      enemies: [
        { id: "fallen_a", templateId: "fallen_cutthroat" },
        { id: "fallen_b", templateId: "fallen_cutthroat" },
        { id: "shaman", templateId: "fallen_shaman" },
      ],
    },
    burial_grounds: {
      id: "burial_grounds",
      name: "Burial Grounds",
      description: "A brute anchors the front while skeletal ranged pressure picks at weak targets.",
      enemies: [
        { id: "grave_brute", templateId: "grave_brute" },
        { id: "bone_archer", templateId: "bone_archer" },
        { id: "fallen_shaman", templateId: "fallen_shaman" },
      ],
    },
    catacombs_gate: {
      id: "catacombs_gate",
      name: "Catacombs Gate",
      description: "A larger pack shows the target state: hero and mercenary against a mixed encounter group.",
      enemies: [
        { id: "knight", templateId: "corrupted_knight" },
        { id: "archer_a", templateId: "bone_archer" },
        { id: "archer_b", templateId: "bone_archer" },
        { id: "fallen", templateId: "fallen_cutthroat" },
      ],
    },
  };

  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  runtimeWindow.ROUGE_GAME_CONTENT = {
    hero,
    mercenaryCatalog,
    cardCatalog,
    starterDeck,
    starterDeckProfiles,
    classDeckProfiles,
    rewardPools,
    consequenceEncounterPackages,
    consequenceRewardPackages,
    enemyCatalog,
    encounterCatalog,
  };
})();
