(() => {
  const runtimeWindow = (typeof window === "object" ? window : ({} as Window)) as Window;

  const consequenceEncounterPackages = {
    1: [
      {
        id: "rogue_recovery_counterline",
        title: "Lantern Counterline",
        zoneRole: "branchBattle",
        requiredFlagIds: ["rogue_recovery_chapel_lanterns"],
        encounterId: "act_1_branch_recovery",
      },
      {
        id: "rogue_accord_cloister_host",
        title: "Cloister Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["rogue_accord_cloister_paths"],
        encounterId: "act_1_miniboss_accord",
      },
      {
        id: "rogue_covenant_catacomb_host",
        title: "Catacomb Covenant Host",
        zoneRole: "boss",
        requiredFlagIds: ["rogue_covenant_wayfinder_ledger"],
        encounterId: "act_1_boss_covenant",
      },
      {
        id: "rogue_detour_convoy_line",
        title: "Abbey Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["rogue_recovery_chapel_lanterns", "rogue_detour_hidden_convoy"],
        encounterId: "act_1_branch_detour",
      },
      {
        id: "rogue_detour_chapel_line",
        title: "Chapel Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["rogue_recovery_chapel_lanterns", "rogue_detour_chapel_sidepass"],
        encounterId: "act_1_branch_detour_guided",
      },
      {
        id: "rogue_detour_signal_line",
        title: "Signal Convoy Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["rogue_recovery_chapel_lanterns", "rogue_detour_hidden_convoy", "rogue_vigil_signal_lanterns"],
        encounterId: "act_1_branch_detour_signal",
      },
      {
        id: "rogue_detour_cloister_line",
        title: "Cloister Mobilized Line",
        zoneRole: "branchBattle",
        requiredFlagIds: [
          "rogue_recovery_chapel_lanterns",
          "rogue_detour_hidden_convoy",
          "rogue_vigil_signal_lanterns",
          "rogue_accord_cloister_paths",
          "rogue_route_vanguard",
        ],
        encounterId: "act_1_branch_detour_mobilized",
      },
      {
        id: "rogue_escalation_catacomb_host",
        title: "Catacomb Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["rogue_reckoning_chapel_ledger", "rogue_escalation_catacomb_surge"],
        encounterId: "act_1_miniboss_escalation",
      },
      {
        id: "rogue_escalation_chapel_host",
        title: "Chapel Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["rogue_reckoning_chapel_ledger", "rogue_escalation_chapel_surge"],
        encounterId: "act_1_miniboss_escalation_breach",
      },
      {
        id: "rogue_escalation_wayfinder_host",
        title: "Wayfinder Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["rogue_reckoning_chapel_ledger", "rogue_escalation_catacomb_surge", "rogue_crossroads_hidden_wayfinders"],
        encounterId: "act_1_miniboss_escalation_directed",
      },
      {
        id: "rogue_escalation_cloister_host",
        title: "Cloister Mobilized Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: [
          "rogue_reckoning_chapel_ledger",
          "rogue_escalation_catacomb_surge",
          "rogue_crossroads_hidden_wayfinders",
          "rogue_accord_cloister_paths",
          "rogue_route_vanguard",
        ],
        encounterId: "act_1_miniboss_escalation_mobilized",
      },
      {
        id: "rogue_aftermath_catacomb_host",
        title: "Catacomb Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["rogue_detour_hidden_convoy", "rogue_escalation_catacomb_surge", "rogue_covenant_wayfinder_ledger"],
        encounterId: "act_1_boss_aftermath",
      },
      {
        id: "rogue_aftermath_wayfinder_host",
        title: "Wayfinder Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["rogue_detour_hidden_convoy", "rogue_escalation_catacomb_surge", "rogue_covenant_wayfinder_ledger", "rogue_crossroads_hidden_wayfinders"],
        encounterId: "act_1_boss_aftermath_directed",
      },
      {
        id: "rogue_aftermath_signal_host",
        title: "Signal Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: [
          "rogue_detour_hidden_convoy",
          "rogue_escalation_catacomb_surge",
          "rogue_covenant_wayfinder_ledger",
          "rogue_crossroads_hidden_wayfinders",
          "rogue_vigil_signal_lanterns",
        ],
        encounterId: "act_1_boss_aftermath_signaled",
      },
      {
        id: "rogue_aftermath_vanguard_host",
        title: "Vanguard Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: [
          "rogue_detour_hidden_convoy",
          "rogue_escalation_catacomb_surge",
          "rogue_covenant_wayfinder_ledger",
          "rogue_crossroads_hidden_wayfinders",
          "rogue_route_vanguard",
          "rogue_vigil_signal_lanterns",
        ],
        encounterId: "act_1_boss_aftermath_drilled",
      },
      {
        id: "rogue_aftermath_cloister_host",
        title: "Cloister Mobilized Host",
        zoneRole: "boss",
        requiredFlagIds: [
          "rogue_detour_hidden_convoy",
          "rogue_escalation_catacomb_surge",
          "rogue_covenant_wayfinder_ledger",
          "rogue_crossroads_hidden_wayfinders",
          "rogue_route_vanguard",
          "rogue_vigil_signal_lanterns",
          "rogue_accord_cloister_paths",
        ],
        encounterId: "act_1_boss_aftermath_mobilized",
      },
      {
        id: "rogue_aftermath_bellwatch_host",
        title: "Bellwatch Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["rogue_detour_chapel_sidepass", "rogue_escalation_chapel_surge", "rogue_covenant_cloister_bell"],
        encounterId: "act_1_boss_aftermath_posted",
      },
    ],
    2: [
      {
        id: "sunwell_recovery_ward_line",
        title: "Ward Line Recovery",
        zoneRole: "branchBattle",
        requiredFlagIds: ["sunwell_recovery_spearline_wards"],
        encounterId: "act_2_branch_recovery",
      },
      {
        id: "sunwell_accord_reliquary_host",
        title: "Reliquary Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["sunwell_accord_spear_posts"],
        encounterId: "act_2_miniboss_accord",
      },
      {
        id: "sunwell_covenant_chamber_host",
        title: "Reliquary Covenant Chamber",
        zoneRole: "boss",
        requiredFlagIds: ["sunwell_covenant_final_lance_ledger"],
        encounterId: "act_2_boss_covenant",
      },
      {
        id: "sunwell_detour_caravan_line",
        title: "Reliquary Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["sunwell_recovery_spearline_wards", "sunwell_detour_hidden_caravan"],
        encounterId: "act_2_branch_detour",
      },
      {
        id: "sunwell_detour_ward_line",
        title: "Warded Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["sunwell_recovery_spearline_wards", "sunwell_detour_warded_sidepass"],
        encounterId: "act_2_branch_detour_guided",
      },
      {
        id: "sunwell_detour_beacon_line",
        title: "Beacon Caravan Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["sunwell_recovery_spearline_wards", "sunwell_detour_hidden_caravan", "sunwell_water_beacons_aligned"],
        encounterId: "act_2_branch_detour_signal",
      },
      {
        id: "sunwell_detour_spear_post_line",
        title: "Spear Post Mobilized Line",
        zoneRole: "branchBattle",
        requiredFlagIds: [
          "sunwell_recovery_spearline_wards",
          "sunwell_detour_hidden_caravan",
          "sunwell_water_beacons_aligned",
          "sunwell_accord_spear_posts",
          "sunwell_crossroads_spearwall_pylons",
        ],
        encounterId: "act_2_branch_detour_mobilized",
      },
      {
        id: "sunwell_escalation_chamber_host",
        title: "Chamber Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["sunwell_reckoning_lance_wards", "sunwell_escalation_chamber_surge"],
        encounterId: "act_2_miniboss_escalation",
      },
      {
        id: "sunwell_escalation_lance_host",
        title: "Lance Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["sunwell_reckoning_lance_wards", "sunwell_escalation_lance_breach"],
        encounterId: "act_2_miniboss_escalation_breach",
      },
      {
        id: "sunwell_escalation_contract_host",
        title: "Contract Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["sunwell_reckoning_lance_wards", "sunwell_escalation_chamber_surge", "sunwell_crossroads_contract_guard"],
        encounterId: "act_2_miniboss_escalation_directed",
      },
      {
        id: "sunwell_escalation_spear_post_host",
        title: "Spear Post Mobilized Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: [
          "sunwell_reckoning_lance_wards",
          "sunwell_escalation_chamber_surge",
          "sunwell_crossroads_contract_guard",
          "sunwell_accord_spear_posts",
          "sunwell_shield_train",
        ],
        encounterId: "act_2_miniboss_escalation_mobilized",
      },
      {
        id: "sunwell_aftermath_chamber_host",
        title: "Reliquary Aftermath Chamber",
        zoneRole: "boss",
        requiredFlagIds: ["sunwell_detour_hidden_caravan", "sunwell_escalation_chamber_surge", "sunwell_covenant_final_lance_ledger"],
        encounterId: "act_2_boss_aftermath",
      },
      {
        id: "sunwell_aftermath_lance_host",
        title: "Directed Lance Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["sunwell_detour_hidden_caravan", "sunwell_escalation_chamber_surge", "sunwell_covenant_final_lance_ledger", "sunwell_crossroads_contract_guard"],
        encounterId: "act_2_boss_aftermath_directed",
      },
      {
        id: "sunwell_aftermath_beacon_host",
        title: "Beacon Aftermath Chamber",
        zoneRole: "boss",
        requiredFlagIds: [
          "sunwell_detour_hidden_caravan",
          "sunwell_escalation_chamber_surge",
          "sunwell_covenant_final_lance_ledger",
          "sunwell_crossroads_contract_guard",
          "sunwell_water_beacons_aligned",
        ],
        encounterId: "act_2_boss_aftermath_signaled",
      },
      {
        id: "sunwell_aftermath_pylon_host",
        title: "Pylon Aftermath Chamber",
        zoneRole: "boss",
        requiredFlagIds: [
          "sunwell_detour_hidden_caravan",
          "sunwell_escalation_chamber_surge",
          "sunwell_covenant_final_lance_ledger",
          "sunwell_crossroads_spearwall_pylons",
          "sunwell_shield_train",
        ],
        encounterId: "act_2_boss_aftermath_drilled",
      },
      {
        id: "sunwell_aftermath_reliquary_host",
        title: "Reliquary Mobilized Chamber",
        zoneRole: "boss",
        requiredFlagIds: [
          "sunwell_detour_hidden_caravan",
          "sunwell_escalation_chamber_surge",
          "sunwell_covenant_final_lance_ledger",
          "sunwell_crossroads_spearwall_pylons",
          "sunwell_shield_train",
          "sunwell_accord_spear_posts",
        ],
        encounterId: "act_2_boss_aftermath_mobilized",
      },
      {
        id: "sunwell_aftermath_banner_host",
        title: "Bannered Aftermath Chamber",
        zoneRole: "boss",
        requiredFlagIds: ["sunwell_detour_warded_sidepass", "sunwell_escalation_lance_breach", "sunwell_covenant_reliquary_banners"],
        encounterId: "act_2_boss_aftermath_posted",
      },
    ],
    3: [
      {
        id: "kurast_recovery_spellward_line",
        title: "Spellward Recovery Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["kurast_recovery_spellward_bins"],
        encounterId: "act_3_branch_recovery",
      },
      {
        id: "kurast_accord_channel_host",
        title: "Channel Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["kurast_accord_channel_marks"],
        encounterId: "act_3_miniboss_accord",
      },
      {
        id: "kurast_covenant_durance_host",
        title: "Harbor Covenant Court",
        zoneRole: "boss",
        requiredFlagIds: ["kurast_covenant_spellward_ledger"],
        encounterId: "act_3_boss_covenant",
      },
      {
        id: "kurast_detour_fleet_line",
        title: "Harbor Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["kurast_recovery_spellward_bins", "kurast_detour_hidden_fleet"],
        encounterId: "act_3_branch_detour",
      },
      {
        id: "kurast_detour_spellward_line",
        title: "Spellward Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["kurast_recovery_spellward_bins", "kurast_detour_spellward_sidepass"],
        encounterId: "act_3_branch_detour_guided",
      },
      {
        id: "kurast_detour_freeport_line",
        title: "Freeport Beacon Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["kurast_recovery_spellward_bins", "kurast_detour_hidden_fleet", "jade_supply_marks_floated"],
        encounterId: "act_3_branch_detour_signal",
      },
      {
        id: "kurast_detour_channel_line",
        title: "Channel Mobilized Line",
        zoneRole: "branchBattle",
        requiredFlagIds: [
          "kurast_recovery_spellward_bins",
          "kurast_detour_hidden_fleet",
          "jade_supply_marks_floated",
          "kurast_accord_channel_marks",
          "kurast_crossroads_night_berths",
        ],
        encounterId: "act_3_branch_detour_mobilized",
      },
      {
        id: "kurast_escalation_durance_host",
        title: "Durance Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["kurast_reckoning_harbor_seals", "kurast_escalation_durance_surge"],
        encounterId: "act_3_miniboss_escalation",
      },
      {
        id: "kurast_escalation_harbor_host",
        title: "Harbor Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["kurast_reckoning_harbor_seals", "kurast_escalation_harbor_push"],
        encounterId: "act_3_miniboss_escalation_breach",
      },
      {
        id: "kurast_escalation_pilot_host",
        title: "Pilot Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["kurast_reckoning_harbor_seals", "kurast_escalation_durance_surge", "kurast_crossroads_shadow_pilots"],
        encounterId: "act_3_miniboss_escalation_directed",
      },
      {
        id: "kurast_escalation_channel_host",
        title: "Channel Mobilized Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: [
          "kurast_reckoning_harbor_seals",
          "kurast_escalation_durance_surge",
          "kurast_crossroads_shadow_pilots",
          "kurast_accord_channel_marks",
          "kurast_shadow_barges",
        ],
        encounterId: "act_3_miniboss_escalation_mobilized",
      },
      {
        id: "kurast_aftermath_durance_host",
        title: "Harbor Aftermath Court",
        zoneRole: "boss",
        requiredFlagIds: ["kurast_detour_hidden_fleet", "kurast_escalation_durance_surge", "kurast_covenant_spellward_ledger"],
        encounterId: "act_3_boss_aftermath",
      },
      {
        id: "kurast_aftermath_spellward_host",
        title: "Directed Harbor Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["kurast_detour_hidden_fleet", "kurast_escalation_durance_surge", "kurast_covenant_spellward_ledger", "kurast_crossroads_shadow_pilots"],
        encounterId: "act_3_boss_aftermath_directed",
      },
      {
        id: "kurast_aftermath_beacon_host",
        title: "Signaled Harbor Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "kurast_detour_hidden_fleet",
          "kurast_escalation_durance_surge",
          "kurast_covenant_spellward_ledger",
          "kurast_crossroads_shadow_pilots",
          "jade_supply_marks_floated",
        ],
        encounterId: "act_3_boss_aftermath_signaled",
      },
      {
        id: "kurast_aftermath_berth_host",
        title: "Night Berth Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "kurast_detour_hidden_fleet",
          "kurast_escalation_durance_surge",
          "kurast_covenant_spellward_ledger",
          "kurast_crossroads_night_berths",
          "kurast_shadow_barges",
        ],
        encounterId: "act_3_boss_aftermath_drilled",
      },
      {
        id: "kurast_aftermath_channel_host",
        title: "Channel Mobilized Berth",
        zoneRole: "boss",
        requiredFlagIds: [
          "kurast_detour_hidden_fleet",
          "kurast_escalation_durance_surge",
          "kurast_covenant_spellward_ledger",
          "kurast_crossroads_night_berths",
          "kurast_shadow_barges",
          "kurast_accord_channel_marks",
        ],
        encounterId: "act_3_boss_aftermath_mobilized",
      },
      {
        id: "kurast_aftermath_bell_host",
        title: "Harbor Bell Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["kurast_detour_spellward_sidepass", "kurast_escalation_harbor_push", "kurast_covenant_harbor_bells"],
        encounterId: "act_3_boss_aftermath_posted",
      },
    ],
    4: [
      {
        id: "hellforge_recovery_hellward_line",
        title: "Hellward Recovery Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["hellforge_recovery_hellward_screen"],
        encounterId: "act_4_branch_recovery",
      },
      {
        id: "hellforge_accord_breach_host",
        title: "Breach Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["hellforge_accord_breach_rivets"],
        encounterId: "act_4_miniboss_accord",
      },
      {
        id: "hellforge_covenant_sanctuary_host",
        title: "Sanctuary Covenant Host",
        zoneRole: "boss",
        requiredFlagIds: ["hellforge_covenant_breachscreen_ledger"],
        encounterId: "act_4_boss_covenant",
      },
      {
        id: "hellforge_detour_relief_line",
        title: "Sanctuary Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["hellforge_recovery_hellward_screen", "hellforge_detour_hidden_relief"],
        encounterId: "act_4_branch_detour",
      },
      {
        id: "hellforge_detour_hellward_line",
        title: "Hellward Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["hellforge_recovery_hellward_screen", "hellforge_detour_hellward_sidepass"],
        encounterId: "act_4_branch_detour_guided",
      },
      {
        id: "hellforge_detour_cinder_line",
        title: "Cinder Signal Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["hellforge_recovery_hellward_screen", "hellforge_detour_hidden_relief", "infernal_forge_gates_chained"],
        encounterId: "act_4_branch_detour_signal",
      },
      {
        id: "hellforge_detour_rivet_line",
        title: "Rivet Mobilized Line",
        zoneRole: "branchBattle",
        requiredFlagIds: [
          "hellforge_recovery_hellward_screen",
          "hellforge_detour_hidden_relief",
          "infernal_forge_gates_chained",
          "hellforge_accord_breach_rivets",
          "hellforge_crossroads_phalanx_reliefs",
        ],
        encounterId: "act_4_branch_detour_mobilized",
      },
      {
        id: "hellforge_escalation_sanctuary_host",
        title: "Sanctuary Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_surge"],
        encounterId: "act_4_miniboss_escalation",
      },
      {
        id: "hellforge_escalation_hellward_host",
        title: "Hellward Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_screen"],
        encounterId: "act_4_miniboss_escalation_breach",
      },
      {
        id: "hellforge_escalation_turn_host",
        title: "Hellward Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["hellforge_reckoning_sanctuary_screens", "hellforge_escalation_sanctuary_surge", "hellforge_crossroads_hellward_turn"],
        encounterId: "act_4_miniboss_escalation_directed",
      },
      {
        id: "hellforge_escalation_rivet_host",
        title: "Rivet Mobilized Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: [
          "hellforge_reckoning_sanctuary_screens",
          "hellforge_escalation_sanctuary_surge",
          "hellforge_crossroads_hellward_turn",
          "hellforge_accord_breach_rivets",
          "hellforge_phalanx_steps_locked",
        ],
        encounterId: "act_4_miniboss_escalation_mobilized",
      },
      {
        id: "hellforge_aftermath_sanctuary_host",
        title: "Sanctuary Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["hellforge_detour_hidden_relief", "hellforge_escalation_sanctuary_surge", "hellforge_covenant_breachscreen_ledger"],
        encounterId: "act_4_boss_aftermath",
      },
      {
        id: "hellforge_aftermath_breachscreen_host",
        title: "Directed Sanctuary Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["hellforge_detour_hidden_relief", "hellforge_escalation_sanctuary_surge", "hellforge_covenant_breachscreen_ledger", "hellforge_crossroads_hellward_turn"],
        encounterId: "act_4_boss_aftermath_directed",
      },
      {
        id: "hellforge_aftermath_cinder_host",
        title: "Signaled Sanctuary Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "hellforge_detour_hidden_relief",
          "hellforge_escalation_sanctuary_surge",
          "hellforge_covenant_breachscreen_ledger",
          "hellforge_crossroads_hellward_turn",
          "infernal_forge_gates_chained",
        ],
        encounterId: "act_4_boss_aftermath_signaled",
      },
      {
        id: "hellforge_aftermath_relief_host",
        title: "Phalanx Relief Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "hellforge_detour_hidden_relief",
          "hellforge_escalation_sanctuary_surge",
          "hellforge_covenant_breachscreen_ledger",
          "hellforge_crossroads_phalanx_reliefs",
          "hellforge_phalanx_steps_locked",
        ],
        encounterId: "act_4_boss_aftermath_drilled",
      },
      {
        id: "hellforge_aftermath_breach_host",
        title: "Breach Mobilized Relief",
        zoneRole: "boss",
        requiredFlagIds: [
          "hellforge_detour_hidden_relief",
          "hellforge_escalation_sanctuary_surge",
          "hellforge_covenant_breachscreen_ledger",
          "hellforge_crossroads_phalanx_reliefs",
          "hellforge_phalanx_steps_locked",
          "hellforge_accord_breach_rivets",
        ],
        encounterId: "act_4_boss_aftermath_mobilized",
      },
      {
        id: "hellforge_aftermath_bell_host",
        title: "Sanctuary Bell Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["hellforge_detour_hellward_sidepass", "hellforge_escalation_sanctuary_screen", "hellforge_covenant_sanctuary_bells"],
        encounterId: "act_4_boss_aftermath_posted",
      },
    ],
    5: [
      {
        id: "harrogath_recovery_banner_line",
        title: "Banner Recovery Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["harrogath_recovery_guard_banners"],
        encounterId: "act_5_branch_recovery",
      },
      {
        id: "harrogath_accord_ancients_host",
        title: "Ancients Accord Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["harrogath_accord_ancients_posts"],
        encounterId: "act_5_miniboss_accord",
      },
      {
        id: "harrogath_covenant_worldstone_host",
        title: "Summit Covenant Host",
        zoneRole: "boss",
        requiredFlagIds: ["harrogath_covenant_ancients_ledger"],
        encounterId: "act_5_boss_covenant",
      },
      {
        id: "harrogath_detour_sled_line",
        title: "Summit Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["harrogath_recovery_guard_banners", "harrogath_detour_hidden_sleds"],
        encounterId: "act_5_branch_detour",
      },
      {
        id: "harrogath_detour_banner_line",
        title: "Banner Sidepass Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["harrogath_recovery_guard_banners", "harrogath_detour_banner_sidepass"],
        encounterId: "act_5_branch_detour_guided",
      },
      {
        id: "harrogath_detour_watchfire_line",
        title: "Watchfire Detour Line",
        zoneRole: "branchBattle",
        requiredFlagIds: ["harrogath_recovery_guard_banners", "harrogath_detour_hidden_sleds", "ancients_watchfires_ringed"],
        encounterId: "act_5_branch_detour_signal",
      },
      {
        id: "harrogath_detour_ancients_line",
        title: "Ancients Mobilized Line",
        zoneRole: "branchBattle",
        requiredFlagIds: [
          "harrogath_recovery_guard_banners",
          "harrogath_detour_hidden_sleds",
          "ancients_watchfires_ringed",
          "harrogath_accord_ancients_posts",
          "harrogath_crossroads_switchbacks",
        ],
        encounterId: "act_5_branch_detour_mobilized",
      },
      {
        id: "harrogath_escalation_worldstone_host",
        title: "Worldstone Escalation Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["harrogath_reckoning_oath_rations", "harrogath_escalation_worldstone_surge"],
        encounterId: "act_5_miniboss_escalation",
      },
      {
        id: "harrogath_escalation_oath_host",
        title: "Oath Breach Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["harrogath_reckoning_oath_rations", "harrogath_escalation_oath_surge"],
        encounterId: "act_5_miniboss_escalation_breach",
      },
      {
        id: "harrogath_escalation_reserve_host",
        title: "Reserve Surge Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: ["harrogath_reckoning_oath_rations", "harrogath_escalation_worldstone_surge", "harrogath_crossroads_summit_reserve"],
        encounterId: "act_5_miniboss_escalation_directed",
      },
      {
        id: "harrogath_escalation_ancients_host",
        title: "Ancients Mobilized Host",
        zoneRole: "branchMiniboss",
        requiredFlagIds: [
          "harrogath_reckoning_oath_rations",
          "harrogath_escalation_worldstone_surge",
          "harrogath_crossroads_summit_reserve",
          "harrogath_accord_ancients_posts",
          "harrogath_peak_guard_drilled",
        ],
        encounterId: "act_5_miniboss_escalation_mobilized",
      },
      {
        id: "harrogath_aftermath_worldstone_host",
        title: "Worldstone Aftermath Host",
        zoneRole: "boss",
        requiredFlagIds: ["harrogath_detour_hidden_sleds", "harrogath_escalation_worldstone_surge", "harrogath_covenant_ancients_ledger"],
        encounterId: "act_5_boss_aftermath",
      },
      {
        id: "harrogath_aftermath_ancients_host",
        title: "Directed Summit Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["harrogath_detour_hidden_sleds", "harrogath_escalation_worldstone_surge", "harrogath_covenant_ancients_ledger", "harrogath_crossroads_summit_reserve"],
        encounterId: "act_5_boss_aftermath_directed",
      },
      {
        id: "harrogath_aftermath_watchfire_host",
        title: "Signaled Summit Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "harrogath_detour_hidden_sleds",
          "harrogath_escalation_worldstone_surge",
          "harrogath_covenant_ancients_ledger",
          "harrogath_crossroads_summit_reserve",
          "ancients_watchfires_ringed",
        ],
        encounterId: "act_5_boss_aftermath_signaled",
      },
      {
        id: "harrogath_aftermath_switchback_host",
        title: "Switchback Aftermath",
        zoneRole: "boss",
        requiredFlagIds: [
          "harrogath_detour_hidden_sleds",
          "harrogath_escalation_worldstone_surge",
          "harrogath_covenant_ancients_ledger",
          "harrogath_crossroads_switchbacks",
          "harrogath_peak_guard_drilled",
        ],
        encounterId: "act_5_boss_aftermath_drilled",
      },
      {
        id: "harrogath_aftermath_accord_host",
        title: "Ancients Mobilized Switchback",
        zoneRole: "boss",
        requiredFlagIds: [
          "harrogath_detour_hidden_sleds",
          "harrogath_escalation_worldstone_surge",
          "harrogath_covenant_ancients_ledger",
          "harrogath_crossroads_switchbacks",
          "harrogath_peak_guard_drilled",
          "harrogath_accord_ancients_posts",
        ],
        encounterId: "act_5_boss_aftermath_mobilized",
      },
      {
        id: "harrogath_aftermath_bell_host",
        title: "Summit Bell Aftermath",
        zoneRole: "boss",
        requiredFlagIds: ["harrogath_detour_banner_sidepass", "harrogath_escalation_oath_surge", "harrogath_covenant_summit_bells"],
        encounterId: "act_5_boss_aftermath_posted",
      },
    ],
  };

  runtimeWindow.__ROUGE_GC_ENCOUNTERS = {
    consequenceEncounterPackages,
  };
})();
