#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CURATED_DIR="$ROOT_DIR/assets/curated/icons"

mkdir -p "$CURATED_DIR/cards" "$CURATED_DIR/enemies" "$CURATED_DIR/ui"

copy() {
  local source_rel="$1"
  local destination_rel="$2"
  cp "$ROOT_DIR/$source_rel" "$CURATED_DIR/$destination_rel"
}

echo "Copying curated card icons..."
copy "assets/raw/game-icons/smoke/icons/000000/transparent/1x1/delapouite/steam-blast.svg" "cards/01_steam-blast.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/bolt-bomb.svg" "cards/02_bolt-bomb.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/delapouite/drill.svg" "cards/03_drill.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/lorc/laser-blast.svg" "cards/04_laser-blast.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/lorc/overdrive.svg" "cards/05_overdrive.svg"
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/lorc/cogsplosion.svg" "cards/06_cogsplosion.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/spark-plug.svg" "cards/07_spark-plug.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/delapouite/walking-turret.svg" "cards/08_walking-turret.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/delapouite/valve.svg" "cards/09_valve.svg"
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/delapouite/steam.svg" "cards/10_steam.svg"
copy "assets/raw/game-icons/smoke/icons/000000/transparent/1x1/delapouite/bellows.svg" "cards/11_bellows.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/plug.svg" "cards/12_plug.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/priorblue/battery-plus.svg" "cards/13_battery-plus.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/priorblue/battery-minus.svg" "cards/14_battery-minus.svg"
copy "assets/raw/game-icons/smoke/icons/000000/transparent/1x1/darkzaitzev/smoke-bomb.svg" "cards/15_smoke-bomb.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/lorc/radar-sweep.svg" "cards/16_radar-sweep.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/power-generator.svg" "cards/17_power-generator.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/nuclear-plant.svg" "cards/18_nuclear-plant.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/caro-asercion/tesla-coil.svg" "cards/19_tesla-coil.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/skoll/oil-drum.svg" "cards/20_oil-drum.svg"
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/delapouite/coal-pile.svg" "cards/21_coal-pile.svg"
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/delapouite/pipes.svg" "cards/22_pipes.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/wind-turbine.svg" "cards/23_wind-turbine.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/energy-tank.svg" "cards/24_energy-tank.svg"

echo "Copying curated enemy icons..."
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/delapouite/steam-locomotive.svg" "enemies/01_steam-locomotive.svg"
copy "assets/raw/game-icons/smoke/icons/000000/transparent/1x1/cathelineau/iron-hulled-warship.svg" "enemies/02_iron-hulled-warship.svg"
copy "assets/raw/game-icons/smoke/icons/000000/transparent/1x1/cathelineau/dreadnought.svg" "enemies/03_dreadnought.svg"
copy "assets/raw/game-icons/smoke/icons/000000/transparent/1x1/lorc/gas-mask.svg" "enemies/04_gas-mask.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/lorc/mechanical-arm.svg" "enemies/05_mechanical-arm.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/delapouite/walking-turret.svg" "enemies/06_walking-turret.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/laser-turret.svg" "enemies/07_laser-turret.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/lorc/spoutnik.svg" "enemies/08_spoutnik.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/lorc/satellite.svg" "enemies/09_satellite.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/sbed/tesla.svg" "enemies/10_tesla.svg"
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/lorc/frankenstein-creature.svg" "enemies/11_frankenstein-creature.svg"
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/skoll/zeppelin.svg" "enemies/12_zeppelin.svg"

echo "Copying curated UI icons..."
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/life-bar.svg" "ui/hp_life-bar.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/radiations.svg" "ui/heat_radiations.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/priorblue/battery-50.svg" "ui/energy_battery-50.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/lorc/cross-flare.svg" "ui/crit_cross-flare.svg"
copy "assets/raw/game-icons/machine/icons/000000/transparent/1x1/lorc/light-bulb.svg" "ui/idea_light-bulb.svg"
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/skoll/pocket-watch.svg" "ui/turn_pocket-watch.svg"
copy "assets/raw/game-icons/energy/icons/000000/transparent/1x1/delapouite/plug.svg" "ui/power_plug.svg"
copy "assets/raw/game-icons/steampunk/icons/000000/transparent/1x1/delapouite/wall-light.svg" "ui/alert_wall-light.svg"

echo "Curated icons written to: $CURATED_DIR"
